// LPFORGE_PHASE6_MAINNET_MODULE
import type {Phase3Orientation,Phase3StrategyFamily} from '../../contracts/src/index.js';
import { quoteMeteoraFundingFromSolCapital } from '../../meteora-execution/src/index.js';

export interface Phase6EntryFundingPlan {strategy:Phase3StrategyFamily;orientation:Phase3Orientation;pairedTokenTargetBps:number;solForLpLamports:bigint;solToPairedTokenLamports:bigint;lowerBinId:number;upperBinId:number;reasonCodes:string[];}

/** Converts the autonomous strategy winner into its asset-funding sequence. SOL is token Y for the configured DLMM pools. */
function pairedTokenTargetBps(orientation:Phase3Orientation,activeBinId:number,weights:Array<{binId:number;weight:number}>|undefined):number{
  if(orientation==='ONE_SIDED_Y')return 0;if(orientation==='ONE_SIDED_X')return 10_000;if(orientation==='BALANCED')return 5_000;
  if(!weights?.length)throw new Error('LPFORGE_P6_SKEWED_ENTRY_WEIGHTS_REQUIRED');const total=weights.reduce((sum,row)=>sum+row.weight,0),xSide=weights.filter(row=>row.binId>=activeBinId).reduce((sum,row)=>sum+row.weight,0);if(!(total>0)||!Number.isFinite(total)||!Number.isFinite(xSide))throw new Error('LPFORGE_P6_SKEWED_ENTRY_WEIGHTS_INVALID');return Math.max(0,Math.min(10_000,Math.round(xSide/total*10_000)));
}
export function planPhase6SolEntryFunding(input:{strategy:Phase3StrategyFamily;orientation?:Phase3Orientation;capitalLamports:bigint;activeBinId:number;lowerBinId:number;upperBinId:number;perBinWeights?:Array<{binId:number;weight:number}>}):Phase6EntryFundingPlan{
  if(input.capitalLamports<2n)throw new Error('LPFORGE_P6_ENTRY_CAPITAL_TOO_SMALL');if(!Number.isInteger(input.activeBinId)||!Number.isInteger(input.lowerBinId)||!Number.isInteger(input.upperBinId)||input.lowerBinId>input.upperBinId)throw new Error('LPFORGE_P6_ENTRY_RANGE_INVALID');
  const orientation=input.orientation??'BALANCED';if(orientation==='ONE_SIDED_X'||orientation==='SKEWED_X')throw new Error('LPFORGE_P6_TOKEN_SIDED_ENTRY_NOT_ENABLED');const targetBps=pairedTokenTargetBps(orientation,input.activeBinId,input.perBinWeights);const solToPairedTokenLamports=input.capitalLamports*BigInt(targetBps)/10_000n;const reason=orientation==='ONE_SIDED_Y'?'P6_SOL_SIDED_ENTRY_NO_SWAP':orientation==='BALANCED'?'P6_BALANCED_ENTRY_PRELIMINARY_SPLIT':'P6_SOL_SKEWED_ENTRY_PRELIMINARY_SPLIT';return{strategy:input.strategy,orientation,pairedTokenTargetBps:targetBps,solForLpLamports:input.capitalLamports-solToPairedTokenLamports,solToPairedTokenLamports,lowerBinId:input.lowerBinId,upperBinId:input.upperBinId,reasonCodes:[reason,'P6_ENTRY_REQUIRES_SDK_FINAL_FUNDING_QUOTE']};
}
export interface Phase6ExactEntryFundingPlan extends Phase6EntryFundingPlan {totalPairedTokenRaw:bigint;sdkVersion:string;}
export async function quotePhase6ExactSolEntryFunding(input:{strategy:Phase3StrategyFamily;orientation:Phase3Orientation;capitalLamports:bigint;activeBinId:number;binStep:number;lowerBinId:number;upperBinId:number;activeBinXAmount:string|bigint;activeBinYAmount:string|bigint;perBinWeights?:Array<{binId:number;weight:number}>}):Promise<Phase6ExactEntryFundingPlan>{
  const preliminary=planPhase6SolEntryFunding(input);if(preliminary.orientation==='ONE_SIDED_X'||preliminary.orientation==='SKEWED_X')throw new Error('LPFORGE_P6_TOKEN_SIDED_ENTRY_NOT_ENABLED');const quote=await quoteMeteoraFundingFromSolCapital({strategy:input.strategy,orientation:preliminary.orientation,capitalYAmount:input.capitalLamports,activeBinId:input.activeBinId,binStep:input.binStep,lowerBinId:input.lowerBinId,upperBinId:input.upperBinId,activeBinXAmount:input.activeBinXAmount,activeBinYAmount:input.activeBinYAmount});const cost=BigInt(quote.pairedTokenCostInYRaw),used=BigInt(quote.capitalUsedYRaw);return{...preliminary,pairedTokenTargetBps:input.capitalLamports>0n?Number(cost*10_000n/input.capitalLamports):0,solForLpLamports:BigInt(quote.totalYAmount),solToPairedTokenLamports:cost,totalPairedTokenRaw:BigInt(quote.totalXAmount),sdkVersion:quote.sdkVersion,reasonCodes:[...preliminary.reasonCodes,'P6_METEORA_SDK_FINAL_FUNDING_QUOTE',...(used<input.capitalLamports?['P6_CAPITAL_ROUNDING_REMAINDER_RESERVED']:[])]};
}
