import type { Phase4PositionState } from '../../contracts/src/index.js';
export interface PaperPosition {id:string;pool:string;token:string;thesisId:string;candidateId:string;state:Phase4PositionState;capital:number;lowerBinId:number;upperBinId:number;openedAt?:string;closedAt?:string;currentActiveBinId?:number;tokenXValue:number;tokenYValue:number;feesValue:number;rewardsValue:number;costsValue:number;paperOnly:true;version:number;}
export type PaperPositionEvent='MARK_ENTRY_READY'|'OPEN_REQUEST'|'OPEN_CONFIRMED'|'MARK_RANGE'|'MANAGEMENT_START'|'REBALANCE_START'|'CLOSE_REQUEST'|'CLOSE_CONFIRMED'|'FAIL'|'RECONCILIATION_HOLD'|'EMERGENCY';
const allowed:Record<Phase4PositionState,PaperPositionEvent[]>={
 PLANNED:['MARK_ENTRY_READY','FAIL','EMERGENCY'],ENTRY_READY:['OPEN_REQUEST','FAIL','EMERGENCY'],OPEN_PENDING:['OPEN_CONFIRMED','FAIL','RECONCILIATION_HOLD','EMERGENCY'],OPEN:['MARK_RANGE','MANAGEMENT_START','CLOSE_REQUEST','RECONCILIATION_HOLD','EMERGENCY'],IN_RANGE:['MARK_RANGE','MANAGEMENT_START','CLOSE_REQUEST','EMERGENCY'],NEAR_LOWER_BOUND:['MARK_RANGE','MANAGEMENT_START','CLOSE_REQUEST','EMERGENCY'],NEAR_UPPER_BOUND:['MARK_RANGE','MANAGEMENT_START','CLOSE_REQUEST','EMERGENCY'],OUT_OF_RANGE_BELOW:['MARK_RANGE','MANAGEMENT_START','CLOSE_REQUEST','EMERGENCY'],OUT_OF_RANGE_ABOVE:['MARK_RANGE','MANAGEMENT_START','CLOSE_REQUEST','EMERGENCY'],MANAGEMENT_PENDING:['MARK_RANGE','REBALANCE_START','CLOSE_REQUEST','EMERGENCY'],REBALANCE_PENDING:['MARK_RANGE','RECONCILIATION_HOLD','FAIL','EMERGENCY'],CLOSE_PENDING:['CLOSE_CONFIRMED','RECONCILIATION_HOLD','FAIL','EMERGENCY'],CLOSED:[],FAILED:[],RECONCILIATION_REQUIRED:['MARK_RANGE','CLOSE_REQUEST','EMERGENCY'],EMERGENCY:['CLOSE_REQUEST','CLOSE_CONFIRMED']};
export function rangeState(lower:number,upper:number,active:number,nearFraction=.12):Phase4PositionState{if(active<lower)return'OUT_OF_RANGE_BELOW';if(active>upper)return'OUT_OF_RANGE_ABOVE';const width=Math.max(1,upper-lower);const edge=Math.max(1,Math.ceil(width*nearFraction));if(active-lower<=edge)return'NEAR_LOWER_BOUND';if(upper-active<=edge)return'NEAR_UPPER_BOUND';return'IN_RANGE';}
export function transitionPaperPosition(position:PaperPosition,event:PaperPositionEvent,at:string,activeBinId?:number):PaperPosition{
 if(!allowed[position.state].includes(event))throw new Error(`LPFORGE_PAPER_ILLEGAL_TRANSITION:${position.state}:${event}`);let state=position.state;const patch:Partial<PaperPosition>={version:position.version+1};
 if(event==='MARK_ENTRY_READY')state='ENTRY_READY';else if(event==='OPEN_REQUEST')state='OPEN_PENDING';else if(event==='OPEN_CONFIRMED'){state='OPEN';patch.openedAt=at;}else if(event==='MARK_RANGE'){if(activeBinId===undefined)throw new Error('LPFORGE_PAPER_ACTIVE_BIN_REQUIRED');state=rangeState(position.lowerBinId,position.upperBinId,activeBinId);patch.currentActiveBinId=activeBinId;}else if(event==='MANAGEMENT_START')state='MANAGEMENT_PENDING';else if(event==='REBALANCE_START')state='REBALANCE_PENDING';else if(event==='CLOSE_REQUEST')state='CLOSE_PENDING';else if(event==='CLOSE_CONFIRMED'){state='CLOSED';patch.closedAt=at;}else if(event==='FAIL')state='FAILED';else if(event==='RECONCILIATION_HOLD')state='RECONCILIATION_REQUIRED';else if(event==='EMERGENCY')state='EMERGENCY';return{...position,...patch,state};
}
export function paperPositionValue(p:PaperPosition):number{return p.tokenXValue+p.tokenYValue+p.feesValue+p.rewardsValue-p.costsValue;}
