// LPFORGE_PHASE5_EXECUTION_MODULE
import { assertAuthority, type ConfirmationRecordContract, type ExecutionAuthority, type SubmissionRecordContract } from '../../execution-contracts/src/index.js';
import type { ExecutionRiskDecision } from '../../execution-risk/src/index.js';
export interface BlockhashLease {blockhash:string;lastValidBlockHeight:number;}
export interface SubmissionLedger {
  prepare(value:{attemptId:string;transactionId:string;idempotencyKey:string;attempt:number;signedPayloadFingerprint:string;blockhash:string;lastValidBlockHeight:number;preparedAt:string;payload:Record<string,unknown>}):Promise<'PREPARED'|'DUPLICATE'>;
  markSent(attemptId:string,signature:string,submittedAt:string):Promise<void>;
  markUnknown(attemptId:string,at:string,error:string):Promise<void>;
  recordConfirmation(value:{attemptId:string;signature?:string;status:ConfirmationRecordContract['status'];observedAt:string;slot?:bigint;error?:string;payload:Record<string,unknown>}):Promise<void>;
}
export interface SubmissionTransport {sendRawTransaction(raw:Uint8Array,options:{skipPreflight:false;maxRetries:0}):Promise<string>;getBlockHeight():Promise<number>;getSignatureStatus(signature:string):Promise<{confirmationStatus?:'processed'|'confirmed'|'finalized';err?:unknown;slot?:number}|null>;}
function fingerprint(raw:Uint8Array):string{let a=0x811c9dc5>>>0;for(const b of raw){a^=b;a=Math.imul(a,16777619)>>>0;}return `${raw.length}:${a.toString(16).padStart(8,'0')}`;}
export async function submitSignedTransaction(input:{authority:ExecutionAuthority;riskDecision:ExecutionRiskDecision;transactionId:string;idempotencyKey:string;attempt:number;raw:Uint8Array;lease:BlockhashLease;ledger:SubmissionLedger;transport:SubmissionTransport;submittedAt:string}):Promise<SubmissionRecordContract>{
  assertAuthority(input.authority,['DEVNET_SUBMIT','MAINNET_CANARY'],input.submittedAt);if(input.authority.cluster==='mainnet-beta'&&input.authority.level!=='MAINNET_CANARY')throw new Error('LPFORGE_MAINNET_SUBMISSION_CANARY_ONLY');if(input.riskDecision.decision!=='APPROVE'||!input.riskDecision.permitId||!input.riskDecision.expiresAt)throw new Error('LPFORGE_SUBMISSION_RISK_PERMIT_REQUIRED');if(Date.parse(input.riskDecision.expiresAt)<=Date.parse(input.submittedAt))throw new Error('LPFORGE_SUBMISSION_RISK_PERMIT_EXPIRED');if(!Number.isInteger(input.attempt)||input.attempt<1)throw new Error('LPFORGE_SUBMISSION_ATTEMPT_INVALID');
  const attemptId=`${input.transactionId}:attempt:${input.attempt}`;const prepared=await input.ledger.prepare({attemptId,transactionId:input.transactionId,idempotencyKey:input.idempotencyKey,attempt:input.attempt,signedPayloadFingerprint:fingerprint(input.raw),blockhash:input.lease.blockhash,lastValidBlockHeight:input.lease.lastValidBlockHeight,preparedAt:input.submittedAt,payload:{permitId:input.riskDecision.permitId,cluster:input.authority.cluster}});if(prepared==='DUPLICATE')throw new Error('LPFORGE_DUPLICATE_SUBMISSION_ATTEMPT');
  try{const signature=await input.transport.sendRawTransaction(input.raw,{skipPreflight:false,maxRetries:0});await input.ledger.markSent(attemptId,signature,input.submittedAt);return{transactionId:input.transactionId,signature,submittedAt:input.submittedAt,blockhash:input.lease.blockhash,lastValidBlockHeight:input.lease.lastValidBlockHeight,attempt:input.attempt};}catch(error){await input.ledger.markUnknown(attemptId,input.submittedAt,error instanceof Error?error.message:String(error));throw new Error('LPFORGE_SUBMISSION_STATUS_UNKNOWN');}
}
export async function observeConfirmation(input:{attemptId:string;record:SubmissionRecordContract;transport:SubmissionTransport;ledger:SubmissionLedger;observedAt:string}):Promise<ConfirmationRecordContract>{const s=await input.transport.getSignatureStatus(input.record.signature);let status:ConfirmationRecordContract['status']='UNKNOWN';let slot:bigint|undefined;let error:string|undefined;if(s?.err!=null){status='FAILED';error=typeof s.err==='string'?s.err:JSON.stringify(s.err);}else if(s?.confirmationStatus){status=s.confirmationStatus==='processed'?'PROCESSED':s.confirmationStatus==='confirmed'?'CONFIRMED':'FINALIZED';if(s.slot!==undefined)slot=BigInt(s.slot);}else if(await input.transport.getBlockHeight()>input.record.lastValidBlockHeight)status='EXPIRED';const result:ConfirmationRecordContract={transactionId:input.record.transactionId,signature:input.record.signature,status,observedAt:input.observedAt,...(slot!==undefined?{slot}:{}),...(error?{error}:{})};await input.ledger.recordConfirmation({attemptId:input.attemptId,signature:input.record.signature,status,observedAt:input.observedAt,...(slot!==undefined?{slot}:{}),...(error?{error}:{}),payload:{lastValidBlockHeight:input.record.lastValidBlockHeight}});return result;}
export function createWeb3SubmissionTransport(connection:{sendRawTransaction(raw:Uint8Array,options:Record<string,unknown>):Promise<string>;getBlockHeight():Promise<number>;getSignatureStatuses(signatures:string[]):Promise<{value:Array<{confirmationStatus?:'processed'|'confirmed'|'finalized'|null;err?:unknown;slot?:number}|null>}>}):SubmissionTransport{return{sendRawTransaction(raw,options){return connection.sendRawTransaction(raw,options);},getBlockHeight(){return connection.getBlockHeight();},async getSignatureStatus(signature){const r=await connection.getSignatureStatuses([signature]);const v=r.value[0];if(!v)return null;return{...(v.confirmationStatus?{confirmationStatus:v.confirmationStatus}:{}),...(v.err!==undefined?{err:v.err}:{}),...(v.slot!==undefined?{slot:v.slot}:{})};}};}
