import assert from 'node:assert/strict';import test from 'node:test';import {decodeConfirmedExecutionReceipt} from '../.build/packages/transaction-receipt/src/index.js';import {deriveTransactionAssetEffects,ASSOCIATED_TOKEN_PROGRAM_ID,TOKEN_PROGRAM_ID,WSOL_MINT} from '../.build/packages/transaction-asset-effects/src/index.js';import {deriveCloseUnwindSettlement,closeUnwindSettlementIds} from '../.build/packages/phase6-close-settlement/src/index.js';import {reconcileConfirmedCloseUnwind} from '../.build/packages/phase6-live-worker/src/index.js';
const OWNER='OWNER',RISK='RISK',WSOL='WSOL',ATA='ATA',POSITION='POSITION',TEMP='TEMP',JUP='JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4';
const ix=(programId,accountKeyIndexes,type)=>({programId,accountKeyIndexes,parsed:{type,info:{destination:OWNER}}});
const token=(accountIndex,mint,amount)=>({accountIndex,mint,owner:OWNER,uiTokenAmount:{amount:String(amount),decimals:9}});
function raw({pre,post,tokensPre=[],tokensPost=[],outer=[],err=null}={}){return{slot:1,version:0,transaction:{message:{accountKeys:[OWNER,RISK,WSOL,ATA,POSITION,TEMP],compiledInstructions:outer}},meta:{err,fee:5,preBalances:pre??[1000,0,1,0,0,0],postBalances:post??[995,0,1,0,0,0],loadedAddresses:{writable:[],readonly:[]},preTokenBalances:tokensPre,postTokenBalances:tokensPost,innerInstructions:[]}};}
function receipt(value={}){return decodeConfirmedExecutionReceipt('sig',raw(value));}
function settlement(value){const r=receipt(value),effects=deriveTransactionAssetEffects(r,{ownerAddress:OWNER,feePayerAddress:OWNER,inputMint:RISK,outputMint:WSOL_MINT,jupiterProgramIds:[JUP],associatedTokenAccountAddresses:[ATA],temporaryAccountAddresses:[TEMP],positionAddress:POSITION});return deriveCloseUnwindSettlement({receipt:r,effects,inputMint:RISK,outputMint:WSOL_MINT});}
test('CLOSE-001 recognizes a native-SOL Jupiter unwrap without requiring persistent WSOL',()=>{const result=settlement({pre:[1000,0,1,0,0,0],post:[1005,0,1,0,0,0],tokensPre:[token(1,RISK,50)],tokensPost:[token(1,RISK,0)],outer:[ix(JUP,[0,1],'route')]});assert.equal(result.state,'SETTLED');assert.equal(result.swapProceedsLamports,10n);assert.equal(result.inputCorroborated,true);});
test('CLOSE-002/003 recognizes persistent and mixed WSOL/native output exactly once',()=>{const wsol=settlement({tokensPre:[token(1,RISK,50)],tokensPost:[token(1,RISK,0),token(2,WSOL_MINT,10)],outer:[ix(JUP,[0,1,2],'route')]});assert.equal(wsol.swapProceedsLamports,10n);const mixed=settlement({pre:[1000,0,1,0,0,0],post:[1005,0,1,0,0,0],tokensPre:[token(1,RISK,50)],tokensPost:[token(1,RISK,0),token(2,WSOL_MINT,7)],outer:[ix(JUP,[0,1,2],'route')]});assert.equal(mixed.swapProceedsLamports,17n);});
test('CLOSE-004/005/006/007 excludes fee, ATA/temp rent, and PositionV2 rent from proceeds',()=>{const result=settlement({pre:[1000,0,1,203,89,71],post:[1368,0,1,0,0,0],tokensPre:[token(1,RISK,50)],tokensPost:[token(1,RISK,0)],outer:[ix(JUP,[0,1],'route'),ix(TOKEN_PROGRAM_ID,[3,0],'closeAccount'),ix('METEORA',[4,0],'closePosition'),ix(TOKEN_PROGRAM_ID,[5,0],'closeAccount')]});assert.equal(result.state,'SETTLED');assert.equal(result.swapProceedsLamports,10n);});
test('CLOSE-008/010 distinguishes rent-only and genuine zero-output transactions',()=>{const result=settlement({pre:[1000,0,1,203,0,0],post:[1198,0,1,0,0,0],outer:[ix(TOKEN_PROGRAM_ID,[3,0],'closeAccount')]});assert.equal(result.state,'MISSING_OUTPUT');assert.deepEqual(result.reasonCodes,['P6_CLOSE_UNWIND_OUTPUT_MISSING']);});
test('CLOSE-009 fails closed on a material unclassified effect',()=>{const result=settlement({pre:[1000,0,1,0,0,0],post:[1004,0,1,0,0,0],tokensPre:[token(1,RISK,50)],tokensPost:[token(1,RISK,0)]});assert.equal(result.state,'UNCLASSIFIED');assert.ok(result.reasonCodes.includes('P6_CLOSE_SETTLEMENT_EFFECT_UNCLASSIFIED'));});
test('CLOSE-012 accepts authoritative output when input-token corroboration is unavailable',()=>{const result=settlement({pre:[1000,0,1,0,0,0],post:[1005,0,1,0,0,0],outer:[ix(JUP,[0,1],'route')]});assert.equal(result.state,'SETTLED');assert.equal(result.inputCorroborated,false);});
test('RECOVERY-001/002 recovers a confirmed swap exactly once through stable durable settlement ids',async()=>{const chain=raw({pre:[1000,0,1,0,0,0],post:[1005,0,1,0,0,0],tokensPre:[token(1,RISK,50)],tokensPost:[token(1,RISK,0)],outer:[ix(JUP,[0,1],'route')]}),cashflows=new Map(),lots=new Map(),store={async insertPositionCashflow(row){cashflows.set(row.cashflowId,row);},async settlePositionInventoryLot(row){lots.set(row.eventId,row);}},input={store,connection:{async getTransaction(){return chain;}},plan:{planId:'plan',ownerAddress:OWNER},positionAddress:POSITION,signature:'sig',transactionId:'unwind',inputMint:RISK,inputAmountRaw:50n,observedAt:'2026-08-22T00:00:00.000Z'};const first=await reconcileConfirmedCloseUnwind(input),second=await reconcileConfirmedCloseUnwind(input);assert.equal(first.ok,true);assert.equal(second.ok,true);assert.equal(first.swapProceedsLamports,10n);assert.equal(cashflows.size,1);assert.equal(lots.size,1);assert.equal(cashflows.get('plan:close-swap-proceeds').lamports,10n);});
test('RECOVERY-003 retains unknown receipt as reconciliation debt, never as a zero-output settlement',async()=>{let writes=0;const result=await reconcileConfirmedCloseUnwind({store:{async insertPositionCashflow(){writes++;},async settlePositionInventoryLot(){writes++;}},connection:{async getTransaction(){return null;}},plan:{planId:'plan',ownerAddress:OWNER},positionAddress:POSITION,signature:'unknown',transactionId:'unwind',inputMint:RISK,inputAmountRaw:50n});assert.equal(result.ok,false);assert.equal(writes,0);});
test('RECOVERY-005 rejects a confirmed failed unwind',()=>{const result=settlement({err:{InstructionError:[0,'failed']}});assert.equal(result.state,'FAILED_TRANSACTION');});
