import test from 'node:test';import assert from 'node:assert/strict';
import {issuePhase7ObserveAuthority} from '../.build/packages/phase7-contracts/src/index.js';
import {buildPhase7LiveControlDecision,derivePhase7AutomaticIncidents,reconcilePhase7AutomaticIncidents} from '../.build/packages/phase7-live-control/src/index.js';
const at='2026-08-13T02:00:00Z';
const health=(status='HEALTHY',domainStatus={RPC:'HEALTHY',METEORA_API:'HEALTHY',DATABASE:'HEALTHY',DECISION:'HEALTHY',EXECUTION:'HEALTHY',PORTFOLIO:'HEALTHY',RECONCILIATION:'HEALTHY'})=>({status,observedAt:at,domainStatus,staleDomains:[],missingDomains:[],reasonCodes:[],newEntriesAllowed:status==='HEALTHY',managementWritesAllowed:status!=='CRITICAL',emergencyCloseAllowed:true});
const drift=(status='STABLE',reasonCodes=[])=>({status,reasonCodes,observedAt:at,sampleCount:100,newEntriesAllowed:status!=='BLOCK',managementAllowed:true,policyMutationAllowed:false,automaticPolicyPromotion:false,deltas:{}});
test('P7-R05 live control turns reconciliation/data-integrity failures into durable critical incidents',()=>{const h=health('CRITICAL',{RPC:'HEALTHY',METEORA_API:'HEALTHY',DATABASE:'HEALTHY',DECISION:'HEALTHY',EXECUTION:'HEALTHY',PORTFOLIO:'HEALTHY',RECONCILIATION:'CRITICAL'});const d=drift('BLOCK',['P7_DRIFT_RECONCILIATION_MISMATCH','P7_DRIFT_DECODER_SKIPS']);const xs=derivePhase7AutomaticIncidents({poolAddress:'p',observedAt:at,health:h,drift:d});assert.ok(xs.some(x=>x.type==='RECONCILIATION_MISMATCH'&&x.severity==='CRITICAL'));assert.ok(xs.some(x=>x.type==='PROTOCOL_COMPATIBILITY'&&x.severity==='CRITICAL'));});
test('P7-R05 acknowledged critical incident remains active and cannot be cleared by acknowledgement',()=>{const current=derivePhase7AutomaticIncidents({poolAddress:'p',observedAt:at,health:health('CRITICAL',{RPC:'HEALTHY',METEORA_API:'HEALTHY',DATABASE:'CRITICAL',DECISION:'HEALTHY',EXECUTION:'HEALTHY',PORTFOLIO:'HEALTHY',RECONCILIATION:'HEALTHY'}),drift:drift()});const prior={...current[0],status:'ACKNOWLEDGED',acknowledgedBy:'op'};const merged=reconcilePhase7AutomaticIncidents({existing:[prior],current,observedAt:at});assert.equal(merged[0].status,'ACKNOWLEDGED');const control=buildPhase7LiveControlDecision({authority:issuePhase7ObserveAuthority({now:at,ttlMs:60000}),health:health('CRITICAL',{RPC:'HEALTHY',METEORA_API:'HEALTHY',DATABASE:'CRITICAL',DECISION:'HEALTHY',EXECUTION:'HEALTHY',PORTFOLIO:'HEALTHY',RECONCILIATION:'HEALTHY'}),drift:drift(),incidents:merged});assert.equal(control.safety.mode,'EMERGENCY_ONLY');assert.equal(control.newEconomicActionAllowed,false);});
test('P7-R05 cleared warning auto-resolves, cleared critical remains until explicit evidence resolution',()=>{const warning={incidentId:'auto:RPC_OUTAGE:p',type:'RPC_OUTAGE',severity:'WARNING',openedAt:at,status:'OPEN',reasonCodes:['x'],pool:'p'};const critical={incidentId:'auto:DATABASE_FAILURE:p',type:'DATABASE_FAILURE',severity:'CRITICAL',openedAt:at,status:'OPEN',reasonCodes:['y'],pool:'p'};const merged=reconcilePhase7AutomaticIncidents({existing:[warning,critical],current:[],observedAt:'2026-08-13T02:05:00Z'});assert.equal(merged.find(x=>x.incidentId===warning.incidentId)?.status,'RESOLVED');assert.equal(merged.find(x=>x.incidentId===critical.incidentId)?.status,'OPEN');assert.ok(merged.find(x=>x.incidentId===critical.incidentId)?.reasonCodes.includes('P7_INCIDENT_MANUAL_RESOLUTION_REQUIRED'));});
