import test from 'node:test'; import assert from 'node:assert/strict'; import { allocateCapital, allocateProductionCapital } from '../.build/packages/capital-allocation/src/index.js';
test('P4-05 allocator preserves reserve and never overallocates',()=>{const r=allocateCapital({walletCapital:10,requests:[{id:'a',pool:'p1',token:'t1',requested:5,confidence:.9,expectedNetValueRate:.02,downsideRisk:.1},{id:'b',pool:'p2',token:'t2',requested:5,confidence:.8,expectedNetValueRate:.015,downsideRisk:.2}]});assert.ok(r.feeAndSafetyReserve>=2.5);assert.ok(r.totalAllocated<=r.deployableLimit+1e-12);assert.ok(r.totalAllocated<=6.5);});
test('P4-05 negative expected value gets zero capital',()=>{const r=allocateCapital({walletCapital:10,requests:[{id:'bad',pool:'p',token:'t',requested:1,confidence:1,expectedNetValueRate:-.1,downsideRisk:0}]});assert.equal(r.allocations[0].allocated,0);assert.ok(r.allocations[0].reasonCodes.includes('CAPITAL_EXPECTED_VALUE_NON_POSITIVE'));});
test('P4-05 existing token exposure constrains new allocation',()=>{const r=allocateCapital({walletCapital:10,exposure:{deployed:2,poolExposure:{},tokenExposure:{t1:2.5},reserved:2.5},requests:[{id:'a',pool:'p',token:'t1',requested:1,confidence:1,expectedNetValueRate:.1,downsideRisk:0}]});assert.equal(r.allocations[0].allocated,0);assert.ok(r.allocations[0].reasonCodes.includes('CAPITAL_TOKEN_LIMIT'));});
const productionPolicy={id:'live-policy:production-capital-v1',reserveCapital:.01,maxPortfolioCapital:.5,maxTokenCapital:.5,targetInitialPosition:.5,maxInitialPosition:.5,minInitialPosition:.01};
test('P4-05 production allocator reaches an explicit target initial position from an ENTRY_READY recommendation without re-scoring thesis confidence',()=>{const r=allocateProductionCapital({walletCapital:.5,policy:productionPolicy,requests:[{id:'entry-ready',pool:'p',token:'t',requested:productionPolicy.targetInitialPosition,maxPoolCapital:.5,entryReady:true,expectedNetValue:.0019}]});assert.equal(r.policyId,productionPolicy.id);assert.equal(r.allocations[0].allocated,.49);assert.ok(r.allocations[0].reasonCodes.includes('CAPITAL_ALLOCATED'));assert.ok(!r.allocations[0].reasonCodes.includes('CAPITAL_QUALITY_TOO_LOW'));});
test('P4-05 production desired sizing is independent from the wallet and respects the explicit initial-position maximum',()=>{const policy={...productionPolicy,targetInitialPosition:.1,maxInitialPosition:.2};const target=allocateProductionCapital({walletCapital:.5,policy,requests:[{id:'target',pool:'p',token:'t',requested:policy.targetInitialPosition,maxPoolCapital:.5,entryReady:true,expectedNetValue:.01}]});assert.equal(target.allocations[0].allocated,.1);const maximum=allocateProductionCapital({walletCapital:1,policy,requests:[{id:'max',pool:'p',token:'t',requested:.8,maxPoolCapital:1,entryReady:true,expectedNetValue:.01}]});assert.equal(maximum.allocations[0].allocated,.2);assert.ok(maximum.allocations[0].reasonCodes.includes('CAPITAL_INITIAL_POSITION_LIMIT'));});
test('P4-05 production allocator retains independent zero-allocation exposure and expected-value blocks',()=>{const exhausted=allocateProductionCapital({walletCapital:.5,policy:productionPolicy,exposure:{deployed:.5,poolExposure:{p:.5},tokenExposure:{t:.5},reserved:0},requests:[{id:'full-pool',pool:'p',token:'t',requested:.5,maxPoolCapital:.5,entryReady:true,expectedNetValue:.01}]});assert.equal(exhausted.allocations[0].allocated,0);assert.ok(exhausted.allocations[0].reasonCodes.includes('CAPITAL_POOL_LIMIT'));const negative=allocateProductionCapital({walletCapital:.5,policy:productionPolicy,requests:[{id:'negative',pool:'p',token:'t',requested:.5,maxPoolCapital:.5,entryReady:true,expectedNetValue:0}]});assert.equal(negative.allocations[0].allocated,0);assert.ok(negative.allocations[0].reasonCodes.includes('CAPITAL_EXPECTED_VALUE_NON_POSITIVE'));});
test('bounded live policy either allocates exactly 0.03 SOL or returns NO_TRADE',()=>{const policy={id:'bounded-exact-0.03',reserveCapital:0,maxPortfolioCapital:.03,maxTokenCapital:.03,targetInitialPosition:.03,maxInitialPosition:.03,minInitialPosition:.03};const exact=allocateProductionCapital({walletCapital:.03,policy,requests:[{id:'exact',pool:'p',token:'t',requested:.03,maxPoolCapital:.03,entryReady:true,expectedNetValue:.01}]});assert.equal(exact.allocations[0].allocated,.03);const insufficient=allocateProductionCapital({walletCapital:.029999999,policy,requests:[{id:'insufficient',pool:'p',token:'t',requested:.03,maxPoolCapital:.03,entryReady:true,expectedNetValue:.01}]});assert.equal(insufficient.allocations[0].allocated,0);assert.ok(insufficient.allocations[0].reasonCodes.includes('CAPITAL_BELOW_MINIMUM'));});
