import test from 'node:test';import assert from 'node:assert/strict';
import {assessPhase7LiveDrift,defaultPhase7LiveDriftPolicy,phase7DriftBaselineHash} from '../.build/packages/phase7-live-drift/src/index.js';
const baseline={sampleCount:100,regimeBrier:.2,survivalBrier:.18,netValueMae:.001,noTradeRate:.7,entryReadyRate:.1,executionCostRate:.0005,reconciliationMismatchRate:0,featureMissingRate:.01,decoderSkipRate:.001};
const facts={cycleCount:100,noTradeCount:70,entryReadyCount:10,reconciliationCount:10,reconciliationMismatchCount:0,canaryCapitalLamports:1000000,canaryExecutionCostLamports:500,featureMissingCount:1};
const store=(overrides={})=>({loadPhase7DriftFacts:async()=>({...facts,...overrides})});
test('P7-R04 live drift uses persisted decision/execution/reconciliation facts and explicit decoder telemetry',async()=>{const r=await assessPhase7LiveDrift({store:store(),poolAddress:'p',since:'2026-08-12T00:00:00Z',observedAt:'2026-08-13T00:00:00Z',baseline,policy:defaultPhase7LiveDriftPolicy,decoderSkipRate:.001,forecastOutcomeMetrics:{regimeBrier:.2,survivalBrier:.18,netValueMae:.001}});assert.equal(r.assessment.status,'STABLE');assert.equal(r.assessment.newEntriesAllowed,true);assert.equal(r.current.noTradeRate,.7);assert.equal(r.current.executionCostRate,.0005);assert.equal(r.baselineHash,phase7DriftBaselineHash(baseline));});
test('P7-R04 missing decoder telemetry fails closed for new entries',async()=>{const r=await assessPhase7LiveDrift({store:store(),poolAddress:'p',since:'2026-08-12T00:00:00Z',observedAt:'2026-08-13T00:00:00Z',baseline,policy:defaultPhase7LiveDriftPolicy});assert.equal(r.assessment.status,'BLOCK');assert.equal(r.assessment.newEntriesAllowed,false);assert.ok(r.assessment.reasonCodes.includes('P7_LIVE_DRIFT_DECODER_TELEMETRY_MISSING'));assert.equal(r.assessment.policyMutationAllowed,false);});
test('P7-R04 persisted reconciliation or feature drift hard-blocks without policy mutation',async()=>{const r=await assessPhase7LiveDrift({store:store({reconciliationCount:10,reconciliationMismatchCount:2,featureMissingCount:10}),poolAddress:'p',since:'2026-08-12T00:00:00Z',observedAt:'2026-08-13T00:00:00Z',baseline,policy:defaultPhase7LiveDriftPolicy,decoderSkipRate:.001,forecastOutcomeMetrics:{regimeBrier:.2,survivalBrier:.18,netValueMae:.001}});assert.equal(r.assessment.status,'BLOCK');assert.equal(r.assessment.newEntriesAllowed,false);assert.ok(r.assessment.reasonCodes.includes('P7_DRIFT_RECONCILIATION_MISMATCH'));assert.ok(r.assessment.reasonCodes.includes('P7_DRIFT_FEATURE_MISSINGNESS'));assert.equal(r.assessment.automaticPolicyPromotion,false);});
test('P7-R04 unavailable forecast outcomes are explicit WATCH evidence, never fabricated stable evidence',async()=>{const r=await assessPhase7LiveDrift({store:store(),poolAddress:'p',since:'2026-08-12T00:00:00Z',observedAt:'2026-08-13T00:00:00Z',baseline,policy:defaultPhase7LiveDriftPolicy,decoderSkipRate:.001});assert.equal(r.assessment.status,'WATCH');assert.ok(r.assessment.reasonCodes.includes('P7_LIVE_DRIFT_FORECAST_OUTCOME_COVERAGE_INCOMPLETE'));});
