import assert from 'node:assert/strict';
import test from 'node:test';
import {validateClaimedPlan} from '../.build/packages/phase6-claim-guard/src/index.js';

const policy={schemaVersion:1,policyId:'p',status:'ENABLED',approvalTtlMs:15000,minDevnetConfirmedRuns:1,maxActionsPerDay:2,maxOpenPositions:2,pools:[{address:'POOL',maxCapitalLamports:20_000_000n,maxOpenPositions:1}]};
const base={planId:'p',intentId:'i',idempotencyKey:'k',action:'OPEN',poolAddress:'POOL',ownerAddress:'OWNER',thesisId:'t',observedAt:'2026-08-13T00:00:00.000Z',expiresAt:'2026-08-13T00:05:00.000Z',intentPayload:{},planPayload:{provenance:{producer:'LPFORGE_PRODUCTION',schemaVersion:1,intentId:'i',poolAddress:'POOL',observedAt:'2026-08-13T00:00:00.000Z'},intent:{capitalLamports:'20000000'}},steps:[]};
test('claim guard rejects forged provenance, unallowlisted pool, excess capital and position limits',()=>{assert.equal(validateClaimedPlan({plan:base,policy,ownedPositions:[]}).approved,true);assert.ok(validateClaimedPlan({plan:{...base,planPayload:{}},policy,ownedPositions:[]}).reasonCodes.includes('P6_CLAIM_PROVENANCE_INVALID'));assert.ok(validateClaimedPlan({plan:{...base,poolAddress:'OTHER'},policy,ownedPositions:[]}).reasonCodes.includes('P6_CLAIM_POOL_NOT_ALLOWLISTED'));assert.ok(validateClaimedPlan({plan:{...base,planPayload:{...base.planPayload,intent:{capitalLamports:'20000001'}}},policy,ownedPositions:[]}).reasonCodes.includes('P6_CLAIM_CAPITAL_EXCEEDS_POOL_POLICY'));assert.ok(validateClaimedPlan({plan:base,policy,ownedPositions:[{lifecycle_state:'OPEN',pool_address:'POOL'}]}).reasonCodes.includes('P6_CLAIM_POSITION_LIMIT'));});
test('claim guard requires LPForge ownership and exact chain position truth for every management action',()=>{const plan={...base,action:'CLOSE',positionAddress:'POS',planPayload:{...base.planPayload,intent:{capitalLamports:'0'}}};assert.ok(validateClaimedPlan({plan,policy,ownedPositions:[]}).reasonCodes.includes('P6_CLAIM_POSITION_NOT_OWNED'));assert.equal(validateClaimedPlan({plan,policy,ownedPositions:[{lifecycle_state:'OPEN',position_address:'POS',owner_address:'OWNER',pool_address:'POOL'}],positionTruth:{owner:'OWNER',pool:'POOL'}}).approved,true);});
test('claim guard admits only fresh production-evaluated Tier-A pools under the versioned execution policy',()=>{const admitted={...policy,productionAdmission:{enabled:true,eligibleTiers:['A'],maxCandidates:1,maxCandidateAgeMs:900000,maxCapitalLamports:20_000_000n,maxOpenPositions:1}},plan={...base,poolAddress:'DISCOVERED',planPayload:{...base.planPayload,provenance:{...base.planPayload.provenance,poolAddress:'DISCOVERED'}}},fresh=[{poolAddress:'DISCOVERED',state:'ACTIVE_CANDIDATE',tier:'A',lastSeenAt:'2026-08-13T00:04:00.000Z'}],now='2026-08-13T00:05:00.000Z';assert.equal(validateClaimedPlan({plan,policy:admitted,ownedPositions:[],productionCandidates:fresh,now}).approved,true);assert.ok(validateClaimedPlan({plan,policy:admitted,ownedPositions:[],productionCandidates:[{...fresh[0],state:'PREFILTERED'}],now}).reasonCodes.includes('P6_CLAIM_PRODUCTION_ADMISSION_INVALID'));assert.ok(validateClaimedPlan({plan,policy:admitted,ownedPositions:[],productionCandidates:[{...fresh[0],lastSeenAt:'2026-08-12T23:40:00.000Z'}],now}).reasonCodes.includes('P6_CLAIM_PRODUCTION_ADMISSION_INVALID'));assert.ok(validateClaimedPlan({plan,policy,ownedPositions:[],productionCandidates:fresh,now}).reasonCodes.includes('P6_CLAIM_POOL_NOT_ALLOWLISTED'));});
