import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {productionPolicyHealthcheckPoolAddressesFromPolicy,getProductionNewEntryEligiblePools,isPostEvidenceProductionEvaluationCandidate,positionUsdValueToSolLamports,runAutonomousDecisionProbe} from '../.build/packages/phase7-production-service/src/index.js';
test('P7-R08 production app exposes once/start/status/evidence commands',()=>{const p=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url)));for(const k of ['production:once','production:start','production:status','production:evidence'])assert.equal(typeof p.scripts[k],'string');});
test('P7-R08 production service and app contain no direct signer/submission path',()=>{for(const f of ['../packages/phase7-production-service/src/index.ts','../apps/production/src/main.ts']){const s=fs.readFileSync(new URL(f,import.meta.url),'utf8');assert.doesNotMatch(s,/phase6-mainnet-signer|execution-submission|sendRawTransaction|sendTransaction|Keypair\.fromSecretKey/);}});
test('P7-R08 autonomous decision probe preserves only the public owner address and strips an external position address',async()=>{const fakeDir=new URL('../.build',import.meta.url);assert.ok(fs.existsSync(fakeDir));const src=fs.readFileSync(new URL('../packages/phase7-production-service/src/index.ts',import.meta.url),'utf8');assert.doesNotMatch(src,/delete childEnv\.LPFORGE_OPERATOR_OWNER_ADDRESS/);assert.match(src,/delete childEnv\.LPFORGE_PREPARE_POSITION_ADDRESS/);assert.match(src,/LPFORGE_LIVE_EXECUTION:'false'/);});
test('P7-R08 static policy pools remain healthcheck-only while the new-entry universe is dynamically admitted',()=>{assert.deepEqual(productionPolicyHealthcheckPoolAddressesFromPolicy({pools:[{address:'pool-a'},{address:'pool-b'},{address:'pool-a'}]}),['pool-a','pool-b']);const src=fs.readFileSync(new URL('../packages/phase7-production-service/src/index.ts',import.meta.url),'utf8');assert.match(src,/getProductionNewEntryEligiblePools/);assert.match(src,/LPFORGE_DISCOVERY_OPERATOR_ENABLED/);assert.match(src,/PostEvidenceEvaluation/);assert.match(src,/Static policy membership.*new-entry universe/s);assert.doesNotMatch(src,/LPFORGE_PRODUCTION_POOL_ADDRESSES/);});

test('P7 probes ACTIVE pools plus only bounded fresh post-evidence QUALIFIED handoffs',async()=>{const future=new Date(Date.now()+60_000).toISOString(),past=new Date(Date.now()-1_000).toISOString(),store={listDiscoveryCandidates:async()=>[{poolAddress:'active',state:'ACTIVE_CANDIDATE',tier:'A',payload:{}},{poolAddress:'handoff',state:'QUALIFIED',tier:'A',payload:{postEvidenceEvaluationState:'ELIGIBLE',postEvidenceEvaluationExpiresAt:future}},{poolAddress:'waiting',state:'QUALIFIED',tier:'A',payload:{}},{poolAddress:'expired',state:'QUALIFIED',tier:'A',payload:{postEvidenceEvaluationState:'ELIGIBLE',postEvidenceEvaluationExpiresAt:past}}]};const env={LPFORGE_DISCOVERY_OPERATOR_ENABLED:'true',LPFORGE_EXECUTION_POLICY_PATH:new URL('../policies/live-execution-policy.json',import.meta.url).pathname,LPFORGE_PRODUCTION_OPERATOR_MAX_POOLS:'10'};const pools=await getProductionNewEntryEligiblePools(store,env,'test');assert.ok(pools.includes('handoff'));assert.ok(pools.includes('active'));assert.equal(pools.includes('waiting'),false);assert.equal(pools.includes('expired'),false);assert.equal(isPostEvidenceProductionEvaluationCandidate({state:'QUALIFIED',tier:'A',payload:{postEvidenceEvaluationState:'ELIGIBLE',postEvidenceEvaluationExpiresAt:future}},new Date().toISOString()),true);});

test('P7-R08 machine summary proves completion and decoder telemetry even when INFO logs are absent',async()=>{const {parsePhase7OperatorProbeOutput}=await import('../.build/packages/phase7-production-service/src/index.js');const line=JSON.stringify({event:'lpforge_operator_machine_summary',transactionsScanned:17,decodedSwapEvents:9,eventDecodeWarnings:2,signing:false,submission:false});const r=parsePhase7OperatorProbeOutput(line+'\n',0);assert.equal(r.operationalCycleComplete,true);assert.equal(r.transactionsScanned,17);assert.equal(r.decodedSwapEvents,9);assert.equal(r.eventDecodeWarnings,2);});
test('P7-R08 portfolio valuation converts a live position through the current SOL price',()=>{assert.equal(positionUsdValueToSolLamports(2.25,75),30_000_000n);assert.throws(()=>positionUsdValueToSolLamports(Number.NaN,75),/P7_PORTFOLIO_POSITION_VALUATION_UNAVAILABLE/);});
test('P7-R08 completed live-once probe terminates so multi-pool production can advance',()=>{const src=fs.readFileSync(new URL('../apps/operator/src/main.ts',import.meta.url),'utf8');assert.match(src,/else if \(cmd === "live-once"\) \{\s*await liveOnce\(\);[\s\S]*?process\.exit\(0\);\s*\}/);});
test('P7-R08 position observation remains read-only and runs before recovery gating',()=>{const service=fs.readFileSync(new URL('../packages/phase7-production-service/src/index.ts',import.meta.url),'utf8'),operator=fs.readFileSync(new URL('../apps/operator/src/main.ts',import.meta.url),'utf8');assert.match(service,/runAutonomousPositionObservationProbe/);assert.ok(service.indexOf('runAutonomousPositionObservationProbe({cwd:input.cwd,env:input.env})')<service.indexOf('loadPhase7RecoveryFacts'));assert.match(operator,/observe-owned-positions/);assert.match(operator,/positionObservationOnly: true/);});
test('M0066 metric persistence normalizes a recovered MFE timestamp before PostgreSQL binding',()=>{const src=fs.readFileSync(new URL('../packages/db/src/index.ts',import.meta.url),'utf8');assert.match(src,/v\.mfeObservedAt\?toIsoTimestamp\(v\.mfeObservedAt\):null/);});
test('global Production selection is canonical, deadline-bounded, fail-closed, and cannot prepare every evaluated pool',()=>{const service=fs.readFileSync(new URL('../packages/phase7-production-service/src/index.ts',import.meta.url),'utf8'),operator=fs.readFileSync(new URL('../apps/operator/src/main.ts',import.meta.url),'utf8');assert.match(service,/runProductionGlobalSelectionCycle/);assert.match(service,/P7_GLOBAL_SELECTION_CYCLE_DEADLINE_MS=120_000/);assert.match(service,/GLOBAL_CYCLE_DEADLINE_REACHED/);assert.match(service,/GLOBAL_COVERAGE_INCOMPLETE/);assert.match(service,/LPFORGE_P7_PLAN_DISPATCH_ENABLED:'false'/);assert.match(service,/LPFORGE_GLOBAL_SELECTED_CANDIDATE_ID/);assert.doesNotMatch(service,/GLOBAL_POOL_SELECTION_SHADOW|GLOBAL_POOL_SELECTION_AUTHORITATIVE/);assert.match(operator,/globalSelectionMatches/);});
test('global selection reads the canonical Production candidate contract rather than recommendation tables',()=>{const service=fs.readFileSync(new URL('../packages/phase7-production-service/src/index.ts',import.meta.url),'utf8'),db=fs.readFileSync(new URL('../packages/db/src/index.ts',import.meta.url),'utf8'),operator=fs.readFileSync(new URL('../apps/operator/src/main.ts',import.meta.url),'utf8');assert.match(service,/LPFORGE_PRODUCTION_GLOBAL_SELECTION_CYCLE_ID/);assert.match(service,/operational_state/);assert.match(db,/SELECT \* FROM execution\.production_global_candidates/);assert.match(operator,/productionGlobalCandidateFromOperationalResult/);});



test('P7 grants its operator only the scoped plan-provenance capability, never signing capability',()=>{
 const src=fs.readFileSync(new URL('../packages/phase7-production-service/src/index.ts',import.meta.url),'utf8');
 assert.match(src,/loadProducerPlanProvenanceSecret/);
 assert.match(src,/childEnv\.LPFORGE_PLAN_PROVENANCE_SECRET=provenanceSecret/);
 for(const key of ['LPFORGE_P6_PRIVATE_KEY','LPFORGE_P6_PRIVATE_WRITE_RPC_URL','LPFORGE_P6_SIGNER_BACKEND_ID','LIVE_SUBMISSION','LPFORGE_P6_EXECUTION_RUNNER_ENABLED'])assert.match(src,new RegExp('delete childEnv\\.'+key));
});
