import test from 'node:test';import assert from 'node:assert/strict';
import {runPhase7RecoveryRuntimeTick} from '../.build/packages/phase7-live-runtime/src/index.js';
const now='2026-08-13T03:00:00Z';
const makeStore=(facts={previousCompletedCycleKeys:[],completedEconomicActionKeys:[],recoveryQueueCount:0,unknownSubmissionCount:0,unresolvedReconciliationDebt:0})=>({claimPhase7RuntimeLease:async()=>({generation:1}),loadPhase7RecoveryFacts:async()=>facts,insertPhase7RuntimeCycle:async()=>true});
test('P7-R06 restart scans recovery state before decision and remains observe-only under observe authority',async()=>{const r=await runPhase7RecoveryRuntimeTick({store:makeStore(),runtimeId:'prod',instanceId:'i',cycleKey:'c',now,leaseTtlMs:60000,restarted:true,control:{authorityMode:'OBSERVE_ONLY',healthStatus:'HEALTHY',newEconomicActionAllowed:false}});assert.equal(r.recoveryScanCompleted,true);assert.equal(r.plan,'OBSERVE_ONLY');assert.equal(r.newEconomicActionAllowed,false);});
test('P7-R06 unresolved recovery facts force RECOVER_ONLY',async()=>{const r=await runPhase7RecoveryRuntimeTick({store:makeStore({previousCompletedCycleKeys:[],completedEconomicActionKeys:[],recoveryQueueCount:1,unknownSubmissionCount:1,unresolvedReconciliationDebt:1}),runtimeId:'prod',instanceId:'i',cycleKey:'c',now,leaseTtlMs:60000,restarted:true,control:{authorityMode:'LIMITED_LIVE',healthStatus:'HEALTHY',newEconomicActionAllowed:true}});assert.equal(r.plan,'RECOVER_ONLY');assert.equal(r.newEconomicActionAllowed,false);});
test('P7-R06 a reconciliation-required plan hold is recovery work even when its journal is terminalized',async()=>{const r=await runPhase7RecoveryRuntimeTick({store:makeStore({previousCompletedCycleKeys:[],completedEconomicActionKeys:[],recoveryQueueCount:1,unknownSubmissionCount:0,unresolvedReconciliationDebt:0}),runtimeId:'prod',instanceId:'i',cycleKey:'hold',now,leaseTtlMs:60000,restarted:false,control:{authorityMode:'PRODUCTION',healthStatus:'HEALTHY',newEconomicActionAllowed:true}});assert.equal(r.plan,'RECOVER_ONLY');assert.equal(r.newEconomicActionAllowed,false);});
test('P7-R06 duplicate cycle and economic action keys fail closed',async()=>{let r=await runPhase7RecoveryRuntimeTick({store:makeStore({previousCompletedCycleKeys:['c'],completedEconomicActionKeys:[],recoveryQueueCount:0,unknownSubmissionCount:0,unresolvedReconciliationDebt:0}),runtimeId:'prod',instanceId:'i',cycleKey:'c',now,leaseTtlMs:60000,restarted:false,control:{authorityMode:'LIMITED_LIVE',healthStatus:'HEALTHY',newEconomicActionAllowed:true}});assert.equal(r.plan,'HOLD');r=await runPhase7RecoveryRuntimeTick({store:makeStore({previousCompletedCycleKeys:[],completedEconomicActionKeys:['a'],recoveryQueueCount:0,unknownSubmissionCount:0,unresolvedReconciliationDebt:0}),runtimeId:'prod',instanceId:'i',cycleKey:'c2',economicActionKey:'a',now,leaseTtlMs:60000,restarted:false,control:{authorityMode:'LIMITED_LIVE',healthStatus:'HEALTHY',newEconomicActionAllowed:true}});assert.equal(r.plan,'HOLD');});
test('P7-R06 lease refusal prevents runtime cycle ownership',async()=>{const store={...makeStore(),claimPhase7RuntimeLease:async()=>undefined};const r=await runPhase7RecoveryRuntimeTick({store,runtimeId:'prod',instanceId:'b',cycleKey:'c',now,leaseTtlMs:60000,restarted:true,control:{authorityMode:'OBSERVE_ONLY',healthStatus:'HEALTHY',newEconomicActionAllowed:false}});assert.equal(r.leaseAcquired,false);assert.equal(r.plan,'HOLD');assert.equal(r.cycleInserted,false);});
