import assert from 'node:assert/strict';
import test from 'node:test';
import {validateClaimedPlan,validateFreshPhase7ExecutionControl} from '../.build/packages/phase6-claim-guard/src/index.js';

const policy={schemaVersion:1,policyId:'p',status:'ENABLED',approvalTtlMs:15000,minDevnetConfirmedRuns:1,maxActionsPerDay:2,maxOpenPositions:2,pools:[{address:'POOL',maxCapitalLamports:20_000_000n,maxOpenPositions:1}]};
const controlObservedAt='2026-08-13T00:04:30.000Z';
const base={planId:'p',intentId:'i',idempotencyKey:'k',action:'OPEN',poolAddress:'POOL',ownerAddress:'OWNER',thesisId:'t',observedAt:'2026-08-13T00:04:45.000Z',expiresAt:'2026-08-13T00:09:45.000Z',intentPayload:{},planPayload:{provenance:{producer:'LPFORGE_PRODUCTION',schemaVersion:1,intentId:'i',poolAddress:'POOL',observedAt:'2026-08-13T00:04:45.000Z',phase7Control:{decisionId:'control-1',cycleKey:'cycle-1',observedAt:controlObservedAt}},intent:{capitalLamports:'20000000'}},steps:[]};
const now='2026-08-13T00:05:00.000Z',control={decisionId:'control-1',cycleKey:'cycle-1',authorityMode:'PRODUCTION',healthStatus:'HEALTHY',driftStatus:'WATCH',safetyMode:'NORMAL',newEconomicActionAllowed:true,observedAt:controlObservedAt};
test('claim guard rejects forged provenance, unallowlisted pool, excess capital and position limits',()=>{const input={policy,ownedPositions:[],phase7Control:control,now};assert.equal(validateClaimedPlan({plan:base,...input}).approved,true);assert.ok(validateClaimedPlan({plan:{...base,planPayload:{}},...input}).reasonCodes.includes('P6_CLAIM_PROVENANCE_INVALID'));assert.ok(validateClaimedPlan({plan:{...base,poolAddress:'OTHER'},...input}).reasonCodes.includes('P6_CLAIM_POOL_NOT_ALLOWLISTED'));assert.ok(validateClaimedPlan({plan:{...base,planPayload:{...base.planPayload,intent:{capitalLamports:'20000001'}}},...input}).reasonCodes.includes('P6_CLAIM_CAPITAL_EXCEEDS_POOL_POLICY'));assert.ok(validateClaimedPlan({plan:base,policy,ownedPositions:[{lifecycle_state:'OPEN',pool_address:'POOL'}],phase7Control:control,now}).reasonCodes.includes('P6_CLAIM_POSITION_LIMIT'));});
test('claim guard requires LPForge ownership and exact chain position truth for every management action',()=>{const plan={...base,action:'CLOSE',positionAddress:'POS',planPayload:{...base.planPayload,intent:{capitalLamports:'0'}}};assert.ok(validateClaimedPlan({plan,policy,ownedPositions:[]}).reasonCodes.includes('P6_CLAIM_POSITION_NOT_OWNED'));assert.equal(validateClaimedPlan({plan,policy,ownedPositions:[{lifecycle_state:'OPEN',position_address:'POS',owner_address:'OWNER',pool_address:'POOL'}],positionTruth:{owner:'OWNER',pool:'POOL'}}).approved,true);});
test('claim guard admits only fresh WSOL-token-Y Tier-A pools under the versioned execution policy',()=>{const admitted={...policy,productionAdmission:{enabled:true,eligibleTiers:['A'],maxCandidates:1,maxCandidateAgeMs:900000,maxCapitalLamports:20_000_000n,maxOpenPositions:1}},plan={...base,poolAddress:'DISCOVERED',planPayload:{...base.planPayload,provenance:{...base.planPayload.provenance,poolAddress:'DISCOVERED'}}},fresh=[{poolAddress:'DISCOVERED',state:'ACTIVE_CANDIDATE',tier:'A',lastSeenAt:'2026-08-13T00:04:00.000Z',tokenYMint:'So11111111111111111111111111111111111111112',pairedTokenMint:'TOKEN'}];assert.equal(validateClaimedPlan({plan,policy:admitted,ownedPositions:[],productionCandidates:fresh,phase7Control:control,now}).approved,true);assert.ok(validateClaimedPlan({plan,policy:admitted,ownedPositions:[],productionCandidates:[{...fresh[0],tokenYMint:'TOKEN'}],phase7Control:control,now}).reasonCodes.includes('P6_PRODUCTION_REQUIRES_WSOL_TOKEN_Y'));assert.ok(validateClaimedPlan({plan,policy:admitted,ownedPositions:[],productionCandidates:[{...fresh[0],state:'PREFILTERED'}],phase7Control:control,now}).reasonCodes.includes('P6_CLAIM_PRODUCTION_ADMISSION_INVALID'));assert.ok(validateClaimedPlan({plan,policy:admitted,ownedPositions:[],productionCandidates:[{...fresh[0],lastSeenAt:'2026-08-12T23:40:00.000Z'}],phase7Control:control,now}).reasonCodes.includes('P6_CLAIM_PRODUCTION_ADMISSION_INVALID'));assert.ok(validateClaimedPlan({plan,policy,ownedPositions:[],productionCandidates:fresh,phase7Control:control,now}).reasonCodes.includes('P6_CLAIM_POOL_NOT_ALLOWLISTED'));});
test('risk-increasing claims require fresh Phase-7 production control and enforce daily action limit',()=>{assert.deepEqual(validateFreshPhase7ExecutionControl(control,now),[]);assert.ok(validateClaimedPlan({plan:base,policy,ownedPositions:[],now}).reasonCodes.includes('P6_CLAIM_P7_CONTROL_MISSING'));assert.ok(validateClaimedPlan({plan:{...base,planPayload:{...base.planPayload,provenance:{...base.planPayload.provenance,phase7Control:undefined}}},policy,ownedPositions:[],phase7Control:control,now}).reasonCodes.includes('P6_CLAIM_P7_CONTROL_BINDING_MISSING'));assert.ok(validateFreshPhase7ExecutionControl({...control,safetyMode:'EMERGENCY_ONLY'},now).includes('P6_CLAIM_P7_SAFETY_NOT_NORMAL'));assert.ok(validateFreshPhase7ExecutionControl({...control,observedAt:'2026-08-12T23:00:00.000Z'},now).includes('P6_CLAIM_P7_CONTROL_STALE'));assert.ok(validateClaimedPlan({plan:base,policy,ownedPositions:[],phase7Control:{...control,newEconomicActionAllowed:false},actionsToday:2,now}).reasonCodes.includes('P6_CLAIM_P7_NEW_ACTION_BLOCKED'));assert.ok(validateClaimedPlan({plan:base,policy,ownedPositions:[],phase7Control:control,actionsToday:2,now}).reasonCodes.includes('P6_CLAIM_DAILY_ACTION_LIMIT'));});
test('risk-increasing claims bind to the exact authenticated P7 decision across newer controls and recovery',()=>{
 const input={plan:base,policy,ownedPositions:[],now};
 assert.equal(validateClaimedPlan({...input,phase7Control:control}).approved,true,'the exact fresh decision passes the binding check');
 const newer={...control,decisionId:'control-2',cycleKey:'cycle-2',observedAt:'2026-08-13T00:04:50.000Z'};
 const older={...control,decisionId:'control-0',cycleKey:'cycle-0',observedAt:'2026-08-13T00:04:20.000Z'};
 for(const phase7Control of [newer,older])assert.ok(validateClaimedPlan({...input,phase7Control}).reasonCodes.includes('P6_CLAIM_P7_CONTROL_BINDING_MISMATCH'),'a different P7 decision never substitutes for the bound decision');
 assert.ok(validateClaimedPlan({...input,phase7Control:{...control,decisionId:undefined}}).reasonCodes.includes('P6_CLAIM_P7_CONTROL_ID_MISSING'),'a control without an id fails closed');
 assert.ok(validateClaimedPlan({...input,phase7Control:{...control,observedAt:'2026-08-13T00:00:00.000Z'}}).reasonCodes.includes('P6_CLAIM_P7_CONTROL_STALE'),'identity does not bypass freshness');
 assert.ok(validateClaimedPlan({...input,phase7Control:{...control,safetyMode:'EMERGENCY_ONLY'}}).reasonCodes.includes('P6_CLAIM_P7_SAFETY_NOT_NORMAL'),'identity does not bypass safety');
 assert.ok(validateClaimedPlan({...input,phase7Control:{...control,authorityMode:'OBSERVE_ONLY'}}).reasonCodes.includes('P6_CLAIM_P7_AUTHORITY_NOT_PRODUCTION'),'identity does not bypass authority');
 assert.ok(validateClaimedPlan({...input,phase7Control:{...control,newEconomicActionAllowed:false}}).reasonCodes.includes('P6_CLAIM_P7_NEW_ACTION_BLOCKED'),'identity does not bypass new-action policy');
 // validateClaimedPlan is stateless: this models a persisted A-bound plan
 // claimed after an execution-process restart under a newer control B.
 assert.ok(validateClaimedPlan({...input,phase7Control:newer}).reasonCodes.includes('P6_CLAIM_P7_CONTROL_BINDING_MISMATCH'),'restart/recovery cannot rebind the persisted plan');
});
test('protective actions are exempt from the daily action cap',()=>{const owned=[{lifecycle_state:'OPEN',position_address:'POS',owner_address:'OWNER',pool_address:'POOL'}];for(const action of ['CLOSE','EMERGENCY_CLOSE','REDUCE','CLAIM']){const plan={...base,action,positionAddress:'POS',planPayload:{...base.planPayload,intent:{capitalLamports:'0'}}};assert.equal(validateClaimedPlan({plan,policy,ownedPositions:owned,positionTruth:{owner:'OWNER',pool:'POOL'},actionsToday:2,now}).approved,true,`${action} must never be starved by the daily cap`);}assert.ok(validateClaimedPlan({plan:base,policy,ownedPositions:[],phase7Control:control,actionsToday:2,now}).reasonCodes.includes('P6_CLAIM_DAILY_ACTION_LIMIT'));});
test('operator separates risk-increasing P7 authority from protective management dispatch',async()=>{const src=await import('node:fs/promises').then(fs=>fs.readFile('apps/operator/src/main.ts','utf8'));assert.ok(src.includes('allowRiskIncreasingPlans'),'new or increased exposure requires the P7 new-economic-action permit');assert.ok(src.includes('allowProtectiveManagementPlans'),'CLOSE/REDUCE/CLAIM have their independent protective dispatch path');assert.ok(src.includes('capitalLamports: position.initialCapitalLamports'),'management plans carry their remaining economic basis for execution-cost checks');});
