import assert from 'node:assert/strict';
import test from 'node:test';
import {MemoryExecutionJournalStore,determineRecoveryAction} from '../.build/packages/execution-recovery/src/index.js';
import {advanceManagementExecutionPlan,createManagementExecutionPlan} from '../.build/packages/management-execution/src/index.js';
import {buildTransactionPlan} from '../.build/packages/transaction-planner/src/index.js';

const now='2026-08-13T00:00:00.000Z',base={cluster:'mainnet-beta',ownerAddress:'OWNER',poolAddress:'POOL',positionAddress:'OLD',thesisId:'TH',observedAt:now,expiresAt:'2026-08-13T00:05:00.000Z',lowerBinId:90,upperBinId:110,strategy:'CURVE'};
test('crash matrix: a prepared journal is single-owner and rejects concurrent state advancement',()=>{const s=new MemoryExecutionJournalStore(),j={journalId:'j',idempotencyKey:'k',planId:'p',state:'SIGNED',version:1,updatedAt:now,payload:{},lastValidBlockHeight:100};assert.equal(s.create(j).created,true);assert.equal(s.create(j).created,false);s.transition('k',1,'SUBMITTED',now);assert.throws(()=>s.transition('k',1,'CONFIRMED',now),/VERSION_CONFLICT/);});
test('crash matrix: no resend before expiry, rebuild only after absence is proven',()=>{const journal={journalId:'j',idempotencyKey:'k',planId:'p',state:'SUBMITTED',version:1,updatedAt:now,payload:{},lastValidBlockHeight:100};assert.equal(determineRecoveryAction({journal,currentBlockHeight:99,confirmationStatus:'UNKNOWN',economicEffect:'UNKNOWN'}),'WAIT_DO_NOT_RESUBMIT');assert.equal(determineRecoveryAction({journal,currentBlockHeight:101,confirmationStatus:'EXPIRED',economicEffect:'ABSENT'}),'REBUILD_WITH_NEW_BLOCKHASH');assert.equal(determineRecoveryAction({journal,currentBlockHeight:101,confirmationStatus:'UNKNOWN',economicEffect:'PRESENT'}),'MARK_RECONCILED');});
test('crash matrix: reshape/rebalance cannot reach replacement open before old removal and wallet refresh',()=>{const plan=buildTransactionPlan({...base,action:'RESHAPE'}),created=createManagementExecutionPlan(plan),remove=advanceManagementExecutionPlan(created,'REMOVE_BUILT',now),reconciled=advanceManagementExecutionPlan(remove,'REMOVE_RECONCILED',now),wallet=advanceManagementExecutionPlan(reconciled,'WALLET_TRUTH_CONSISTENT',now),built=advanceManagementExecutionPlan(wallet,'REPLACEMENT_BUILT',now);assert.equal(created.stage,'REMOVE_OLD');assert.equal(remove.stage,'AWAIT_REMOVE_RECONCILIATION');assert.equal(reconciled.stage,'REFRESH_WALLET_TRUTH');assert.equal(wallet.stage,'BUILD_REPLACEMENT');assert.equal(built.stage,'OPEN_REPLACEMENT');});
test('crash matrix: close-family plans complete only when the position is provably gone',()=>{const journal=(action,state='SUBMITTED')=>({journalId:'j',idempotencyKey:'k',planId:'p',state,version:1,updatedAt:now,payload:{action}});assert.equal(determineRecoveryAction({journal:journal('CLOSE'),currentBlockHeight:1,confirmationStatus:'CONFIRMED',economicEffect:'PRESENT'}),'MARK_RECONCILED');assert.equal(determineRecoveryAction({journal:journal('EMERGENCY_CLOSE'),currentBlockHeight:1,confirmationStatus:'FINALIZED',economicEffect:'PRESENT'}),'MARK_RECONCILED');assert.equal(determineRecoveryAction({journal:journal('CLOSE'),currentBlockHeight:1,confirmationStatus:'CONFIRMED',economicEffect:'ABSENT'}),'HOLD_FOR_OPERATOR');assert.equal(determineRecoveryAction({journal:journal('CLOSE'),currentBlockHeight:1,confirmationStatus:'UNKNOWN',economicEffect:'PRESENT'}),'HOLD_FOR_OPERATOR');assert.equal(determineRecoveryAction({journal:journal('CLOSE'),currentBlockHeight:1,confirmationStatus:'FAILED',economicEffect:'PRESENT'}),'HOLD_FOR_OPERATOR');assert.equal(determineRecoveryAction({journal:journal('CLOSE'),currentBlockHeight:1,confirmationStatus:'CONFIRMED',economicEffect:'UNKNOWN'}),'HOLD_FOR_OPERATOR');assert.equal(determineRecoveryAction({journal:journal('OPEN'),currentBlockHeight:1,confirmationStatus:'CONFIRMED',economicEffect:'PRESENT'}),'RECONCILE_FIRST');assert.equal(determineRecoveryAction({journal:journal('OPEN'),currentBlockHeight:1,confirmationStatus:'UNKNOWN',economicEffect:'PRESENT'}),'MARK_RECONCILED');});
