import test from 'node:test';import assert from 'node:assert/strict';import {governPhase7Portfolio} from '../.build/packages/phase7-portfolio-governor/src/index.js';
const policy={minReserveLamports:10n,maxDeployedBps:6000,maxPoolBps:3000,maxTokenBps:4000,maxDailyDrawdownBps:600,maxRollingDrawdownBps:1000,maxOpenPositions:3,maxSnapshotAgeMs:30000,permitTtlMs:30000};
const snap={observedAt:'2026-08-13T00:49:50Z',walletBalanceLamports:100n,deployedLamports:20n,pendingReservedLamports:5n,poolExposureLamports:{p:10n},poolPendingLamports:{p:2n},tokenExposureLamports:{t:12n},tokenPendingLamports:{t:3n},dailyStartEquityLamports:100n,currentEquityLamports:100n,peakEquityLamports:105n,openPositions:1,unresolvedReconciliationDebt:0};
const req={requestId:'r1',pool:'p',token:'t',requestedLamports:10n,action:'OPEN',now:'2026-08-13T00:50:00Z'};
test('P7-06 permits only capital that fits wallet, global, pool, token and position budgets',()=>{const r=governPhase7Portfolio(snap,req,policy);assert.equal(r.decision,'APPROVE');assert.equal(r.approvedLamports,10n);assert.equal(r.permit?.singleUse,true);assert.equal(r.permit?.autonomousScaling,false);});
test('P7-06 pending reservations count against exposure and wallet capacity',()=>{const r=governPhase7Portfolio({...snap,pendingReservedLamports:85n},req,policy);assert.equal(r.decision,'BLOCK');assert.ok(r.reasonCodes.includes('P7_PORTFOLIO_WALLET_RESERVE'));assert.ok(r.reasonCodes.includes('P7_PORTFOLIO_GLOBAL_EXPOSURE'));});
test('P7-06 pool and token concentration block independently',()=>{const pool=governPhase7Portfolio({...snap,poolExposureLamports:{p:25n}},req,policy);assert.ok(pool.reasonCodes.includes('P7_PORTFOLIO_POOL_EXPOSURE'));const token=governPhase7Portfolio({...snap,tokenExposureLamports:{t:35n}},req,policy);assert.ok(token.reasonCodes.includes('P7_PORTFOLIO_TOKEN_EXPOSURE'));});
test('P7-06 stale snapshot, reconciliation debt and position limit fail closed',()=>{const r=governPhase7Portfolio({...snap,observedAt:'2026-08-13T00:48:00Z',unresolvedReconciliationDebt:1,openPositions:3},req,policy);assert.equal(r.decision,'BLOCK');for(const x of ['P7_PORTFOLIO_SNAPSHOT_STALE','P7_PORTFOLIO_RECONCILIATION_DEBT','P7_PORTFOLIO_POSITION_LIMIT'])assert.ok(r.reasonCodes.includes(x));});
test('P7-06 daily and rolling drawdown breakers independently suppress allocation',()=>{const r=governPhase7Portfolio({...snap,currentEquityLamports:80n,dailyStartEquityLamports:100n,peakEquityLamports:110n},req,policy);assert.equal(r.decision,'BLOCK');assert.ok(r.reasonCodes.includes('P7_PORTFOLIO_DAILY_DRAWDOWN'));assert.ok(r.reasonCodes.includes('P7_PORTFOLIO_ROLLING_DRAWDOWN'));});
