import test from 'node:test';import assert from 'node:assert/strict';import {evaluatePhase7Promotion} from '../.build/packages/phase7-promotion/src/index.js';
const health={status:'HEALTHY',observedAt:'2026-08-13T01:20:00Z',domainStatus:{},staleDomains:[],missingDomains:[],reasonCodes:[],newEntriesAllowed:true,managementWritesAllowed:true,emergencyCloseAllowed:true};
const phase6={implementationStatus:'PASS',operationalStatus:'PASS',productionPromotion:'LIMITED_LIVE_ELIGIBLE',reasonCodes:[],autonomousScalingEnabled:false,productionAuthorityIssued:false};
const bundle=(target,complete=true)=>({target,policyHash:'p',bundleHash:'b',complete,reasonCodes:complete?[]:['missing'],evidence:{},automaticPromotion:false});
const live={runs:5,fullyReconciledRuns:5,failedRuns:0,duplicateEconomicActions:0,unresolvedReconciliationDebt:0,reconciliationMismatchRate:0,maxDrawdownFraction:.02,emergencyStopEvidence:true,rollbackTested:true};const policy={minLimitedLiveRuns:5,minFullyReconciledLimitedLiveRuns:5,maxLimitedLiveFailures:0,maxReconciliationMismatchRate:.01,maxDrawdownFraction:.05,requireEmergencyStopEvidence:true,requireRollbackTest:true};
test('P7-09 limited-live eligibility requires P6 readiness, complete bundle and healthy operations',()=>{const r=evaluatePhase7Promotion({target:'LIMITED_LIVE',bundle:bundle('LIMITED_LIVE'),health,phase6,limitedLive:live,policy});assert.equal(r.operationalStatus,'PASS');assert.equal(r.promotion,'LIMITED_LIVE_ELIGIBLE');assert.equal(r.productionAuthorityIssued,false);assert.equal(r.scalingEnabled,false);});
test('P7-09 production eligibility requires reconciled limited-live evidence and still issues no authority',()=>{const r=evaluatePhase7Promotion({target:'PRODUCTION',bundle:bundle('PRODUCTION'),health,phase6,limitedLive:live,policy});assert.equal(r.operationalStatus,'PASS');assert.equal(r.promotion,'PRODUCTION_ELIGIBLE');assert.equal(r.productionAuthorityIssued,false);assert.equal(r.automaticPolicyPromotion,false);});
test('P7-09 insufficient evidence holds without pretending failure',()=>{const r=evaluatePhase7Promotion({target:'PRODUCTION',bundle:bundle('PRODUCTION'),health,phase6,limitedLive:{...live,runs:2,fullyReconciledRuns:2,emergencyStopEvidence:false},policy});assert.equal(r.operationalStatus,'HOLD');assert.equal(r.promotion,'NOT_ELIGIBLE');assert.ok(r.reasonCodes.includes('P7_PROMOTION_LIMITED_LIVE_RUNS_INSUFFICIENT'));});
test('P7-09 reconciliation debt, duplicate actions, mismatch or drawdown are hard blocks',()=>{const r=evaluatePhase7Promotion({target:'PRODUCTION',bundle:bundle('PRODUCTION'),health,phase6,limitedLive:{...live,unresolvedReconciliationDebt:1,duplicateEconomicActions:1,reconciliationMismatchRate:.02,maxDrawdownFraction:.06},policy});assert.equal(r.operationalStatus,'BLOCK');for(const x of ['P7_PROMOTION_RECONCILIATION_DEBT','P7_PROMOTION_DUPLICATE_ECONOMIC_ACTION','P7_PROMOTION_MISMATCH_RATE_LIMIT','P7_PROMOTION_DRAWDOWN_LIMIT'])assert.ok(r.reasonCodes.includes(x));});
