import test from 'node:test';import assert from 'node:assert/strict';
import {assessPhase7Health,defaultPhase7HealthPolicy} from '../.build/packages/phase7-health/src/index.js';
const now='2026-08-13T00:20:00.000Z';
const obs=(domain,status='HEALTHY',observedAt='2026-08-13T00:19:50.000Z',reasonCodes=[])=>({domain,status,observedAt,reasonCodes});
const all=()=>['RPC','METEORA_API','DATABASE','DECISION','EXECUTION','PORTFOLIO','RECONCILIATION'].map(d=>obs(d));

test('P7-03 healthy required domains allow entries and management',()=>{const r=assessPhase7Health(all(),defaultPhase7HealthPolicy,now);assert.equal(r.status,'HEALTHY');assert.equal(r.newEntriesAllowed,true);assert.equal(r.managementWritesAllowed,true);});
test('P7-03 stale hard domain fails closed for new entries and management writes',()=>{const xs=all().filter(x=>x.domain!=='RPC');xs.push(obs('RPC','HEALTHY','2026-08-13T00:19:00.000Z'));const r=assessPhase7Health(xs,defaultPhase7HealthPolicy,now);assert.equal(r.status,'CRITICAL');assert.equal(r.newEntriesAllowed,false);assert.equal(r.managementWritesAllowed,false);assert.ok(r.reasonCodes.includes('P7_HEALTH_RPC_STALE'));assert.equal(r.emergencyCloseAllowed,true);});
test('P7-03 degraded API suppresses new entries but preserves management',()=>{const xs=all().map(x=>x.domain==='METEORA_API'?obs('METEORA_API','DEGRADED',x.observedAt,['P7_API_SCHEMA_WARNING']):x);const r=assessPhase7Health(xs,defaultPhase7HealthPolicy,now);assert.equal(r.status,'DEGRADED');assert.equal(r.newEntriesAllowed,false);assert.equal(r.managementWritesAllowed,true);});
test('P7-03 reconciliation critical is a hard write gate',()=>{const xs=all().map(x=>x.domain==='RECONCILIATION'?obs('RECONCILIATION','CRITICAL',x.observedAt,['P7_RECONCILIATION_DEBT']):x);const r=assessPhase7Health(xs,defaultPhase7HealthPolicy,now);assert.equal(r.status,'CRITICAL');assert.equal(r.managementWritesAllowed,false);assert.ok(r.reasonCodes.includes('P7_RECONCILIATION_DEBT'));});
test('P7-03 missing required domain is critical and future evidence is rejected',()=>{const missing=assessPhase7Health(all().filter(x=>x.domain!=='DATABASE'),defaultPhase7HealthPolicy,now);assert.equal(missing.status,'CRITICAL');assert.ok(missing.missingDomains.includes('DATABASE'));assert.throws(()=>assessPhase7Health([...all(),obs('RPC','HEALTHY','2026-08-13T00:20:01.000Z')],defaultPhase7HealthPolicy,now),/FUTURE_OBSERVATION/);});
