import test from 'node:test';
import assert from 'node:assert/strict';
import {deepScreenPool,computeDirectionalToxicity,estimateOpportunityHalfLife} from '../.build/packages/pool-deep-screen/src/index.js';
import {assignUniverseTiers} from '../.build/packages/pool-universe/src/index.js';
import {deriveDiscoveryLifecycleState,selectDeepScreenSlice} from '../.build/packages/discovery-runtime/src/index.js';
import {evaluateDiscoveryStrategies} from '../.build/packages/discovery-strategy-evaluation/src/index.js';
import {makePrediction,calibratePredictions,buildReputation,selectBaselines,purgeEmbargo} from '../.build/packages/discovery-learning/src/index.js';
import {createPolicyProposal,advanceProposal,assertNoAutomaticPolicyMutation} from '../.build/packages/discovery-governance/src/index.js';
const pool={address:'P1',tvl:200000,current_price:1,fee_tvl_ratio:{'1h':.008,'24h':.035},fees:{'1h':100,'24h':1200},volume:{'1h':30000,'24h':400000},token_x:{address:'X',freeze_authority_disabled:true},token_y:{address:'Y',freeze_authority_disabled:true}};
const bins=Array.from({length:21},(_,i)=>({pool:'P1',binId:i-10,amountX:String(1000+i),amountY:String(1000-i),pricePerToken:'1',liquiditySupply:'1',observedAt:'2026-08-13T10:00:00Z'}));
const swaps=[
 {pool:'P1',signature:'a',eventIndex:0,blockTime:'2026-08-13T09:55:00Z',startBinId:-1,endBinId:0,mmFee:'10'},
 {pool:'P1',signature:'b',eventIndex:0,blockTime:'2026-08-13T09:56:00Z',startBinId:0,endBinId:-1,mmFee:'10'},
 {pool:'P1',signature:'c',eventIndex:0,blockTime:'2026-08-13T09:57:00Z',startBinId:-1,endBinId:0,mmFee:'10'},
 {pool:'P1',signature:'d',eventIndex:0,blockTime:'2026-08-13T09:58:00Z',startBinId:0,endBinId:-1,mmFee:'10'}
];
const hist=Array.from({length:12},(_,i)=>({timestamp:1+i,timestamp_str:'',fees:8+i*.2,protocol_fees:1,volume:1000+i*10}));
const deep=()=>deepScreenPool({pool,protocolCompatible:true,observedAt:'2026-08-13T10:00:00Z',activeBinId:0,bins,activeBinHistory:[{binId:-1,observedAt:'2026-08-13T09:55:00Z'},{binId:0,observedAt:'2026-08-13T09:57:00Z'},{binId:0,observedAt:'2026-08-13T10:00:00Z'}],swaps,historicalFees:hist,marketFragility:.2,dataFresh:true});
test('D3 deep screen separates pool quality/opportunity and toxicity',()=>{const d=deep();assert.ok(d.poolQualityScore>0);assert.ok(d.currentOpportunityScore>0);assert.ok(d.toxicity.toxicityProbability>=0&&d.toxicity.toxicityProbability<=1);assert.notEqual(d.poolQualityScore,d.currentOpportunityScore);});
test('D3 high one-way movement increases toxicity',()=>{const low=computeDirectionalToxicity({movement:deep().movement,flow:deep().flow,bin:deep().bin});const high=computeDirectionalToxicity({movement:{observations:5,netBins:20,absoluteBins:20,reversals:0,directionality:1,velocityBinsPerMinute:5},flow:{swaps:10,upwardBinMoves:10,downwardBinMoves:0,flatBinMoves:0,twoWayRatio:0,netDirection:1,meanBinsCrossed:8,totalMmFeeRaw:'1'},bin:deep().bin});assert.ok(high.toxicityProbability>low.toxicityProbability);});
test('D3 opportunity half-life is scheduler evidence only',()=>{const d=deep();const h=estimateOpportunityHalfLife({fee:d.feeSustainability,movement:d.movement,flow:d.flow});assert.ok(h===null||(h>=5&&h<=360));});
test('D4 assigns active and deterministic control cohorts',()=>{const ds=[deep(),{...deep(),poolAddress:'P2',currentOpportunityScore:90},{...deep(),poolAddress:'P3',eligibility:'WATCHLIST'}];const a=assignUniverseTiers(ds,{id:'u',maxActive:1,maxWatch:1,controlCount:1,urgentHalfLifeMinutes:20,controlSeed:'x'});assert.equal(a.filter(x=>x.tier==='A').length,1);assert.ok(a.some(x=>x.tier==='C'||x.tier==='CONTROL'));});
test('D3/D4 lifecycle leaves Tier-A pools QUALIFIED for durable live-evidence admission',()=>{const qualified=deep();assert.deepEqual(deriveDiscoveryLifecycleState({deep:qualified,assignment:{tier:'A'}}),{state:'QUALIFIED',tier:'A'});assert.deepEqual(deriveDiscoveryLifecycleState({deep:qualified,assignment:{tier:'B'}}),{state:'WATCHLIST',tier:'B'});assert.deepEqual(deriveDiscoveryLifecycleState({deep:{...qualified,eligibility:'WATCHLIST'},assignment:{tier:'A'}}),{state:'OBSERVING',tier:'C'});assert.deepEqual(deriveDiscoveryLifecycleState({deep:{...qualified,eligibility:'BLOCK'},assignment:{tier:'A'}}),{state:'REJECTED',tier:'REJECTED'});assert.deepEqual(deriveDiscoveryLifecycleState({deep:{...qualified,eligibility:'BLOCK',reasonCodes:['DEEP_READ_FAILED:rate_limited']},assignment:{tier:'A'}}),{state:'OBSERVING',tier:'C'});});
test('D3 scheduling preserves economic priority while bounded fairness prevents permanent starvation',()=>{const queue=['high-economic','weaker-b','weaker-c','weaker-d'];const slices=Array.from({length:9},(_,minute)=>selectDeepScreenSlice(queue,2,new Date(minute*60_000).toISOString(),60_000));assert.ok(slices.every(slice=>slice[0]==='high-economic'),'priority receives the first D3 slot');assert.deepEqual(slices[2],['high-economic','weaker-c']);assert.deepEqual(slices[5],['high-economic','weaker-d']);assert.ok(new Set(slices.flat()).size===4,'every bounded-tail candidate eventually receives a D3 opportunity');});
test('D5 distributional EV quantiles monotonic and NO_TRADE remains possible',()=>{const ev=evaluateDiscoveryStrategies({deep:deep(),capitalSol:.1});for(const x of ev.strategies)assert.ok(x.p05<=x.p10&&x.p10<=x.p25&&x.p25<=x.p50&&x.p50<=x.p75&&x.p75<=x.p90&&x.p90<=x.p95);assert.ok(['SPOT_CENTER','CURVE_CENTER','SOL_BID_ASK','NO_TRADE'].includes(ev.winner));assert.equal(ev.authority,'RESEARCH_ONLY_NO_EXECUTION');});
test('D6 prediction is prospective and episode keyed',()=>{const d=deep(),ev=evaluateDiscoveryStrategies({deep:d,capitalSol:.1});const p=makePrediction({poolAddress:d.poolAddress,observedAt:d.observedAt,policyVersion:'p',deep:d,strategy:ev,selectionContext:{rank:1},cohort:'A'});assert.ok(p.predictionId.startsWith('pred-'));assert.ok(p.episodeKey.includes('P1'));});
test('D7 calibration reports independent episodes not raw observations',()=>{const d=deep(),ev=evaluateDiscoveryStrategies({deep:d,capitalSol:.1});const p=makePrediction({poolAddress:d.poolAddress,observedAt:d.observedAt,policyVersion:'p',deep:d,strategy:ev,selectionContext:{},cohort:'A'});const o={predictionId:p.predictionId,poolAddress:'P1',observedAt:'2026-08-13T12:00:00Z',horizonMinutes:120,outcomeClass:'TRADED',realizedNetValue:.01,realizedFees:.002,realizedDirectionalPnl:.008,rangeSurvived:true,eventAttribution:'NORMAL',structuralEventCodes:[]};const c=calibratePredictions([p],[o]);assert.equal(c.samples,1);assert.equal(c.independentEpisodes,1);assert.equal(c.allOutcomeNet,.01);});
test('D7 structural break never erases all-outcome performance',()=>{const d=deep(),ev=evaluateDiscoveryStrategies({deep:d,capitalSol:.1});const p=makePrediction({poolAddress:d.poolAddress,observedAt:d.observedAt,policyVersion:'p',deep:d,strategy:ev,selectionContext:{},cohort:'A'});const o={predictionId:p.predictionId,poolAddress:'P1',observedAt:'2026-08-13T12:00:00Z',horizonMinutes:120,outcomeClass:'TRADED',realizedNetValue:-.02,eventAttribution:'STRUCTURAL_BREAK',structuralEventCodes:['LIQUIDITY_COLLAPSE']};const c=calibratePredictions([p],[o]);assert.equal(c.allOutcomeNet,-.02);assert.equal(c.modelCalibrationNet,0);});
test('D7 baseline selectors are explicit',()=>{const b=selectBaselines([{poolAddress:'A',feeTvl:.1,feePersistence:.5,liquidity:.9,toxicity:.2,eligible:true},{poolAddress:'B',feeTvl:.2,feePersistence:.9,liquidity:.7,toxicity:.1,eligible:true}],'x');assert.equal(b.HIGHEST_FEE_TVL,'B');assert.equal(b.HIGHEST_PERSISTENT_FEE_TVL,'B');});
test('D7 purged embargo removes overlapping outcome windows',()=>{const rows=[{observedAt:'2026-08-13T10:00:00Z'},{observedAt:'2026-08-13T14:00:00Z'},{observedAt:'2026-08-14T10:00:00Z'}];const kept=purgeEmbargo(rows,'2026-08-13T12:00:00Z','2026-08-13T13:00:00Z',360);assert.equal(kept.length,1);assert.equal(kept[0].observedAt,'2026-08-14T10:00:00Z');});
test('D8 governance cannot skip validation stages or auto-promote',()=>{let p=createPolicyProposal({proposalId:'x',createdAt:'2026-08-13T10:00:00Z',hypothesis:'h',targetPolicy:'d',changes:{a:1},evidence:{}});assert.equal(assertNoAutomaticPolicyMutation(p).policyMutationAllowed,false);assert.throws(()=>advanceProposal(p,'APPROVED',{}));p=advanceProposal(p,'BACKTESTED',{});assert.equal(p.state,'BACKTESTED');assert.equal(p.automaticPromotion,false);});
test('D7 reputation is confidence-limited by independent episodes',()=>{const d=deep(),ev=evaluateDiscoveryStrategies({deep:d,capitalSol:.1});const p=makePrediction({poolAddress:d.poolAddress,observedAt:d.observedAt,policyVersion:'p',deep:d,strategy:ev,selectionContext:{},cohort:'A'});const o={predictionId:p.predictionId,poolAddress:'P1',observedAt:'2026-08-13T12:00:00Z',horizonMinutes:120,outcomeClass:'TRADED',realizedNetValue:.01,eventAttribution:'NORMAL',structuralEventCodes:[]};const r=buildReputation([p],[o],x=>x.poolAddress);assert.equal(r[0].episodes,1);assert.ok(r[0].confidence<.1);});
