import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {copyFileSync,mkdtempSync,mkdirSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import test from 'node:test';

const files=['live-execution-policy.json','pool-discovery-policy.json','autonomous-entry-policy.json','live-position-management-policy.json','oor-lifecycle-policy.json','live-exit-governor-policy.json'];
const hash=value=>createHash('sha256').update(value).digest('hex');
function fixture(t){const root=mkdtempSync(path.join(tmpdir(),'lpforge-policy-deploy-plan-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const template=path.join(root,'template'),runtime=path.join(root,'runtime');mkdirSync(template);mkdirSync(runtime);for(const file of files){writeFileSync(path.join(template,file),`{"file":"${file}","value":60}\n`);writeFileSync(path.join(runtime,file),`{"file":"${file}","value":60}\n`);}return{template,runtime};}
function plan(template,runtime){return JSON.parse(execFileSync(process.execPath,['scripts/production-policy-deployment-plan.mjs',template,runtime],{encoding:'utf8'}));}

test('single-command planner maps a 60 to 65 live-execution fixture change to every required consumer',t=>{const x=fixture(t);writeFileSync(path.join(x.template,'live-execution-policy.json'),'{"file":"live-execution-policy.json","value":65}\n');const p=plan(x.template,x.runtime);assert.deepEqual(p.services,['production','execution','discovery']);assert.equal(p.changes.length,1);assert.equal(p.changes[0].domain,'LIVE_EXECUTION');assert.equal(p.changes[0].nextHash,hash('{"file":"live-execution-policy.json","value":65}\n'));});
test('same command maps a hard-stop exit-policy change without source-code or PM2 selection by the operator',t=>{const x=fixture(t);writeFileSync(path.join(x.template,'live-exit-governor-policy.json'),'{"file":"live-exit-governor-policy.json","hardStopLossFraction":0.10}\n');const p=plan(x.template,x.runtime);assert.deepEqual(p.services,['production','execution']);assert.equal(p.changes[0].domain,'LIVE_EXIT_GOVERNOR');});
test('the single deployment command validates a temporary 60 to 65 fixture with no source edit, hash edit, copy, or PM2 command',t=>{const root=mkdtempSync(path.join(tmpdir(),'lpforge-policy-deploy-command-')),template=path.join(root,'template'),runtime=path.join(root,'runtime');t.after(()=>rmSync(root,{recursive:true,force:true}));mkdirSync(template);mkdirSync(runtime);for(const file of files){copyFileSync(path.join('release-policy-templates',file),path.join(template,file));copyFileSync(path.join('release-policy-templates',file),path.join(runtime,file));}const live=JSON.parse(readFileSync(path.join(template,'live-execution-policy.json'),'utf8'));live.range.minimumIncludedBins=65;writeFileSync(path.join(template,'live-execution-policy.json'),`${JSON.stringify(live,null,2)}\n`);const result=execFileSync('bash',['scripts/deploy-production-policy.sh','--dry-run'],{encoding:'utf8',env:{...process.env,LPFORGE_POLICY_TEMPLATE_DIR:template,LPFORGE_POLICY_RUNTIME_DIR:runtime}});assert.match(result,/LPFORGE_POLICY_DEPLOY_DRY_RUN_PASS services=production execution discovery/);});
test('deployment command is explicit, performs focused validation/build/install/restart/verification, and has rollback handling',()=>{const source=readFileSync('scripts/deploy-production-policy.sh','utf8');for(const token of ['production-policy-deployment-plan.mjs','SCHEMA_AND_INVARIANTS','FOCUSED_VALIDATION','build-production-release.sh','install-production-release.sh','pm2-restart.sh','RUNTIME_VERIFY','LPFORGE_POLICY_DEPLOY_ROLLBACK,P7 HEALTH[[:space:]]+HEALTHY,RECOVERY QUEUE[[:space:]]+0,PARTIAL ENTRY[[:space:]]+0'])assert.match(source,new RegExp(token));assert.doesNotMatch(source,/inotify|fswatch|watch\s+release-policy/);});
