import assert from 'node:assert/strict';import test from 'node:test';import {decodeConfirmedExecutionReceipt} from '../.build/packages/transaction-receipt/src/index.js';import {deriveTransactionAssetEffects,ASSOCIATED_TOKEN_PROGRAM_ID,TOKEN_PROGRAM_ID,WSOL_MINT} from '../.build/packages/transaction-asset-effects/src/index.js';
const JUP='JUPITER_PROGRAM',OWNER='OWNER',PAYER='PAYER',RISK='RISK',WSOL='WSOL_ACCOUNT',ATA='ATA_ACCOUNT',TEMP='TEMP_ACCOUNT',POSITION='POSITION';
const instruction=(programId,accountKeyIndexes,type)=>({programId,accountKeyIndexes,parsed:{type,info:{destination:OWNER}}});
function receipt({pre=[100,1000,0,0,0,0,0,0],post=pre,tokensPre=[],tokensPost=[],outer=[],inner=[],version=0}={}){const balances=values=>Array.from({length:10},(_,index)=>values[index]??0);return decodeConfirmedExecutionReceipt('sig',{slot:1,version,transaction:{message:{accountKeys:[PAYER,OWNER,RISK,WSOL,ATA,TEMP,POSITION,'LOADED_STATIC'],compiledInstructions:outer}},meta:{err:null,fee:5,preBalances:balances(pre),postBalances:balances(post),loadedAddresses:{writable:['LOADED_TOKEN'],readonly:['LOADED_READONLY']},preTokenBalances:tokensPre,postTokenBalances:tokensPost,innerInstructions:inner}});}
const token=(accountIndex,mint,amount,owner=OWNER,decimals=9)=>({accountIndex,mint,owner,uiTokenAmount:{amount:String(amount),decimals}});
const context={ownerAddress:OWNER,feePayerAddress:PAYER,inputMint:RISK,outputMint:WSOL_MINT,jupiterProgramIds:[JUP],associatedTokenAccountAddresses:[ATA],temporaryAccountAddresses:[TEMP,WSOL],positionAddress:POSITION};
test('EFFECT-001/002/005/021/022 derives non-index-zero owner and loaded-account U64 token deltas exactly',()=>{const r=receipt({pre:[100,1000,0,0,0,0,0,0,0],post:[95,1011,0,0,0,0,0,0,0],tokensPre:[token(8,RISK,'18446744073709551615')],tokensPost:[token(8,RISK,'18446744073709551610')]});const e=deriveTransactionAssetEffects(r,context);assert.equal(e.ownerAccountIndex,1);assert.equal(e.nativeWalletDeltaLamports,11n);assert.equal(e.tokenEffects[0].deltaRaw,-5n);assert.equal(e.transactionFeeLamports,5n);assert.equal(e.transactionFeeEffect.classification,'TRANSACTION_FEE');});
test('EFFECT-003/004 preserves exact created-only and closed-only owner token-account deltas',()=>{const created=deriveTransactionAssetEffects(receipt({tokensPost:[token(8,'OUTPUT','18446744073709551615')]}),context);assert.equal(created.tokenEffects[0].deltaRaw,18446744073709551615n);const closed=deriveTransactionAssetEffects(receipt({tokensPre:[token(8,'OUTPUT','18446744073709551615')]}),context);assert.equal(closed.tokenEffects[0].deltaRaw,-18446744073709551615n);});
test('EFFECT-003/006/007 classifies ATA create and close rent without making it swap output',()=>{const create=deriveTransactionAssetEffects(receipt({pre:[100,1000,0,0,0,0,0,0],post:[95,797,0,0,203,0,0,0],outer:[instruction(ASSOCIATED_TOKEN_PROGRAM_ID,[1,4],'create')] }),context);assert.equal(create.rentDebits[0].classification,'ATA_RENT_DEBIT');assert.equal(create.rentDebits[0].amountLamports,203n);assert.equal(create.classificationState,'FULLY_CLASSIFIED');const close=deriveTransactionAssetEffects(receipt({pre:[100,1000,0,0,203,0,0,0],post:[95,1203,0,0,0,0,0,0],outer:[instruction(TOKEN_PROGRAM_ID,[4,1],'closeAccount')]}),context);assert.equal(close.rentRefunds[0].classification,'ATA_RENT_REFUND');assert.equal(close.swapOutputEffects.length,0);assert.equal(close.classificationState,'FULLY_CLASSIFIED');});
test('EFFECT-008/009/013 classifies temporary lifecycle and PositionV2 rent separately from fee',()=>{const created=deriveTransactionAssetEffects(receipt({pre:[100,1000,0,0,0,0,0,0],post:[95,929,0,0,0,71,0,0],outer:[instruction(TOKEN_PROGRAM_ID,[5,1],'createAccount')]}),context);assert.equal(created.rentDebits[0].classification,'TEMP_ACCOUNT_RENT_DEBIT');const e=deriveTransactionAssetEffects(receipt({pre:[100,1000,0,0,0,71,89,0],post:[95,1160,0,0,0,0,0,0],outer:[instruction(TOKEN_PROGRAM_ID,[5,1],'closeAccount'),instruction('METEORA_PROGRAM',[6,1],'closePosition')]}),context);assert.equal(e.rentRefunds[0].classification,'TEMP_ACCOUNT_RENT_REFUND');assert.equal(e.positionRentRecoveryLamports,89n);assert.equal(e.transactionFeeLamports,5n);assert.equal(e.classificationState,'FULLY_CLASSIFIED');});
test('EFFECT-010/011/012 recognizes WSOL wrap and unwrap as representation changes, not swap output',()=>{const wrap=deriveTransactionAssetEffects(receipt({pre:[100,1000,0,1,0,0,0,0],post:[95,900,0,1,0,0,0,0],tokensPost:[token(3,WSOL_MINT,100)],outer:[instruction(TOKEN_PROGRAM_ID,[3,1],'syncNative')]}),context);assert.equal(wrap.wsolWrapEffects[0].classification,'WSOL_WRAP');assert.equal(wrap.swapOutputEffects.length,0);assert.equal(wrap.classificationState,'FULLY_CLASSIFIED');const unwrap=deriveTransactionAssetEffects(receipt({pre:[100,1000,0,1,0,0,0,0],post:[95,1101,0,0,0,0,0,0],tokensPre:[token(3,WSOL_MINT,100)],outer:[instruction(TOKEN_PROGRAM_ID,[3,1],'closeAccount')]}),context);assert.equal(unwrap.wsolUnwrapEffects[0].classification,'WSOL_UNWRAP');assert.equal(unwrap.swapOutputEffects.length,0);assert.equal(unwrap.classificationState,'FULLY_CLASSIFIED');});
test('EFFECT-014/015/016 classifies Jupiter input and native plus persistent-WSOL output without double count',()=>{const e=deriveTransactionAssetEffects(receipt({pre:[100,1000,0,1,0,0,0,0],post:[95,1010,0,1,0,0,0,0],tokensPre:[token(2,RISK,50)],tokensPost:[token(2,RISK,0),token(3,WSOL_MINT,7)],outer:[instruction(JUP,[1,2,3],'route')]}),context);assert.equal(e.swapInputEffects[0].classification,'SWAP_INPUT');assert.equal(e.swapOutputEffects.length,2);assert.equal(e.swapOutputEffects.reduce((sum,x)=>sum+(x.amountLamports??x.rawAmount),0n),17n);assert.equal(e.classificationState,'FULLY_CLASSIFIED');});
test('EFFECT-018 keeps owner-paid fee, ATA refund, and Jupiter output as distinct components',()=>{const e=deriveTransactionAssetEffects(receipt({pre:[100,1000,0,1,203,0,0,0],post:[100,1208,0,1,0,0,0,0],tokensPre:[token(2,RISK,50)],tokensPost:[token(2,RISK,0)],outer:[instruction(JUP,[1,2],'route'),instruction(TOKEN_PROGRAM_ID,[4,1],'closeAccount')]}),{...context,feePayerAddress:OWNER});assert.equal(e.transactionFeeEffect.amountLamports,5n);assert.equal(e.rentRefunds[0].amountLamports,203n);assert.equal(e.swapOutputEffects.at(-1).amountLamports,10n);assert.equal(e.classificationState,'FULLY_CLASSIFIED');});
test('EFFECT-017/019/020 retains rent-only, unknown native, and unknown token movements as non-swap ambiguity',()=>{const rentOnly=deriveTransactionAssetEffects(receipt({pre:[100,1000,0,0,203,0,0,0],post:[95,1203,0,0,0,0,0,0],outer:[instruction(TOKEN_PROGRAM_ID,[4,1],'closeAccount')]}),context);assert.equal(rentOnly.swapOutputEffects.length,0);assert.equal(rentOnly.classificationState,'FULLY_CLASSIFIED');const unknown=deriveTransactionAssetEffects(receipt({pre:[100,1000,0,0,0,0,0,0],post:[95,1009,0,0,0,0,0,0],tokensPre:[token(2,'OTHER',9)],tokensPost:[token(2,'OTHER',10)]}),context);assert.equal(unknown.classificationState,'AMBIGUOUS');assert.equal(unknown.unclassifiedNativeEffects[0].amountLamports,9n);assert.equal(unknown.unclassifiedTokenEffects[0].classification,'UNCLASSIFIED');});
