// LPFORGE_PHASE7_RUNTIME_INTEGRATION_APP
import {readFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {composePhase7RuntimeTick} from '../../../packages/phase7-runtime/src/index.js';
import {assessPhase7Health,defaultPhase7HealthPolicy} from '../../../packages/phase7-health/src/index.js';
import {loadPhase1Config} from '../../../packages/config/src/index.js';
import {createPostgresStore} from '../../../packages/db/src/index.js';
import {createMeteoraDataApi} from '../../../packages/data-api/src/index.js';
import {createSolanaRpcClient} from '../../../packages/meteora/src/index.js';
import {collectPhase7LiveHealthObservations} from '../../../packages/phase7-live-health/src/index.js';
import {assessPhase7LiveDrift,defaultPhase7LiveDriftPolicy} from '../../../packages/phase7-live-drift/src/index.js';
import type {Phase7EvaluationMetrics,Phase7DriftAssessment} from '../../../packages/phase7-drift/src/index.js';
import type {Phase7HealthAssessment} from '../../../packages/phase7-health/src/index.js';
import {loadPhase7ControlConfig,loadPhase7ManualApproval,resolvePhase7Authority} from '../../../packages/phase7-authority/src/index.js';
import {buildPhase7LiveControlDecision,derivePhase7AutomaticIncidents,reconcilePhase7AutomaticIncidents} from '../../../packages/phase7-live-control/src/index.js';
import type {Phase7Incident} from '../../../packages/phase7-incidents/src/index.js';
import {runPhase7RecoveryRuntimeTick} from '../../../packages/phase7-live-runtime/src/index.js';
import {buildPhase7RuntimeEvidence} from '../../../packages/phase7-live-evidence/src/index.js';
import {loadPhase7ProductionStatus,runPhase7ProductionOnce} from '../../../packages/phase7-production-service/src/index.js';
import {registerPhase7RuntimeReleaseEvidence,type Phase7RuntimeReleaseEvidence} from '../../../packages/phase7-release-evidence/src/index.js';
import {Phase7TelegramAlerter,alertsForPhase7ProductionResult,loadPhase7TelegramConfig,type Phase7Alert} from '../../../packages/phase7-alerting/src/index.js';

const json=(v:unknown)=>JSON.stringify(v,null,2);
type VerifiedRuntimeArtifactIdentity=Readonly<{sourceCommit:string;buildIdentity:string;policyHash:string;migrationHead:string;migrationCount:number}>;
let verifiedRuntimeArtifactIdentity:VerifiedRuntimeArtifactIdentity|undefined;
function requireVerifiedRuntimeArtifactIdentity():VerifiedRuntimeArtifactIdentity{
  if(verifiedRuntimeArtifactIdentity)return verifiedRuntimeArtifactIdentity;
  const result=spawnSync('bash',['scripts/verify-release-integrity.sh'],{cwd:process.cwd(),env:{...process.env,LPFORGE_RUNTIME_RELEASE_VERIFY:'true'},encoding:'utf8'});
  if(result.error||result.status!==0)throw new Error(`LPFORGE_RUNTIME_RELEASE_INTEGRITY_FAILED:${(result.stderr||result.stdout||result.error?.message||'unknown').trim().slice(0,500)}`);
  const manifest=JSON.parse(readFileSync('RELEASE_MANIFEST.json','utf8')) as {sourceCommit?:unknown;buildIdentity?:unknown;policyHash?:unknown;migrationHead?:unknown;migrationCount?:unknown};
  const sourceRevision=readFileSync('SOURCE_REVISION.txt','utf8').trim().replace(/^source_git_commit=/,'');
  const sourceCommit=typeof manifest.sourceCommit==='string'?manifest.sourceCommit.trim():'';
  const buildIdentity=typeof manifest.buildIdentity==='string'?manifest.buildIdentity.trim():'';
  const policyHash=typeof manifest.policyHash==='string'?manifest.policyHash.trim():'';
  const migrationHead=typeof manifest.migrationHead==='string'?manifest.migrationHead.trim():'';
  const migrationCount=typeof manifest.migrationCount==='number'?manifest.migrationCount:Number(manifest.migrationCount);
  if(!/^[0-9a-f]{40}$/i.test(sourceCommit)||sourceRevision!==sourceCommit||!/^[0-9a-f]{64}$/i.test(buildIdentity)||!/^[0-9a-f]{64}$/i.test(policyHash)||!migrationHead||!Number.isSafeInteger(migrationCount)||migrationCount<0)throw new Error('LPFORGE_RUNTIME_RELEASE_IDENTITY_MALFORMED');
  verifiedRuntimeArtifactIdentity=Object.freeze({sourceCommit,buildIdentity,policyHash,migrationHead,migrationCount});
  console.log(json({event:'lpforge_runtime_artifact_identity_verified',artifactDerived:true,...verifiedRuntimeArtifactIdentity}));
  return verifiedRuntimeArtifactIdentity;
}
function artifactBoundEnvironment(identity:VerifiedRuntimeArtifactIdentity):NodeJS.ProcessEnv{const home=process.env.LPFORGE_HOME?.trim()||'/root/systems/LPForge',policy=process.env.LPFORGE_EXECUTION_POLICY_PATH?.trim()||`${home}/policy/live-execution-policy.json`;return {...process.env,LPFORGE_SOURCE_COMMIT:identity.sourceCommit,LPFORGE_BUILD_ID:identity.buildIdentity,LPFORGE_P7_POLICY_HASH:identity.policyHash,LPFORGE_EXECUTION_POLICY_PATH:policy,LPFORGE_APPROVED_RELEASE_IDENTITY_PATH:'RELEASE_MANIFEST.json'};}
const baseline={sampleCount:100,regimeBrier:.2,survivalBrier:.18,netValueMae:.001,noTradeRate:.7,entryReadyRate:.1,executionCostRate:.0005,reconciliationMismatchRate:0,featureMissingRate:.01,decoderSkipRate:.001};
const driftPolicy={minSamples:50,maxForecastRelativeDegradation:.25,maxNetValueMaeRelativeDegradation:.5,maxDecisionRateShift:.2,maxExecutionCostRelativeDegradation:.5,maxReconciliationMismatchRate:.01,maxFeatureMissingRate:.05,maxDecoderSkipRate:.02};
const telegramAlerter=new Phase7TelegramAlerter(loadPhase7TelegramConfig());
async function safeTelegramAlert(alert:Phase7Alert){try{const r=await telegramAlerter.send(alert);if(r.sent)console.log(json({event:'lpforge_telegram_alert_sent',code:alert.code,severity:alert.severity}));}catch(e){console.error(json({event:'lpforge_telegram_alert_failed',code:alert.code,error:e instanceof Error?e.message:String(e)}));}}
async function alertProductionResult(result:Awaited<ReturnType<typeof runPhase7ProductionOnce>>){for(const alert of alertsForPhase7ProductionResult(result))await safeTelegramAlert(alert);}
function fixtureInput(now:string){
  const observedAt=new Date(Date.parse(now)-5_000).toISOString();
  return {now,runtimeId:'lpforge-production',instanceId:'fixture-instance',cycleKey:`fixture-${now}`,leaseTtlMs:60_000,previousCompletedCycleKeys:[],completedEconomicActionKeys:[],restarted:false,recoveryScanCompleted:true,recoveryQueueCount:0,unknownSubmissionCount:0,unresolvedReconciliationDebt:0,
    healthObservations:['RPC','METEORA_API','DATABASE','DECISION','EXECUTION','PORTFOLIO','RECONCILIATION'].map(domain=>({domain:domain as 'RPC'|'METEORA_API'|'DATABASE'|'DECISION'|'EXECUTION'|'PORTFOLIO'|'RECONCILIATION',observedAt,status:'HEALTHY' as const,reasonCodes:[]})),healthPolicy:defaultPhase7HealthPolicy,
    driftBaseline:baseline,driftCurrent:{...baseline,sampleCount:80},driftPolicy,incidents:[]};
}
async function fixtureOnce(){const now='2026-08-13T00:00:00.000Z';const result=composePhase7RuntimeTick(fixtureInput(now));console.log(json(result));return result;}
async function fixtureRun(){const interval=Math.max(1000,Number(process.env.LPFORGE_P7_FIXTURE_INTERVAL_MS??5000));for(;;){await fixtureOnce();await new Promise(r=>setTimeout(r,interval));}}
async function liveHealthOnce(){
  const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_P7_PRODUCTION_REQUIRES_LIVE_READ_ONLY');if(!cfg.smokePoolAddress)throw new Error('LPFORGE_CONFIG_REQUIRED:LPFORGE_SMOKE_POOL_ADDRESS');
  const runtimeId=(process.env.LPFORGE_P7_RUNTIME_ID??'lpforge-production').trim();const cycleKey=(process.env.LPFORGE_P7_HEALTH_CYCLE_KEY??`health-${Date.now()}`).trim();const store=await createPostgresStore(cfg.databaseUrl);
  try{
    const probeAt=new Date().toISOString();const rpc=createSolanaRpcClient({url:cfg.solanaRpcHttpUrl,timeoutMs:cfg.rpcTimeoutMs,minIntervalMs:cfg.rpcMinIntervalMs,maxRetries:cfg.rpcMaxRetries,retryBaseDelayMs:cfg.rpcRetryBaseDelayMs,retryMaxDelayMs:cfg.rpcRetryMaxDelayMs,priority:'P2_POSITION_MANAGEMENT'});const dataApi=createMeteoraDataApi({baseUrl:cfg.meteoraDataApiUrl,maxRps:cfg.dataApiMaxRps,timeoutMs:cfg.httpTimeoutMs});
    const observations=await collectPhase7LiveHealthObservations({assessmentAt:probeAt,poolAddress:cfg.smokePoolAddress,rpc,dataApi,store});const assessedAt=new Date().toISOString();const health=assessPhase7Health(observations,defaultPhase7HealthPolicy,assessedAt);const assessmentId=`${runtimeId}:${cycleKey}:health`;
    await store.insertPhase7HealthAssessment({assessmentId,runtimeId,cycleKey,observedAt:assessedAt,status:health.status,newEntriesAllowed:health.newEntriesAllowed,managementWritesAllowed:health.managementWritesAllowed,reasonCodes:health.reasonCodes,domainStatus:health.domainStatus,payload:{poolAddress:cfg.smokePoolAddress,observations,staleDomains:health.staleDomains,missingDomains:health.missingDomains,emergencyCloseAllowed:health.emergencyCloseAllowed}});console.log(json({assessmentId,runtimeId,cycleKey,poolAddress:cfg.smokePoolAddress,health,observations,directSigner:false,directTransactionSend:false}));return health;
  } finally {await store.close();}
}
async function liveDriftOnce(){
  const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_P7_PRODUCTION_REQUIRES_LIVE_READ_ONLY');if(!cfg.smokePoolAddress)throw new Error('LPFORGE_CONFIG_REQUIRED:LPFORGE_SMOKE_POOL_ADDRESS');const raw=process.env.LPFORGE_P7_DRIFT_BASELINE_JSON?.trim();if(!raw)throw new Error('LPFORGE_P7_DRIFT_BASELINE_REQUIRED');let baseline:Phase7EvaluationMetrics;try{baseline=JSON.parse(raw) as Phase7EvaluationMetrics;}catch{throw new Error('LPFORGE_P7_DRIFT_BASELINE_JSON');}
  const runtimeId=(process.env.LPFORGE_P7_RUNTIME_ID??'lpforge-production').trim();const cycleKey=(process.env.LPFORGE_P7_DRIFT_CYCLE_KEY??`drift-${Date.now()}`).trim();const hours=Math.max(1,Math.min(720,Number(process.env.LPFORGE_P7_DRIFT_WINDOW_HOURS??24)));const observedAt=new Date().toISOString();const since=new Date(Date.parse(observedAt)-hours*3600_000).toISOString();const decoderRaw=process.env.LPFORGE_P7_DECODER_SKIP_RATE;const decoderSkipRate=decoderRaw==null||decoderRaw===''?undefined:Number(decoderRaw);if(decoderSkipRate!==undefined&&(!Number.isFinite(decoderSkipRate)||decoderSkipRate<0))throw new Error('LPFORGE_P7_DECODER_SKIP_RATE');const store=await createPostgresStore(cfg.databaseUrl);
  try{const live=await assessPhase7LiveDrift({store,poolAddress:cfg.smokePoolAddress,since,observedAt,baseline,policy:defaultPhase7LiveDriftPolicy,...(decoderSkipRate!==undefined?{decoderSkipRate}:{})});const assessmentId=`${runtimeId}:${cycleKey}:drift`;await store.insertPhase7DriftAssessment({assessmentId,policyHash:live.baselineHash,observedAt,status:live.assessment.status,sampleCount:live.assessment.sampleCount,reasonCodes:live.assessment.reasonCodes,deltas:live.assessment.deltas,payload:{runtimeId,cycleKey,poolAddress:cfg.smokePoolAddress,since,baselineHash:live.baselineHash,current:live.current,coverage:live.coverage,policyMutationAllowed:false,automaticPolicyPromotion:false}});console.log(json({assessmentId,runtimeId,cycleKey,poolAddress:cfg.smokePoolAddress,...live,directSigner:false,directTransactionSend:false}));return live;}finally{await store.close();}
}
function healthFromRow(row:Record<string,unknown>):Phase7HealthAssessment{const payload=(row.payload??{}) as Record<string,unknown>;return{status:String(row.status) as Phase7HealthAssessment['status'],observedAt:new Date(String(row.observed_at)).toISOString(),domainStatus:(row.domain_status??{}) as Phase7HealthAssessment['domainStatus'],staleDomains:(payload.staleDomains??[]) as Phase7HealthAssessment['staleDomains'],missingDomains:(payload.missingDomains??[]) as Phase7HealthAssessment['missingDomains'],reasonCodes:(row.reason_codes??[]) as string[],newEntriesAllowed:Boolean(row.new_entries_allowed),managementWritesAllowed:Boolean(row.management_writes_allowed),emergencyCloseAllowed:true};}
function driftFromRow(row:Record<string,unknown>):Phase7DriftAssessment{return{status:String(row.status) as Phase7DriftAssessment['status'],reasonCodes:(row.reason_codes??[]) as string[],observedAt:new Date(String(row.observed_at)).toISOString(),sampleCount:Number(row.sample_count),newEntriesAllowed:String(row.status)!=='BLOCK',managementAllowed:true,policyMutationAllowed:false,automaticPolicyPromotion:false,deltas:(row.deltas??{}) as Record<string,number>};}
function incidentFromRow(row:Record<string,unknown>):Phase7Incident{return{incidentId:String(row.incident_id),type:String(row.incident_type) as Phase7Incident['type'],severity:String(row.severity) as Phase7Incident['severity'],openedAt:new Date(String(row.opened_at)).toISOString(),status:String(row.status) as Phase7Incident['status'],reasonCodes:(row.reason_codes??[]) as string[],...(row.pool_address?{pool:String(row.pool_address)}:{}),...(row.token_mint?{token:String(row.token_mint)}:{}),...(row.resolved_at?{resolvedAt:new Date(String(row.resolved_at)).toISOString()}:{}),...((row.payload as Record<string,unknown>|undefined)?.acknowledgedBy?{acknowledgedBy:String((row.payload as Record<string,unknown>).acknowledgedBy)}:{})};}
async function liveControlOnce(){const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_P7_PRODUCTION_REQUIRES_LIVE_READ_ONLY');if(!cfg.smokePoolAddress)throw new Error('LPFORGE_CONFIG_REQUIRED:LPFORGE_SMOKE_POOL_ADDRESS');const runtimeId=(process.env.LPFORGE_P7_RUNTIME_ID??'lpforge-production').trim();const cycleKey=(process.env.LPFORGE_P7_CONTROL_CYCLE_KEY??`control-${Date.now()}`).trim();const store=await createPostgresStore(cfg.databaseUrl);try{const [hrow,drow,activeRows]=await Promise.all([store.loadLatestPhase7HealthAssessment(runtimeId),store.loadLatestPhase7DriftAssessment(),store.loadActivePhase7Incidents()]);if(!hrow)throw new Error('LPFORGE_P7_CONTROL_HEALTH_MISSING');if(!drow)throw new Error('LPFORGE_P7_CONTROL_DRIFT_MISSING');const health=healthFromRow(hrow),drift=driftFromRow(drow);const observedAt=new Date().toISOString();const approval=loadPhase7ManualApproval();const authority=resolvePhase7Authority({config:loadPhase7ControlConfig(),now:observedAt,...(approval?{approval}:{})});const existing=activeRows.map(incidentFromRow);const current=derivePhase7AutomaticIncidents({poolAddress:cfg.smokePoolAddress,observedAt,health,drift});const updates=reconcilePhase7AutomaticIncidents({existing,current,observedAt});for(const i of updates)await store.upsertPhase7IncidentState({incidentId:i.incidentId,incidentType:i.type,severity:i.severity,status:i.status,openedAt:i.openedAt,observedAt,...(i.resolvedAt?{resolvedAt:i.resolvedAt}:{}),...(i.pool?{poolAddress:i.pool}:{}),...(i.token?{tokenMint:i.token}:{}),reasonCodes:i.reasonCodes,payload:{acknowledgedBy:i.acknowledgedBy??null,automatic:i.incidentId.startsWith('auto:')}});const active=updates.filter(i=>i.status!=='RESOLVED');const control=buildPhase7LiveControlDecision({authority,health,drift,incidents:active});const decisionId=`${runtimeId}:${cycleKey}:control`;await store.insertPhase7ControlDecision({decisionId,runtimeId,cycleKey,observedAt,authorityMode:control.authorityMode,healthStatus:control.healthStatus,driftStatus:control.driftStatus,safetyMode:control.safety.mode,daemonPlan:control.daemonPlan,newEconomicActionAllowed:control.newEconomicActionAllowed,reasonCodes:control.reasonCodes,payload:{poolAddress:cfg.smokePoolAddress,activeIncidentIds:active.map(i=>i.incidentId),directSigner:false,directTransactionSend:false}});console.log(json({decisionId,runtimeId,cycleKey,authority,health,drift,incidentUpdates:updates,control}));return control;}finally{await store.close();}}
async function liveRuntimeOnce(){const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_P7_PRODUCTION_REQUIRES_LIVE_READ_ONLY');const runtimeId=(process.env.LPFORGE_P7_RUNTIME_ID??'lpforge-production').trim();const instanceId=process.env.LPFORGE_P7_INSTANCE_ID?.trim();if(!instanceId)throw new Error('LPFORGE_P7_INSTANCE_ID_REQUIRED');const cycleKey=(process.env.LPFORGE_P7_RUNTIME_CYCLE_KEY??`runtime-${Date.now()}`).trim();const ttl=Math.max(1000,Math.min(300000,Number(process.env.LPFORGE_P7_LEASE_TTL_MS??60000)));const restarted=(process.env.LPFORGE_P7_RESTARTED??'true').toLowerCase()==='true';const store=await createPostgresStore(cfg.databaseUrl);try{const row=await store.loadLatestPhase7ControlDecision(runtimeId);if(!row)throw new Error('LPFORGE_P7_RUNTIME_CONTROL_MISSING');const result=await runPhase7RecoveryRuntimeTick({store,runtimeId,instanceId,cycleKey,now:new Date().toISOString(),leaseTtlMs:ttl,restarted,control:{authorityMode:String(row.authority_mode) as 'OBSERVE_ONLY'|'LIMITED_LIVE'|'PRODUCTION',healthStatus:String(row.health_status) as 'HEALTHY'|'DEGRADED'|'CRITICAL',newEconomicActionAllowed:Boolean(row.new_economic_action_allowed)}});console.log(json(result));return result;}finally{await store.close();}}
async function liveEvidenceOnce(){const artifact=requireVerifiedRuntimeArtifactIdentity();const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_P7_PRODUCTION_REQUIRES_LIVE_READ_ONLY');const runtimeId=(process.env.LPFORGE_P7_RUNTIME_ID??'lpforge-production').trim();const cycleKey=(process.env.LPFORGE_P7_EVIDENCE_CYCLE_KEY??`evidence-${Date.now()}`).trim();const observedAt=new Date().toISOString();const store=await createPostgresStore(cfg.databaseUrl);try{const summary=await buildPhase7RuntimeEvidence({store,runtimeId,observedAt,sourceCommit:artifact.sourceCommit,policyHash:artifact.policyHash,packId:`${runtimeId}:${cycleKey}:pack`});const implementationStatus=summary.statuses.IMPLEMENTATION==='PASS'?'PASS':summary.statuses.IMPLEMENTATION==='BLOCK'?'FAIL':'UNKNOWN';const operationalStatus=summary.statuses.PRODUCTION==='PASS'?'PASS':summary.statuses.PRODUCTION==='BLOCK'?'BLOCK':'HOLD';await store.insertPhase7EvidenceSnapshot({snapshotId:`${runtimeId}:${cycleKey}:snapshot`,runtimeId,cycleKey,observedAt,implementationStatus,operationalStatus,payload:{statuses:summary.statuses,facts:summary.facts,reasonCodes:summary.reasonCodes,packHash:summary.pack?.packHash??null}});if(summary.pack)await store.insertPhase7EvidencePack({packHash:summary.pack.packHash,packId:summary.pack.packId,sourceCommit:summary.pack.sourceCommit,policyHash:summary.pack.policyHash,complete:summary.pack.complete,operationalPass:summary.pack.operationalPass,createdAt:summary.pack.createdAt,payload:summary.pack as unknown as Record<string,unknown>});console.log(json({runtimeId,cycleKey,...summary,directSigner:false,directTransactionSend:false}));return summary;}finally{await store.close();}}
function requiredRuntimeIdentity(){const instanceId=process.env.LPFORGE_P7_INSTANCE_ID?.trim();if(!instanceId)throw new Error('LPFORGE_P7_INSTANCE_ID_REQUIRED');const raw=process.env.LPFORGE_P7_DRIFT_BASELINE_JSON?.trim();if(!raw)throw new Error('LPFORGE_P7_DRIFT_BASELINE_REQUIRED');let driftBaseline:Phase7EvaluationMetrics;try{driftBaseline=JSON.parse(raw) as Phase7EvaluationMetrics;}catch{throw new Error('LPFORGE_P7_DRIFT_BASELINE_JSON');}return{runtimeId:(process.env.LPFORGE_P7_RUNTIME_ID??'lpforge-production').trim(),instanceId,driftBaseline};}
async function productionOnce(restarted=true){const artifact=requireVerifiedRuntimeArtifactIdentity();const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_P7_PRODUCTION_REQUIRES_LIVE_READ_ONLY');const {runtimeId,instanceId,driftBaseline}=requiredRuntimeIdentity();const cycleKey=`${runtimeId}:${instanceId}:${Date.now()}`;const store=await createPostgresStore(cfg.databaseUrl);try{const result=await runPhase7ProductionOnce({cfg,store,runtimeId,instanceId,cycleKey,driftBaseline,cwd:process.cwd(),env:artifactBoundEnvironment(artifact),restarted,sourceCommit:artifact.sourceCommit,policyHash:artifact.policyHash,leaseTtlMs:Math.max(1000,Math.min(300000,Number(process.env.LPFORGE_P7_LEASE_TTL_MS??60000)))});console.log(json(result));await alertProductionResult(result);return result;}finally{await store.close();}}
async function productionStart(){requireVerifiedRuntimeArtifactIdentity();const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_P7_PRODUCTION_REQUIRES_LIVE_READ_ONLY');const identity=requiredRuntimeIdentity();const interval=Math.max(5000,Number(process.env.LPFORGE_P7_INTERVAL_MS??cfg.collectIntervalMs));if(telegramAlerter.config.notifyStartup)await safeTelegramAlert({severity:'INFO',code:'P7_DAEMON_START',title:'LPForge production daemon started',message:'Phase 7 production control-plane daemon is running. Execution authority remains governed by frozen LPForge gates.',runtimeId:identity.runtimeId,instanceId:identity.instanceId,observedAt:new Date().toISOString()});let restarted=true;for(;;){const started=Date.now();try{await productionOnce(restarted);restarted=false;}catch(e){const message=e instanceof Error?e.message:String(e);console.error(e);await safeTelegramAlert({severity:'CRITICAL',code:'P7_DAEMON_CYCLE_EXCEPTION',title:'LPForge production cycle exception',message:'The production loop caught an exception and will retry fail-closed.',runtimeId:identity.runtimeId,instanceId:identity.instanceId,observedAt:new Date().toISOString(),reasonCodes:[message.slice(0,300)]});restarted=true;}await new Promise(r=>setTimeout(r,Math.max(1000,interval-(Date.now()-started))));}}
async function productionStatus(){const cfg=loadPhase1Config();const runtimeId=(process.env.LPFORGE_P7_RUNTIME_ID??'lpforge-production').trim();const store=await createPostgresStore(cfg.databaseUrl);try{const status=await loadPhase7ProductionStatus({store,runtimeId});console.log(json(status));return status;}finally{await store.close();}}
async function registerReleaseEvidence(){const artifact=requireVerifiedRuntimeArtifactIdentity();const cfg=loadPhase1Config();const path=(process.env.LPFORGE_P7_RELEASE_EVIDENCE_PATH??'PHASE7_RUNTIME_RELEASE_EVIDENCE.json').trim();const evidence=JSON.parse(readFileSync(path,'utf8')) as Phase7RuntimeReleaseEvidence;const store=await createPostgresStore(cfg.databaseUrl);try{const result=await registerPhase7RuntimeReleaseEvidence({store,evidence,expectedSourceCommit:artifact.sourceCommit});console.log(json(result));return result;}finally{await store.close();}}
const command=process.argv[2]??'fixture-once';
if(command==='fixture-once')await fixtureOnce();else if(command==='fixture-run')await fixtureRun();else if(command==='health-once')await liveHealthOnce();else if(command==='drift-once')await liveDriftOnce();else if(command==='control-once')await liveControlOnce();else if(command==='runtime-once')await liveRuntimeOnce();else if(command==='evidence-once')await liveEvidenceOnce();else if(command==='once')await productionOnce(true);else if(command==='start')await productionStart();else if(command==='status')await productionStatus();else if(command==='register-release-evidence')await registerReleaseEvidence();else throw new Error('Usage: production fixture-once|fixture-run|health-once|drift-once|control-once|runtime-once|evidence-once|once|start|status|register-release-evidence');
