import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { createMeteoraDataApi } from '../../../packages/data-api/src/index.js';
import { createPostgresStore } from '../../../packages/db/src/index.js';
import { loadPhase1Config } from '../../../packages/config/src/index.js';
import { createMeteoraReadAdapter, createSolanaRpcClient } from '../../../packages/meteora/src/index.js';
import { loadDeploymentPolicyFile } from '../../../packages/deployment-policy/src/index.js';
import { DEFAULT_DISCOVERY_RUNTIME_POLICY, deriveDiscoveryLifecycleState, runDeepDiscoveryCycle, selectDeepScreenSlice } from '../../../packages/discovery-runtime/src/index.js';
import { collectActiveCandidateEvidence } from '../../../packages/active-candidate-evidence/src/index.js';
import { discoverUniverse, parseDiscoveryPolicy, type DiscoveryPolicy, type RankedDiscoveryPool } from '../../../packages/pool-discovery/src/index.js';

function json(v:unknown){return JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x,2)}
function env(name:string,fallback?:string):string{const v=process.env[name]??fallback;if(!v)throw new Error(`LPFORGE_DISCOVERY_ENV_REQUIRED:${name}`);return v}
async function loadPolicy():Promise<DiscoveryPolicy>{
  const path=process.env.LPFORGE_DISCOVERY_POLICY_PATH??'policies/pool-discovery-policy.json';
  const raw=JSON.parse(readFileSync(path,'utf8')) as Record<string,unknown>;
  if(process.env.LPFORGE_POOL_SOURCE_MODE) raw.sourceMode=process.env.LPFORGE_POOL_SOURCE_MODE;
  if(process.env.LPFORGE_MANUAL_POOLS) raw.manualPools=process.env.LPFORGE_MANUAL_POOLS.split(',').map(x=>x.trim()).filter(Boolean);
  return parseDiscoveryPolicy(raw);
}
function cycleId(policyId:string,observedAt:string){return createHash('sha256').update(`${policyId}:${observedAt}`).digest('hex').slice(0,32)}
function reasonCodes(r:RankedDiscoveryPool){return [...new Set([...r.hardReasons,...r.warnings,...r.selectionReasons])].sort()}
function productionEvidencePools(){const path=process.env.LPFORGE_EXECUTION_POLICY_PATH?.trim()||'policies/live-execution-policy.json';return loadDeploymentPolicyFile(path).pools.map(pool=>pool.address)}
async function once(){
  const policy=await loadPolicy();
  const api=createMeteoraDataApi({...((process.env.LPFORGE_METEORA_DATA_API_URL??'').trim()?{baseUrl:process.env.LPFORGE_METEORA_DATA_API_URL!}:{}),maxRps:Number(process.env.LPFORGE_DATA_API_MAX_RPS??1),timeoutMs:Number(process.env.LPFORGE_HTTP_TIMEOUT_MS??10000)});
  const result=await discoverUniverse(api,policy);
  const databaseUrl=env('DATABASE_URL');const store=await createPostgresStore(databaseUrl);const rankingCycleId=cycleId(policy.policyId,result.observedAt);
  try{
    const ranked=new Map(result.rankings.map(x=>[x.pool.address,x]));
    for(const raw of [...result.accepted,...result.rejected]){
      const r=ranked.get(raw.pool.address);const state=r?.state??'REJECTED',tier=r?.tier??'REJECTED';
      await store.insertDiscoveryObservation({poolAddress:raw.pool.address,observedAt:result.observedAt,policyId:policy.policyId,source:raw.source,decision:raw.decision,priorityScore:raw.priorityScore,metrics:{tvlUsd:raw.features.tvlUsd,volume30mUsd:raw.features.volume30mUsd,volume1hUsd:raw.features.volume1hUsd,volume24hUsd:raw.features.volume24hUsd,fees30mUsd:raw.features.fees30mUsd,fees1hUsd:raw.features.fees1hUsd,fees24hUsd:raw.features.fees24hUsd,feeTvl30m:raw.features.feeTvl30m,feeTvl1h:raw.features.feeTvl1h,feeTvl24h:raw.features.feeTvl24h,marketCapUsd:raw.features.marketCapUsd,liquidityToMarketCap:raw.features.liquidityToMarketCap,volume24hToMarketCap:raw.features.volume24hToMarketCap,fees24hToMarketCap:raw.features.fees24hToMarketCap,holders:raw.features.holders},hardReasons:raw.hardReasons,warnings:raw.warnings,selectionReasons:raw.selectionReasons,evidenceState:raw.features.evidence,payload:{name:raw.features.name,marketCapCohort:raw.features.marketCapCohort,wsolPair:raw.features.wsolPair,dataApi:raw.pool}});
      await store.upsertDiscoveryPool({poolAddress:raw.pool.address,observedAt:result.observedAt,sourceManual:raw.source==='MANUAL'||raw.source==='BOTH',sourceAuto:raw.source==='AUTO'||raw.source==='BOTH',tokenXMint:raw.features.tokenX,tokenYMint:raw.features.tokenY,pairedTokenMint:raw.features.pairedTokenMint,pairedTokenSymbol:raw.features.pairedTokenSymbol,marketCapCohort:raw.features.marketCapCohort,state,tier,priorityScore:raw.priorityScore,rank:r?.rank,universePercentile:r?.universePercentile,reasonCodes:r?reasonCodes(r):raw.hardReasons,evidenceState:raw.features.evidence,payload:{policyId:policy.policyId,decision:raw.decision,selectionReasons:raw.selectionReasons,warnings:raw.warnings}});
    }
    for(const r of result.rankings)await store.insertDiscoveryRanking({rankingCycleId,poolAddress:r.pool.address,observedAt:result.observedAt,policyId:policy.policyId,rank:r.rank,universePercentile:r.universePercentile,feePercentile:r.feePercentile,volumePercentile:r.volumePercentile,liquidityPercentile:r.liquidityPercentile,priorityScore:r.priorityScore,state:r.state,tier:r.tier,reasonCodes:reasonCodes(r),payload:{marketCapCohort:r.features.marketCapCohort,source:r.source}});
    const staleCutoff=new Date(Date.parse(result.observedAt)-policy.staleAfterMs).toISOString();const staleMarked=await store.markDiscoveryPoolsStale(staleCutoff,result.observedAt);
    let deep:Awaited<ReturnType<typeof runDeepDiscoveryCycle>>|undefined;
    if((process.env.LPFORGE_DISCOVERY_DEEP_ENABLED??'true').toLowerCase()==='true'&&result.deepScreenQueue.length){
      const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_DISCOVERY_DEEP_REQUIRES_LIVE_READ_ONLY');
      // A pool entering D3 is deliberately non-executable until the current
      // deep-screen result and D4 tier assignment have both been persisted.
      const deepQueue=selectDeepScreenSlice(result.deepScreenQueue,collectorNumber('LPFORGE_DISCOVERY_DEEP_MAX_POOLS',1,1,10),result.observedAt,Math.max(30_000,Number(process.env.LPFORGE_DISCOVERY_INTERVAL_MS??180_000)));
      for(const r of deepQueue)await store.upsertDiscoveryPool({poolAddress:r.pool.address,observedAt:result.observedAt,sourceManual:r.source==='MANUAL'||r.source==='BOTH',sourceAuto:r.source==='AUTO'||r.source==='BOTH',tokenXMint:r.features.tokenX,tokenYMint:r.features.tokenY,pairedTokenMint:r.features.pairedTokenMint,pairedTokenSymbol:r.features.pairedTokenSymbol,marketCapCohort:r.features.marketCapCohort,state:'OBSERVING',tier:'C',priorityScore:r.priorityScore,rank:r.rank,universePercentile:r.universePercentile,reasonCodes:['DISCOVERY_DEEP_SCREEN_IN_PROGRESS'],evidenceState:r.features.evidence,payload:{policyId:policy.policyId,deepScreenInProgressAt:result.observedAt}});
      const discoveryRpcInterval=Math.max(cfg.rpcMinIntervalMs,collectorNumber('LPFORGE_DISCOVERY_RPC_MIN_INTERVAL_MS',1_000,100,10_000));
      // Deep screening replays historical chain activity. It is backfill, so
      // it must yield to the live candidate collector's P3 observation lane.
      const adapter=createMeteoraReadAdapter({rpcUrl:cfg.solanaRpcHttpUrl,cluster:cfg.cluster,programId:cfg.programId,expectedSdkVersion:cfg.expectedSdkVersion,rpcTimeoutMs:cfg.rpcTimeoutMs,rpcMinIntervalMs:discoveryRpcInterval,rpcMaxRetries:cfg.rpcMaxRetries,retryBaseDelayMs:cfg.rpcRetryBaseDelayMs,retryMaxDelayMs:cfg.rpcRetryMaxDelayMs,priority:'P4_BACKFILL'});
      const rpc=createSolanaRpcClient({url:cfg.solanaRpcHttpUrl,timeoutMs:cfg.rpcTimeoutMs,minIntervalMs:discoveryRpcInterval,maxRetries:cfg.rpcMaxRetries,retryBaseDelayMs:cfg.rpcRetryBaseDelayMs,retryMaxDelayMs:cfg.rpcRetryMaxDelayMs,priority:'P4_BACKFILL'});
      deep=await runDeepDiscoveryCycle({api,adapter,rpc,store,cheapQueue:deepQueue,observedAt:result.observedAt,policy:{...DEFAULT_DISCOVERY_RUNTIME_POLICY,eventScanLimit:collectorNumber('LPFORGE_DISCOVERY_DEEP_EVENT_SCAN_LIMIT',1,1,100)}});
      const byPool=new Map(deep.assignments.map(x=>[x.poolAddress,x])),deepByPool=new Map(deep.deep.map(x=>[x.poolAddress,x]));
      for(const r of result.rankings){const a=byPool.get(r.pool.address),d=deepByPool.get(r.pool.address);if(!a||!d)continue;const lifecycle=deriveDiscoveryLifecycleState({deep:d,assignment:a});await store.upsertDiscoveryPool({poolAddress:r.pool.address,observedAt:result.observedAt,sourceManual:r.source==='MANUAL'||r.source==='BOTH',sourceAuto:r.source==='AUTO'||r.source==='BOTH',tokenXMint:r.features.tokenX,tokenYMint:r.features.tokenY,pairedTokenMint:r.features.pairedTokenMint,pairedTokenSymbol:r.features.pairedTokenSymbol,marketCapCohort:r.features.marketCapCohort,state:lifecycle.state,tier:lifecycle.tier,priorityScore:a.deepPriority,rank:a.rank??undefined,universePercentile:r.universePercentile,reasonCodes:a.selectionReason,evidenceState:r.features.evidence,payload:{policyId:policy.policyId,deepScreened:true,deepScreenedAt:result.observedAt,control:a.control,opportunityHalfLifeMinutes:a.opportunityHalfLifeMinutes}});}
    }
    const summary={status:'PASS',authority:'DISCOVERY_ONLY_NO_EXECUTION',observedAt:result.observedAt,policyId:policy.policyId,rankingCycleId,enumerated:result.enumeratedCount,deduplicated:result.deduplicatedCount,accepted:result.accepted.length,rejected:result.rejected.length,deepScreenQueue:result.deepScreenQueue.length,deepScreened:deep?.deep.length??0,predictions:deep?.predictions.length??0,baselines:deep?.baselines??{},staleMarked,tierA:deep?.assignments.filter(x=>x.tier==='A').length??0,tierB:deep?.assignments.filter(x=>x.tier==='B').length??0,tierControl:deep?.assignments.filter(x=>x.tier==='CONTROL').length??0,top:result.rankings.slice(0,10).map(x=>({rank:x.rank,pool:x.pool.address,name:x.features.name,score:x.priorityScore,marketCapCohort:x.features.marketCapCohort,feeTvl1h:x.features.feeTvl1h,volume1hUsd:x.features.volume1hUsd,tvlUsd:x.features.tvlUsd,reasons:reasonCodes(x)}))};console.log(json(summary));return summary;
  } finally {await store.close()}
}
async function status(){const store=await createPostgresStore(env('DATABASE_URL'));try{console.log(json({authority:'DISCOVERY_ONLY_NO_EXECUTION',candidates:await store.listDiscoveryCandidates(['A','B','C'])}))}finally{await store.close()}}
function collectorNumber(name:string,fallback:number,min:number,max:number){const aliases:Record<string,string>={LPFORGE_DISCOVERY_BACKFILL_LOOKBACK_MINUTES:'LPFORGE_ENTRY_BACKFILL_CONTEXT_MINUTES',LPFORGE_DISCOVERY_BACKFILL_MIN_HISTORY_MINUTES:'LPFORGE_ENTRY_BACKFILL_RECENT_MINUTES',LPFORGE_DISCOVERY_LIVE_CONFIRMATION_MINUTES:'LPFORGE_ENTRY_LIVE_CONFIRMATION_MINUTES',LPFORGE_DISCOVERY_LIVE_CONFIRMATION_MIN_OBSERVATIONS:'LPFORGE_ENTRY_LIVE_CONFIRMATION_MIN_OBSERVATIONS',LPFORGE_DISCOVERY_LIVE_CONFIRMATION_MAX_GAP_MS:'LPFORGE_ENTRY_LIVE_CONFIRMATION_MAX_GAP_MS'};const defaultValue=name==='LPFORGE_DISCOVERY_BACKFILL_LOOKBACK_MINUTES'?240:name==='LPFORGE_DISCOVERY_BACKFILL_MIN_HISTORY_MINUTES'?90:fallback;const value=Number(process.env[aliases[name]??name]??process.env[name]??defaultValue);return Number.isFinite(value)?Math.max(min,Math.min(max,Math.floor(value))):defaultValue;}
async function collect(){
 const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_DISCOVERY_COLLECTOR_REQUIRES_LIVE_READ_ONLY');
 const store=await createPostgresStore(env('DATABASE_URL'));try{
  const rpcInterval=Math.max(cfg.rpcMinIntervalMs,collectorNumber('LPFORGE_ACTIVE_COLLECTOR_RPC_MIN_INTERVAL_MS',400,100,10_000));
  const api=createMeteoraDataApi({baseUrl:cfg.meteoraDataApiUrl,maxRps:Math.max(1,Math.min(cfg.dataApiMaxRps,collectorNumber('LPFORGE_ACTIVE_COLLECTOR_DATA_API_MAX_RPS',2,1,10))),timeoutMs:cfg.httpTimeoutMs});
  const adapter=createMeteoraReadAdapter({rpcUrl:cfg.solanaRpcHttpUrl,cluster:cfg.cluster,programId:cfg.programId,expectedSdkVersion:cfg.expectedSdkVersion,rpcTimeoutMs:cfg.rpcTimeoutMs,rpcMinIntervalMs:rpcInterval,rpcMaxRetries:cfg.rpcMaxRetries,retryBaseDelayMs:cfg.rpcRetryBaseDelayMs,retryMaxDelayMs:cfg.rpcRetryMaxDelayMs,priority:'P3_DISCOVERY'});
  const rpc=createSolanaRpcClient({url:cfg.solanaRpcHttpUrl,timeoutMs:cfg.rpcTimeoutMs,minIntervalMs:rpcInterval,maxRetries:cfg.rpcMaxRetries,retryBaseDelayMs:cfg.rpcRetryBaseDelayMs,retryMaxDelayMs:cfg.rpcRetryMaxDelayMs,priority:'P3_DISCOVERY'});
  const result=await collectActiveCandidateEvidence({api,adapter,rpc,store,observedAt:new Date().toISOString(),policy:{maxActiveCandidateCollectors:collectorNumber('LPFORGE_ACTIVE_COLLECTOR_MAX_POOLS',30,1,30),maxConcurrentPoolReads:collectorNumber('LPFORGE_ACTIVE_COLLECTOR_MAX_CONCURRENT',2,1,4),p3BudgetRps:collectorNumber('LPFORGE_RPC_P3_MAX_RPS',3,1,100),estimatedP3CallsPerPool:collectorNumber('LPFORGE_ACTIVE_COLLECTOR_ESTIMATED_P3_CALLS_PER_POOL',12,1,100),p95PoolCollectionMs:collectorNumber('LPFORGE_ACTIVE_COLLECTOR_P95_POOL_COLLECTION_MS',90_000,1_000,300_000),serviceabilitySafetyMargin:collectorNumber('LPFORGE_ACTIVE_COLLECTOR_SERVICEABILITY_MARGIN_PCT',70,5,95)/100,serviceableActiveCandidateHardCap:collectorNumber('LPFORGE_ACTIVE_COLLECTOR_SERVICEABLE_MAX_POOLS',30,0,30),perPoolMinIntervalMs:collectorNumber('LPFORGE_ACTIVE_COLLECTOR_PER_POOL_MIN_INTERVAL_MS',30_000,30_000,300_000),eventScanLimit:collectorNumber('LPFORGE_ACTIVE_COLLECTOR_EVENT_SCAN_LIMIT',10,1,100),backfillLookbackMinutes:collectorNumber('LPFORGE_DISCOVERY_BACKFILL_LOOKBACK_MINUTES',90,60,240),backfillMinHistoryMinutes:collectorNumber('LPFORGE_DISCOVERY_BACKFILL_MIN_HISTORY_MINUTES',60,15,240),liveConfirmationMinutes:collectorNumber('LPFORGE_DISCOVERY_LIVE_CONFIRMATION_MINUTES',10,10,15),liveConfirmationMinObservations:collectorNumber('LPFORGE_DISCOVERY_LIVE_CONFIRMATION_MIN_OBSERVATIONS',4,2,60),liveConfirmationMaxGapMs:collectorNumber('LPFORGE_DISCOVERY_LIVE_CONFIRMATION_MAX_GAP_MS',450_000,30_000,600_000),maxConcurrentBackfills:collectorNumber('LPFORGE_BACKFILL_MAX_CONCURRENT_POOLS',1,1,2),backfillEventScanLimit:collectorNumber('LPFORGE_BACKFILL_MAX_TX_SIGNATURES_PER_POOL',100,10,300),backfillRetryMs:collectorNumber('LPFORGE_BACKFILL_RETRY_MS',900_000,60_000,3_600_000),supplementalPoolAddresses:productionEvidencePools()}});
  console.log(json({...result,status:result.results.every(x=>x.status==='PASS')?'PASS':'DEGRADED'}));return result;
 }finally{await store.close()}
}
async function start(){const discoveryInterval=Math.max(30_000,Number(process.env.LPFORGE_DISCOVERY_INTERVAL_MS??180_000)),perPoolMinInterval=collectorNumber('LPFORGE_ACTIVE_COLLECTOR_PER_POOL_MIN_INTERVAL_MS',30_000,30_000,300_000),collectorInterval=Math.max(collectorNumber('LPFORGE_ACTIVE_COLLECTOR_INTERVAL_MS',30_000,30_000,300_000),perPoolMinInterval);let nextDiscovery=0,nextCollection=0;for(;;){const now=Date.now();if(now>=nextDiscovery){try{await once()}catch(e){console.error(json({status:'ERROR',authority:'DISCOVERY_ONLY_NO_EXECUTION',component:'D1_D8',error:e instanceof Error?e.message:String(e)}))}nextDiscovery=Date.now()+discoveryInterval;}if(Date.now()>=nextCollection){try{await collect()}catch(e){console.error(json({status:'ERROR',authority:'DISCOVERY_OBSERVATION_ONLY',component:'ACTIVE_CANDIDATE_COLLECTOR',error:e instanceof Error?e.message:String(e)}))}nextCollection=Date.now()+collectorInterval;}await new Promise(r=>setTimeout(r,Math.max(250,Math.min(1000,nextDiscovery-Date.now(),nextCollection-Date.now()))));}}
const cmd=process.argv[2]??'once';if(cmd==='once')await once();else if(cmd==='collect-once')await collect();else if(cmd==='start')await start();else if(cmd==='status')await status();else throw new Error(`LPFORGE_DISCOVERY_COMMAND:${cmd}`);
