import { fixtureBins, fixtureDataApiPool, fixturePool, fixtureSwaps } from '../../../packages/test-fixtures/src/index.js';
import { computeActiveBinMovement, computeBinWindowFeatures, computeFeeQuality, computeSwapFlowFeatures, type Phase1PoolFeatures } from '../../../packages/features/src/index.js';
import { assessPool, computeSustainability, poolInputFromDataApi } from '../../../packages/pool-intelligence/src/index.js';
import { simulateSyntheticPosition, summarizeRangeOutcome, type BinFrame, type SyntheticPosition } from '../../../packages/simulator/src/index.js';
import { loadPhase1Config } from '../../../packages/config/src/index.js';
import { createMeteoraDataApi } from '../../../packages/data-api/src/index.js';
import { createMeteoraReadAdapter } from '../../../packages/meteora/src/index.js';

function json(value:unknown):string{return JSON.stringify(value,(_,v)=>typeof v==='bigint'?v.toString():v,2);}
function fixtureFrames():BinFrame[]{return[
  {observedAt:'2026-08-12T09:58:00.000Z',activeBinId:99,bins:fixtureBins},
  {observedAt:'2026-08-12T09:59:00.000Z',activeBinId:100,bins:fixtureBins.map((b)=>({...b,amountX:String(Number(b.amountX)+10),amountY:String(Math.max(0,Number(b.amountY)-5))}))},
  {observedAt:'2026-08-12T10:00:00.000Z',activeBinId:102,bins:fixtureBins.map((b)=>({...b,amountX:String(Number(b.amountX)+20),amountY:String(Math.max(0,Number(b.amountY)-10))}))},
  {observedAt:'2026-08-12T10:01:00.000Z',activeBinId:104,bins:fixtureBins},
  {observedAt:'2026-08-12T10:02:00.000Z',activeBinId:101,bins:fixtureBins},
];}
function fixturePosition():SyntheticPosition{return{pool:fixturePool.address,lowerBinId:99,upperBinId:102,openedAt:'2026-08-12T09:58:00.000Z',bins:[99,100,101,102].map((binId)=>({binId,positionShareRaw:500n,competingSupplyRaw:500n})),strategyLabel:'PHASE2_FIXTURE_UNIFORM'}};
function printableSimulation(sim:ReturnType<typeof simulateSyntheticPosition>){return{...sim,totalAttributedFeeXRaw:sim.totalAttributedFeeXRaw.toString(),totalAttributedFeeYRaw:sim.totalAttributedFeeYRaw.toString(),inventory:sim.inventory.map((x)=>({...x,tokenXRaw:x.tokenXRaw.toString(),tokenYRaw:x.tokenYRaw.toString()})),feeAttribution:sim.feeAttribution.map((x)=>({...x,mmFeeRaw:x.mmFeeRaw.toString(),attributedLpFeeRaw:x.attributedLpFeeRaw.toString()}))};}
async function fixtureReport():Promise<void>{const frames=fixtureFrames(),position=fixturePosition();const labEvents=fixtureSwaps.map((e,i)=>({...e,mmFee:String(BigInt(e.mmFee??'0')*100n),feesOnTokenX:i%2===0}));const sim=simulateSyntheticPosition({position,frames,events:labEvents});const bin=computeBinWindowFeatures(fixtureBins,fixturePool.activeBinId),flow=computeSwapFlowFeatures(fixtureSwaps),movement=computeActiveBinMovement(frames.map((f)=>({binId:f.activeBinId,observedAt:f.observedAt}))),fee=computeFeeQuality(fixtureDataApiPool);const assessment=assessPool({pool:fixturePool.address,protocolCompatible:true,dataFreshness:'GOOD',observedAt:frames.at(-1)!.observedAt,dataAgeSeconds:10,tokenX:{freezeAuthorityDisabled:true,isVerified:true,holders:5000},tokenY:{freezeAuthorityDisabled:true,isVerified:true,holders:100000},tvl:fixtureDataApiPool.tvl,bin,flow,movement,fee});console.log(json({phase:'P2',mode:'FIXTURE',simulation:printableSimulation(sim),range:summarizeRangeOutcome(position,frames),poolAssessment:assessment}));}
async function livePool(address:string):Promise<void>{const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_PHASE2_LIVE_POOL_REQUIRES_LIVE_READ_ONLY');const api=createMeteoraDataApi({baseUrl:cfg.meteoraDataApiUrl,maxRps:cfg.dataApiMaxRps,timeoutMs:cfg.httpTimeoutMs});const adapter=createMeteoraReadAdapter({rpcUrl:cfg.solanaRpcHttpUrl,cluster:cfg.cluster,programId:cfg.programId,expectedSdkVersion:cfg.expectedSdkVersion,rpcTimeoutMs:cfg.rpcTimeoutMs});const [poolFact,active,bins,poolApi,hist,compat]=await Promise.all([adapter.getPool(address),adapter.getActiveBin(address),adapter.getBinsAroundActive(address,30),api.getPool(address),api.getHistoricalVolume(address,{timeframe:'1h'}),adapter.verifyCompatibility(address)]);const features:Phase1PoolFeatures={bin:computeBinWindowFeatures(bins,active.binId),fee:computeFeeQuality(poolApi)};const sustainability=computeSustainability(hist.data);const input=poolInputFromDataApi(poolApi,features,{protocolCompatible:compat.state==='VERIFIED',dataFreshness:'GOOD',observedAt:new Date().toISOString(),dataAgeSeconds:0,functionType:poolFact.functionType==='UNDETERMINED'?'UNKNOWN':poolFact.functionType});const assessment=assessPool(input);console.log(json({phase:'P2',mode:'LIVE_READ_ONLY',pool:poolFact,activeBin:active,binWindow:{count:bins.length,features:features.bin},historicalSustainability:sustainability,poolAssessment:assessment,note:'Flow/movement history is intentionally absent from one-shot live-pool; collector history is required before ELIGIBLE can be trusted.'}));}
async function main():Promise<void>{const cmd=process.argv[2]??'fixture-report';if(cmd==='fixture-report'){await fixtureReport();return;}if(cmd==='live-pool'){const address=process.argv[3];if(!address)throw new Error('Usage: lpforge lab live-pool <poolAddress>');await livePool(address);return;}throw new Error('Usage: lpforge lab fixture-report | live-pool <poolAddress>');}
main().catch((e:unknown)=>{console.error(e instanceof Error?e.message:String(e));process.exitCode=1;});
