import type { ThesisStatus } from '../../thesis-monitor/src/index.js';
export interface RebalanceCandidate {id:string;strategy:string;orientation:string;lowerBinId:number;upperBinId:number;expectedGrossForwardValue:number;implementationCost:number;tailRiskCharge:number;survivalProbability:number;inventoryRiskBefore:number;inventoryRiskAfter:number;uncertainty:number;}
export interface RebalanceAssessment {decision:'REBALANCE'|'NO_REBALANCE';selectedCandidateId?:string;incrementalValue:number;inventoryRiskImprovement:number;reasonCodes:string[];ranked:Array<RebalanceCandidate&{netForwardEv:number;inventoryRiskImprovement:number}>;}
export function assessRebalance(input:{currentForwardEv:number;thesisStatus:ThesisStatus;candidates:RebalanceCandidate[];minimumIncrementalValue?:number;}):RebalanceAssessment{
 const min=input.minimumIncrementalValue??.0002;if(input.thesisStatus==='INVALIDATED'||input.thesisStatus==='EMERGENCY')return{decision:'NO_REBALANCE',incrementalValue:0,inventoryRiskImprovement:0,reasonCodes:['REBALANCE_NOT_ALLOWED_AFTER_THESIS_INVALIDATION'],ranked:[]};
 const ranked=input.candidates.map((c)=>({...c,netForwardEv:c.expectedGrossForwardValue-c.implementationCost-c.tailRiskCharge,inventoryRiskImprovement:c.inventoryRiskBefore-c.inventoryRiskAfter})).sort((a,b)=>b.netForwardEv-a.netForwardEv||b.inventoryRiskImprovement-a.inventoryRiskImprovement||a.id.localeCompare(b.id));const best=ranked[0];
 if(!best)return{decision:'NO_REBALANCE',incrementalValue:0,inventoryRiskImprovement:0,reasonCodes:['REBALANCE_NO_CANDIDATE'],ranked};const incremental=best.netForwardEv-input.currentForwardEv;
 if(incremental<=min)return{decision:'NO_REBALANCE',incrementalValue:incremental,inventoryRiskImprovement:best.inventoryRiskImprovement,reasonCodes:['REBALANCE_COST_NOT_RECOVERED'],ranked};if(best.survivalProbability<.45)return{decision:'NO_REBALANCE',incrementalValue:incremental,inventoryRiskImprovement:best.inventoryRiskImprovement,reasonCodes:['REBALANCE_SURVIVAL_TOO_LOW'],ranked};if(best.uncertainty>.75)return{decision:'NO_REBALANCE',incrementalValue:incremental,inventoryRiskImprovement:best.inventoryRiskImprovement,reasonCodes:['REBALANCE_UNCERTAINTY_TOO_HIGH'],ranked};return{decision:'REBALANCE',selectedCandidateId:best.id,incrementalValue:incremental,inventoryRiskImprovement:best.inventoryRiskImprovement,reasonCodes:[best.inventoryRiskImprovement>0?'REBALANCE_EV_AND_INVENTORY_IMPROVE':'REBALANCE_EV_IMPROVES'],ranked};
}
