import { canonicalJson, sha256Hex } from '../../domain/src/index.js';
import type { DataApiPool, HistoricalVolumePoint, MeteoraDataApi } from '../../data-api/src/index.js';
import { buildMarketContext, type MarketObservation } from '../../market-context/src/index.js';
import type { MeteoraReadAdapter, SolanaRpcClient } from '../../meteora/src/index.js';
import { EXPECTED_DLMM_PROGRAM_ID, scanAddressTransactions } from '../../meteora/src/index.js';
import type { Phase1Store } from '../../db/src/index.js';

export interface ActiveCandidateEvidencePolicy { id:string;maxActiveCandidateCollectors:number;maxConcurrentPoolReads:number;perPoolMinIntervalMs:number;collectionIntervalMs:number;liveConfirmationTargetCoverageMs:number;binRadius:number;eventScanLimit:number;historyWindowMs:number;staleAfterMs:number;recentBackfillMinutes:number;contextBackfillMinutes:number;backfillLookbackMinutes:number;backfillMinHistoryMinutes:number;liveConfirmationMinutes:number;liveConfirmationMinObservations:number;liveConfirmationMaxGapMs:number;backfillRetryMs:number;maxConcurrentBackfills:number;backfillEventScanLimit:number;supplementalPoolAddresses:string[];p3BudgetRps:number;estimatedP3CallsPerPool:number;p95PoolCollectionMs:number;serviceabilitySafetyMargin:number;serviceableActiveCandidateHardCap:number; }
export const DEFAULT_ACTIVE_CANDIDATE_EVIDENCE_POLICY:ActiveCandidateEvidencePolicy={id:'phase4-active-candidate-evidence-v3-multi-horizon',maxActiveCandidateCollectors:30,maxConcurrentPoolReads:2,perPoolMinIntervalMs:30_000,collectionIntervalMs:60_000,liveConfirmationTargetCoverageMs:360_000,binRadius:35,eventScanLimit:10,historyWindowMs:4*60*60_000,staleAfterMs:180_000,recentBackfillMinutes:90,contextBackfillMinutes:240,backfillLookbackMinutes:240,backfillMinHistoryMinutes:90,liveConfirmationMinutes:10,liveConfirmationMinObservations:4,liveConfirmationMaxGapMs:450_000,backfillRetryMs:15*60_000,maxConcurrentBackfills:1,backfillEventScanLimit:100,supplementalPoolAddresses:[],p3BudgetRps:3,estimatedP3CallsPerPool:12,p95PoolCollectionMs:90_000,serviceabilitySafetyMargin:.70,serviceableActiveCandidateHardCap:30};
/** Deterministic fair rotation prevents a large candidate universe from
 * repeatedly collecting only the first addresses and bursting shared RPC. */
export function selectActiveCandidateCollectionSlice<T extends {poolAddress:string;state?:string}>(all:readonly T[],maxPools:number,observedAt:string,collectionIntervalMs:number):T[]{
 // Select a non-overlapping partition for each collector cycle.  Advancing a
 // sliding window by one address looked fair, but with four slots it sampled
 // the same pools on consecutive cycles and left later pools idle long enough
 // to violate the live-confirmation gap.  Production-monitored pools remain
 // first in the deterministic ordering, while every remaining active pool is
 // guaranteed one slot in a complete round.
 const priority=[...all].filter(x=>x.state==='PRODUCTION_MONITORED').sort((a,b)=>a.poolAddress.localeCompare(b.poolAddress));
 const active=[...all].filter(x=>x.state!=='PRODUCTION_MONITORED').sort((a,b)=>a.poolAddress.localeCompare(b.poolAddress));
 const ordered=[...priority,...active],limit=Math.min(Math.max(0,Math.floor(maxPools)),ordered.length);
 if(!ordered.length||limit<=0)return [];
 const parsed=Date.parse(observedAt),epoch=Number.isFinite(parsed)?Math.floor(parsed/Math.max(1,collectionIntervalMs)):0,rounds=Math.ceil(ordered.length/limit),round=((epoch%rounds)+rounds)%rounds,start=round*limit;
 return ordered.slice(start,start+limit);
}
export function requiredActiveCandidateCollectionCapacity(candidateCount:number,collectorIntervalMs:number,targetCoverageMs=180_000){return Math.max(1,Math.ceil(Math.max(0,candidateCount)*Math.max(1,collectorIntervalMs)/Math.max(1,targetCoverageMs)));}
export function calculateServiceableActiveCandidateCapacity(input:{p3BudgetRps:number;estimatedP3CallsPerPool:number;p95PoolCollectionMs:number;maxConcurrentPoolReads:number;targetCoverageMs:number;serviceabilitySafetyMargin:number;hardCap:number}){
 const margin=Math.max(.05,Math.min(.95,input.serviceabilitySafetyMargin)),rpc=Math.floor(Math.max(0,input.p3BudgetRps)*Math.max(1,input.targetCoverageMs)/1000*margin/Math.max(1,input.estimatedP3CallsPerPool)),cadence=Math.floor(Math.max(1,input.targetCoverageMs)/Math.max(1,input.p95PoolCollectionMs)*Math.max(1,Math.floor(input.maxConcurrentPoolReads)));
 return Math.max(0,Math.min(rpc,cadence,Math.max(0,Math.floor(input.hardCap))));
}
export interface BackfillQuality {requestedMinutes:number;coveredMinutes:number;coverageRatio:number;feeBucketCount:number;ohlcvBucketCount:number;swapEventCount:number;independent15mEpisodes:number;oldestEvidenceAt?:string;newestEvidenceAt?:string;quality:'SUFFICIENT'|'PARTIAL'|'INSUFFICIENT'|'DEGRADED';reasonCodes:string[];}
export interface HistoryMaturity {state:'WARMING'|'MATURE'|'STALE'|'DEGRADED';historicalState:'WARMING'|'MATURE'|'DEGRADED';liveConfirmationState:'WARMING'|'CONFIRMED'|'STALE'|'DEGRADED';marketObservationCount:number;activeBinObservationCount:number;binFrameCount:number;swapEventCount:number;oldestObservationAt?:string;latestObservationAt?:string;completeness5m:number;completeness15m:number;completeness1h:number;reasonCodes:string[];}
export interface EconomicEstimateDraft {economicEstimateId:string;poolAddress:string;asOf:string;fidelity:'AGGREGATE_ESTIMATE'|'EVENT_PATH_ESTIMATE';rawObservationCount:number;effectiveSampleCount:number;independentEpisodeCount:number;feeObservationCount:number;eventPathObservationCount:number;feeRatePerCapitalHour:number;uncertainty:number;evidenceAgeSeconds:number;sourceHashes:Record<string,unknown>;payload:Record<string,unknown>;}
const n=(x:unknown)=>Number.isFinite(Number(x))?Number(x):0;
const hasMeasuredEconomics=(...values:unknown[])=>values.some(value=>value!==undefined&&value!==null&&Number.isFinite(Number(value)));
const clamp=(x:number,min=0,max=1)=>Math.max(min,Math.min(max,x));
const iso=(x:number)=>new Date(x).toISOString();
const episodes=(times:string[])=>new Set(times.map(x=>Math.floor(Date.parse(x)/(15*60_000))).filter(Number.isFinite)).size;
const asMarket=(rows:Awaited<ReturnType<Phase1Store['loadCandidateMarketObservations']>>):MarketObservation[]=>(rows.map(x=>({observedAt:x.observedAt,price:x.price,...(x.activeBinId!==undefined?{activeBinId:x.activeBinId}:{}),resolutionMs:x.resolutionMs,...(x.volume!==undefined?{volume:x.volume}:{}),...(x.feeValue!==undefined?{feeValue:x.feeValue}:{}),...(x.localLiquidity!==undefined?{localLiquidity:x.localLiquidity}:{})})));

export function assessBackfillQuality(input:{requestedMinutes:number;feeBuckets:HistoricalVolumePoint[];ohlcvBuckets:Array<{timestamp:number}>;swapEventCount:number}):BackfillQuality {
 const stamps=[...input.feeBuckets.map(x=>x.timestamp),...input.ohlcvBuckets.map(x=>x.timestamp)].filter(Number.isFinite).sort((a,b)=>a-b),oldest=stamps[0],newest=stamps.at(-1),covered=oldest===undefined||newest===undefined?0:Math.min(input.requestedMinutes,Math.max(0,Math.floor((newest-oldest)/60))),coverageRatio=clamp(covered/Math.max(1,input.requestedMinutes)),independent15mEpisodes=episodes(input.feeBuckets.map(x=>iso(x.timestamp*1000)));
 const quality:BackfillQuality['quality']=coverageRatio>=.60&&input.feeBuckets.length>=12&&independent15mEpisodes>=6?'SUFFICIENT':stamps.length?'PARTIAL':'INSUFFICIENT';
 return{requestedMinutes:input.requestedMinutes,coveredMinutes:covered,coverageRatio,feeBucketCount:input.feeBuckets.length,ohlcvBucketCount:input.ohlcvBuckets.length,swapEventCount:input.swapEventCount,independent15mEpisodes,...(oldest!==undefined?{oldestEvidenceAt:iso(oldest*1000)}:{}),...(newest!==undefined?{newestEvidenceAt:iso(newest*1000)}:{}),quality,reasonCodes:quality==='SUFFICIENT'?['HISTORY_BACKFILL_SUFFICIENT']:quality==='PARTIAL'?['ENTRY_HISTORY_BACKFILL_PARTIAL']:['ENTRY_HISTORY_BACKFILL_PENDING']};
}

export async function assessHistoryMaturity(input:{poolAddress:string;assessedAt:string;history:Awaited<ReturnType<Phase1Store['loadOperationalHistory']>>;staleAfterMs?:number;historicalMarket?:Awaited<ReturnType<Phase1Store['loadCandidateMarketObservations']>>;liveMarket?:Awaited<ReturnType<Phase1Store['loadCandidateMarketObservations']>>;liveConfirmationMinutes?:number;liveConfirmationMinObservations?:number;liveConfirmationMaxGapMs?:number}):Promise<HistoryMaturity>{
 const market=input.history.marketObservations,context=await buildMarketContext(input.poolAddress,input.assessedAt,market),oldest=market.at(0)?.observedAt,latest=market.at(-1)?.observedAt,c5=context.horizons['5m'].completeness,c15=context.horizons['15m'].completeness,c1h=context.horizons['1h'].completeness;
 const historical=input.historicalMarket??market.map(x=>({observedAt:x.observedAt,sourceType:'LIVE_OBSERVED',sourceProvider:'COMPATIBILITY',price:x.price,resolutionMs:60_000,...(x.activeBinId!==undefined?{activeBinId:x.activeBinId}:{}),...(x.volume!==undefined?{volume:x.volume}:{}),...(x.feeValue!==undefined?{feeValue:x.feeValue}:{}),...(x.localLiquidity!==undefined?{localLiquidity:x.localLiquidity}:{})})),historicalRows=asMarket(historical),historicalEnds=historicalRows.map(row=>Date.parse(row.observedAt)+Math.max(1_000,Number(row.resolutionMs??60_000))).filter(Number.isFinite),historicalAt=historicalEnds.length?iso(Math.max(...historicalEnds)):input.assessedAt,historicalContext=await buildMarketContext(input.poolAddress,historicalAt,historicalRows);
 const historicalState:HistoryMaturity['historicalState']=Math.min(historicalContext.horizons['5m'].completeness,historicalContext.horizons['15m'].completeness,historicalContext.horizons['1h'].completeness)>=.60?'MATURE':'WARMING';
 let liveConfirmationState:HistoryMaturity['liveConfirmationState']='CONFIRMED',liveConfirmationReason:string|undefined;if(input.liveMarket){
  const assessed=Date.parse(input.assessedAt),confirmationMs=Math.max(0,input.liveConfirmationMinutes??0)*60_000,minObservations=Math.max(1,input.liveConfirmationMinObservations??1),maxGapMs=Math.max(1_000,input.liveConfirmationMaxGapMs??Number.POSITIVE_INFINITY),windowStart=assessed-confirmationMs,ts=input.liveMarket.map(x=>Date.parse(x.observedAt)).filter(t=>Number.isFinite(t)&&t>=windowStart-maxGapMs&&t<=assessed).sort((a,b)=>a-b),anchor=ts.filter(t=>t<=windowStart).at(-1),inWindow=ts.filter(t=>t>=windowStart),first=inWindow[0],last=ts.at(-1);
  const gaps=first===undefined?[]:[first-windowStart,...inWindow.slice(1).map((t,i)=>t-inWindow[i]!),assessed-(last??assessed)],largestGap=Math.max(0,...gaps);
  if(!last||assessed-last>(input.staleAfterMs??180_000))liveConfirmationState='STALE';
  else if(ts.length<minObservations){liveConfirmationState='WARMING';liveConfirmationReason='ENTRY_LIVE_CONFIRMATION_INSUFFICIENT_OBSERVATIONS';}
  else if(largestGap>=maxGapMs){liveConfirmationState='WARMING';liveConfirmationReason='ENTRY_LIVE_CONFIRMATION_GAP';}
  else if(!anchor||!first){liveConfirmationState='WARMING';liveConfirmationReason='ENTRY_LIVE_CONFIRMATION_PENDING';}
 }
 const reasons:string[]=[];let state:HistoryMaturity['state']='WARMING';if(!latest||Date.parse(input.assessedAt)-Date.parse(latest)>(input.staleAfterMs??180_000)){state='STALE';reasons.push('HISTORY_STALE');}else if(historicalState==='MATURE'&&liveConfirmationState==='CONFIRMED'){state='MATURE';reasons.push('HISTORY_MATURE','LIVE_CONFIRMATION_CONFIRMED');}else{if(historicalState!=='MATURE')reasons.push('HISTORY_WARMING');if(liveConfirmationState==='WARMING')reasons.push('ENTRY_LIVE_CONFIRMATION_PENDING');if(liveConfirmationState==='STALE')reasons.push('ENTRY_LIVE_CONFIRMATION_STALE');}
 if(liveConfirmationReason&&liveConfirmationState==='WARMING')reasons.push(liveConfirmationReason);
 return{state,historicalState,liveConfirmationState,marketObservationCount:market.length,activeBinObservationCount:input.history.activeBins.length,binFrameCount:input.history.binFrames.length,swapEventCount:input.history.swapEvents.length,...(oldest?{oldestObservationAt:oldest}:{}),...(latest?{latestObservationAt:latest}:{}),completeness5m:c5,completeness15m:c15,completeness1h:c1h,reasonCodes:[...new Set(reasons)]};
}

export async function deriveEventPathEconomicEstimate(input:{poolAddress:string;asOf:string;dataApiPool:DataApiPool;feeBuckets:HistoricalVolumePoint[];history:Awaited<ReturnType<Phase1Store['loadOperationalHistory']>>}):Promise<EconomicEstimateDraft>{
 const recentStart=Date.parse(input.asOf)-90*60_000,fees=input.feeBuckets.filter(x=>Number.isFinite(x.timestamp)&&x.timestamp*1000>=recentStart&&n(x.fees)>=0).sort((a,b)=>a.timestamp-b.timestamp),feeCount=fees.length,pathTimes=[...input.history.swapEvents.map(x=>x.stamp.observedAt),...input.history.binFrames.map(x=>x.observedAt)].filter(x=>Date.parse(x)>=recentStart),pathCount=pathTimes.length,effective=Math.min(episodes(fees.map(x=>iso(x.timestamp*1000))),episodes(pathTimes)),mature=feeCount>=12&&pathCount>=12&&effective>=6,first=fees[0]?.timestamp,last=fees.at(-1)?.timestamp,spanHours=first!==undefined&&last!==undefined?Math.max(1/12,(last-first)/3600):1,feeRate=clamp(fees.reduce((s,x)=>s+Math.max(0,n(x.fees)),0)/Math.max(1,n(input.dataApiPool.tvl))/spanHours,0,5),uncertainty=mature?clamp(.12+.30*(1-Math.min(1,effective/24))+.18*(1-Math.min(1,feeCount/36))+.12*(1-Math.min(1,pathCount/36))):.55,fidelity=mature?'EVENT_PATH_ESTIMATE' as const:'AGGREGATE_ESTIMATE' as const;
 const sourceHashes={feeBuckets:await sha256Hex(canonicalJson(fees)),eventPath:await sha256Hex(canonicalJson(pathTimes))},raw=feeCount+pathCount,core={poolAddress:input.poolAddress,asOf:input.asOf,fidelity,raw,effective,feeCount,pathCount,feeRate,uncertainty,sourceHashes};
 return{economicEstimateId:`econ-${await sha256Hex(canonicalJson(core))}`,poolAddress:input.poolAddress,asOf:input.asOf,fidelity,rawObservationCount:raw,effectiveSampleCount:effective,independentEpisodeCount:effective,feeObservationCount:feeCount,eventPathObservationCount:pathCount,feeRatePerCapitalHour:feeRate,uncertainty,evidenceAgeSeconds:last===undefined?Number.POSITIVE_INFINITY:Math.max(0,(Date.parse(input.asOf)-last*1000)/1000),sourceHashes,payload:{policyId:DEFAULT_ACTIVE_CANDIDATE_EVIDENCE_POLICY.id,feeBucketWindow:'NON_OVERLAPPING_5M',eventPathSources:['SWAP2EVT','BIN_FRAME'],mature}};
}

async function bounded<T,R>(items:T[],limit:number,fn:(x:T)=>Promise<R>):Promise<R[]>{const out:R[]=[];let i=0;await Promise.all(Array.from({length:Math.max(1,Math.min(limit,items.length))},async()=>{for(;;){const index=i++;if(index>=items.length)return;out[index]=await fn(items[index]!);}}));return out;}
export async function collectActiveCandidateEvidence(input:{api:MeteoraDataApi;adapter:MeteoraReadAdapter;rpc:SolanaRpcClient;store:Phase1Store;observedAt:string;policy?:Partial<ActiveCandidateEvidencePolicy>}):Promise<{authority:'DISCOVERY_OBSERVATION_ONLY';observedAt:string;serviceableCapacity:number;results:Array<{poolAddress:string;status:'PASS'|'DEGRADED';maturity?:HistoryMaturity;estimate?:EconomicEstimateDraft;error?:string}>}>{
 const p={...DEFAULT_ACTIVE_CANDIDATE_EVIDENCE_POLICY,...input.policy},supplementalAddresses=[...new Set(p.supplementalPoolAddresses.map(x=>x.trim()).filter(Boolean))],serviceableCapacity=calculateServiceableActiveCandidateCapacity({p3BudgetRps:p.p3BudgetRps,estimatedP3CallsPerPool:p.estimatedP3CallsPerPool,p95PoolCollectionMs:p.p95PoolCollectionMs,maxConcurrentPoolReads:p.maxConcurrentPoolReads,targetCoverageMs:p.liveConfirmationTargetCoverageMs,serviceabilitySafetyMargin:p.serviceabilitySafetyMargin,hardCap:p.serviceableActiveCandidateHardCap});
 if(typeof input.store.reconcileLiveEvidenceAdmission==='function')await input.store.reconcileLiveEvidenceAdmission({observedAt:input.observedAt,serviceableCapacity,productionMonitoredPoolAddresses:supplementalAddresses});
 const discovered=(await input.store.listDiscoveryCandidates(['A'])).filter(x=>x.state==='ACTIVE_CANDIDATE'),supplemental=supplementalAddresses.map(poolAddress=>({poolAddress,state:'PRODUCTION_MONITORED',tier:'MANUAL',priorityScore:Number.POSITIVE_INFINITY,lastSeenAt:input.observedAt,payload:{collectionTarget:'PRODUCTION_MONITORED'}})),byPool=new Map([...supplemental,...discovered].map(x=>[x.poolAddress,x])),requiredCapacity=requiredActiveCandidateCollectionCapacity(byPool.size,p.collectionIntervalMs,p.liveConfirmationTargetCoverageMs),capacity=Math.min(p.maxActiveCandidateCollectors,requiredCapacity),candidates=selectActiveCandidateCollectionSlice([...byPool.values()],capacity,input.observedAt,Math.max(30_000,p.collectionIntervalMs)),backfillPools=new Set<string>();
 for(const c of candidates){if(backfillPools.size>=p.maxConcurrentBackfills)break;const prior=await input.store.loadActiveCandidateBackfill(c.poolAddress),last=prior?.last_successful_at??prior?.last_attempt_at,historical=await input.store.loadCandidateMarketObservations(c.poolAddress,iso(Date.parse(input.observedAt)-p.historyWindowMs),2000),hasHistoricalPrice=historical.some(row=>row.sourceType==='HISTORICAL_API_BACKFILL');if(!last||!hasHistoricalPrice||Date.parse(input.observedAt)-Date.parse(String(last))>=p.backfillRetryMs)backfillPools.add(c.poolAddress);}
 const results=await bounded(candidates,p.maxConcurrentPoolReads,async c=>{try{
   const [apiPool,pool,bins,liveTxs]=await Promise.all([input.api.getPool(c.poolAddress),input.adapter.getPool(c.poolAddress),input.adapter.getBinsAroundActive(c.poolAddress,p.binRadius),scanAddressTransactions({rpc:input.rpc,address:c.poolAddress,limit:p.eventScanLimit,programId:EXPECTED_DLMM_PROGRAM_ID})]);
   // The cycle timestamp is captured before network reads begin.  Live facts
   // are stamped at their read completion; the decision timestamp is derived
   // below only after every current and historical read has completed.
   const collectedAt=new Date().toISOString();
   await input.store.insertPoolSnapshot(pool);await input.store.insertBins(bins);await input.store.insertDataApiPool(apiPool as Record<string,unknown>,collectedAt);await input.store.insertCandidateMarketObservations({poolAddress:c.poolAddress,ingestedAt:collectedAt,rows:[{observedAt:collectedAt,sourceType:'LIVE_OBSERVED',sourceProvider:'METEORA_API+RPC',price:n(apiPool.current_price),activeBinId:pool.activeBinId,resolutionMs:p.perPoolMinIntervalMs,volume:n(apiPool.volume?.['5m']),feeValue:n(apiPool.fees?.['5m']),localLiquidity:n(apiPool.tvl),payload:{freshPoolState:true,freshActiveBin:true}}]});
   const currentBucket=iso(Math.floor(Date.parse(collectedAt)/(5*60_000))*5*60_000),rollingFees=apiPool.fees?.['5m'],rollingProtocolFees=apiPool.protocol_fees?.['5m'],rollingVolume=apiPool.volume?.['5m'],rollingEvidenceState=hasMeasuredEconomics(rollingFees,rollingProtocolFees,rollingVolume)?'MEASURED':'PLACEHOLDER';await input.store.insertFeeVolumeObservations({poolAddress:c.poolAddress,observedAt:collectedAt,source:'METEORA_API_ROLLING_5M',rows:[{bucketAt:currentBucket,fees:n(rollingFees),protocolFees:n(rollingProtocolFees),volume:n(rollingVolume),payload:{sourceType:'LIVE_OBSERVED',observedAt:collectedAt,nonOverlappingBucket:'5m',evidenceState:rollingEvidenceState}}]});
   for(const tx of liveTxs)for(const e of await input.adapter.decodeEvents(c.poolAddress,tx.signature,tx.slot,tx.blockTime,tx.logs,tx.cpiInstructionData))if(e.pool===c.poolAddress)await input.store.insertSwapEvent(e);
   if(backfillPools.has(c.poolAddress))await runBackfill({api:input.api,adapter:input.adapter,rpc:input.rpc,store:input.store,poolAddress:c.poolAddress,apiPool,observedAt:collectedAt,policy:p});
   const since=iso(Date.parse(collectedAt)-p.historyWindowMs),history=await input.store.loadOperationalHistory(c.poolAddress,since,2000),all=await input.store.loadCandidateMarketObservations(c.poolAddress,since,2000),evidenceTimes=[Date.parse(collectedAt),...history.marketObservations.map(x=>Date.parse(x.observedAt)),...history.activeBins.map(x=>Date.parse(x.observedAt)),...history.binFrames.map(x=>Date.parse(x.observedAt)),...history.swapEvents.map(x=>Date.parse(x.stamp.observedAt))].filter(Number.isFinite),assessedAt=iso(Math.max(...evidenceTimes)),maturity=await assessHistoryMaturity({poolAddress:c.poolAddress,assessedAt,history,staleAfterMs:p.staleAfterMs,historicalMarket:all.filter(x=>x.sourceType!=='LIVE_OBSERVED'),liveMarket:all.filter(x=>x.sourceType==='LIVE_OBSERVED'),liveConfirmationMinutes:p.liveConfirmationMinutes,liveConfirmationMinObservations:p.liveConfirmationMinObservations,liveConfirmationMaxGapMs:p.liveConfirmationMaxGapMs}),feeRows=await input.store.loadFeeVolumeObservations(c.poolAddress,since,1000),estimate=await deriveEventPathEconomicEstimate({poolAddress:c.poolAddress,asOf:assessedAt,dataApiPool:apiPool,feeBuckets:feeRows.map(x=>({timestamp:Math.floor(Date.parse(x.bucketAt)/1000),fees:x.fees,protocol_fees:x.protocolFees,volume:x.volume})),history}),backfill=await input.store.loadActiveCandidateBackfill(c.poolAddress);
   await input.store.upsertActiveCandidateHistoryMaturity({poolAddress:c.poolAddress,assessedAt,...maturity,payload:{authority:'DISCOVERY_OBSERVATION_ONLY',policyId:p.id,collectionTarget:c.state==='PRODUCTION_MONITORED'?'PRODUCTION_MONITORED':'ACTIVE_CANDIDATE',deepQualifiedState:c.state,deepTier:c.tier,historicalMaturity:maturity.historicalState,liveConfirmation:maturity.liveConfirmationState,backfill:backfill??null}});await input.store.insertEconomicEstimate(estimate);return{poolAddress:c.poolAddress,status:'PASS' as const,maturity,estimate};
  }catch(error){const message=error instanceof Error?error.message:String(error);await input.store.upsertActiveCandidateHistoryMaturity({poolAddress:c.poolAddress,assessedAt:input.observedAt,state:'DEGRADED',marketObservationCount:0,activeBinObservationCount:0,binFrameCount:0,swapEventCount:0,completeness5m:0,completeness15m:0,completeness1h:0,reasonCodes:['HISTORY_COLLECTOR_POOL_FAILURE'],payload:{authority:'DISCOVERY_OBSERVATION_ONLY',historicalMaturity:'DEGRADED',liveConfirmation:'DEGRADED',error:message.slice(0,300)}});return{poolAddress:c.poolAddress,status:'DEGRADED' as const,error:message};}});
 return{authority:'DISCOVERY_OBSERVATION_ONLY',observedAt:input.observedAt,serviceableCapacity,results};
}
async function chunkedHistory(api:MeteoraDataApi,pool:string,requestedMinutes:number,observedAt:string){
 const end=Math.floor(Date.parse(observedAt)/300_000)*300,start=end-requestedMinutes*60,windows:Array<{start:number;end:number}>=[];
 for(let cursor=start;cursor<end;cursor+=3600)windows.push({start:cursor,end:Math.min(end,cursor+3600)});
 const rawFees:HistoricalVolumePoint[]=[];const rawOhlcv:Array<{timestamp:number;open:number;high:number;low:number;close:number;volume:number}>=[];
 for(const window of windows){
  // API pacing is per request.  Two concurrent calls per window violate a
  // nominal 1 RPS limit and were a direct source of 429 bursts.
  const fees=await api.getHistoricalVolume(pool,{timeframe:'5m',startTime:window.start,endTime:window.end});
  const ohlcv=await api.getOhlcv(pool,{timeframe:'5m',startTime:window.start,endTime:window.end});
  rawFees.push(...fees.data);rawOhlcv.push(...ohlcv.data);
 }
 const dedupe=<T extends {timestamp:number}>(rows:T[])=>[...new Map(rows.map(x=>[x.timestamp,x])).values()].sort((a,b)=>a.timestamp-b.timestamp);
 const fees=dedupe(rawFees),ohlcv=dedupe(rawOhlcv),expected=Math.floor((end-start)/300)+1,missing=Array.from({length:expected},(_,i)=>start+i*300).filter(t=>!new Set(ohlcv.map(x=>x.timestamp)).has(t));
 return{fees,ohlcv,metrics:{windows:windows.length,rawFeeBuckets:rawFees.length,rawOhlcvBuckets:rawOhlcv.length,uniqueFeeBuckets:fees.length,uniqueOhlcvBuckets:ohlcv.length,duplicateFeeBuckets:rawFees.length-fees.length,duplicateOhlcvBuckets:rawOhlcv.length-ohlcv.length,missingBuckets:missing.length,largestGapMinutes:missing.length?5:0,coverageRatio:expected?ohlcv.length/expected:0}};
}
async function runBackfill(input:{api:MeteoraDataApi;adapter:MeteoraReadAdapter;rpc:SolanaRpcClient;store:Phase1Store;poolAddress:string;apiPool:DataApiPool;observedAt:string;policy:ActiveCandidateEvidencePolicy}){
 const requestedMinutes=Math.max(input.policy.backfillMinHistoryMinutes,input.policy.backfillLookbackMinutes);
 try{
  // A historical enrichment is low priority: do not run its Data API and RPC
  // fans concurrently against a shared provider budget.
  const historical=await chunkedHistory(input.api,input.poolAddress,requestedMinutes,input.observedAt);
  const txs=await scanAddressTransactions({rpc:input.rpc,address:input.poolAddress,limit:input.policy.backfillEventScanLimit,programId:EXPECTED_DLMM_PROGRAM_ID});
  const quality=assessBackfillQuality({requestedMinutes,feeBuckets:historical.fees,ohlcvBuckets:historical.ohlcv,swapEventCount:txs.length});
  if(historical.metrics.missingBuckets>0)quality.reasonCodes.push('ENTRY_HISTORY_BACKFILL_GAPS');if(historical.metrics.coverageRatio<.60)quality.quality='PARTIAL';
  await input.store.insertOhlcv(input.poolAddress,'5m',historical.ohlcv as unknown as Array<Record<string,unknown>>,input.observedAt,'METEORA_API');await input.store.insertFeeVolumeObservations({poolAddress:input.poolAddress,observedAt:input.observedAt,source:'METEORA_API_HISTORICAL_5M',rows:historical.fees.map(x=>({bucketAt:iso(x.timestamp*1000),fees:n(x.fees),protocolFees:n(x.protocol_fees),volume:n(x.volume),payload:{sourceType:'HISTORICAL_API_BACKFILL',sourceProvider:'METEORA_DATA_API',observedAt:iso(x.timestamp*1000),ingestedAt:input.observedAt,nonOverlappingBucket:'5m',evidenceState:'MEASURED'}}))});
  const candles=[...historical.ohlcv],historicalRows:Parameters<Phase1Store['insertCandidateMarketObservations']>[0]['rows']=candles.filter(candle=>n(candle.close)>0).map(candle=>({observedAt:iso(candle.timestamp*1000),sourceType:'HISTORICAL_API_BACKFILL',sourceProvider:'METEORA_DATA_API_OHLCV',price:n(candle.close),resolutionMs:5*60_000,volume:n(candle.volume),payload:{marketEvidence:'HISTORICAL_OHLCV',observedAt:iso(candle.timestamp*1000),ingestedAt:input.observedAt}})),reconstructed:Parameters<Phase1Store['insertCandidateMarketObservations']>[0]['rows']=[];for(const tx of txs)for(const e of await input.adapter.decodeEvents(input.poolAddress,tx.signature,tx.slot,tx.blockTime,tx.logs,tx.cpiInstructionData))if(e.pool===input.poolAddress){await input.store.insertSwapEvent(e);if(e.endBinId===undefined||!e.stamp.blockTime)continue;const eventTime=Date.parse(e.stamp.blockTime),candle=[...candles].sort((a,b)=>Math.abs(a.timestamp*1000-eventTime)-Math.abs(b.timestamp*1000-eventTime))[0];if(candle&&n(candle.close)>0)reconstructed.push({observedAt:iso(eventTime),sourceType:'RECONSTRUCTED',sourceProvider:'SWAP2EVT+METEORA_OHLCV',price:n(candle.close),activeBinId:e.endBinId,resolutionMs:5*60_000,payload:{activeBinEvidence:'EVENT_RECONSTRUCTED',signature:e.signature,eventIndex:e.eventIndex,priceCandleAt:iso(candle.timestamp*1000)}});}await input.store.insertCandidateMarketObservations({poolAddress:input.poolAddress,ingestedAt:input.observedAt,rows:[...historicalRows,...reconstructed]});await input.store.upsertActiveCandidateBackfill({poolAddress:input.poolAddress,lastAttemptAt:input.observedAt,...(quality.quality!=='DEGRADED'?{lastSuccessfulAt:input.observedAt}:{}),...quality,payload:{authority:'DISCOVERY_OBSERVATION_ONLY',sourceTypes:['HISTORICAL_API_BACKFILL','HISTORICAL_RPC_BACKFILL','RECONSTRUCTED'],poolCreatedAt:input.apiPool.created_at??null,continuity:historical.metrics}});
 }catch(error){await input.store.upsertActiveCandidateBackfill({poolAddress:input.poolAddress,lastAttemptAt:input.observedAt,requestedMinutes,coveredMinutes:0,coverageRatio:0,feeBucketCount:0,ohlcvBucketCount:0,swapEventCount:0,independent15mEpisodes:0,quality:'DEGRADED',reasonCodes:['ENTRY_HISTORY_BACKFILL_FAILED'],payload:{authority:'DISCOVERY_OBSERVATION_ONLY',error:error instanceof Error?error.message.slice(0,300):String(error).slice(0,300)}});}
}
