import { canonicalJson, nowIso, sha256Hex, type BinLiquidityFact, type FeatureEnvelope, type SwapEventFact } from '../../domain/src/index.js';
import type { DataApiPool, WindowMetrics } from '../../data-api/src/index.js';

export interface BinWindowFeatures { binCount:number; localAmountX:number; localAmountY:number; liquiditySkew:number; nonEmptyRatio:number; emptyGapCount:number; maxConsecutiveEmpty:number; activeBinLiquidityShare:number; }
export interface ActiveBinMovementFeatures { observations:number; netBins:number; absoluteBins:number; reversals:number; directionality:number; velocityBinsPerMinute:number; }
export interface SwapFlowFeatures { swaps:number; upwardBinMoves:number; downwardBinMoves:number; flatBinMoves:number; twoWayRatio:number; netDirection:number; meanBinsCrossed:number; totalMmFeeRaw:string; }
export interface FeeQualityFeatures { dynamicFeePct?:number; tvl?:number; fees:WindowMetrics; volume:WindowMetrics; feeTvlRatio:WindowMetrics; feeBurstRatio1hTo24h?:number; }
export interface Phase1PoolFeatures { bin?:BinWindowFeatures; movement?:ActiveBinMovementFeatures; flow?:SwapFlowFeatures; fee?:FeeQualityFeatures; }

function n(v:string|undefined):number { const x=Number(v??0); return Number.isFinite(x)?x:0; }
export function computeBinWindowFeatures(bins:BinLiquidityFact[],activeBinId:number):BinWindowFeatures { if(!bins.length)return{binCount:0,localAmountX:0,localAmountY:0,liquiditySkew:0,nonEmptyRatio:0,emptyGapCount:0,maxConsecutiveEmpty:0,activeBinLiquidityShare:0}; let x=0,y=0,non=0,gaps=0,run=0,maxRun=0,active=0,total=0; for(const b of [...bins].sort((a,b)=>a.binId-b.binId)){const bx=n(b.amountX),by=n(b.amountY),liq=bx+by;x+=bx;y+=by;total+=liq;if(b.binId===activeBinId)active=liq;if(liq>0){non++;run=0;}else{if(run===0)gaps++;run++;maxRun=Math.max(maxRun,run);}} const denom=x+y; return{binCount:bins.length,localAmountX:x,localAmountY:y,liquiditySkew:denom?((x-y)/denom):0,nonEmptyRatio:non/bins.length,emptyGapCount:gaps,maxConsecutiveEmpty:maxRun,activeBinLiquidityShare:total?active/total:0}; }
export function computeActiveBinMovement(history:Array<{binId:number;observedAt:string}>):ActiveBinMovementFeatures { const s=[...history].sort((a,b)=>Date.parse(a.observedAt)-Date.parse(b.observedAt)); if(s.length<2)return{observations:s.length,netBins:0,absoluteBins:0,reversals:0,directionality:0,velocityBinsPerMinute:0}; let abs=0,rev=0,lastSign=0; for(let i=1;i<s.length;i++){const d=s[i]!.binId-s[i-1]!.binId;abs+=Math.abs(d);const sign=Math.sign(d);if(sign&&lastSign&&sign!==lastSign)rev++;if(sign)lastSign=sign;} const net=s[s.length-1]!.binId-s[0]!.binId; const mins=Math.max((Date.parse(s[s.length-1]!.observedAt)-Date.parse(s[0]!.observedAt))/60000,1/60); return{observations:s.length,netBins:net,absoluteBins:abs,reversals:rev,directionality:abs?Math.abs(net)/abs:0,velocityBinsPerMinute:abs/mins}; }
export function computeSwapFlowFeatures(events:SwapEventFact[]):SwapFlowFeatures { let up=0,down=0,flat=0,cross=0,fee=0n; for(const e of events){const d=(e.endBinId??0)-(e.startBinId??0);if(d>0)up++;else if(d<0)down++;else flat++;cross+=Math.abs(d);try{fee+=BigInt(e.mmFee??'0');}catch{}} const directional=up+down; return{swaps:events.length,upwardBinMoves:up,downwardBinMoves:down,flatBinMoves:flat,twoWayRatio:directional?2*Math.min(up,down)/directional:0,netDirection:directional?(up-down)/directional:0,meanBinsCrossed:events.length?cross/events.length:0,totalMmFeeRaw:fee.toString()}; }
export function computeFeeQuality(pool:DataApiPool):FeeQualityFeatures { const fees=pool.fees??{},volume=pool.volume??{},feeTvlRatio=pool.fee_tvl_ratio??{}; const f1=fees['1h'],f24=fees['24h']; return{...(typeof pool.dynamic_fee_pct==='number'?{dynamicFeePct:pool.dynamic_fee_pct}:{}),...(typeof pool.tvl==='number'?{tvl:pool.tvl}:{}),fees,volume,feeTvlRatio,...(typeof f1==='number'&&typeof f24==='number'&&f24>0?{feeBurstRatio1hTo24h:f1/(f24/24)}:{})}; }
export async function finalizeFeatureSnapshot(pool:string,sourceWatermark:FeatureEnvelope<Phase1PoolFeatures>['sourceWatermark'],features:Phase1PoolFeatures,missing:string[]=[]):Promise<{snapshot:FeatureEnvelope<Phase1PoolFeatures>;hash:string}>{ const snapshot:FeatureEnvelope<Phase1PoolFeatures>={pool,schemaVersion:'phase1-features-v1',sourceWatermark,freshness:missing.length?'DEGRADED':'GOOD',missing:[...missing].sort(),features,createdAt:nowIso()}; const hashBasis={pool:snapshot.pool,schemaVersion:snapshot.schemaVersion,sourceWatermark:snapshot.sourceWatermark,freshness:snapshot.freshness,missing:snapshot.missing,features:snapshot.features}; return{snapshot,hash:await sha256Hex(canonicalJson(hashBasis))}; }
