import { loadPhase1Config } from '../../../packages/config/src/index.js';
import { createMeteoraDataApi } from '../../../packages/data-api/src/index.js';
import { createPostgresStore } from '../../../packages/db/src/index.js';
import { createMeteoraReadAdapter, createSolanaRpcClient, scanAddressTransactions } from '../../../packages/meteora/src/index.js';
import { Logger } from '../../../packages/observability/src/index.js';
import { fixturePool } from '../../../packages/test-fixtures/src/index.js';
const cfg=loadPhase1Config(); const log=new Logger('collector',cfg.logLevel); const store=await createPostgresStore(cfg.databaseUrl);
try {
  if(cfg.dataMode==='FIXTURE'){ await store.insertPoolSnapshot(fixturePool); log.info('fixture_pool_persisted',{pool:fixturePool.address}); }
  else { const adapter=createMeteoraReadAdapter({rpcUrl:cfg.solanaRpcHttpUrl,cluster:cfg.cluster,programId:cfg.programId,expectedSdkVersion:cfg.expectedSdkVersion,rpcTimeoutMs:cfg.rpcTimeoutMs,priority:'P4_BACKFILL',onEventDecodeWarning:warning=>log.warn('meteora_event_decode_quarantined',{...warning})}); const compat=await adapter.verifyCompatibility(cfg.smokePoolAddress); await store.insertCompatibility(compat); if(compat.state!=='VERIFIED')throw new Error('LPFORGE_PROTOCOL_COMPATIBILITY_HOLD'); if(!cfg.smokePoolAddress)throw new Error('LPFORGE_CONFIG_REQUIRED:LPFORGE_SMOKE_POOL_ADDRESS'); const [pool,bins]=await Promise.all([adapter.getPool(cfg.smokePoolAddress),adapter.getBinsAroundActive(cfg.smokePoolAddress,35)]); await store.insertPoolSnapshot(pool); await store.insertBins(bins); const api=createMeteoraDataApi({baseUrl:cfg.meteoraDataApiUrl,maxRps:cfg.dataApiMaxRps,timeoutMs:cfg.httpTimeoutMs}); const apiObservedAt=new Date().toISOString(); const [apiPool,ohlcv]=await Promise.all([api.getPool(cfg.smokePoolAddress),api.getOhlcv(cfg.smokePoolAddress,{timeframe:'5m'})]); await store.insertDataApiPool(apiPool as Record<string,unknown>,apiObservedAt); await store.insertOhlcv(cfg.smokePoolAddress,'5m',ohlcv.data as unknown as Array<Record<string,unknown>>,apiObservedAt,'METEORA_API'); if(cfg.smokePositionAddress){const position=await adapter.getPositionV2(cfg.smokePoolAddress,cfg.smokePositionAddress);await store.upsertPosition(position);} const rpc=createSolanaRpcClient({url:cfg.solanaRpcHttpUrl,timeoutMs:cfg.rpcTimeoutMs,priority:'P4_BACKFILL'}); const transactions=await scanAddressTransactions({rpc,address:cfg.smokePoolAddress,limit:cfg.eventBackfillLimit,programId:cfg.programId}); let decodedEvents=0; for(const tx of transactions){for(const event of await adapter.decodeEvents(cfg.smokePoolAddress,tx.signature,tx.slot,tx.blockTime,tx.logs,tx.cpiInstructionData)){if(event.pool!==cfg.smokePoolAddress)continue;await store.insertSwapEvent(event);decodedEvents++;}} const latest=transactions.at(-1); if(latest)await store.setCheckpoint({stream:`pool:${cfg.smokePoolAddress}:transactions`,lastSeenSlot:latest.slot,lastFullyProcessedSlot:latest.slot,state:{lastSignature:latest.signature}}); log.info('live_read_cycle_complete',{pool:cfg.smokePoolAddress,bins:bins.length,ohlcv:ohlcv.data.length,transactions:transactions.length,decodedEvents,liveSigning:false}); }
} finally {await store.close();}
