import { createHash } from 'node:crypto';
import { createMeteoraDataApi } from '../../../packages/data-api/src/index.js';
import { createPostgresStore } from '../../../packages/db/src/index.js';
import { calibratePredictions, buildReputation, type PredictionRecord, type OutcomeRecord } from '../../../packages/discovery-learning/src/index.js';
import { researchProposalFromCalibration } from '../../../packages/discovery-runtime/src/index.js';
const json=(v:unknown)=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x,2);
const env=(n:string)=>{const v=process.env[n];if(!v)throw new Error(`LPFORGE_DISCOVERY_LEARNING_ENV_REQUIRED:${n}`);return v};
const horizons=[30,60,120,240,360];
const hash=(x:string)=>createHash('sha256').update(x).digest('hex').slice(0,32);
function predictionFromRow(row:Record<string,unknown>):PredictionRecord|undefined{
 const p=row.prediction;if(!p||typeof p!=='object'||Array.isArray(p))return undefined;return p as PredictionRecord;
}
function outcomeFromRow(row:Record<string,unknown>):OutcomeRecord{
 return{predictionId:String(row.prediction_id),poolAddress:String(row.pool_address),observedAt:new Date(String(row.observed_at)).toISOString(),horizonMinutes:Number(row.horizon_minutes),outcomeClass:String(row.outcome_class) as OutcomeRecord['outcomeClass'],...(row.realized_net_value!==null&&row.realized_net_value!==undefined?{realizedNetValue:Number(row.realized_net_value)}:{}),...(row.realized_fees!==null&&row.realized_fees!==undefined?{realizedFees:Number(row.realized_fees)}:{}),...(row.realized_directional_pnl!==null&&row.realized_directional_pnl!==undefined?{realizedDirectionalPnl:Number(row.realized_directional_pnl)}:{}),...(row.range_survived!==null&&row.range_survived!==undefined?{rangeSurvived:Boolean(row.range_survived)}:{}),...(row.inventory_conversion!==null&&row.inventory_conversion!==undefined?{inventoryConversion:Number(row.inventory_conversion)}:{}),eventAttribution:String(row.event_attribution) as OutcomeRecord['eventAttribution'],structuralEventCodes:Array.isArray(row.structural_event_codes)?row.structural_event_codes.map(String):[]};
}
function startPrice(p:PredictionRecord):number|undefined{const v=p.deep.evidence.currentPrice;return typeof v==='number'&&Number.isFinite(v)?v:undefined}
async function collectCounterfactuals(store:Awaited<ReturnType<typeof createPostgresStore>>,api:ReturnType<typeof createMeteoraDataApi>,predictions:PredictionRecord[],now:string){
 let inserted=0;for(const p of predictions){const start=startPrice(p);if(start===undefined||start<=0)continue;let current;try{current=await api.getPool(p.poolAddress)}catch{continue}const currentPrice=typeof current.current_price==='number'?current.current_price:undefined;if(currentPrice===undefined||currentPrice<=0)continue;
  for(const h of horizons){if(Date.parse(now)<Date.parse(p.observedAt)+h*60000)continue;let history;try{history=await api.getHistoricalVolume(p.poolAddress,{timeframe:'5m',startTime:Math.floor(Date.parse(p.observedAt)/1000),endTime:Math.floor((Date.parse(p.observedAt)+h*60000)/1000)})}catch{continue}
   const fees=history.data.reduce((a,b)=>a+Math.max(0,Number(b.fees)||0),0);const ret=currentPrice/start-1;const capital=.1;const directional=capital*ret*.5;const feeApprox=Math.min(capital*.2,fees/Math.max(1,Number(current.tvl??1))*capital);const net=feeApprox+directional;const clazz=p.cohort==='RANDOM_QUALIFIED_CONTROL'?'CONTROL_COUNTERFACTUAL':p.selectedAction==='NO_TRADE'?'NO_TRADE_COUNTERFACTUAL':'NO_TRADE_COUNTERFACTUAL';
   await store.insertDiscoveryOutcome({predictionId:p.predictionId,poolAddress:p.poolAddress,observedAt:now,horizonMinutes:h,outcomeClass:clazz,eventAttribution:'NORMAL',structuralEventCodes:[],realizedNetValue:net,realizedFees:feeApprox,realizedDirectionalPnl:directional,inventoryConversion:Math.min(1,Math.abs(ret)*2),payload:{fidelity:'COUNTERFACTUAL_MARK_TO_MARKET_APPROXIMATION',startPrice:start,currentPrice,returnPct:ret*100,historicalFeeUsd:fees,warning:'Not equivalent to an executed DLMM position; used for rejected/control learning only.'}});inserted++;
  }
 }return inserted;
}
async function once(){
 const now=new Date().toISOString(),store=await createPostgresStore(env('DATABASE_URL')),api=createMeteoraDataApi({...((process.env.LPFORGE_METEORA_DATA_API_URL??'').trim()?{baseUrl:process.env.LPFORGE_METEORA_DATA_API_URL!}:{}),maxRps:Number(process.env.LPFORGE_DATA_API_MAX_RPS??1),timeoutMs:Number(process.env.LPFORGE_HTTP_TIMEOUT_MS??10000)});
 try{
  const rows=await store.loadRecentDiscoveryPredictions(Number(process.env.LPFORGE_DISCOVERY_LEARNING_MAX_PREDICTIONS??5000));const predictions=rows.map(predictionFromRow).filter((x):x is PredictionRecord=>Boolean(x));const counterfactuals=await collectCounterfactuals(store,api,predictions,now);const outcomes=(await store.loadDiscoveryOutcomes()).map(outcomeFromRow);const calibration=calibratePredictions(predictions,outcomes);const snapshotId=`cal-${hash(`${now}:${predictions.length}:${outcomes.length}`)}`;await store.insertDiscoveryCalibration({snapshotId,observedAt:now,modelVersion:'discovery-distributional-ev-v1',sampleCount:calibration.samples,independentEpisodes:calibration.independentEpisodes,...(calibration.brierProfit!==null?{brierProfit:calibration.brierProfit}:{}),...(calibration.survivalBrier!==null?{survivalBrier:calibration.survivalBrier}:{}),...(calibration.netValueMae!==null?{netValueMae:calibration.netValueMae}:{}),...(calibration.meanBias!==null?{meanBias:calibration.meanBias}:{}),allOutcomeNet:calibration.allOutcomeNet,modelCalibrationNet:calibration.modelCalibrationNet,payload:{allOutcomeIncludesStructuralBreaks:true}});
  for(const [level,keyFn] of [['POOL',(p:PredictionRecord)=>p.poolAddress],['STRATEGY',(p:PredictionRecord)=>String(p.selectedAction)],['POOL_STRATEGY_REGIME',(p:PredictionRecord)=>`${p.poolAddress}:${p.selectedAction}:${String(p.selectionContext.regime??'UNKNOWN')}`]] as const){for(const r of buildReputation(predictions,outcomes,keyFn))await store.upsertDiscoveryReputation({reputationKey:`${level}:${r.key}`,level,asOf:now,samples:r.samples,independentEpisodes:r.episodes,meanNet:r.meanNet,positiveRate:r.positiveRate,confidence:r.confidence,payload:{meanFees:r.meanFees,meanDirectional:r.meanDirectional}});}
  const proposal=researchProposalFromCalibration({observedAt:now,calibration});if(proposal)await store.upsertDiscoveryPolicyProposal({proposalId:proposal.proposal.proposalId,createdAt:proposal.proposal.createdAt,state:proposal.proposal.state,hypothesis:proposal.proposal.hypothesis,targetPolicy:proposal.proposal.targetPolicy,changes:proposal.proposal.changes,evidence:{...proposal.proposal.evidence,authority:proposal.authority}});
  const summary={status:'PASS',authority:'RESEARCH_ONLY_NO_POLICY_MUTATION',observedAt:now,predictions:predictions.length,outcomes:outcomes.length,counterfactualsUpserted:counterfactuals,calibration,proposal:proposal?.proposal??null};console.log(json(summary));return summary;
 }finally{await store.close()}
}
const cmd=process.argv[2]??'once';if(cmd==='once')await once();else if(cmd==='start'){const ms=Math.max(300_000,Number(process.env.LPFORGE_DISCOVERY_LEARNING_INTERVAL_MS??900_000));for(;;){try{await once()}catch(e){console.error(json({status:'ERROR',error:e instanceof Error?e.message:String(e)}))}await new Promise(r=>setTimeout(r,ms));}}else throw new Error(`LPFORGE_DISCOVERY_LEARNING_COMMAND:${cmd}`);
