import { createHash } from 'node:crypto';
import { createMeteoraDataApi } from '../../../packages/data-api/src/index.js';
import { createPostgresStore } from '../../../packages/db/src/index.js';
import { calibratePredictions, calibrateLiveSettledOutcomes, buildReputation, type LiveSettledLearningSample, type PredictionRecord, type OutcomeRecord } from '../../../packages/discovery-learning/src/index.js';
import { researchProposalFromCalibration } from '../../../packages/discovery-runtime/src/index.js';
import { buildPhase3ForwardCalibration, buildPhase3ForwardEpisodeCalibration, buildPoolQualityProspectiveShadowReport, matureFrozenPhase3ForwardOutcome, phase3ForwardOutcomeResultHash, PHASE3_FORWARD_OUTCOME_MODEL_VERSION_V1, PHASE3_FORWARD_OUTCOME_MODEL_VERSION_V2, type FrozenPhase3ForwardDecision, type Phase3ForwardOutcome } from '../../../packages/phase3-forward-validation/src/index.js';
import { counterfactualV3ReservedSlots, deriveForwardMaturationRetryPlan, processDueForwardMaturations, startIndependentForwardMaturationLoop } from './forward-maturation-scheduler.js';
import { runPostEntryTelemetryCapture, startIndependentPostEntryTelemetryLoop } from './post-entry-telemetry-capture.js';
import { runProspectiveMarketContextTelemetryCapture, startIndependentProspectiveMarketContextTelemetryLoop } from './market-context-telemetry-capture.js';
import { runProspectiveInventoryForecastV2Capture, startIndependentProspectiveInventoryForecastV2Loop } from './inventory-forecast-v2-capture.js';
import { runBoundedBinSnapshotRetention } from './bin-snapshot-retention.js';
const json=(v:unknown)=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x,2);
const env=(n:string)=>{const v=process.env[n];if(!v)throw new Error(`LPFORGE_DISCOVERY_LEARNING_ENV_REQUIRED:${n}`);return v};
const horizons=[30,60,120,240,360];
const hash=(x:string)=>createHash('sha256').update(x).digest('hex').slice(0,32);
const bounded=(name:string,fallback:number,max:number)=>{const value=Number(process.env[name]??fallback);return Number.isFinite(value)?Math.max(1,Math.min(max,Math.floor(value))):fallback;};
const memory=(stage:string)=>{if((process.env.LPFORGE_DISCOVERY_LEARNING_MEMORY_DIAGNOSTICS??'false').toLowerCase()!=='true')return;const usage=process.memoryUsage();console.log(json({event:'DISCOVERY_LEARNING_MEMORY',authority:'RESEARCH_ONLY_NO_POLICY_MUTATION',stage,heapUsed:usage.heapUsed,heapTotal:usage.heapTotal,rss:usage.rss,external:usage.external,arrayBuffers:usage.arrayBuffers}));};
const rateLimited=(error:unknown)=>/\b429\b|too many requests|rate.?limit/i.test(error instanceof Error?error.message:String(error));
function predictionFromRow(row:Record<string,unknown>):PredictionRecord|undefined{
 const p=row.prediction;if(!p||typeof p!=='object'||Array.isArray(p))return undefined;return p as PredictionRecord;
}
function outcomeFromRow(row:Record<string,unknown>):OutcomeRecord{
 return{predictionId:String(row.prediction_id),poolAddress:String(row.pool_address),observedAt:new Date(String(row.observed_at)).toISOString(),horizonMinutes:Number(row.horizon_minutes),outcomeClass:String(row.outcome_class) as OutcomeRecord['outcomeClass'],...(row.realized_net_value!==null&&row.realized_net_value!==undefined?{realizedNetValue:Number(row.realized_net_value)}:{}),...(row.realized_fees!==null&&row.realized_fees!==undefined?{realizedFees:Number(row.realized_fees)}:{}),...(row.realized_directional_pnl!==null&&row.realized_directional_pnl!==undefined?{realizedDirectionalPnl:Number(row.realized_directional_pnl)}:{}),...(row.range_survived!==null&&row.range_survived!==undefined?{rangeSurvived:Boolean(row.range_survived)}:{}),...(row.inventory_conversion!==null&&row.inventory_conversion!==undefined?{inventoryConversion:Number(row.inventory_conversion)}:{}),eventAttribution:String(row.event_attribution) as OutcomeRecord['eventAttribution'],structuralEventCodes:Array.isArray(row.structural_event_codes)?row.structural_event_codes.map(String):[]};
}
const object=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const finite=(value:unknown):number|undefined=>typeof value==='number'&&Number.isFinite(value)?value:undefined;
async function maturePhase3ForwardOutcomes(store:Awaited<ReturnType<typeof createPostgresStore>>,now:string,options:{includeCalibration?:boolean}={}){
 memory('selected-forward:start');
 const due=await store.loadDuePhase3ForwardOutcomes(now,bounded('LPFORGE_FORWARD_VALIDATION_MAX_BATCH',12,50));
 const batch=await processDueForwardMaturations({tasks:due,mature:async row=>{
   const decision=row.decisionPayload as unknown as FrozenPhase3ForwardDecision,start=Date.parse(decision.decisionTimestamp);if(!Number.isFinite(start))throw new Error('LPFORGE_FORWARD_DECISION_TIMESTAMP_INVALID');
   /* Freeze source selection to the same baseline-through-horizon evidence
    * window that V2 outcome semantics evaluate. This is an access-path bound
    * only: matureFrozenPhase3ForwardOutcome retains all existing baseline,
    * coverage, continuity, and economic checks. */
   const history=await store.loadOperationalHistory(decision.poolAddress,new Date(start-15*60_000).toISOString(),2000,new Date(start+row.horizonMinutes*60_000).toISOString());
   return matureFrozenPhase3ForwardOutcome({decision,horizonMinutes:row.horizonMinutes,outcomeModelVersion:row.outcomeModelVersion,frames:history.binFrames,events:history.swapEvents,now});
  },persist:async (row,outcome)=>{
   const decision=row.decisionPayload as unknown as FrozenPhase3ForwardDecision,retry=deriveForwardMaturationRetryPlan({priorState:row.state,resultState:outcome.state,reasonCodes:outcome.reasonCodes,retryCount:row.retryCount,attemptedAt:now});
   return store.persistPhase3ForwardOutcome({recommendationId:outcome.recommendationId,horizonMinutes:outcome.horizonMinutes,outcomeModelVersion:outcome.outcomeModelVersion,state:outcome.state,...(outcome.evidenceHash?{evidenceHash:outcome.evidenceHash}:{}),resultHash:await phase3ForwardOutcomeResultHash(outcome),reasonCodes:outcome.reasonCodes,...(outcome.realized?{realized:outcome.realized as unknown as Record<string,unknown>}:{}) ,payload:{authority:'RESEARCH_ONLY_NO_POLICY_MUTATION',decisionTimestamp:decision.decisionTimestamp,sourceSha:decision.sourceSha,selectedCandidateKind:decision.selectedCandidateKind,...(outcome.replayContract?{canonicalReplayContract:outcome.replayContract}:{})},maturedAt:now,attemptedAt:now,retryCount:retry.retryCount,...(retry.nextRetryAt?{nextRetryAt:retry.nextRetryAt}:{}),...(retry.terminal?{terminalAt:now}:{})});
  },emit:event=>console.log(json({...event,authority:'RESEARCH_ONLY_NO_POLICY_MUTATION'}))});
 if(options.includeCalibration===false){memory('selected-forward:complete');return{...batch,calibration:{deferredToBoundedLearningCycle:true}};}
 const rows=await store.loadPhase3ForwardOutcomes(bounded('LPFORGE_FORWARD_CALIBRATION_MAX_ROWS',500,1000)),calibrationRows=rows.flatMap(row=>{const decision=(row.decisionPayload??{}) as FrozenPhase3ForwardDecision,realized=row.realized as Phase3ForwardOutcome['realized']|undefined;const outcome:Phase3ForwardOutcome={recommendationId:String(row.recommendationId),horizonMinutes:Number(row.horizonMinutes) as 30|60|120,outcomeModelVersion:String(row.outcomeModelVersion),state:String(row.state) as Phase3ForwardOutcome['state'],...(row.evidenceHash?{evidenceHash:String(row.evidenceHash)}:{}),reasonCodes:Array.isArray(row.reasonCodes)?row.reasonCodes.map(String):[],...(realized?{realized}:{})};return decision.recommendationId?[{decision,outcome}]:[];});
 memory('selected-forward:calibration-loaded');
 return{...batch,calibration:{v1:buildPhase3ForwardCalibration(calibrationRows,{outcomeModelVersion:PHASE3_FORWARD_OUTCOME_MODEL_VERSION_V1}),v2:buildPhase3ForwardCalibration(calibrationRows,{outcomeModelVersion:PHASE3_FORWARD_OUTCOME_MODEL_VERSION_V2}),v2Episode:buildPhase3ForwardEpisodeCalibration(calibrationRows,{outcomeModelVersion:PHASE3_FORWARD_OUTCOME_MODEL_VERSION_V2}),poolQualityProspectiveShadow:buildPoolQualityProspectiveShadowReport(calibrationRows,{outcomeModelVersion:PHASE3_FORWARD_OUTCOME_MODEL_VERSION_V2})}};
}
async function matureCandidateCounterfactualRows(store:Awaited<ReturnType<typeof createPostgresStore>>,rows:Awaited<ReturnType<Awaited<ReturnType<typeof createPostgresStore>>['loadDueCandidateCounterfactualOutcomes']>>,now:string){
 let failures=0;
 for(const row of rows){try{const raw=row.rawContract, mechanical=object(raw.mechanicalConstructibility), decision=object(raw.frozenDecision) as unknown as FrozenPhase3ForwardDecision;
  if(typeof raw.reset3cReconstructionFailure==='string'){const resultHash=hash(JSON.stringify({id:row.capitalEvaluationId,h:row.horizonMinutes,state:'INSUFFICIENT_EVIDENCE',reason:raw.reset3cReconstructionFailure}));await store.persistCandidateCounterfactualOutcome({capitalEvaluationId:row.capitalEvaluationId,horizonMinutes:row.horizonMinutes,outcomeModelVersion:row.outcomeModelVersion,state:'INSUFFICIENT_EVIDENCE',resultHash,reasonCodes:[String(raw.reset3cReconstructionFailure)],payload:{namespace:'COUNTERFACTUAL_CANONICAL'},attemptedAt:now,retryCount:row.retryCount+1,terminalAt:now});continue;}
  if(mechanical.mechanicallyConstructible!==true||!decision.poolAddress||!decision.selectedCandidate){const resultHash=hash(JSON.stringify({id:row.capitalEvaluationId,h:row.horizonMinutes,state:'INSUFFICIENT_EVIDENCE',reason:'COUNTERFACTUAL_MECHANICAL_CONSTRUCTIBILITY_REQUIRED'}));await store.persistCandidateCounterfactualOutcome({capitalEvaluationId:row.capitalEvaluationId,horizonMinutes:row.horizonMinutes,outcomeModelVersion:row.outcomeModelVersion,state:'INSUFFICIENT_EVIDENCE',resultHash,reasonCodes:['COUNTERFACTUAL_MECHANICAL_CONSTRUCTIBILITY_REQUIRED'],payload:{namespace:'COUNTERFACTUAL_CANONICAL'},attemptedAt:now,retryCount:row.retryCount+1,terminalAt:now});continue;}
  const start=Date.parse(decision.decisionTimestamp),history=await store.loadOperationalHistory(decision.poolAddress,new Date(start-15*60_000).toISOString(),2000,new Date(start+row.horizonMinutes*60_000).toISOString());
  const outcome=await matureFrozenPhase3ForwardOutcome({decision,horizonMinutes:row.horizonMinutes,outcomeModelVersion:row.outcomeModelVersion,frames:history.binFrames,events:history.swapEvents,now,enforcePriceTakingOwnershipCap:false});
  const state=outcome.state==='FINAL'?'FINAL':'INSUFFICIENT_EVIDENCE',retry=deriveForwardMaturationRetryPlan({priorState:row.state,resultState:state,reasonCodes:outcome.reasonCodes,retryCount:row.retryCount,attemptedAt:now}),resultHash=await phase3ForwardOutcomeResultHash(outcome);
  await store.persistCandidateCounterfactualOutcome({capitalEvaluationId:row.capitalEvaluationId,horizonMinutes:row.horizonMinutes,outcomeModelVersion:row.outcomeModelVersion,state,...(outcome.evidenceHash?{evidenceHash:outcome.evidenceHash}:{}),resultHash,reasonCodes:outcome.reasonCodes,...(outcome.realized?{realized:outcome.realized as unknown as Record<string,unknown>}:{}),payload:{namespace:'COUNTERFACTUAL_CANONICAL',decisionTimestamp:decision.decisionTimestamp},attemptedAt:now,retryCount:retry.retryCount,...(retry.nextRetryAt?{nextRetryAt:retry.nextRetryAt}:{}),...(retry.terminal?{terminalAt:now}:{})});
 }catch(error){failures++;const reason='COUNTERFACTUAL_MATURATION_RUNTIME_ERROR',retry=deriveForwardMaturationRetryPlan({priorState:row.state,resultState:'INSUFFICIENT_EVIDENCE',reasonCodes:[reason],retryCount:row.retryCount,attemptedAt:now}),resultHash=hash(JSON.stringify({id:row.capitalEvaluationId,h:row.horizonMinutes,state:'INSUFFICIENT_EVIDENCE',reason}));try{await store.persistCandidateCounterfactualOutcome({capitalEvaluationId:row.capitalEvaluationId,horizonMinutes:row.horizonMinutes,outcomeModelVersion:row.outcomeModelVersion,state:'INSUFFICIENT_EVIDENCE',resultHash,reasonCodes:[reason],payload:{namespace:'COUNTERFACTUAL_CANONICAL',error:error instanceof Error?error.message:String(error)},attemptedAt:now,retryCount:retry.retryCount,...(retry.nextRetryAt?{nextRetryAt:retry.nextRetryAt}:{}),...(retry.terminal?{terminalAt:now}:{})});}catch(persistError){console.error(json({event:'COUNTERFACTUAL_MATURATION_PERSIST_FAILED',error:persistError instanceof Error?persistError.message:String(persistError),authority:'RESEARCH_ONLY_NO_POLICY_MUTATION'}));}console.error(json({event:'COUNTERFACTUAL_MATURATION_ROW_FAILED',error:error instanceof Error?error.message:String(error),authority:'RESEARCH_ONLY_NO_POLICY_MUTATION',horizonMinutes:row.horizonMinutes}));}}
 return failures;
}
async function matureCandidateCounterfactualOutcomes(store:Awaited<ReturnType<typeof createPostgresStore>>,now:string){
 memory('candidate-counterfactual:start');
 // M0056 raw evidence is an active bounded working set, so V3 is fetched and
 // matured before the slower historical lane is even queried. Historical work
 // still gets the remainder of the same finite batch after V3 service.
 const batchLimit=bounded('LPFORGE_RESET3C_COUNTERFACTUAL_MAX_BATCH',30,50),v3Limit=counterfactualV3ReservedSlots(batchLimit),v3Rows=await store.loadDueCandidateCounterfactualOutcomes(now,v3Limit,'V3'),v3Failures=await matureCandidateCounterfactualRows(store,v3Rows,now),historicalRows=await store.loadDueCandidateCounterfactualOutcomes(now,batchLimit-v3Rows.length,'HISTORICAL'),historicalFailures=await matureCandidateCounterfactualRows(store,historicalRows,now);
 const retentionLimit=bounded('LPFORGE_RESET3C_RETENTION_MAX_BATCH',8,50),terminalEligible=await store.markTerminalEligibleReset3cValidationUniverses(now,retentionLimit),purged=await store.purgeTerminalEligibleReset3cValidationEvidence(now,retentionLimit),binSnapshotRetention=await runBoundedBinSnapshotRetention({store,now,limit:Number(process.env.LPFORGE_BIN_SNAPSHOT_RETENTION_MAX_DELETE??2000),dryRun:process.env.LPFORGE_BIN_SNAPSHOT_RETENTION_DRY_RUN!=='false',emit:event=>console.log(json({...event,authority:'RESEARCH_ONLY_NO_POLICY_MUTATION'}))});
 memory('candidate-counterfactual:complete');
 return{processed:v3Rows.length+historicalRows.length,v3Selected:v3Rows.length,historicalSelected:historicalRows.length,failures:v3Failures+historicalFailures,terminalEligible,purged,binSnapshotRetention};
}
/** Read the immutable snapshot copied into the terminal outcome, never a newer recommendation or a live token price. */
function liveSettledSampleFromRow(row:Record<string,unknown>):LiveSettledLearningSample|undefined{
 const kind=String(row.outcome_kind);if(kind!=='LIVE_SOL_SETTLED'&&kind!=='LIVE_ENTRY_ABORTED_SOL_SETTLED')return undefined;
 const payload=object(row.payload),original=object(payload.originalPrediction),thesis=object(original.thesis),economics=object(thesis.expectedEconomics),expectedNet=finite(economics.netLpValue),confidence=finite(thesis.confidence),pnl=row.realized_sol_pnl_lamports;
 if(!row.outcome_id||!row.prediction_id||!row.pool_address||!row.entry_at||pnl===null||pnl===undefined)return undefined;
 return{outcomeId:String(row.outcome_id),predictionId:String(row.prediction_id),poolAddress:String(row.pool_address),...(row.strategy?{strategy:String(row.strategy)}:{}),...(row.entry_regime?{entryRegime:String(row.entry_regime)}:{}),entryAt:new Date(String(row.entry_at)).toISOString(),realizedSolPnlLamports:BigInt(String(pnl)),...(expectedNet!==undefined?{predictedNetSolLamports:BigInt(Math.round(expectedNet*1_000_000_000))}:{}),...(confidence!==undefined?{predictedProfitProbability:confidence}:{}),outcomeKind:kind};
}
function startPrice(p:PredictionRecord):number|undefined{const v=p.deep.evidence.currentPrice;return typeof v==='number'&&Number.isFinite(v)?v:undefined}
async function collectCounterfactuals(store:Awaited<ReturnType<typeof createPostgresStore>>,api:ReturnType<typeof createMeteoraDataApi>,predictions:PredictionRecord[],now:string){
 let inserted=0,throttled=false;predictions:for(const p of predictions){const start=startPrice(p);if(start===undefined||start<=0)continue;let current;try{current=await api.getPool(p.poolAddress)}catch(error){if(rateLimited(error)){throttled=true;break predictions;}continue}const currentPrice=typeof current.current_price==='number'?current.current_price:undefined;if(currentPrice===undefined||currentPrice<=0)continue;
  for(const h of horizons){if(Date.parse(now)<Date.parse(p.observedAt)+h*60000)continue;let history;try{history=await api.getHistoricalVolume(p.poolAddress,{timeframe:'5m',startTime:Math.floor(Date.parse(p.observedAt)/1000),endTime:Math.floor((Date.parse(p.observedAt)+h*60000)/1000)})}catch(error){if(rateLimited(error)){throttled=true;break predictions;}continue}
   const fees=history.data.reduce((a,b)=>a+Math.max(0,Number(b.fees)||0),0);const ret=currentPrice/start-1;const capital=.1;const directional=capital*ret*.5;const feeApprox=Math.min(capital*.2,fees/Math.max(1,Number(current.tvl??1))*capital);const net=feeApprox+directional;const clazz=p.cohort==='RANDOM_QUALIFIED_CONTROL'?'CONTROL_COUNTERFACTUAL':p.selectedAction==='NO_TRADE'?'NO_TRADE_COUNTERFACTUAL':'NO_TRADE_COUNTERFACTUAL';
   await store.insertDiscoveryOutcome({predictionId:p.predictionId,poolAddress:p.poolAddress,observedAt:now,horizonMinutes:h,outcomeClass:clazz,eventAttribution:'NORMAL',structuralEventCodes:[],realizedNetValue:net,realizedFees:feeApprox,realizedDirectionalPnl:directional,inventoryConversion:Math.min(1,Math.abs(ret)*2),payload:{fidelity:'COUNTERFACTUAL_MARK_TO_MARKET_APPROXIMATION',startPrice:start,currentPrice,returnPct:ret*100,historicalFeeUsd:fees,warning:'Not equivalent to an executed DLMM position; used for rejected/control learning only.'}});inserted++;
  }
 }if(throttled)console.warn(json({event:'DISCOVERY_COUNTERFACTUAL_RATE_LIMITED',authority:'RESEARCH_ONLY_NO_POLICY_MUTATION',processedBeforeThrottle:inserted}));return{inserted,throttled};
}
async function once(options:{includeForwardMaturation?:boolean}={}){
 const now=new Date().toISOString(),store=await createPostgresStore(env('DATABASE_URL')),api=createMeteoraDataApi({...((process.env.LPFORGE_METEORA_DATA_API_URL??'').trim()?{baseUrl:process.env.LPFORGE_METEORA_DATA_API_URL!}:{}),maxRps:Number(process.env.LPFORGE_DATA_API_MAX_RPS??1),timeoutMs:Number(process.env.LPFORGE_HTTP_TIMEOUT_MS??10000)});
 try{
  memory('cycle:start');
  let postEntryTelemetry;try{postEntryTelemetry=await runPostEntryTelemetryCapture({store,now});}catch(error){postEntryTelemetry={status:'ERROR',error:error instanceof Error?error.message:String(error)};console.error(json({event:'POST_ENTRY_TELEMETRY_CAPTURE_FAILED',authority:'RESEARCH_ONLY_NO_POLICY_MUTATION',...postEntryTelemetry}));}memory('post-entry:complete');
  let marketContextTelemetry;try{marketContextTelemetry=await runProspectiveMarketContextTelemetryCapture({store,now});}catch(error){marketContextTelemetry={status:'ERROR',error:error instanceof Error?error.message:String(error)};console.error(json({event:'M0050_MARKET_CONTEXT_TELEMETRY_CAPTURE_FAILED',authority:'RESEARCH_ONLY_NO_POLICY_MUTATION',...marketContextTelemetry}));}memory('m0050:complete');
  let inventoryForecastV2Shadow;try{inventoryForecastV2Shadow=await runProspectiveInventoryForecastV2Capture({store,now});}catch(error){inventoryForecastV2Shadow={status:'ERROR',error:error instanceof Error?error.message:String(error)};console.error(json({event:'INVENTORY_FORECAST_V2_SHADOW_CAPTURE_FAILED',authority:'RESEARCH_ONLY_NO_POLICY_MUTATION',...inventoryForecastV2Shadow}));}memory('m0052:complete');
  const phase3ForwardValidation=options.includeForwardMaturation===false?{deferredToIndependentScheduler:true}:await maturePhase3ForwardOutcomes(store,now,{includeCalibration:false});const candidateCounterfactualMaturation=options.includeForwardMaturation===false?{deferredToIndependentScheduler:true}:await matureCandidateCounterfactualOutcomes(store,now);
  const pendingSettlements=await store.loadPendingLiveSolSettledLearningOutcomes();let materializedLiveOutcomes=0;for(const positionAddress of pendingSettlements){const outcome=await store.createLiveSolSettledLearningOutcome({positionAddress,at:now});if(!outcome.outcome)throw new Error(`LPFORGE_LIVE_OUTCOME_MATERIALIZATION_PENDING:${outcome.reasonCodes.join(',')}`);if(outcome.created)materializedLiveOutcomes++;}
  const predictionLimit=bounded('LPFORGE_DISCOVERY_LEARNING_MAX_PREDICTIONS',500,1000),outcomeLimit=bounded('LPFORGE_DISCOVERY_LEARNING_MAX_OUTCOMES',2000,5000),liveOutcomeLimit=bounded('LPFORGE_LIVE_LEARNING_MAX_OUTCOMES',500,1000),counterfactualLimit=bounded('LPFORGE_DISCOVERY_COUNTERFACTUAL_MAX_BATCH',5,25);
  const rows=await store.loadRecentDiscoveryPredictions(predictionLimit),predictions=rows.map(predictionFromRow).filter((x):x is PredictionRecord=>Boolean(x));memory('calibration:predictions-loaded');
  const dueCounterfactuals=(await store.loadDueDiscoveryCounterfactualPredictions(now,counterfactualLimit)).map(predictionFromRow).filter((x):x is PredictionRecord=>Boolean(x)),counterfactuals=await collectCounterfactuals(store,api,dueCounterfactuals,now);const outcomes=(await store.loadDiscoveryOutcomes(outcomeLimit)).map(outcomeFromRow);memory('calibration:outcomes-loaded');const calibration=calibratePredictions(predictions,outcomes);const snapshotId=`cal-${hash(`${now}:${predictions.length}:${outcomes.length}`)}`;await store.insertDiscoveryCalibration({snapshotId,observedAt:now,modelVersion:'discovery-distributional-ev-v1',sampleCount:calibration.samples,independentEpisodes:calibration.independentEpisodes,...(calibration.brierProfit!==null?{brierProfit:calibration.brierProfit}:{}),...(calibration.survivalBrier!==null?{survivalBrier:calibration.survivalBrier}:{}),...(calibration.netValueMae!==null?{netValueMae:calibration.netValueMae}:{}),...(calibration.meanBias!==null?{meanBias:calibration.meanBias}:{}),allOutcomeNet:calibration.allOutcomeNet,modelCalibrationNet:calibration.modelCalibrationNet,payload:{allOutcomeIncludesStructuralBreaks:true,runtimeBounds:{predictionLimit,outcomeLimit,counterfactualLimit}}});
  const liveOutcomes=(await store.loadLiveLearningOutcomes(liveOutcomeLimit)).map(liveSettledSampleFromRow).filter((x):x is LiveSettledLearningSample=>Boolean(x));memory('calibration:live-outcomes-loaded');const liveCalibration=calibrateLiveSettledOutcomes(liveOutcomes);const liveSnapshotId=`live-sol-settled-cal-${hash(`${now}:${liveOutcomes.map(x=>x.outcomeId).sort().join(':')}`)}`;await store.insertLiveLearningCalibration({snapshotId:liveSnapshotId,observedAt:now,sampleCount:liveCalibration.samples,independentEpisodes:liveCalibration.independentEpisodes,...(liveCalibration.brierProfit!==null?{brierProfit:liveCalibration.brierProfit}:{}),...(liveCalibration.netPnlMaeLamports!==null?{netPnlMaeLamports:liveCalibration.netPnlMaeLamports}:{}),...(liveCalibration.meanBiasLamports!==null?{meanBiasLamports:liveCalibration.meanBiasLamports}:{}),payload:{authority:'RESEARCH_ONLY_NO_POLICY_MUTATION',terminalOutcomeKinds:['LIVE_SOL_SETTLED','LIVE_ENTRY_ABORTED_SOL_SETTLED'],cohorts:liveCalibration.byCohort,profitableCount:liveCalibration.profitableCount,lossCount:liveCalibration.lossCount,counterfactualComparison:'PRESERVED_IN_EXISTING_DISCOVERY_OUTCOMES',runtimeBounds:{liveOutcomeLimit}}});
  for(const [level,keyFn] of [['POOL',(p:PredictionRecord)=>p.poolAddress],['STRATEGY',(p:PredictionRecord)=>String(p.selectedAction)],['POOL_STRATEGY_REGIME',(p:PredictionRecord)=>`${p.poolAddress}:${p.selectedAction}:${String(p.selectionContext.regime??'UNKNOWN')}`]] as const){for(const r of buildReputation(predictions,outcomes,keyFn))await store.upsertDiscoveryReputation({reputationKey:`${level}:${r.key}`,level,asOf:now,samples:r.samples,independentEpisodes:r.episodes,meanNet:r.meanNet,positiveRate:r.positiveRate,confidence:r.confidence,payload:{meanFees:r.meanFees,meanDirectional:r.meanDirectional}});}
  const proposal=researchProposalFromCalibration({observedAt:now,calibration});if(proposal)await store.upsertDiscoveryPolicyProposal({proposalId:proposal.proposal.proposalId,createdAt:proposal.proposal.createdAt,state:proposal.proposal.state,hypothesis:proposal.proposal.hypothesis,targetPolicy:proposal.proposal.targetPolicy,changes:proposal.proposal.changes,evidence:{...proposal.proposal.evidence,authority:proposal.authority}});
  memory('cycle:complete');
  const summary={status:'PASS',authority:'RESEARCH_ONLY_NO_POLICY_MUTATION',observedAt:now,predictions:predictions.length,outcomes:outcomes.length,liveSolSettledOutcomes:liveOutcomes.length,materializedLiveOutcomes,counterfactualsUpserted:counterfactuals.inserted,counterfactualRateLimited:counterfactuals.throttled,calibration,liveCalibration,phase3ForwardValidation,postEntryTelemetry,marketContextTelemetry,inventoryForecastV2Shadow,proposal:proposal?.proposal??null};console.log(json(summary));return summary;
 }finally{await store.close()}
}
const cmd=process.argv[2]??'once';if(cmd==='once')await once();else if(cmd==='start'){
 const learningMs=Math.max(300_000,Number(process.env.LPFORGE_DISCOVERY_LEARNING_INTERVAL_MS??900_000));
 const forwardMaturationMs=Math.max(30_000,Math.min(300_000,Number(process.env.LPFORGE_FORWARD_VALIDATION_INTERVAL_MS??60_000)));
 const postEntryTelemetryMs=Math.max(30_000,Math.min(300_000,Number(process.env.LPFORGE_POST_ENTRY_TELEMETRY_INTERVAL_MS??60_000)));
 const marketContextTelemetryMs=Math.max(30_000,Math.min(300_000,Number(process.env.LPFORGE_MARKET_CONTEXT_TELEMETRY_INTERVAL_MS??60_000)));
 const inventoryForecastV2Ms=Math.max(30_000,Math.min(300_000,Number(process.env.LPFORGE_INVENTORY_FORECAST_V2_INTERVAL_MS??60_000)));
 startIndependentForwardMaturationLoop({intervalMs:forwardMaturationMs,run:async()=>{const store=await createPostgresStore(env('DATABASE_URL')),now=new Date().toISOString();try{await maturePhase3ForwardOutcomes(store,now,{includeCalibration:false});await matureCandidateCounterfactualOutcomes(store,now);}finally{await store.close();}},onError:(error)=>console.error(json({event:'FORWARD_MATURATION_FAILED',error:error instanceof Error?error.message:String(error),authority:'RESEARCH_ONLY_NO_POLICY_MUTATION'}))});
 startIndependentPostEntryTelemetryLoop({intervalMs:postEntryTelemetryMs,run:async()=>{const store=await createPostgresStore(env('DATABASE_URL'));try{await runPostEntryTelemetryCapture({store,now:new Date().toISOString()});}finally{await store.close();}},onError:(error)=>console.error(json({event:'POST_ENTRY_TELEMETRY_CAPTURE_FAILED',error:error instanceof Error?error.message:String(error),authority:'RESEARCH_ONLY_NO_POLICY_MUTATION'}))});
 startIndependentProspectiveMarketContextTelemetryLoop({intervalMs:marketContextTelemetryMs,run:async()=>{const store=await createPostgresStore(env('DATABASE_URL'));try{await runProspectiveMarketContextTelemetryCapture({store,now:new Date().toISOString()});}finally{await store.close();}},onError:(error)=>console.error(json({event:'M0050_MARKET_CONTEXT_TELEMETRY_CAPTURE_FAILED',error:error instanceof Error?error.message:String(error),authority:'RESEARCH_ONLY_NO_POLICY_MUTATION'}))});
 startIndependentProspectiveInventoryForecastV2Loop({intervalMs:inventoryForecastV2Ms,run:async()=>{const store=await createPostgresStore(env('DATABASE_URL'));try{await runProspectiveInventoryForecastV2Capture({store,now:new Date().toISOString()});}finally{await store.close();}},onError:(error)=>console.error(json({event:'INVENTORY_FORECAST_V2_SHADOW_CAPTURE_FAILED',error:error instanceof Error?error.message:String(error),authority:'RESEARCH_ONLY_NO_POLICY_MUTATION'}))});
 for(;;){try{await once({includeForwardMaturation:false})}catch(error){console.error(json({status:'ERROR',error:error instanceof Error?error.message:String(error)}))}await new Promise(resolve=>setTimeout(resolve,learningMs));}
}else throw new Error(`LPFORGE_DISCOVERY_LEARNING_COMMAND:${cmd}`);
