// LPFORGE_PHASE6_MAINNET_MODULE
import {createLocalKeypairFileSigner,createRemoteKmsHttpSigner,type MainnetSignerBackend} from '../../../packages/phase6-mainnet-signer/src/index.js';
import {assertCapitalDeploymentAuthorized,evaluatePhase6LivePathAuthorization,loadPhase6LiveAuthorizationConfig} from '../../../packages/phase6-operational-gates/src/index.js';

const json=(value:unknown)=>JSON.stringify(value,null,2);
const yes=(value:string|undefined)=>String(value??'').toLowerCase()==='true';
function signerFromEnvironment():MainnetSignerBackend{const common={backendId:process.env.LPFORGE_P6_SIGNER_BACKEND_ID??'',publicKeyAddress:process.env.LPFORGE_P6_SIGNER_PUBLIC_KEY??''},mode=(process.env.LPFORGE_P6_SIGNER_MODE??'').trim();if(mode==='LOCAL_KEYPAIR_FILE')return createLocalKeypairFileSigner({...common,keypairPath:process.env.LPFORGE_P6_KEYPAIR_PATH??''});if(mode==='REMOTE_KMS')return createRemoteKmsHttpSigner({...common,endpoint:process.env.LPFORGE_P6_REMOTE_SIGNER_URL??'',authorizationToken:process.env.LPFORGE_P6_REMOTE_SIGNER_AUTH_TOKEN??'',timeoutMs:Number(process.env.LPFORGE_P6_REMOTE_SIGNER_TIMEOUT_MS??5000)});throw new Error('LPFORGE_P6_SIGNER_MODE_INVALID');}
function status(){const gate=evaluatePhase6LivePathAuthorization(loadPhase6LiveAuthorizationConfig());const runnerEnabled=yes(process.env.LPFORGE_P6_EXECUTION_RUNNER_ENABLED);let signerReady=false,signerError:string|undefined,signerMode:string|undefined;try{const signer=signerFromEnvironment();signerReady=signer.secretExportable===false;signerMode=signer.custodyMode;}catch(error){signerError=error instanceof Error?error.message:'LPFORGE_P6_SIGNER_INVALID';}return{service:'lpforge-execution',runnerEnabled,gate,signerReady,...(signerMode?{signerMode}:{}),...(signerError?{signerError}:{}),executionPlanSource:'NOT_CONFIGURED',directKeyMaterial:false,transactionSubmitted:false};}
function assertLaunchable(){const current=status();if(!current.runnerEnabled)throw new Error('LPFORGE_P6_EXECUTION_RUNNER_DISABLED');assertCapitalDeploymentAuthorized(current.gate);if(!current.signerReady)throw new Error(current.signerError??'LPFORGE_P6_SIGNER_NOT_READY');return current;}
async function start(){const current=assertLaunchable();console.log(json({...current,status:'ARMED_NO_PLAN_SOURCE'}));const interval=Math.max(1000,Math.min(60000,Number(process.env.LPFORGE_P6_EXECUTION_RUNNER_INTERVAL_MS??5000)));for(;;){await new Promise(resolve=>setTimeout(resolve,interval));const next=status();if(!next.runnerEnabled||!next.gate.capitalDeploymentAuthorized||!next.signerReady)throw new Error(`LPFORGE_P6_EXECUTION_RUNNER_GATE_REVOKED:${next.gate.reasonCodes.join(',')}`);console.log(json({service:'lpforge-execution',status:'ARMED_NO_PLAN_SOURCE',observedAt:new Date().toISOString(),transactionSubmitted:false}));}}
const cmd=process.argv[2]??'status';if(cmd==='status')console.log(json(status()));else if(cmd==='assert-launchable')console.log(json(assertLaunchable()));else if(cmd==='start')await start();else{console.error('Usage: execution [status|assert-launchable|start]');process.exitCode=2;}
