// LPFORGE_PHASE7_RUNTIME_INTEGRATION_MODULE
import {createHash} from 'node:crypto';
import type {Phase1Store} from '../../db/src/index.js';
import {buildPhase7EvidencePack,requiredPhase7Runbooks,type Phase7EvidenceItem,type Phase7EvidencePack} from '../../phase7-evidence/src/index.js';
export type RuntimeEvidenceStatus='PASS'|'HOLD'|'BLOCK';
export interface Phase7RuntimeEvidenceSummary {observedAt:string;statuses:{IMPLEMENTATION:RuntimeEvidenceStatus;HEALTH:RuntimeEvidenceStatus;DRIFT:RuntimeEvidenceStatus;RECOVERY:RuntimeEvidenceStatus;MAINNET_READ_ONLY:RuntimeEvidenceStatus;CANARY:RuntimeEvidenceStatus;LIMITED_LIVE:RuntimeEvidenceStatus;DR:RuntimeEvidenceStatus;PRODUCTION:RuntimeEvidenceStatus};facts:Awaited<ReturnType<Phase1Store['loadPhase7EvidenceFacts']>>;reasonCodes:string[];pack?:Phase7EvidencePack;}
const sha=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const mapHealth=(v?:string):RuntimeEvidenceStatus=>v==='HEALTHY'?'PASS':v==='CRITICAL'?'BLOCK':'HOLD';
const mapDrift=(v?:string):RuntimeEvidenceStatus=>v==='STABLE'?'PASS':v==='BLOCK'?'BLOCK':'HOLD';
const mapGeneric=(v?:string):RuntimeEvidenceStatus=>v==='PASS'?'PASS':v==='BLOCK'?'BLOCK':'HOLD';
export async function buildPhase7RuntimeEvidence(input:{store:Pick<Phase1Store,'loadPhase7EvidenceFacts'>;runtimeId:string;observedAt:string;sourceCommit?:string;policyHash?:string;packId?:string}):Promise<Phase7RuntimeEvidenceSummary>{
  const facts=await input.store.loadPhase7EvidenceFacts(input.runtimeId);const recovery:RuntimeEvidenceStatus=facts.unresolvedReconciliationDebt>0?'BLOCK':facts.runtimeCycleCount>0&&facts.latestRuntimePlan!=='RECOVER_ONLY'?'PASS':'HOLD';const readOnly:RuntimeEvidenceStatus=facts.mainnetReadOnlyCycleCount>0?'PASS':'HOLD';const canary:RuntimeEvidenceStatus=facts.fullyReconciledCanaryCount>0?'PASS':'HOLD';const limited=mapGeneric(facts.latestLimitedLiveStatus);const dr=mapGeneric(facts.latestDrStatus);let production=mapGeneric(facts.latestProductionStatus);const implementation:RuntimeEvidenceStatus=facts.phase7ExitPass?'PASS':'HOLD';const health=mapHealth(facts.latestHealthStatus),drift=mapDrift(facts.latestDriftStatus);if([implementation,health,drift,recovery,readOnly,canary,limited,dr].some(x=>x==='BLOCK'))production='BLOCK';else if([implementation,health,drift,recovery,readOnly,canary,limited,dr].some(x=>x!=='PASS'))production='HOLD';const statuses={IMPLEMENTATION:implementation,HEALTH:health,DRIFT:drift,RECOVERY:recovery,MAINNET_READ_ONLY:readOnly,CANARY:canary,LIMITED_LIVE:limited,DR:dr,PRODUCTION:production};const reasons=Object.entries(statuses).filter(([,v])=>v!=='PASS').map(([k,v])=>`P7_RUNTIME_EVIDENCE_${k}_${v}`);if(facts.submissionCount>0&&facts.fullyReconciledCanaryCount===0)reasons.push('P7_RUNTIME_EVIDENCE_SUBMISSION_WITHOUT_RECONCILED_CANARY');
  let pack:Phase7EvidencePack|undefined; if(input.sourceCommit?.trim()&&input.policyHash?.trim()){
    const item=(kind:string,id:string,status:RuntimeEvidenceStatus,detail:unknown):Phase7EvidenceItem=>({kind,id,status,observedAt:input.observedAt,hash:sha({kind,id,status,detail})});
    const items=[item('FULL_REGRESSION','implementation',implementation,{phase7ExitPass:facts.phase7ExitPass}),item('PHASE_BOUNDARIES','implementation-boundaries',implementation,{phase7ExitPass:facts.phase7ExitPass}),item('MIGRATIONS','postgres-runtime',implementation,{phase7ExitPass:facts.phase7ExitPass}),item('POSTGRES_RUNTIME','runtime',recovery,{runtimeCycleCount:facts.runtimeCycleCount}),item('LOCAL_METEORA_LIFECYCLE','local-lifecycle',implementation,{phase7ExitPass:facts.phase7ExitPass}),item('MAINNET_READ_ONLY','mainnet-read-only',readOnly,{cycles:facts.mainnetReadOnlyCycleCount}),item('CANARY_PROGRAM','canary',canary,{runs:facts.canaryRunCount,reconciled:facts.fullyReconciledCanaryCount}),item('DISASTER_RECOVERY','dr',dr,{status:facts.latestDrStatus}),item('PROMOTION_DECISION','promotion',production,{limited:facts.latestLimitedLiveStatus,production:facts.latestProductionStatus})];pack=buildPhase7EvidencePack({packId:input.packId??`runtime-${input.observedAt}`,createdAt:input.observedAt,sourceCommit:input.sourceCommit,policyHash:input.policyHash,runbookIds:[...requiredPhase7Runbooks],items});
  }
  return{observedAt:input.observedAt,statuses,facts,reasonCodes:[...new Set(reasons)].sort(),...(pack?{pack}:{})};
}
