// Shared representation only: this package carries no canary or runtime authority.
import {readFileSync} from 'node:fs';
export interface MainnetCanaryPoolPolicy {address:string;maxCapitalLamports:bigint;maxOpenPositions:number;}
export interface ProductionAdmissionPolicy {enabled:boolean;eligibleTiers:ReadonlyArray<'A'|'B'|'C'>;maxCandidates:number;maxCandidateAgeMs:number;maxCapitalLamports:bigint;maxOpenPositions:number;}
export interface ProductionCapitalDeploymentPolicy {reserveLamports:bigint;maxPortfolioLamports:bigint;maxTokenLamports:bigint;targetInitialPositionLamports:bigint;maxInitialPositionLamports:bigint;minInitialPositionLamports:bigint;}
export interface MainnetCanaryDeploymentPolicy {schemaVersion:1;policyId:string;status:'DISABLED'|'ENABLED';approvalTtlMs:number;minDevnetConfirmedRuns:number;maxActionsPerDay:number;maxOpenPositions:number;pools:MainnetCanaryPoolPolicy[];productionAdmission?:ProductionAdmissionPolicy;productionCapital?:ProductionCapitalDeploymentPolicy;}
function int(name:string,v:string|undefined,min:number,max:number){const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw new Error(`LPFORGE_CANARY_CONFIG:${name}`);return n;}
function sol(value:unknown,zero=false){if(zero&&(value===0||value==='0'||value==='0.0'))return 0n;const source=typeof value==='string'?value.trim():typeof value==='number'&&Number.isFinite(value)?value.toFixed(9):'';const m=/^(0|[1-9]\d*)(?:\.(\d{1,9}))?$/.exec(source);if(!m)throw new Error('LPFORGE_CANARY_POLICY_CAPITAL_SOL');const n=BigInt(m[1]!)*1_000_000_000n+BigInt((m[2]??'').padEnd(9,'0')||'0');if(n<=0n&&!zero)throw new Error('LPFORGE_CANARY_POLICY_CAPITAL_SOL');return n;}
function positive(name:string,value:unknown){const n=Number(value);if(!Number.isSafeInteger(n)||n<1)throw new Error(`LPFORGE_CANARY_POLICY:${name}`);return n;}
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('LPFORGE_CANARY_POLICY_FORMAT');return value as Record<string,unknown>;}
function text(name:string,value:unknown){if(typeof value!=='string'||!value.trim())throw new Error(`LPFORGE_CANARY_POLICY:${name}`);return value.trim();}
function admission(value:unknown):ProductionAdmissionPolicy|undefined{if(value===undefined)return;const v=object(value);if(typeof v.enabled!=='boolean')throw new Error('LPFORGE_CANARY_POLICY:PRODUCTION_ADMISSION_ENABLED');const tiers=Array.isArray(v.eligibleTiers)?[...new Set(v.eligibleTiers)]:[];if(!tiers.length||tiers.some(x=>x!=='A'&&x!=='B'&&x!=='C'))throw new Error('LPFORGE_CANARY_POLICY:PRODUCTION_ADMISSION_TIERS');return{enabled:v.enabled,eligibleTiers:tiers as Array<'A'|'B'|'C'>,maxCandidates:positive('PRODUCTION_ADMISSION_MAX_CANDIDATES',v.maxCandidates),maxCandidateAgeMs:int('PRODUCTION_ADMISSION_MAX_CANDIDATE_AGE_MS',String(v.maxCandidateAgeMs),60_000,86_400_000),maxCapitalLamports:sol(v.maxCapitalSol),maxOpenPositions:positive('PRODUCTION_ADMISSION_MAX_OPEN_POSITIONS',v.maxOpenPositions)};}
function capital(value:unknown):ProductionCapitalDeploymentPolicy|undefined{if(value===undefined)return;const v=object(value),reserveLamports=sol(v.reserveSol,true),maxPortfolioLamports=sol(v.maxPortfolioCapitalSol),maxTokenLamports=sol(v.maxTokenCapitalSol),targetInitialPositionLamports=sol(v.targetInitialPositionSol),maxInitialPositionLamports=sol(v.maxInitialPositionSol),minInitialPositionLamports=sol(v.minInitialPositionSol);if(reserveLamports>=maxPortfolioLamports||minInitialPositionLamports>targetInitialPositionLamports||targetInitialPositionLamports>maxInitialPositionLamports||maxInitialPositionLamports>maxPortfolioLamports)throw new Error('LPFORGE_CANARY_POLICY:PRODUCTION_CAPITAL_RANGE');return{reserveLamports,maxPortfolioLamports,maxTokenLamports,targetInitialPositionLamports,maxInitialPositionLamports,minInitialPositionLamports};}
export function parseDeploymentPolicy(raw:unknown):MainnetCanaryDeploymentPolicy{const v=object(raw);if(v.schemaVersion!==1)throw new Error('LPFORGE_CANARY_POLICY_SCHEMA');if(v.status!=='DISABLED'&&v.status!=='ENABLED')throw new Error('LPFORGE_CANARY_POLICY_STATUS');if(!Array.isArray(v.pools))throw new Error('LPFORGE_CANARY_POLICY:POOLS');const pools=v.pools.map(x=>{const p=object(x);return{address:text('POOL_ADDRESS',p.address),maxCapitalLamports:sol(p.maxCapitalSol),maxOpenPositions:positive('POOL_MAX_OPEN_POSITIONS',p.maxOpenPositions)}}),productionAdmission=admission(v.productionAdmission),productionCapital=capital(v.productionCapital);if(new Set(pools.map(p=>p.address)).size!==pools.length)throw new Error('LPFORGE_CANARY_POLICY_POOL_DUPLICATE');if(v.status==='ENABLED'&&!pools.length&&!productionAdmission?.enabled)throw new Error('LPFORGE_CANARY_POLICY_POOL_REQUIRED');return{schemaVersion:1,policyId:text('POLICY_ID',v.policyId),status:v.status,approvalTtlMs:int('APPROVAL_TTL_MS',String(v.approvalTtlMs),5_000,60_000),minDevnetConfirmedRuns:positive('MIN_DEVNET_CONFIRMED',v.minDevnetConfirmedRuns),maxActionsPerDay:positive('MAX_ACTIONS_PER_DAY',v.maxActionsPerDay),maxOpenPositions:positive('MAX_OPEN_POSITIONS',v.maxOpenPositions),pools,...(productionAdmission?{productionAdmission}:{}),...(productionCapital?{productionCapital}:{})};}
export function loadDeploymentPolicyFile(path:string):MainnetCanaryDeploymentPolicy{try{return parseDeploymentPolicy(JSON.parse(readFileSync(path,'utf8')));}catch(error){if(error instanceof Error&&error.message.startsWith('LPFORGE_CANARY_'))throw error;throw new Error('LPFORGE_CANARY_POLICY_FILE_INVALID');}}
export const parseMainnetCanaryDeploymentPolicy=parseDeploymentPolicy;
export const loadMainnetCanaryDeploymentPolicyFile=loadDeploymentPolicyFile;
