// LPFORGE_PHASE6_MAINNET_MODULE
import {Transaction} from '@solana/web3.js';
import {buildExtendedChunkableOpenTransactions,type MeteoraOpenAddPoolLike} from '../../meteora-execution/src/index.js';
import {createEphemeralPositionSigner,type AuxiliaryMainnetSignerBackend} from '../../phase6-mainnet-signer/src/index.js';
import {createLegacyMainnetEnvelope} from '../../phase6-live-envelope/src/index.js';

export interface AutonomousOpenPlan {planId:string;intentId:string;idempotencyKey:string;poolAddress:string;ownerAddress:string;thesisId:string;observedAt:string;expiresAt:string;intentPayload:Record<string,unknown>;planPayload:Record<string,unknown>;transactionId:string;transactionMetadata:Record<string,unknown>;steps?:Array<{transactionId:string;kind:string;metadata:Record<string,unknown>}>;swapTransactionId?:string;swapTransactionMetadata?:Record<string,unknown>;}
export interface PreparedAutonomousOpenStep {transactionId:string;kind:'METEORA_OPEN'|'METEORA_POSITION_EXTEND'|'METEORA_OPEN_CHUNK';requiredSignerAddresses:string[];transaction:Transaction;envelope:ReturnType<typeof createLegacyMainnetEnvelope>;metadata:Record<string,unknown>;}
export interface PreparedAutonomousOpen {plan:AutonomousOpenPlan;positionSigner:AuxiliaryMainnetSignerBackend;steps:PreparedAutonomousOpenStep[];/** Compatibility aliases for the one-step path only. */requiredSignerAddresses:string[];transaction:Transaction;envelope:ReturnType<typeof createLegacyMainnetEnvelope>;metadata:Record<string,unknown>;}
function object(value:unknown,code:string){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(code);return value as Record<string,unknown>;}
function integer(value:unknown,code:string){const n=Number(value);if(!Number.isInteger(n))throw new Error(code);return n;}
function text(value:unknown,code:string){if(typeof value!=='string'||!value.trim())throw new Error(code);return value.trim();}
function openFields(plan:AutonomousOpenPlan){const intent=object(plan.planPayload.intent,'LPFORGE_P6_AUTONOMOUS_PLAN_INTENT_MISSING'),funding=object(plan.intentPayload.entryFunding,'LPFORGE_P6_AUTONOMOUS_PLAN_FUNDING_MISSING');const strategy=intent.strategy;if(strategy!=='SPOT'&&strategy!=='CURVE'&&strategy!=='BID_ASK')throw new Error('LPFORGE_P6_AUTONOMOUS_PLAN_STRATEGY');const maxPositionWidthBins=integer(intent.maxPositionWidthBins??plan.transactionMetadata.maxPositionWidthBins??100,'LPFORGE_P6_AUTONOMOUS_PLAN_MAX_POSITION_WIDTH');if(maxPositionWidthBins<3||maxPositionWidthBins>1400)throw new Error('LPFORGE_P6_AUTONOMOUS_PLAN_MAX_POSITION_WIDTH');return{lowerBinId:integer(intent.lowerBinId,'LPFORGE_P6_AUTONOMOUS_PLAN_LOWER_BIN'),upperBinId:integer(intent.upperBinId,'LPFORGE_P6_AUTONOMOUS_PLAN_UPPER_BIN'),strategy:strategy as 'SPOT'|'CURVE'|'BID_ASK',totalXAmount:text(funding.totalPairedTokenRaw,'LPFORGE_P6_AUTONOMOUS_PLAN_TOTAL_X'),totalYAmount:text(funding.solForLpLamports,'LPFORGE_P6_AUTONOMOUS_PLAN_TOTAL_Y'),maxPositionWidthBins};}
/**
 * Binds a fresh stored decision to one fresh PositionV2 account and a real
 * SDK-built transaction. This has no signer-owner or network-send capability.
 */
export async function prepareAutonomousMeteoraOpen(input:{plan:AutonomousOpenPlan;pool:MeteoraOpenAddPoolLike}):Promise<PreparedAutonomousOpen>{
  if(Date.parse(input.plan.expiresAt)<=Date.now())throw new Error('LPFORGE_P6_AUTONOMOUS_PLAN_EXPIRED');
  const fields=openFields(input.plan),positionSigner=createEphemeralPositionSigner(),built=await buildExtendedChunkableOpenTransactions(input.pool,{userAddress:input.plan.ownerAddress,positionAddress:positionSigner.publicKeyAddress,totalXAmount:fields.totalXAmount,totalYAmount:fields.totalYAmount,lowerBinId:fields.lowerBinId,upperBinId:fields.upperBinId,strategy:fields.strategy,maxPositionWidthBins:fields.maxPositionWidthBins});
  const expected=input.plan.steps?.filter(step=>step.kind==='METEORA_OPEN'||step.kind==='METEORA_POSITION_EXTEND'||step.kind==='METEORA_OPEN_CHUNK')??[{transactionId:input.plan.transactionId,kind:'METEORA_OPEN',metadata:input.plan.transactionMetadata}];if(expected.length!==built.length)throw new Error('LPFORGE_P6_AUTONOMOUS_OPEN_STEP_COUNT_MISMATCH');
  const steps=built.map((row,index)=>{const expectation=expected[index]!;const expectedKind=row.builder==='createExtendedEmptyPosition'?'METEORA_POSITION_EXTEND':row.builder==='addLiquidityByStrategyChunkable'?'METEORA_OPEN_CHUNK':'METEORA_OPEN';if(expectation.kind!==expectedKind)throw new Error('LPFORGE_P6_AUTONOMOUS_OPEN_STEP_KIND_MISMATCH');if(!(row.transaction instanceof Transaction))throw new Error('LPFORGE_P6_AUTONOMOUS_OPEN_TRANSACTION_UNSUPPORTED');const required=[...new Set([...row.requiredSignerAddresses,input.plan.ownerAddress,...(expectedKind==='METEORA_POSITION_EXTEND'?[positionSigner.publicKeyAddress]:[])])];return{transactionId:expectation.transactionId,kind:expectedKind as PreparedAutonomousOpenStep['kind'],requiredSignerAddresses:required,transaction:row.transaction,envelope:createLegacyMainnetEnvelope(row.transaction),metadata:{...row.metadata,...expectation.metadata,stepIndex:index,stepCount:built.length}};});
  const first=steps[0]!;return{plan:input.plan,positionSigner,steps,requiredSignerAddresses:first.requiredSignerAddresses,transaction:first.transaction,envelope:first.envelope,metadata:{planId:input.plan.planId,thesisId:input.plan.thesisId,positionAddress:positionSigner.publicKeyAddress,autonomous:true,positionWidthBins:fields.upperBinId-fields.lowerBinId+1,maxPositionWidthBins:fields.maxPositionWidthBins}};
}
