import { loadPhase1Config, phase1Capabilities } from '../../../packages/config/src/index.js';
import { createMeteoraDataApi } from '../../../packages/data-api/src/index.js';
import { computeActiveBinMovement, computeBinWindowFeatures, computeFeeQuality, computeSwapFlowFeatures, finalizeFeatureSnapshot } from '../../../packages/features/src/index.js';
import { createMeteoraReadAdapter, createSolanaRpcClient, scanAddressTransactions } from '../../../packages/meteora/src/index.js';
import { valuePosition } from '../../../packages/accounting/src/index.js';
import { fixtureBins, fixtureDataApiPool, fixturePool, fixtureSwaps } from '../../../packages/test-fixtures/src/index.js';
const cmd=process.argv[2]??'help';
function print(v:unknown){console.log(JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x,2));}
async function fixtureFeatures(){const bin=computeBinWindowFeatures(fixtureBins,fixturePool.activeBinId);const movement=computeActiveBinMovement([{binId:99,observedAt:'2026-08-12T09:55:00Z'},{binId:101,observedAt:'2026-08-12T09:58:00Z'},{binId:100,observedAt:'2026-08-12T10:00:00Z'}]);const flow=computeSwapFlowFeatures(fixtureSwaps);const fee=computeFeeQuality(fixtureDataApiPool);return finalizeFeatureSnapshot(fixturePool.address,{slot:1000n},{bin,movement,flow,fee});}
if(cmd==='capabilities') print(phase1Capabilities());
else if(cmd==='fixture-features') print(await fixtureFeatures());
else if(cmd==='fixture-valuation') print(valuePosition({positionAddress:'FixturePosition111111111111111111111111111',poolAddress:fixturePool.address,tokenX:{mint:fixturePool.tokenXMint,raw:1_000_000_000n,decimals:9},tokenY:{mint:fixturePool.tokenYMint,raw:25_000_000n,decimals:6},priceX:{quote:'USD',value:'150.25',source:'FIXTURE',observedAt:new Date().toISOString()},priceY:{quote:'USD',value:'1',source:'FIXTURE',observedAt:new Date().toISOString()},feeX:{mint:fixturePool.tokenXMint,raw:1_000_000n,decimals:9},feeY:{mint:fixturePool.tokenYMint,raw:50_000n,decimals:6},contributedValue:'175',hodlBenchmarkValue:'176'}));
else if(cmd==='fixture-all'){print({capabilities:phase1Capabilities(),features:await fixtureFeatures()});}
else if(cmd==='data-api-pools'||cmd==='data-api-ohlcv'){const cfg=loadPhase1Config();const api=createMeteoraDataApi({baseUrl:cfg.meteoraDataApiUrl,maxRps:cfg.dataApiMaxRps,timeoutMs:cfg.httpTimeoutMs});if(cmd==='data-api-pools'){print(await api.listPools(Number(process.argv[3]??1),Number(process.argv[4]??10),process.argv[5]));}else{const address=process.argv[3]??cfg.smokePoolAddress;if(!address)throw new Error('pool address required');print(await api.getOhlcv(address,{timeframe:'5m'}));}}
else if(cmd==='event-scan'){const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_LIVE_READ_REQUIRED');const pool=process.argv[3]??cfg.smokePoolAddress;if(!pool)throw new Error('pool address required');const a=createMeteoraReadAdapter({rpcUrl:cfg.solanaRpcHttpUrl,cluster:cfg.cluster,programId:cfg.programId,expectedSdkVersion:cfg.expectedSdkVersion,rpcTimeoutMs:cfg.rpcTimeoutMs});const rpc=createSolanaRpcClient({url:cfg.solanaRpcHttpUrl,timeoutMs:cfg.rpcTimeoutMs});const txs=await scanAddressTransactions({rpc,address:pool,limit:Number(process.argv[4]??20),programId:cfg.programId});const events=[];for(const tx of txs)events.push(...await a.decodeEvents(pool,tx.signature,tx.slot,tx.blockTime,tx.logs,tx.cpiInstructionData));print({transactions:txs.length,events});}
else if(cmd==='protocol-verify'||cmd==='pool-inspect'||cmd==='position-inspect'){const cfg=loadPhase1Config();if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_LIVE_READ_REQUIRED');const a=createMeteoraReadAdapter({rpcUrl:cfg.solanaRpcHttpUrl,cluster:cfg.cluster,programId:cfg.programId,expectedSdkVersion:cfg.expectedSdkVersion,rpcTimeoutMs:cfg.rpcTimeoutMs});if(cmd==='protocol-verify')print(await a.verifyCompatibility(cfg.smokePoolAddress));else if(cmd==='pool-inspect'){const address=process.argv[3]??cfg.smokePoolAddress;if(!address)throw new Error('pool address required');print({pool:await a.getPool(address),activeBin:await a.getActiveBin(address),bins:await a.getBinsAroundActive(address,10)});}else{const pool=process.argv[3]??cfg.smokePoolAddress,pos=process.argv[4]??cfg.smokePositionAddress;if(!pool||!pos)throw new Error('pool and position required');print(await a.getPositionV2(pool,pos));}}
else print({usage:['observer capabilities','observer fixture-features','observer fixture-valuation','observer fixture-all','observer data-api-pools [page] [page_size] [query]','observer data-api-ohlcv <pool>','observer protocol-verify','observer pool-inspect <pool>','observer position-inspect <pool> <position>','observer event-scan <pool> [limit]']});
