export type ConfirmedExecutionReceiptState='CONFIRMED_SUCCESS'|'CONFIRMED_FAILURE'|'NOT_FOUND_YET'|'RPC_UNAVAILABLE'|'MALFORMED_RECEIPT'|'UNSUPPORTED_VERSION';
export interface ReceiptTokenBalance {accountIndex:number;resolvedAccountAddress:string;mint:string;owner?:string;rawAmount:bigint;decimals:number;}
export interface ConfirmedExecutionReceipt {state:ConfirmedExecutionReceiptState;signature:string;slot?:bigint;blockTime?:string;err?:unknown;feeLamports?:bigint;staticAccountKeys:string[];loadedWritableAddresses:string[];loadedReadonlyAddresses:string[];resolvedAccountKeys:string[];preBalancesLamports:bigint[];postBalancesLamports:bigint[];preTokenBalances:ReceiptTokenBalance[];postTokenBalances:ReceiptTokenBalance[];outerInstructions:unknown[];innerInstructions:unknown[];logMessages:string[];messageVersion?:number|'legacy';}
export interface ReceiptConnection {getTransaction(signature:string,config:{commitment:'confirmed';maxSupportedTransactionVersion:0}):Promise<unknown>}
const record=(x:unknown):Record<string,unknown>|undefined=>x&&typeof x==='object'&&!Array.isArray(x)?x as Record<string,unknown>:undefined;
const publicKey=(value:unknown):string|undefined=>{if(typeof value==='string')return value;const candidate=value as {toBase58?:unknown};return typeof candidate?.toBase58==='function'?candidate.toBase58() as string:undefined;};
const keys=(rows:unknown):string[]=>Array.isArray(rows)?rows.flatMap(row=>{const direct=publicKey(row),nested=publicKey(record(row)?.pubkey);return direct?[direct]:nested?[nested]:[];}):[];
const ints=(x:unknown):bigint[]|undefined=>Array.isArray(x)&&x.every(v=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0)?x.map(BigInt):undefined;
function balances(value:unknown,resolved:string[]):ReceiptTokenBalance[]|undefined{if(!Array.isArray(value))return [];const out:ReceiptTokenBalance[]=[];for(const row of value){const r=record(row),u=record(r?.uiTokenAmount);const i=Number(r?.accountIndex),amount=u?.amount,decimals=Number(u?.decimals);if(!r||!Number.isInteger(i)||i<0||i>=resolved.length||typeof r.mint!=='string'||typeof amount!=='string'||!/^\d+$/.test(amount)||!Number.isInteger(decimals)||decimals<0)return;out.push({accountIndex:i,resolvedAccountAddress:resolved[i]!,mint:r.mint,...(typeof r.owner==='string'?{owner:r.owner}:{}),rawAmount:BigInt(amount),decimals});}return out;}
const empty=(state:ConfirmedExecutionReceiptState,signature:string):ConfirmedExecutionReceipt=>({state,signature,staticAccountKeys:[],loadedWritableAddresses:[],loadedReadonlyAddresses:[],resolvedAccountKeys:[],preBalancesLamports:[],postBalancesLamports:[],preTokenBalances:[],postTokenBalances:[],outerInstructions:[],innerInstructions:[],logMessages:[]});
export function decodeConfirmedExecutionReceipt(signature:string,value:unknown):ConfirmedExecutionReceipt{if(value===null||value===undefined)return empty('NOT_FOUND_YET',signature);const tx=record(value),transaction=record(tx?.transaction),message=record(transaction?.message),meta=record(tx?.meta);if(!tx||!transaction||!message||!meta)return empty('MALFORMED_RECEIPT',signature);if(tx.version!==undefined&&tx.version!==0&&tx.version!=='legacy')return empty('UNSUPPORTED_VERSION',signature);const staticAccountKeys=keys(message.accountKeys),loaded=record(meta.loadedAddresses),loadedWritableAddresses=keys(loaded?.writable),loadedReadonlyAddresses=keys(loaded?.readonly),resolvedAccountKeys=[...staticAccountKeys,...loadedWritableAddresses,...loadedReadonlyAddresses],preBalancesLamports=ints(meta.preBalances),postBalancesLamports=ints(meta.postBalances),fee=meta.fee;if(!staticAccountKeys.length||!preBalancesLamports||!postBalancesLamports||preBalancesLamports.length!==postBalancesLamports.length||typeof fee!=='number'||!Number.isSafeInteger(fee)||fee<0)return empty('MALFORMED_RECEIPT',signature);const preTokenBalances=balances(meta.preTokenBalances,resolvedAccountKeys),postTokenBalances=balances(meta.postTokenBalances,resolvedAccountKeys);if(!preTokenBalances||!postTokenBalances)return empty('MALFORMED_RECEIPT',signature);const slot=typeof tx.slot==='number'&&Number.isSafeInteger(tx.slot)?BigInt(tx.slot):undefined,blockTime=typeof tx.blockTime==='number'?new Date(tx.blockTime*1000).toISOString():undefined;return{state:meta.err===null||meta.err===undefined?'CONFIRMED_SUCCESS':'CONFIRMED_FAILURE',signature,...(slot===undefined?{}:{slot}),...(blockTime===undefined?{}:{blockTime}),err:meta.err,feeLamports:BigInt(fee),staticAccountKeys,loadedWritableAddresses,loadedReadonlyAddresses,resolvedAccountKeys,preBalancesLamports,postBalancesLamports,preTokenBalances,postTokenBalances,outerInstructions:Array.isArray(message.instructions)?message.instructions:[],innerInstructions:Array.isArray(meta.innerInstructions)?meta.innerInstructions:[],logMessages:Array.isArray(meta.logMessages)?meta.logMessages.filter((x):x is string=>typeof x==='string'):[],messageVersion:tx.version===0?0:'legacy'};}
export async function loadConfirmedExecutionReceipt(connection:ReceiptConnection,signature:string):Promise<ConfirmedExecutionReceipt>{try{return decodeConfirmedExecutionReceipt(signature,await connection.getTransaction(signature,{commitment:'confirmed',maxSupportedTransactionVersion:0}));}catch{return empty('RPC_UNAVAILABLE',signature);}}
