// LPFORGE_PHASE6_MAINNET_MODULE
import type { ExecutionAction } from '../../execution-contracts/src/index.js';
export type Phase6AuthorityLevel='MAINNET_READ_ONLY'|'MAINNET_BUILD_ONLY'|'MAINNET_SIMULATE_ONLY'|'MAINNET_CANARY_OPEN'|'MAINNET_CANARY_MANAGE'|'MAINNET_CANARY_CLOSE';
export type Phase6GateStatus='PASS'|'HOLD'|'BLOCK';
export interface Phase6Authority {phase:'P6';cluster:'mainnet-beta';level:Phase6AuthorityLevel;liveExecution:boolean;canaryOnly:boolean;issuedAt:string;expiresAt:string;ticketId:string;reasonCodes:string[];}
export interface Phase6CanaryTicket {ticketId:string;poolAddress:string;ownerAddress:string;action:ExecutionAction;maxLamports:bigint;issuedAt:string;expiresAt:string;policyHash:string;singlePositionOnly:true;autonomousScaling:false;}
export interface Phase6EvidenceRef {kind:string;id:string;observedAt:string;status:Phase6GateStatus;hash?:string;}
export interface Phase6StageDecision {stage:string;status:Phase6GateStatus;reasonCodes:string[];evidence:Phase6EvidenceRef[];}
export function assertPhase6Authority(a:Phase6Authority,allowed:Phase6AuthorityLevel[],now:string):void{if(a.phase!=='P6'||a.cluster!=='mainnet-beta')throw new Error('LPFORGE_P6_AUTHORITY_CLUSTER');if(!allowed.includes(a.level))throw new Error(`LPFORGE_P6_AUTHORITY_DENIED:${a.level}`);if(Date.parse(a.expiresAt)<=Date.parse(now))throw new Error('LPFORGE_P6_AUTHORITY_EXPIRED');if(!a.canaryOnly)throw new Error('LPFORGE_P6_CANARY_ONLY_REQUIRED');if((a.level==='MAINNET_CANARY_OPEN'||a.level==='MAINNET_CANARY_MANAGE'||a.level==='MAINNET_CANARY_CLOSE')&&!a.liveExecution)throw new Error('LPFORGE_P6_LIVE_AUTHORITY_REQUIRED');}
export function issueReadBuildAuthority(input:{level:'MAINNET_READ_ONLY'|'MAINNET_BUILD_ONLY'|'MAINNET_SIMULATE_ONLY';now:string;ttlMs:number;reasonCodes?:string[]}):Phase6Authority{if(input.ttlMs<1000||input.ttlMs>300000)throw new Error('LPFORGE_P6_AUTHORITY_TTL');return{phase:'P6',cluster:'mainnet-beta',level:input.level,liveExecution:false,canaryOnly:true,issuedAt:input.now,expiresAt:new Date(Date.parse(input.now)+input.ttlMs).toISOString(),ticketId:`p6-${input.level.toLowerCase()}-${Date.parse(input.now)}`,reasonCodes:input.reasonCodes??[]};}
