// LPFORGE_PHASE6_MAINNET_MODULE
import {Connection,PublicKey} from '@solana/web3.js';
import {createLiveMeteoraOpenPool} from '../../meteora-execution/src/index.js';
import {prepareAutonomousMeteoraOpen,type AutonomousOpenPlan} from '../../phase6-autonomous-dispatch/src/index.js';
import {createWeb3SimulationTransport,simulateExecutionTransaction} from '../../simulation-gateway/src/index.js';
import {estimateExecutionFee,assessExecutionCost} from '../../execution-cost/src/index.js';
import {governExecutionRisk} from '../../execution-risk/src/index.js';
import {executeMainnetCanaryOpen} from '../../phase6-canary-runtime/src/index.js';
import {createWeb3SubmissionTransport,observeConfirmation,type SubmissionLedger} from '../../execution-submission/src/index.js';
import type {MainnetSignerBackend} from '../../phase6-mainnet-signer/src/index.js';
import type {Phase1Store} from '../../db/src/index.js';

export interface LiveWorkerConfig {rpcUrl:string;programId:string;maxFeeLamports:bigint;maxFeeFraction:number;simulationFreshnessMs:number;riskPermitTtlMs:number;confirmPollMs:number;confirmAttempts:number;}
export interface LiveWorkerResult {status:'IDLE'|'BLOCKED'|'SUBMITTED'|'RECONCILED'|'UNKNOWN';planId?:string;reasonCodes:string[];transactionSubmitted:boolean;}
function planFields(plan:AutonomousOpenPlan){const intent=plan.planPayload.intent as Record<string,unknown>|undefined;if(!intent)throw new Error('LPFORGE_P6_PLAN_INTENT_MISSING');const capital=BigInt(String(intent.capitalLamports??'')),lower=Number(intent.lowerBinId),upper=Number(intent.upperBinId);if(capital<=0n||!Number.isInteger(lower)||!Number.isInteger(upper))throw new Error('LPFORGE_P6_PLAN_FIELDS_INVALID');return{capital,lower,upper};}
function ledger(store:Phase1Store):SubmissionLedger{return{prepare:v=>store.prepareSubmissionAttempt(v),markSent:(attemptId,signature,submittedAt)=>store.markSubmissionSent(attemptId,signature,submittedAt),markUnknown:(attemptId,at,error)=>store.markSubmissionUnknown(attemptId,at,error),recordConfirmation:v=>store.insertExecutionConfirmation({attemptId:v.attemptId,...(v.signature?{signature:v.signature}:{}),status:v.status,observedAt:v.observedAt,...(v.slot!==undefined?{slot:v.slot}:{}),...(v.error?{error:v.error}:{}),payload:v.payload})};}
function authority(level:'MAINNET_BUILD_SIMULATE'|'MAINNET_CANARY',now:string,ttlMs:number){return{phase:'P5' as const,cluster:'mainnet-beta' as const,level,liveExecution:level==='MAINNET_CANARY',issuedAt:now,expiresAt:new Date(Date.parse(now)+ttlMs).toISOString(),reasonCodes:['P6_AUTONOMOUS_DISPATCH']};}
function ticket(plan:AutonomousOpenPlan,capital:bigint,now:string,ttlMs:number){return{ticketId:`${plan.planId}:open:${Date.parse(now)}`,poolAddress:plan.poolAddress,ownerAddress:plan.ownerAddress,action:'OPEN' as const,maxLamports:capital,maxOpenPositions:1,issuedAt:now,expiresAt:new Date(Date.parse(now)+ttlMs).toISOString(),policyHash:'autonomous-plan-bound',autonomousScaling:false as const};}
/** Executes one already-claimed plan. A caller must claim from storage before calling this function. */
export async function executeAutonomousOpen(input:{store:Phase1Store;plan:AutonomousOpenPlan;signer:MainnetSignerBackend;config:LiveWorkerConfig}):Promise<LiveWorkerResult>{
  const now=new Date().toISOString(),fields=planFields(input.plan);
  try{if(input.signer.publicKeyAddress!==input.plan.ownerAddress)throw new Error('LPFORGE_P6_OWNER_SIGNER_PLAN_MISMATCH');const connection=new Connection(input.config.rpcUrl,'confirmed');const pool=await createLiveMeteoraOpenPool({rpcUrl:input.config.rpcUrl,poolAddress:input.plan.poolAddress,programId:input.config.programId});const prepared=await prepareAutonomousMeteoraOpen({plan:input.plan,pool});
    const simAuthority=authority('MAINNET_BUILD_SIMULATE',now,input.config.riskPermitTtlMs);const simulation=await simulateExecutionTransaction({authority:simAuthority,transactionId:input.plan.transactionId,transaction:prepared.transaction,transport:createWeb3SimulationTransport(connection),simulatedAt:new Date().toISOString(),freshnessMs:input.config.simulationFreshnessMs});await input.store.insertExecutionSimulation({transactionId:input.plan.transactionId,simulatedAt:simulation.simulatedAt,freshUntil:simulation.simulationFreshUntil,ok:simulation.ok,...(simulation.unitsConsumed!==undefined?{unitsConsumed:simulation.unitsConsumed}:{}),logs:simulation.logs,...(simulation.error?{error:simulation.error}:{}),payload:{planId:input.plan.planId,positionAddress:prepared.positionSigner.publicKeyAddress,autonomous:true}});
    const fee=estimateExecutionFee({signatureCount:2,computeUnitLimit:simulation.recommendedComputeUnitLimit??0,computeUnitPriceMicroLamports:0n}),cost=assessExecutionCost(fee,fields.capital,{maxAbsoluteFeeLamports:input.config.maxFeeLamports,maxFeeFractionOfCapital:input.config.maxFeeFraction});const risk=governExecutionRisk({action:'OPEN',planId:input.plan.planId,now:new Date().toISOString(),thesisExpiresAt:input.plan.expiresAt,planExpiresAt:input.plan.expiresAt,simulationOk:simulation.ok,simulationFreshUntil:simulation.simulationFreshUntil,walletTruthConsistent:true,protocolCompatible:true,rpcHealthy:true,referenceDivergenceBps:0,activeBinId:fields.lower,intendedCenterBinId:fields.lower,costApproved:cost.approved,reconciliationRequired:false,globalKillSwitch:false,liquidityCollapse:false},{maxReferenceDivergenceBps:100,maxActiveBinDriftBins:100000,approvalTtlMs:input.config.riskPermitTtlMs,allowEmergencyCostOverride:false});if(risk.decision!=='APPROVE'||!risk.permitId||!risk.expiresAt){await input.store.completeAutonomousPlan({planId:input.plan.planId,state:'BLOCKED',at:new Date().toISOString(),payload:{stage:'SIMULATE_RISK',reasonCodes:risk.reasonCodes,simulationOk:simulation.ok}});return{status:'BLOCKED',planId:input.plan.planId,reasonCodes:risk.reasonCodes,transactionSubmitted:false};}await input.store.insertExecutionRiskPermit({permitId:risk.permitId,planId:input.plan.planId,decision:risk.decision,issuedAt:risk.issuedAt,expiresAt:risk.expiresAt,reasonCodes:risk.reasonCodes,payload:{autonomous:true,simulationFreshUntil:simulation.simulationFreshUntil,feeLamports:fee.totalFeeLamports.toString()}});
    const latest=await connection.getLatestBlockhash('confirmed');prepared.transaction.recentBlockhash=latest.blockhash;prepared.transaction.lastValidBlockHeight=latest.lastValidBlockHeight;prepared.transaction.feePayer=new PublicKey(input.plan.ownerAddress);const signedAt=new Date().toISOString(),openTicket=ticket(input.plan,fields.capital,signedAt,input.config.riskPermitTtlMs),openAuthority={phase:'P6' as const,cluster:'mainnet-beta' as const,level:'MAINNET_CANARY_OPEN' as const,liveExecution:true,canaryOnly:true,issuedAt:signedAt,expiresAt:openTicket.expiresAt,ticketId:openTicket.ticketId,reasonCodes:['P6_AUTONOMOUS_FINAL_REVALIDATION']};const submitted=await executeMainnetCanaryOpen({authority:openAuthority,ticket:openTicket,transactionId:input.plan.transactionId,idempotencyKey:input.plan.idempotencyKey,requiredSignerAddresses:prepared.requiredSignerAddresses,backend:input.signer,auxiliaryBackends:[prepared.positionSigner],envelope:prepared.envelope,phase5RiskDecision:risk,lease:latest,ledger:ledger(input.store),transport:createWeb3SubmissionTransport(connection),submittedAt:signedAt});await input.store.completeAutonomousPlan({planId:input.plan.planId,state:'SUBMITTED',at:signedAt,payload:{signature:submitted.signature,positionAddress:prepared.positionSigner.publicKeyAddress}});
    for(let i=0;i<input.config.confirmAttempts;i++){await new Promise(resolve=>setTimeout(resolve,input.config.confirmPollMs));const confirmation=await observeConfirmation({attemptId:`${input.plan.transactionId}:attempt:1`,record:{transactionId:input.plan.transactionId,signature:submitted.signature,submittedAt:signedAt,blockhash:latest.blockhash,lastValidBlockHeight:latest.lastValidBlockHeight,attempt:1},transport:createWeb3SubmissionTransport(connection),ledger:ledger(input.store),observedAt:new Date().toISOString()});if(confirmation.status==='CONFIRMED'||confirmation.status==='FINALIZED'){const position=await pool.getPosition?.(new PublicKey(prepared.positionSigner.publicKeyAddress));if(!position)throw new Error('LPFORGE_P6_POSITION_RECONCILIATION_MISSING');await input.store.insertExecutionReconciliation({reconciliationId:`${input.plan.planId}:open`,planId:input.plan.planId,observedAt:new Date().toISOString(),status:'MATCH',expected:{owner:input.plan.ownerAddress,pool:input.plan.poolAddress,lowerBinId:fields.lower,upperBinId:fields.upper},actual:{positionAddress:prepared.positionSigner.publicKeyAddress},discrepancies:[],payload:{signature:submitted.signature,autonomous:true}});await input.store.completeAutonomousPlan({planId:input.plan.planId,state:'RECONCILED',at:new Date().toISOString(),payload:{signature:submitted.signature,positionAddress:prepared.positionSigner.publicKeyAddress}});return{status:'RECONCILED',planId:input.plan.planId,reasonCodes:[],transactionSubmitted:true};}if(confirmation.status==='FAILED'||confirmation.status==='EXPIRED'){await input.store.completeAutonomousPlan({planId:input.plan.planId,state:'FAILED',at:new Date().toISOString(),payload:{signature:submitted.signature,confirmation:confirmation.status}});return{status:'BLOCKED',planId:input.plan.planId,reasonCodes:[`P6_CONFIRM_${confirmation.status}`],transactionSubmitted:true};}}
    return{status:'SUBMITTED',planId:input.plan.planId,reasonCodes:['P6_CONFIRMATION_PENDING'],transactionSubmitted:true};
  }catch(error){const reason=error instanceof Error?error.message:'LPFORGE_P6_AUTONOMOUS_UNKNOWN';if(!reason.includes('LPFORGE_SUBMISSION_STATUS_UNKNOWN'))await input.store.completeAutonomousPlan({planId:input.plan.planId,state:'FAILED',at:new Date().toISOString(),payload:{error:reason}});return{status:reason.includes('LPFORGE_SUBMISSION_STATUS_UNKNOWN')?'UNKNOWN':'BLOCKED',planId:input.plan.planId,reasonCodes:[reason],transactionSubmitted:false};}
}
