import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { loadPhase1Config, phase5Capabilities } from '../../../packages/config/src/index.js';
import { errorEnvelope } from '../../../packages/contracts/src/index.js';
import { createMeteoraDataApi } from '../../../packages/data-api/src/index.js';
import { createMeteoraReadAdapter } from '../../../packages/meteora/src/index.js';
import { Logger, requestId } from '../../../packages/observability/src/index.js';
const cfg=loadPhase1Config(); const log=new Logger('api',cfg.logLevel); const api=createMeteoraDataApi({baseUrl:cfg.meteoraDataApiUrl,maxRps:cfg.dataApiMaxRps,timeoutMs:cfg.httpTimeoutMs}); const adapter=cfg.dataMode==='LIVE_READ_ONLY'?createMeteoraReadAdapter({rpcUrl:cfg.solanaRpcHttpUrl,cluster:cfg.cluster,programId:cfg.programId,expectedSdkVersion:cfg.expectedSdkVersion,rpcTimeoutMs:cfg.rpcTimeoutMs}):undefined;
function send(res:ServerResponse,status:number,body:unknown){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(body,(_,v)=>typeof v==='bigint'?v.toString():v));}
async function handler(req:IncomingMessage,res:ServerResponse){const id=requestId();try{const url=new URL(req.url??'/',`http://localhost:${cfg.port}`);if(req.method!=='GET'){send(res,405,errorEnvelope('LPFORGE_PHASE5_EXECUTION_API_DISABLED','Phase 5 execution is not exposed through the inspection HTTP API.',id));return;}if(url.pathname==='/health/live'){send(res,200,{status:'UP',phase:'P5',liveSigning:false});return;}if(url.pathname==='/health/ready'){const compat=adapter?await adapter.verifyCompatibility(cfg.smokePoolAddress):{state:'VERIFIED',details:{fixture:true}};send(res,compat.state==='VERIFIED'?200:503,{status:compat.state==='VERIFIED'?'UP':'DOWN',phase:'P5',liveSigning:false,protocol:compat});return;}if(url.pathname==='/api/v1/capabilities'||url.pathname==='/api/v1/research/capabilities'){send(res,200,phase5Capabilities());return;}if(url.pathname==='/api/v1/data-api/pools'){const page=Number(url.searchParams.get('page')??1),pageSize=Number(url.searchParams.get('page_size')??100);send(res,200,await api.listPools(page,pageSize,url.searchParams.get('query')??undefined));return;}if(url.pathname==='/api/v1/inspect/pool'){if(!adapter){send(res,409,errorEnvelope('LPFORGE_LIVE_READ_REQUIRED','Set LPFORGE_DATA_MODE=LIVE_READ_ONLY.',id));return;}const address=url.searchParams.get('address');if(!address){send(res,400,errorEnvelope('LPFORGE_ADDRESS_REQUIRED','address query parameter is required.',id));return;}send(res,200,{pool:await adapter.getPool(address),activeBin:await adapter.getActiveBin(address),bins:await adapter.getBinsAroundActive(address,10)});return;}if(url.pathname==='/api/v1/inspect/position'){if(!adapter){send(res,409,errorEnvelope('LPFORGE_LIVE_READ_REQUIRED','Set LPFORGE_DATA_MODE=LIVE_READ_ONLY.',id));return;}const pool=url.searchParams.get('pool'),address=url.searchParams.get('address');if(!pool||!address){send(res,400,errorEnvelope('LPFORGE_POSITION_PARAMS_REQUIRED','pool and address are required.',id));return;}send(res,200,await adapter.getPositionV2(pool,address));return;}send(res,404,errorEnvelope('LPFORGE_NOT_FOUND','Not found',id));}catch(error){log.error('request_failed',{requestId:id,error:error instanceof Error?error.message:String(error)});send(res,500,errorEnvelope('LPFORGE_INTERNAL','Request failed',id));}}
createServer((req,res)=>{void handler(req,res);}).listen(cfg.port,()=>log.info('api_started',{port:cfg.port,phase:'P5',liveSigning:false}));
