import { loadPhase1Config } from '../../../packages/config/src/index.js';
import { createMeteoraDataApi } from '../../../packages/data-api/src/index.js';
import { createPostgresStore, type Phase1Store } from '../../../packages/db/src/index.js';
import { createMeteoraReadAdapter, createSolanaRpcClient, scanAddressTransactions } from '../../../packages/meteora/src/index.js';
import { Logger } from '../../../packages/observability/src/index.js';
import { evaluateOperationalCycle, type OperationalCycleResult } from '../../../packages/operational-runtime/src/index.js';
import { createJupiterSwapQuoteProvider, loadAutonomousEntryPolicy } from '../../../packages/phase6-swap-quote/src/index.js';
import { fixtureBins, fixtureDataApiPool, fixturePool, fixtureSwaps } from '../../../packages/test-fixtures/src/index.js';

function json(v:unknown){return JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x,2);}
async function persistResult(store:Phase1Store,r:OperationalCycleResult){
  await store.insertPoolAssessment({...r.poolAssessment,poolAddress:r.poolAssessment.pool});
  if(r.shadow){await store.insertShadowRecommendation({recommendationId:r.shadow.recommendationId,poolAddress:r.poolAddress,decisionAt:r.shadow.decisionAt,expiresAt:r.shadow.expiresAt,state:r.shadow.state,noTrade:r.shadow.noTrade,marketContextHash:r.shadow.marketContextHash,candidateCount:r.shadow.candidateCount,ranking:r.shadow.ranking as unknown as Record<string,unknown>,economics:r.shadow.economics as unknown as Record<string,unknown>,reasonCodes:r.shadow.reasonCodes,payload:r.shadow as unknown as Record<string,unknown>});await store.insertRegimeAssessment({poolAddress:r.poolAddress,decisionAt:r.shadow.decisionAt,primaryRegime:r.shadow.regime.primary,probabilities:r.shadow.regime.probabilities,confidence:r.shadow.regime.confidence,stability:r.shadow.regime.stability,transitionRisk:r.shadow.regime.transitionRisk,evidence:{reasonCodes:r.shadow.regime.reasonCodes,rawScores:r.shadow.regime.rawScores,features:r.shadow.regime.evidence},recommendationId:r.shadow.recommendationId});if(r.shadow.thesis)await store.insertLpThesis({thesisId:r.shadow.thesis.thesisId,recommendationId:r.shadow.recommendationId,poolAddress:r.poolAddress,observedAt:r.shadow.thesis.observedAt,expiresAt:r.shadow.thesis.expiresAt,selectedCandidateId:r.shadow.thesis.selectedCandidate.id,thesis:r.shadow.thesis as unknown as Record<string,unknown>});}
  if(r.entry&&r.shadow?.thesis){const entryId=`entry-${r.cycleId}`;await store.insertEntryEvaluation({entryEvaluationId:entryId,thesisId:r.shadow.thesis.thesisId,poolAddress:r.poolAddress,observedAt:r.entry.observedAt,expiresAt:r.entry.expiresAt,decision:r.entry.decision,readinessScore:r.entry.readinessScore,confidence:r.entry.confidence,reasonCodes:r.entry.reasonCodes,payload:r.entry as unknown as Record<string,unknown>});}
  if(r.risk){await store.insertRiskDecision({riskDecisionId:`risk-${r.cycleId}`,observedAt:r.observedAt,expiresAt:r.risk.expiresAt,scope:r.risk.scope,decision:r.risk.decision,reasonCodes:r.risk.reasonCodes,payload:r.risk as unknown as Record<string,unknown>});}
  if(r.allocation){const a=r.allocation.allocations[0];if(a)await store.insertCapitalAllocation({allocationId:`allocation-${r.cycleId}`,observedAt:r.observedAt,poolAddress:r.poolAddress,requested:a.requested,allocated:a.allocated,payload:r.allocation as unknown as Record<string,unknown>});}
  if(r.plan){await store.insertExecutionIntent({intentId:r.plan.intent.intentId,idempotencyKey:r.plan.intent.idempotencyKey,action:r.plan.intent.action,poolAddress:r.plan.intent.poolAddress,ownerAddress:r.plan.intent.ownerAddress,...(r.plan.intent.positionAddress?{positionAddress:r.plan.intent.positionAddress}:{}),thesisId:r.plan.intent.thesisId,observedAt:r.plan.intent.observedAt,expiresAt:r.plan.intent.expiresAt,payload:r.plan.intent.payload});await store.insertTransactionPlan({planId:r.plan.planId,intentId:r.plan.intent.intentId,cluster:r.plan.cluster,state:r.plan.state,createdAt:r.plan.createdAt,expiresAt:r.plan.expiresAt,payload:{reasonCodes:r.plan.reasonCodes,authority:'BUILD_ONLY'},steps:r.plan.transactions.map(t=>({transactionId:t.transactionId,sequence:t.sequence,kind:t.kind,state:t.state,requiredSignerAddresses:t.requiredSignerAddresses,metadata:t.metadata}))});}
  await store.insertOperationalCycle({cycleId:r.cycleId,poolAddress:r.poolAddress,observedAt:r.observedAt,phase3Status:r.phase3Status,phase4Status:r.phase4Status,phase5Status:r.phase5Status,...(r.shadow?{recommendationId:r.shadow.recommendationId}:{}),...(r.shadow?.thesis?{thesisId:r.shadow.thesis.thesisId}:{}),...(r.entry?{entryDecision:r.entry.decision}:{}),...(r.plan?{planId:r.plan.planId}:{}),payload:{reasonCodes:r.reasonCodes,evidence:r.evidence,liveSigning:false,submissionPerformed:false}});
}
async function liveOnce(){
  const cfg=loadPhase1Config(); if(cfg.dataMode!=='LIVE_READ_ONLY')throw new Error('LPFORGE_OPERATOR_REQUIRES_LIVE_READ_ONLY'); if(!cfg.smokePoolAddress)throw new Error('LPFORGE_CONFIG_REQUIRED:LPFORGE_SMOKE_POOL_ADDRESS');
  const log=new Logger('operator',cfg.logLevel);const store=await createPostgresStore(cfg.databaseUrl);const cycleStartedAt=new Date().toISOString();
  try{
    let eventDecodeWarnings=0;const adapter=createMeteoraReadAdapter({rpcUrl:cfg.solanaRpcHttpUrl,cluster:cfg.cluster,programId:cfg.programId,expectedSdkVersion:cfg.expectedSdkVersion,rpcTimeoutMs:cfg.rpcTimeoutMs,onEventDecodeWarning:warning=>{eventDecodeWarnings++;log.warn('meteora_event_decode_quarantined',{...warning});}});const compat=await adapter.verifyCompatibility(cfg.smokePoolAddress);await store.insertCompatibility(compat);if(compat.state!=='VERIFIED')throw new Error('LPFORGE_PROTOCOL_COMPATIBILITY_HOLD');
    const [pool,bins]=await Promise.all([adapter.getPool(cfg.smokePoolAddress),adapter.getBinsAroundActive(cfg.smokePoolAddress,35)]);await store.insertPoolSnapshot(pool);await store.insertBins(bins);
    const api=createMeteoraDataApi({baseUrl:cfg.meteoraDataApiUrl,maxRps:cfg.dataApiMaxRps,timeoutMs:cfg.httpTimeoutMs});const [apiPool,ohlcv]=await Promise.all([api.getPool(cfg.smokePoolAddress),api.getOhlcv(cfg.smokePoolAddress,{timeframe:'5m'})]);const apiObservedAt=new Date().toISOString();await store.insertDataApiPool(apiPool as Record<string,unknown>,apiObservedAt);await store.insertOhlcv(cfg.smokePoolAddress,'5m',ohlcv.data as unknown as Array<Record<string,unknown>>,apiObservedAt,'METEORA_API');
    const rpc=createSolanaRpcClient({url:cfg.solanaRpcHttpUrl,timeoutMs:cfg.rpcTimeoutMs,minIntervalMs:cfg.rpcMinIntervalMs,maxRetries:cfg.rpcMaxRetries,retryBaseDelayMs:cfg.rpcRetryBaseDelayMs,retryMaxDelayMs:cfg.rpcRetryMaxDelayMs});const transactions=await scanAddressTransactions({rpc,address:cfg.smokePoolAddress,limit:cfg.eventBackfillLimit,programId:cfg.programId});let decodedSwapEvents=0;for(const tx of transactions)for(const event of await adapter.decodeEvents(cfg.smokePoolAddress,tx.signature,tx.slot,tx.blockTime,tx.logs,tx.cpiInstructionData))if(event.pool===cfg.smokePoolAddress){decodedSwapEvents++;await store.insertSwapEvent(event);}log.info('meteora_ingestion_summary',{transactionsScanned:transactions.length,decodedSwapEvents,eventDecodeWarnings});
    const since=new Date(Date.now()-4*60*60*1000).toISOString();const history=await store.loadOperationalHistory(cfg.smokePoolAddress,since,2000);const decisionAt=new Date().toISOString();const priorRegimeAssessments=await store.loadRegimeAssessmentHistory(cfg.smokePoolAddress,decisionAt,120);const walletCapital=Number(process.env.LPFORGE_SHADOW_WALLET_CAPITAL??'1');if(!(walletCapital>0))throw new Error('LPFORGE_OPERATOR_INVALID_SHADOW_CAPITAL');
    const entryPolicy=loadAutonomousEntryPolicy(process.env.LPFORGE_AUTONOMOUS_ENTRY_POLICY_PATH??'policies/autonomous-entry-policy.json');const swapQuoteProvider=entryPolicy.status==='ENABLED'?createJupiterSwapQuoteProvider({policy:entryPolicy.swapQuote,...(process.env.LPFORGE_JUPITER_API_KEY?{apiKey:process.env.LPFORGE_JUPITER_API_KEY}:{})}):undefined;const result=await evaluateOperationalCycle({observedAt:decisionAt,pool,bins,dataApiPool:apiPool,history,priorRegimeAssessments,protocolCompatible:true,walletCapital,...(swapQuoteProvider?{swapQuoteProvider}:{}),...(process.env.LPFORGE_OPERATOR_OWNER_ADDRESS?{ownerAddress:process.env.LPFORGE_OPERATOR_OWNER_ADDRESS}:{}),...(process.env.LPFORGE_PREPARE_POSITION_ADDRESS?{replacementPositionAddress:process.env.LPFORGE_PREPARE_POSITION_ADDRESS}:{})});await persistResult(store,result);await store.upsertRuntimeHeartbeat({runtimeId:'lpforge-live-shadow',poolAddress:cfg.smokePoolAddress,observedAt:decisionAt,status:'PASS',cycleId:result.cycleId,payload:{cycleStartedAt,phase3Status:result.phase3Status,phase4Status:result.phase4Status,phase5Status:result.phase5Status}});log.info('operational_cycle_complete',{cycleId:result.cycleId,cycleStartedAt,decisionAt,phase3:result.phase3Status,phase4:result.phase4Status,phase5:result.phase5Status,swapQuote:result.swapQuote?.status??'NOT_REQUIRED',signing:false,submission:false});if((process.env.LPFORGE_OPERATOR_MACHINE_SUMMARY??'false').toLowerCase()==='true')console.log(JSON.stringify({event:'lpforge_operator_machine_summary',cycleId:result.cycleId,cycleStartedAt,decisionAt,phase3:result.phase3Status,phase4:result.phase4Status,phase5:result.phase5Status,swapQuote:result.swapQuote?.status??'NOT_REQUIRED',transactionsScanned:transactions.length,decodedSwapEvents,eventDecodeWarnings,signing:false,submission:false}));console.log(json(result));return result;
  }catch(error){await store.upsertRuntimeHeartbeat({runtimeId:'lpforge-live-shadow',poolAddress:cfg.smokePoolAddress,observedAt:new Date().toISOString(),status:'FAILED',payload:{cycleStartedAt,error:error instanceof Error?error.message:String(error)}});throw error;}finally{await store.close();}
}
async function fixtureOnce(){const observedAt='2026-08-12T12:00:00Z';const minute=(i:number)=>new Date(Date.parse(observedAt)-(180-i)*60000).toISOString();const market=Array.from({length:181},(_,i)=>({observedAt:minute(i),price:100+Math.sin(i/12)*.3,activeBinId:fixturePool.activeBinId+Math.round(Math.sin(i/10)*3),volume:100,feeValue:.01,twoWayRatio:.8,localLiquidity:200000}));const activeBins=market.map(x=>({observedAt:x.observedAt,activeBinId:x.activeBinId}));const binFrames=[40,80,120,160].map(i=>({observedAt:minute(i),activeBinId:activeBins[i]!.activeBinId,bins:fixtureBins.map(b=>({binId:b.binId,price:b.price,amountX:b.amountX,amountY:b.amountY,...(b.liquiditySupply?{liquiditySupply:b.liquiditySupply}:{})}))}));const pool={...fixturePool,stamp:{...fixturePool.stamp,observedAt}};const result=await evaluateOperationalCycle({observedAt,pool,bins:fixtureBins.map(b=>({...b,stamp:{...b.stamp,observedAt}})),dataApiPool:fixtureDataApiPool,history:{marketObservations:market,activeBins,binFrames,swapEvents:fixtureSwaps.map((e,i)=>({...e,stamp:{...e.stamp,observedAt:minute(100+i)}}))},protocolCompatible:true,walletCapital:1});console.log(json(result));return result;}
async function liveRun(){const interval=Math.max(5000,Number(process.env.COLLECT_INTERVAL_MS??30000));for(;;){const started=Date.now();try{await liveOnce();}catch(e){console.error(e);}const wait=Math.max(1000,interval-(Date.now()-started));await new Promise(r=>setTimeout(r,wait));}}
const cmd=process.argv[2]??'fixture-once';if(cmd==='fixture-once')await fixtureOnce();else if(cmd==='live-once')await liveOnce();else if(cmd==='live-run')await liveRun();else throw new Error('Usage: operator fixture-once|live-once|live-run');
