import type { DeepScreenResult } from '../../pool-deep-screen/src/index.js';
import type { StrategyEvaluation, DiscoveryStrategy } from '../../discovery-strategy-evaluation/src/index.js';
export type OutcomeClass='TRADED'|'NO_TRADE_COUNTERFACTUAL'|'CONTROL_COUNTERFACTUAL';
export type EventAttribution='MODEL_PREDICTION_ERROR'|'DATA_FAILURE'|'EXECUTION_FAILURE'|'STRUCTURAL_BREAK'|'EXOGENOUS_EVENT'|'NORMAL';
export interface PredictionRecord {predictionId:string;poolAddress:string;observedAt:string;policyVersion:string;modelVersion:string;selectionContext:Record<string,unknown>;deep:DeepScreenResult;strategy:StrategyEvaluation;selectedAction:DiscoveryStrategy|'NO_TRADE';cohort:string;episodeKey:string;}
export interface OutcomeRecord {predictionId:string;poolAddress:string;observedAt:string;horizonMinutes:number;outcomeClass:OutcomeClass;realizedNetValue?:number;realizedFees?:number;realizedDirectionalPnl?:number;rangeSurvived?:boolean;inventoryConversion?:number;eventAttribution:EventAttribution;structuralEventCodes:string[];}
export interface CalibrationSummary {samples:number;independentEpisodes:number;brierProfit:number|null;survivalBrier:number|null;netValueMae:number|null;meanBias:number|null;allOutcomeNet:number;modelCalibrationNet:number;}
export interface ReputationSummary {key:string;samples:number;episodes:number;meanNet:number;positiveRate:number;meanFees:number;meanDirectional:number;confidence:number;}
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const hash=(s:string)=>{let h=0;for(let i=0;i<s.length;i++)h=(Math.imul(h,31)+s.charCodeAt(i))|0;return(h>>>0).toString(16)};
export function episodeKey(input:{poolAddress:string;observedAt:string;regime?:string;episodeMinutes?:number}){const m=input.episodeMinutes??60;const bucket=Math.floor(Date.parse(input.observedAt)/(m*60000));return`${input.poolAddress}:${input.regime??'UNKNOWN'}:${bucket}`}
export function makePrediction(input:{poolAddress:string;observedAt:string;policyVersion:string;deep:DeepScreenResult;strategy:StrategyEvaluation;selectionContext:Record<string,unknown>;cohort:string;regime?:string}):PredictionRecord{
 const episode=episodeKey({poolAddress:input.poolAddress,observedAt:input.observedAt,...(input.regime?{regime:input.regime}:{})});const predictionId=`pred-${hash(`${input.poolAddress}:${input.observedAt}:${input.policyVersion}:${input.strategy.modelVersion}`)}`;return{predictionId,poolAddress:input.poolAddress,observedAt:input.observedAt,policyVersion:input.policyVersion,modelVersion:input.strategy.modelVersion,selectionContext:input.selectionContext,deep:input.deep,strategy:input.strategy,selectedAction:input.strategy.winner,cohort:input.cohort,episodeKey:episode};
}
export function calibratePredictions(predictions:PredictionRecord[],outcomes:OutcomeRecord[]):CalibrationSummary{
 const om=new Map(outcomes.map(x=>[`${x.predictionId}:${x.horizonMinutes}`,x]));const rows=predictions.map(p=>({p,o:om.get(`${p.predictionId}:120`)})).filter((x):x is {p:PredictionRecord;o:OutcomeRecord}=>Boolean(x.o));const profitErrors:number[]=[],survivalErrors:number[]=[],mae:number[]=[],bias:number[]=[];let all=0,model=0;
 for(const {p,o} of rows){const candidate=p.strategy.strategies.find(x=>x.strategy===p.selectedAction)??p.strategy.strategies[0];if(!candidate)continue;if(o.realizedNetValue!==undefined){const actual=o.realizedNetValue>0?1:0;profitErrors.push((candidate.pProfit-actual)**2);mae.push(Math.abs(candidate.expectedNetValue-o.realizedNetValue));bias.push(candidate.expectedNetValue-o.realizedNetValue);all+=o.realizedNetValue;if(o.eventAttribution!=='STRUCTURAL_BREAK'&&o.eventAttribution!=='EXOGENOUS_EVENT')model+=o.realizedNetValue;}if(o.rangeSurvived!==undefined){const a=o.rangeSurvived?1:0;survivalErrors.push((candidate.survival2h-a)**2);}}
 return{samples:rows.length,independentEpisodes:new Set(rows.map(x=>x.p.episodeKey)).size,brierProfit:profitErrors.length?mean(profitErrors):null,survivalBrier:survivalErrors.length?mean(survivalErrors):null,netValueMae:mae.length?mean(mae):null,meanBias:bias.length?mean(bias):null,allOutcomeNet:all,modelCalibrationNet:model};
}
export function buildReputation(predictions:PredictionRecord[],outcomes:OutcomeRecord[],keyFn:(p:PredictionRecord)=>string):ReputationSummary[]{
 const pm=new Map(predictions.map(p=>[p.predictionId,p]));const groups=new Map<string,Array<{p:PredictionRecord;o:OutcomeRecord}>>();for(const o of outcomes){const p=pm.get(o.predictionId);if(!p||o.realizedNetValue===undefined)continue;const k=keyFn(p),a=groups.get(k)??[];a.push({p,o});groups.set(k,a)}
 return[...groups].map(([key,rows])=>{const nets=rows.map(x=>x.o.realizedNetValue??0),fees=rows.map(x=>x.o.realizedFees??0),dir=rows.map(x=>x.o.realizedDirectionalPnl??0),episodes=new Set(rows.map(x=>x.p.episodeKey)).size;return{key,samples:rows.length,episodes,meanNet:mean(nets),positiveRate:nets.filter(x=>x>0).length/Math.max(1,nets.length),meanFees:mean(fees),meanDirectional:mean(dir),confidence:Math.min(1,episodes/30)};}).sort((a,b)=>b.confidence-a.confidence||b.meanNet-a.meanNet);
}
export interface BaselineCandidate {poolAddress:string;feeTvl:number;feePersistence:number;liquidity:number;toxicity:number;eligible:boolean;}
export function selectBaselines(candidates:BaselineCandidate[],seed='baseline'){const eligible=candidates.filter(x=>x.eligible);const random=[...eligible].sort((a,b)=>hash(seed+a.poolAddress).localeCompare(hash(seed+b.poolAddress)))[0]?.poolAddress??null;const fee=[...eligible].sort((a,b)=>b.feeTvl-a.feeTvl)[0]?.poolAddress??null;const persistent=[...eligible].sort((a,b)=>(b.feeTvl*b.feePersistence)-(a.feeTvl*a.feePersistence))[0]?.poolAddress??null;const simple=[...eligible].sort((a,b)=>((b.feeTvl*b.feePersistence*b.liquidity*(1-b.toxicity))- (a.feeTvl*a.feePersistence*a.liquidity*(1-a.toxicity))))[0]?.poolAddress??null;return{RANDOM_ELIGIBLE:random,HIGHEST_FEE_TVL:fee,HIGHEST_PERSISTENT_FEE_TVL:persistent,SIMPLE_FEE_LIQUIDITY_TOXICITY:simple};}
export function purgeEmbargo<T extends {observedAt:string}>(train:T[],testStart:string,testEnd:string,maxHorizonMinutes:number){const embargo=maxHorizonMinutes*60000,start=Date.parse(testStart)-embargo,end=Date.parse(testEnd)+embargo;return train.filter(x=>{const t=Date.parse(x.observedAt);return t<start||t>end})}
