// LPFORGE_PHASE6_MAINNET_MODULE
import fs from 'node:fs';

export interface JupiterRouteFee {feeMint:string;feeAmount:bigint;}
export interface JupiterSwapQuote {inputMint:string;outputMint:string;inAmount:bigint;outAmount:bigint;otherAmountThreshold:bigint;slippageBps:number;priceImpactBps:number;contextSlot?:number;routeFees:JupiterRouteFee[];quotedAt:string;}
export interface Phase6SwapQuotePolicy {provider:'JUPITER_METIS';endpoint:string;slippageBps:number;maxPriceImpactBps:number;maxInputFeeBps:number;timeoutMs:number;}
export interface AutonomousEntryPolicy {schemaVersion:1;policyId:string;status:'ENABLED'|'DISABLED';swapQuote:Phase6SwapQuotePolicy;}
export interface SwapQuoteAssessment {status:'APPROVED'|'REJECTED'|'UNAVAILABLE';quote?:JupiterSwapQuote;reasonCodes:string[];}
type FetchLike=(input:string,init?:{headers?:Record<string,string>;signal?:AbortSignal})=>Promise<{ok:boolean;status:number;json():Promise<unknown>}>;
function finiteInteger(value:unknown,label:string,min:number,max:number){const n=Number(value);if(!Number.isInteger(n)||n<min||n>max)throw new Error(`LPFORGE_SWAP_POLICY_${label}`);return n;}
function decimalPercentToBps(value:unknown):number{const text=String(value??'0');if(!/^\d+(?:\.\d+)?$/.test(text))throw new Error('LPFORGE_SWAP_QUOTE_PRICE_IMPACT_INVALID');const [whole,fraction='']=text.split('.');const scaled=BigInt(whole??'0')*1_000_000n+BigInt((fraction??'').padEnd(6,'0').slice(0,6));return Number((scaled*100n+999_999n)/1_000_000n);}
function rawAmount(value:unknown,label:string):bigint{const text=String(value??'');if(!/^\d+$/.test(text))throw new Error(`LPFORGE_SWAP_QUOTE_${label}_INVALID`);return BigInt(text);}
function asText(value:unknown,label:string):string{const text=String(value??'').trim();if(!text)throw new Error(`LPFORGE_SWAP_QUOTE_${label}_MISSING`);return text;}
function requireHttps(url:string){const parsed=new URL(url);if(parsed.protocol!=='https:')throw new Error('LPFORGE_SWAP_QUOTE_ENDPOINT_HTTPS_REQUIRED');return parsed;}
export function loadAutonomousEntryPolicy(path='policies/autonomous-entry-policy.json'):AutonomousEntryPolicy{const value=JSON.parse(fs.readFileSync(path,'utf8')) as Partial<AutonomousEntryPolicy>;if(value.schemaVersion!==1||typeof value.policyId!=='string'||!value.policyId||!(value.status==='ENABLED'||value.status==='DISABLED')||!value.swapQuote)throw new Error('LPFORGE_AUTONOMOUS_ENTRY_POLICY_INVALID');const q=value.swapQuote;const endpoint=requireHttps(String(q.endpoint??'')).toString();if(q.provider!=='JUPITER_METIS')throw new Error('LPFORGE_SWAP_POLICY_PROVIDER');return{schemaVersion:1,policyId:value.policyId,status:value.status,swapQuote:{provider:'JUPITER_METIS',endpoint,slippageBps:finiteInteger(q.slippageBps,'SLIPPAGE_BPS',1,10_000),maxPriceImpactBps:finiteInteger(q.maxPriceImpactBps,'MAX_PRICE_IMPACT_BPS',0,10_000),maxInputFeeBps:finiteInteger(q.maxInputFeeBps,'MAX_INPUT_FEE_BPS',0,10_000),timeoutMs:finiteInteger(q.timeoutMs,'TIMEOUT_MS',100,60_000)}};}
export async function readJupiterMetisQuote(input:{policy:Phase6SwapQuotePolicy;inputMint:string;outputMint:string;amount:bigint;apiKey?:string;fetcher?:FetchLike}):Promise<JupiterSwapQuote>{const endpoint=requireHttps(input.policy.endpoint);if(input.amount<1n)throw new Error('LPFORGE_SWAP_QUOTE_AMOUNT_INVALID');endpoint.searchParams.set('inputMint',input.inputMint);endpoint.searchParams.set('outputMint',input.outputMint);endpoint.searchParams.set('amount',input.amount.toString());endpoint.searchParams.set('slippageBps',String(input.policy.slippageBps));const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),input.policy.timeoutMs);try{const response=await (input.fetcher??fetch)(endpoint.toString(),{headers:{...(input.apiKey?{'x-api-key':input.apiKey}:{}),accept:'application/json'},signal:controller.signal});if(!response.ok)throw new Error(`LPFORGE_SWAP_QUOTE_HTTP_${response.status}`);const raw=await response.json() as Record<string,unknown>;const routePlan=Array.isArray(raw.routePlan)?raw.routePlan:[];const routeFees:JupiterRouteFee[]=[];for(const row of routePlan){const swapInfo=(row as Record<string,unknown>).swapInfo as Record<string,unknown>|undefined;if(swapInfo&&swapInfo.feeAmount!==undefined)routeFees.push({feeMint:asText(swapInfo.feeMint,'FEE_MINT'),feeAmount:rawAmount(swapInfo.feeAmount,'FEE_AMOUNT')});}return{inputMint:asText(raw.inputMint,'INPUT_MINT'),outputMint:asText(raw.outputMint,'OUTPUT_MINT'),inAmount:rawAmount(raw.inAmount,'IN_AMOUNT'),outAmount:rawAmount(raw.outAmount,'OUT_AMOUNT'),otherAmountThreshold:rawAmount(raw.otherAmountThreshold,'OTHER_AMOUNT_THRESHOLD'),slippageBps:finiteInteger(raw.slippageBps,'QUOTE_SLIPPAGE_BPS',0,10_000),priceImpactBps:decimalPercentToBps(raw.priceImpactPct),...(raw.contextSlot===undefined?{}:{contextSlot:finiteInteger(raw.contextSlot,'CONTEXT_SLOT',0,Number.MAX_SAFE_INTEGER)}),routeFees,quotedAt:new Date().toISOString()};}finally{clearTimeout(timer);}}
export function assessSwapQuote(input:{quote:JupiterSwapQuote;policy:Phase6SwapQuotePolicy;inputMint:string;outputMint:string;inputAmount:bigint;requiredOutputAmount:bigint}):SwapQuoteAssessment{const q=input.quote,reasons:string[]=[];if(q.inputMint!==input.inputMint||q.outputMint!==input.outputMint)reasons.push('P6_SWAP_QUOTE_MINT_MISMATCH');if(q.inAmount!==input.inputAmount)reasons.push('P6_SWAP_QUOTE_INPUT_AMOUNT_MISMATCH');if(q.slippageBps!==input.policy.slippageBps)reasons.push('P6_SWAP_QUOTE_SLIPPAGE_MISMATCH');if(q.priceImpactBps>input.policy.maxPriceImpactBps)reasons.push('P6_SWAP_QUOTE_PRICE_IMPACT_EXCEEDED');if(q.otherAmountThreshold<input.requiredOutputAmount)reasons.push('P6_SWAP_QUOTE_MIN_OUTPUT_INSUFFICIENT');const inputFee=q.routeFees.filter(f=>f.feeMint===input.inputMint).reduce((sum,f)=>sum+f.feeAmount,0n);if(input.inputAmount>0n&&inputFee*10_000n>input.inputAmount*BigInt(input.policy.maxInputFeeBps))reasons.push('P6_SWAP_QUOTE_INPUT_FEE_EXCEEDED');return{status:reasons.length?'REJECTED':'APPROVED',quote:q,reasonCodes:reasons.length?reasons:['P6_SWAP_QUOTE_APPROVED']};}
export function unavailableSwapQuote(reason:string):SwapQuoteAssessment{return{status:'UNAVAILABLE',reasonCodes:[reason]};}
export function createJupiterSwapQuoteProvider(input:{policy:Phase6SwapQuotePolicy;apiKey?:string;fetcher?:FetchLike}){return{async quote(request:{inputMint:string;outputMint:string;inputAmount:bigint;requiredOutputAmount:bigint}):Promise<SwapQuoteAssessment>{try{const quote=await readJupiterMetisQuote({policy:input.policy,inputMint:request.inputMint,outputMint:request.outputMint,amount:request.inputAmount,...(input.apiKey?{apiKey:input.apiKey}:{}),...(input.fetcher?{fetcher:input.fetcher}:{})});return assessSwapQuote({quote,policy:input.policy,...request});}catch(error){return unavailableSwapQuote(error instanceof Error?error.message:'P6_SWAP_QUOTE_UNAVAILABLE');}}};}
