export interface ReshapeCandidate {id:string;strategy:string;orientation:string;lowerBinId:number;upperBinId:number;expectedGrossForwardValue:number;implementationCost:number;tailRiskCharge:number;survivalProbability:number;uncertainty:number;}
export interface CurrentShape {strategy:string;orientation:string;lowerBinId:number;upperBinId:number;holdForwardEv:number;}
export interface ReshapeAssessment {decision:'RESHAPE'|'NO_RESHAPE';selectedCandidateId?:string;incrementalValue:number;reasonCodes:string[];eligibleCandidates:Array<ReshapeCandidate&{netForwardEv:number}>;}
export function assessReshape(input:{current:CurrentShape;candidates:ReshapeCandidate[];thesisValid:boolean;minimumIncrementalValue?:number;}):ReshapeAssessment{
 const min=input.minimumIncrementalValue??.0001;if(!input.thesisValid)return{decision:'NO_RESHAPE',incrementalValue:0,reasonCodes:['RESHAPE_REQUIRES_VALID_THESIS'],eligibleCandidates:[]};
 const eligible=input.candidates.filter((c)=>c.strategy===input.current.strategy&&c.orientation===input.current.orientation&&c.lowerBinId<=c.upperBinId).map((c)=>({...c,netForwardEv:c.expectedGrossForwardValue-c.implementationCost-c.tailRiskCharge})).sort((a,b)=>b.netForwardEv-a.netForwardEv||b.survivalProbability-a.survivalProbability||a.id.localeCompare(b.id));
 const best=eligible[0];if(!best)return{decision:'NO_RESHAPE',incrementalValue:0,reasonCodes:['RESHAPE_NO_THESIS_PRESERVING_CANDIDATE'],eligibleCandidates:eligible};const incremental=best.netForwardEv-input.current.holdForwardEv;
 if(incremental<=min)return{decision:'NO_RESHAPE',incrementalValue:incremental,reasonCodes:['RESHAPE_COST_NOT_RECOVERED'],eligibleCandidates:eligible};if(best.survivalProbability<.45)return{decision:'NO_RESHAPE',incrementalValue:incremental,reasonCodes:['RESHAPE_SURVIVAL_TOO_LOW'],eligibleCandidates:eligible};if(best.uncertainty>.75)return{decision:'NO_RESHAPE',incrementalValue:incremental,reasonCodes:['RESHAPE_UNCERTAINTY_TOO_HIGH'],eligibleCandidates:eligible};return{decision:'RESHAPE',selectedCandidateId:best.id,incrementalValue:incremental,reasonCodes:['RESHAPE_INCREMENTAL_EV_POSITIVE'],eligibleCandidates:eligible};
}
