// LPFORGE_PHASE7_RUNTIME_INTEGRATION_MODULE
import type {Phase1Store} from '../../db/src/index.js';
import {planPhase7DaemonTick} from '../../phase7-daemon/src/index.js';
export interface Phase7PersistedControlState {authorityMode:'OBSERVE_ONLY'|'LIMITED_LIVE'|'PRODUCTION';healthStatus:'HEALTHY'|'DEGRADED'|'CRITICAL';newEconomicActionAllowed:boolean;}
export interface Phase7RecoveryRuntimeResult {runtimeId:string;instanceId:string;cycleKey:string;leaseAcquired:boolean;leaseGeneration?:number;recoveryScanCompleted:boolean;recoveryFacts:{previousCompletedCycleKeys:string[];completedEconomicActionKeys:string[];recoveryQueueCount:number;unknownSubmissionCount:number;unresolvedReconciliationDebt:number};plan:'RECOVER_ONLY'|'OBSERVE_ONLY'|'DECISION_CYCLE'|'HOLD';reasonCodes:string[];newEconomicActionAllowed:boolean;cycleInserted:boolean;requiresExistingExecutionWorkflow:true;directSigner:false;directTransactionSend:false;}
export async function runPhase7RecoveryRuntimeTick(input:{store:Pick<Phase1Store,'claimPhase7RuntimeLease'|'loadPhase7RecoveryFacts'|'insertPhase7RuntimeCycle'>;runtimeId:string;instanceId:string;cycleKey:string;now:string;leaseTtlMs:number;restarted:boolean;control:Phase7PersistedControlState;economicActionKey?:string}):Promise<Phase7RecoveryRuntimeResult>{
  const nowMs=Date.parse(input.now);if(!Number.isFinite(nowMs)||input.leaseTtlMs<1000||input.leaseTtlMs>300000)throw new Error('LPFORGE_P7_RECOVERY_RUNTIME_FIELDS');const expiresAt=new Date(nowMs+input.leaseTtlMs).toISOString();const lease=await input.store.claimPhase7RuntimeLease({runtimeId:input.runtimeId,holderId:input.instanceId,now:input.now,expiresAt});
  const empty={previousCompletedCycleKeys:[],completedEconomicActionKeys:[],recoveryQueueCount:0,unknownSubmissionCount:0,unresolvedReconciliationDebt:0};if(!lease)return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,leaseAcquired:false,recoveryScanCompleted:false,recoveryFacts:empty,plan:'HOLD',reasonCodes:['P7_RUNTIME_LEASE_HELD_BY_OTHER'],newEconomicActionAllowed:false,cycleInserted:false,requiresExistingExecutionWorkflow:true,directSigner:false,directTransactionSend:false};
  const facts=await input.store.loadPhase7RecoveryFacts(input.runtimeId);let daemon=planPhase7DaemonTick({now:input.now,instanceId:input.instanceId,cycleKey:input.cycleKey,previousCompletedCycleKeys:facts.previousCompletedCycleKeys,...(input.economicActionKey?{economicActionKey:input.economicActionKey}:{}),completedEconomicActionKeys:facts.completedEconomicActionKeys,restarted:input.restarted,recoveryScanCompleted:true,recoveryQueueCount:facts.recoveryQueueCount,unknownSubmissionCount:facts.unknownSubmissionCount,unresolvedReconciliationDebt:facts.unresolvedReconciliationDebt,healthStatus:input.control.healthStatus,authorityMode:input.control.authorityMode});
  if(daemon.plan==='DECISION_CYCLE'&&!input.control.newEconomicActionAllowed)daemon={plan:'OBSERVE_ONLY',reasonCodes:[...new Set([...daemon.reasonCodes,'P7_RUNTIME_CONTROL_DECISION_BLOCK'])].sort(),newEconomicActionAllowed:false,requiresExistingExecutionWorkflow:true};
  const inserted=await input.store.insertPhase7RuntimeCycle({cycleKey:input.cycleKey,runtimeId:input.runtimeId,instanceId:input.instanceId,observedAt:input.now,plan:daemon.plan,...(input.economicActionKey?{economicActionKey:input.economicActionKey}:{}),payload:{restarted:input.restarted,recoveryScanCompleted:true,recoveryQueueCount:facts.recoveryQueueCount,unknownSubmissionCount:facts.unknownSubmissionCount,unresolvedReconciliationDebt:facts.unresolvedReconciliationDebt,control:input.control,reasonCodes:daemon.reasonCodes,directSigner:false,directTransactionSend:false}});
  if(!inserted)return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,leaseAcquired:true,leaseGeneration:Number(lease.generation),recoveryScanCompleted:true,recoveryFacts:facts,plan:'HOLD',reasonCodes:['P7_RUNTIME_DUPLICATE_CYCLE_INSERT'],newEconomicActionAllowed:false,cycleInserted:false,requiresExistingExecutionWorkflow:true,directSigner:false,directTransactionSend:false};
  return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,leaseAcquired:true,leaseGeneration:Number(lease.generation),recoveryScanCompleted:true,recoveryFacts:facts,plan:daemon.plan,reasonCodes:daemon.reasonCodes,newEconomicActionAllowed:daemon.newEconomicActionAllowed&&input.control.newEconomicActionAllowed,cycleInserted:true,requiresExistingExecutionWorkflow:true,directSigner:false,directTransactionSend:false};
}
