import type { CandidateEconomicSimulation } from '../../candidate-simulator/src/index.js';
import type { RangeStrategyCandidate } from '../../rangeforge/src/index.js';
import type { SurvivalForecast } from '../../range-survival/src/index.js';

export interface CandidateRankingPolicy {id:string;oorPenalty:number;inventoryPenalty:number;costPenalty:number;uncertaintyPenalty:number;complexityPenalty:number;minimumUtilityEdge:number;}
export const RESEARCH_RANKING_POLICY_V1:CandidateRankingPolicy={id:'rangeforge-ranking-research-v1',oorPenalty:.30,inventoryPenalty:.20,costPenalty:.12,uncertaintyPenalty:.18,complexityPenalty:.08,minimumUtilityEdge:0};
export interface RankedCandidate {candidateId:string;utility:number;netValue:number;survivalProbability:number;activeTimeRatio:number;inventoryTail:number;costValue:number;uncertainty:number;complexity:number;actionable:boolean;penalties:{oor:number;inventory:number;cost:number;uncertainty:number;complexity:number};reasonCodes:string[];}
export interface CandidateRankingResult {policyId:string;winner:'NO_TRADE'|string;noTradeUtility:0;rankings:RankedCandidate[];reasonCodes:string[];}
const clamp=(x:number,min=0,max=1)=>Math.max(min,Math.min(max,x));
function complexity(c:RangeStrategyCandidate):number{return clamp((c.widthBins/1400)*.45+(c.strategy==='BID_ASK'?.2:c.strategy==='CURVE'?.1:0)+(c.orientation==='BALANCED'?0:.15));}
export function rankCandidates(input:{candidates:RangeStrategyCandidate[];simulations:CandidateEconomicSimulation[];survivalForecasts:Record<string,SurvivalForecast|undefined>;uncertainty?:Record<string,number|undefined>;policy?:CandidateRankingPolicy;globalActionable?:boolean;}):CandidateRankingResult{
 const p=input.policy??RESEARCH_RANKING_POLICY_V1,sim=new Map(input.simulations.map((s)=>[s.candidateId,s]));const rankings:RankedCandidate[]=[];
 for(const c of input.candidates){const s=sim.get(c.id);if(!s)continue;const sf=input.survivalForecasts[c.id],survivalEvidenceInsufficient=!sf||sf.samples===0;const survival=survivalEvidenceInsufficient?0:sf.survivalProbability;const uncertainty=clamp(input.uncertainty?.[c.id]??(sf?1-sf.confidence:.65));const inv=Math.max(0,-s.inventoryChangeValue);const scale=Math.max(Math.abs(s.netValue),s.feeValue,inv,s.totalCostValue,1e-9);const invNorm=clamp(inv/scale),costNorm=clamp(s.totalCostValue/scale),comp=complexity(c);const penalties={oor:p.oorPenalty*(1-survival)*scale,inventory:p.inventoryPenalty*invNorm*scale,cost:p.costPenalty*costNorm*scale,uncertainty:p.uncertaintyPenalty*uncertainty*scale,complexity:p.complexityPenalty*comp*scale};const utility=s.netValue-Object.values(penalties).reduce((a,b)=>a+b,0);const actionable=(input.globalActionable??true)&&(s.evidenceActionable??true)&&!survivalEvidenceInsufficient;const reasons:string[]=[];if(survivalEvidenceInsufficient)reasons.push('RANGE_SURVIVAL_EVIDENCE_INSUFFICIENT');else if(survival<.6)reasons.push('RANK_RANGE_SURVIVAL_WEAK');if(invNorm>.5)reasons.push('RANK_INVENTORY_TAIL_HIGH');if(uncertainty>.6)reasons.push('RANK_UNCERTAINTY_HIGH');if(utility<=0)reasons.push('RANK_UTILITY_NON_POSITIVE');if(s.evidenceActionable===false)reasons.push('RANK_EVIDENCE_NON_ACTIONABLE');if(input.globalActionable===false)reasons.push('RANK_GLOBAL_ECONOMIC_BLOCK');rankings.push({candidateId:c.id,utility,netValue:s.netValue,survivalProbability:survival,activeTimeRatio:s.activeTimeRatio,inventoryTail:inv,costValue:s.totalCostValue,uncertainty,complexity:comp,actionable,penalties,reasonCodes:reasons});}
 rankings.sort((a,b)=>b.utility-a.utility||b.survivalProbability-a.survivalProbability||a.candidateId.localeCompare(b.candidateId));const best=rankings.find(r=>r.actionable&&r.utility>p.minimumUtilityEdge);const winner=best?.candidateId??'NO_TRADE';let reasonCodes:string[];if(winner!=='NO_TRADE')reasonCodes=['POSITIVE_RISK_ADJUSTED_CANDIDATE'];else if(input.globalActionable===false)reasonCodes=['NO_TRADE_ECONOMICS_NON_POSITIVE'];else if(!rankings.some(r=>r.actionable))reasonCodes=['NO_TRADE_EVIDENCE_NON_ACTIONABLE'];else reasonCodes=['NO_TRADE_DOMINATES_CANDIDATES'];return{policyId:p.id,winner,noTradeUtility:0,rankings,reasonCodes};
}
