export interface ActiveBinObservation { observedAt:string; activeBinId:number; }
export interface RangeShape { id:string; lowerOffsetBins:number; upperOffsetBins:number; }
import { deriveElapsedOccupancy } from '../../elapsed-occupancy/src/index.js';

export interface SurvivalForecast {
  rangeId:string;horizonMinutes:number;samples:number;survivalProbability:number;expectedActiveTimeRatio:number;meanOccupancyCoverageRatio:number;lowerExitProbability:number;upperExitProbability:number;medianFirstPassageMinutes:number|null;revisitAfterExitProbability:number;confidence:number;fitThrough:string;
}
export interface RangeSurvivalModel {version:'range-survival-empirical-v1';fitThrough:string;forecasts:SurvivalForecast[];}
const clamp=(x:number,min=0,max=1)=>Math.max(min,Math.min(max,x));
const median=(a:number[])=>{if(!a.length)return null;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]!:((s[m-1]??0)+(s[m]??0))/2;};
function outcome(anchor:ActiveBinObservation,future:ActiveBinObservation[],shape:RangeShape,horizonMinutes:number){const lo=anchor.activeBinId+shape.lowerOffsetBins,hi=anchor.activeBinId+shape.upperOffsetBins;let firstExit:number|null=null,lower=false,upper=false,revisit=false,wasOut=false;const at=Date.parse(anchor.observedAt);for(const o of future){const inRange=o.activeBinId>=lo&&o.activeBinId<=hi;if(inRange){if(wasOut)revisit=true;}else{wasOut=true;if(firstExit===null)firstExit=(Date.parse(o.observedAt)-at)/60000;if(o.activeBinId<lo)lower=true;if(o.activeBinId>hi)upper=true;}}const occupancy=deriveElapsedOccupancy({observations:[anchor,...future],lowerBinId:lo,upperBinId:hi,horizonStart:anchor.observedAt,horizonEnd:new Date(at+horizonMinutes*60_000).toISOString()});return{survived:firstExit===null,activeRatio:occupancy.activeRatio,coverageRatio:occupancy.coverageRatio,occupancyState:occupancy.state,firstExit,lower,upper,revisit};}
export function fitRangeSurvivalModel(input:{history:ActiveBinObservation[];fitThrough:string;horizonsMinutes:number[];ranges:RangeShape[];anchorStride?:number;minimumFutureSamples?:number;}):RangeSurvivalModel{
 const fitMs=Date.parse(input.fitThrough);if(!Number.isFinite(fitMs))throw new Error('LPFORGE_SURVIVAL_INVALID_FIT_TIME');const s=[...input.history].sort((a,b)=>Date.parse(a.observedAt)-Date.parse(b.observedAt));if(s.some((x)=>Date.parse(x.observedAt)>fitMs))throw new Error('LPFORGE_SURVIVAL_LOOKAHEAD_INPUT');const stride=Math.max(1,input.anchorStride??5),minFuture=Math.max(2,input.minimumFutureSamples??3);const forecasts:SurvivalForecast[]=[];
 for(const horizonMinutes of input.horizonsMinutes){if(horizonMinutes<=0)throw new Error('LPFORGE_SURVIVAL_INVALID_HORIZON');for(const range of input.ranges){if(range.lowerOffsetBins>0||range.upperOffsetBins<0||range.lowerOffsetBins>range.upperOffsetBins)throw new Error('LPFORGE_SURVIVAL_INVALID_RANGE');const outcomes=[] as ReturnType<typeof outcome>[];for(let i=0;i<s.length;i+=stride){const anchor=s[i]!;const end=Date.parse(anchor.observedAt)+horizonMinutes*60000;if(end>fitMs)continue;const future=s.slice(i+1).filter((o)=>{const t=Date.parse(o.observedAt);return t<=end;});if(future.length<minFuture)continue;const observed=outcome(anchor,future,range,horizonMinutes);if(observed.occupancyState==='COMPLETE')outcomes.push(observed);}const n=outcomes.length,first=outcomes.flatMap((o)=>o.firstExit===null?[]:[o.firstExit]);forecasts.push({rangeId:range.id,horizonMinutes,samples:n,survivalProbability:n?outcomes.filter((o)=>o.survived).length/n:0,expectedActiveTimeRatio:n?outcomes.reduce((a,b)=>a+(b.activeRatio??0),0)/n:0,meanOccupancyCoverageRatio:n?outcomes.reduce((a,b)=>a+b.coverageRatio,0)/n:0,lowerExitProbability:n?outcomes.filter((o)=>o.lower).length/n:0,upperExitProbability:n?outcomes.filter((o)=>o.upper).length/n:0,medianFirstPassageMinutes:median(first),revisitAfterExitProbability:first.length?outcomes.filter((o)=>o.firstExit!==null&&o.revisit).length/first.length:0,confidence:clamp(n/40),fitThrough:input.fitThrough});}}
 return{version:'range-survival-empirical-v1',fitThrough:input.fitThrough,forecasts};
}
export function getSurvivalForecast(model:RangeSurvivalModel,rangeId:string,horizonMinutes:number):SurvivalForecast{const f=model.forecasts.find((x)=>x.rangeId===rangeId&&x.horizonMinutes===horizonMinutes);if(!f)throw new Error(`LPFORGE_SURVIVAL_FORECAST_MISSING:${rangeId}:${horizonMinutes}`);return f;}
