// LPFORGE_PHASE6_MAINNET_MODULE
import {assertPhase6Authority,type Phase6Authority,type Phase6CanaryTicket} from '../../phase6-contracts/src/index.js';
import {signMainnetCanaryWithAuxiliaries,type MainnetSignerBackend,type AuxiliaryMainnetSignerBackend,type MainnetSignableEnvelope} from '../../phase6-mainnet-signer/src/index.js';
import {submitSignedTransaction,type BlockhashLease,type SubmissionLedger,type SubmissionTransport} from '../../execution-submission/src/index.js';
import type {ExecutionAuthority} from '../../execution-contracts/src/index.js';import type {ExecutionRiskDecision} from '../../execution-risk/src/index.js';
export interface SerializableMainnetEnvelope extends MainnetSignableEnvelope {serializeSigned():Uint8Array;}
export interface CanaryOpenResult {status:'SUBMITTED';ticketId:string;transactionId:string;signature:string;submittedAt:string;signerBackendId:string;}
function phase5Authority(a:Phase6Authority):ExecutionAuthority{return{phase:'P5',cluster:'mainnet-beta',level:'MAINNET_CANARY',liveExecution:true,issuedAt:a.issuedAt,expiresAt:a.expiresAt,reasonCodes:['DERIVED_FROM_PHASE6',a.ticketId]};}
export async function executeMainnetCanaryOpen(input:{authority:Phase6Authority;ticket:Phase6CanaryTicket;transactionId:string;idempotencyKey:string;requiredSignerAddresses:string[];backend:MainnetSignerBackend;auxiliaryBackends?:AuxiliaryMainnetSignerBackend[];envelope:SerializableMainnetEnvelope;phase5RiskDecision:ExecutionRiskDecision;lease:BlockhashLease;ledger:SubmissionLedger;transport:SubmissionTransport;submittedAt:string}):Promise<CanaryOpenResult>{assertPhase6Authority(input.authority,['MAINNET_CANARY_OPEN'],input.submittedAt);if(input.ticket.action!=='OPEN')throw new Error('LPFORGE_P6_OPEN_TICKET_ACTION');if(input.authority.ticketId!==input.ticket.ticketId)throw new Error('LPFORGE_P6_OPEN_TICKET_MISMATCH');const audits=await signMainnetCanaryWithAuxiliaries({authority:input.authority,ticket:input.ticket,transactionId:input.transactionId,requiredSignerAddresses:input.requiredSignerAddresses,ownerBackend:input.backend,auxiliaryBackends:input.auxiliaryBackends,envelope:input.envelope,signedAt:input.submittedAt});const record=await submitSignedTransaction({authority:phase5Authority(input.authority),riskDecision:input.phase5RiskDecision,transactionId:input.transactionId,idempotencyKey:input.idempotencyKey,attempt:1,raw:input.envelope.serializeSigned(),lease:input.lease,ledger:input.ledger,transport:input.transport,submittedAt:input.submittedAt});return{status:'SUBMITTED',ticketId:input.ticket.ticketId,transactionId:input.transactionId,signature:record.signature,submittedAt:input.submittedAt,signerBackendId:audits.find(a=>a.purpose==='OWNER')?.backendId??input.backend.backendId};}
export async function executeMainnetCanaryClose(input:{authority:Phase6Authority;ticket:Phase6CanaryTicket;transactionId:string;idempotencyKey:string;requiredSignerAddresses:string[];backend:MainnetSignerBackend;envelope:SerializableMainnetEnvelope;phase5RiskDecision:ExecutionRiskDecision;lease:BlockhashLease;ledger:SubmissionLedger;transport:SubmissionTransport;submittedAt:string}):Promise<CanaryOpenResult>{assertPhase6Authority(input.authority,['MAINNET_CANARY_CLOSE'],input.submittedAt);if(input.ticket.action!=='CLOSE'&&input.ticket.action!=='EMERGENCY_CLOSE')throw new Error('LPFORGE_P6_CLOSE_TICKET_ACTION');if(input.authority.ticketId!==input.ticket.ticketId)throw new Error('LPFORGE_P6_CLOSE_TICKET_MISMATCH');const audits=await signMainnetCanaryWithAuxiliaries({authority:input.authority,ticket:input.ticket,transactionId:input.transactionId,requiredSignerAddresses:input.requiredSignerAddresses,ownerBackend:input.backend,auxiliaryBackends:[],envelope:input.envelope,signedAt:input.submittedAt});const record=await submitSignedTransaction({authority:phase5Authority(input.authority),riskDecision:input.phase5RiskDecision,transactionId:input.transactionId,idempotencyKey:input.idempotencyKey,attempt:1,raw:input.envelope.serializeSigned(),lease:input.lease,ledger:input.ledger,transport:input.transport,submittedAt:input.submittedAt});return{status:'SUBMITTED',ticketId:input.ticket.ticketId,transactionId:input.transactionId,signature:record.signature,submittedAt:input.submittedAt,signerBackendId:audits.find(a=>a.purpose==='OWNER')?.backendId??input.backend.backendId};}
/** Shared live mutation path for ADD, CLAIM, REDUCE, RESHAPE and REBALANCE steps. */
export async function executeMainnetCanaryManage(input:{authority:Phase6Authority;ticket:Phase6CanaryTicket;transactionId:string;idempotencyKey:string;requiredSignerAddresses:string[];backend:MainnetSignerBackend;envelope:SerializableMainnetEnvelope;phase5RiskDecision:ExecutionRiskDecision;lease:BlockhashLease;ledger:SubmissionLedger;transport:SubmissionTransport;submittedAt:string}):Promise<CanaryOpenResult>{assertPhase6Authority(input.authority,['MAINNET_CANARY_MANAGE'],input.submittedAt);if(!['ADD','CLAIM','REDUCE','RESHAPE','REBALANCE'].includes(input.ticket.action))throw new Error('LPFORGE_P6_MANAGE_TICKET_ACTION');if(input.authority.ticketId!==input.ticket.ticketId)throw new Error('LPFORGE_P6_MANAGE_TICKET_MISMATCH');const audits=await signMainnetCanaryWithAuxiliaries({authority:input.authority,ticket:input.ticket,transactionId:input.transactionId,requiredSignerAddresses:input.requiredSignerAddresses,ownerBackend:input.backend,auxiliaryBackends:[],envelope:input.envelope,signedAt:input.submittedAt});const record=await submitSignedTransaction({authority:phase5Authority(input.authority),riskDecision:input.phase5RiskDecision,transactionId:input.transactionId,idempotencyKey:input.idempotencyKey,attempt:1,raw:input.envelope.serializeSigned(),lease:input.lease,ledger:input.ledger,transport:input.transport,submittedAt:input.submittedAt});return{status:'SUBMITTED',ticketId:input.ticket.ticketId,transactionId:input.transactionId,signature:record.signature,submittedAt:input.submittedAt,signerBackendId:audits.find(a=>a.purpose==='OWNER')?.backendId??input.backend.backendId};}
