// Canary owns only canary authority. Shared deployment policy lives in deployment-policy.
import type {ExecutionAction,ExecutionAuthority} from '../../execution-contracts/src/index.js';
import type {MainnetCanaryDeploymentPolicy} from '../../deployment-policy/src/index.js';
export {loadDeploymentPolicyFile,loadMainnetCanaryDeploymentPolicyFile,parseDeploymentPolicy,parseMainnetCanaryDeploymentPolicy} from '../../deployment-policy/src/index.js';
export type {MainnetCanaryDeploymentPolicy,MainnetCanaryPoolPolicy,ProductionAdmissionPolicy,ProductionCapitalDeploymentPolicy} from '../../deployment-policy/src/index.js';
export interface MainnetCanaryPolicy extends MainnetCanaryDeploymentPolicy {rpcClass:'DEDICATED_PRIVATE';allowedActions:ReadonlyArray<'OPEN'|'CLOSE'|'EMERGENCY_CLOSE'>;}
export interface MainnetCanaryReadiness {externalReadHealthy:boolean;databaseRuntimeVerified:boolean;phase5BoundaryPass:boolean;recoverySuitePass:boolean;emergencyStopTested:boolean;devnetConfirmedRuns:number;devnetReconciledRuns:number;unresolvedReconciliations:number;openMainnetCanaryPositions:number;openMainnetCanaryPositionsByPool:Record<string,number>;actionsToday:number;globalKillSwitch:boolean;}
export interface MainnetCanaryIntent {action:ExecutionAction;poolAddress:string;capitalLamports:bigint;now:string;}
export function loadMainnetCanaryPolicy(env:Record<string,string|undefined>,deployment:MainnetCanaryDeploymentPolicy):MainnetCanaryPolicy{if(env.LPFORGE_LIVE_EXECUTION!=='true')throw new Error('LPFORGE_CANARY_LIVE_EXECUTION_NOT_ENABLED');if(env.LPFORGE_MAINNET_CANARY!=='true')throw new Error('LPFORGE_CANARY_NOT_ENABLED');if(env.LPFORGE_RPC_CLASS!=='DEDICATED_PRIVATE')throw new Error('LPFORGE_CANARY_DEDICATED_RPC_REQUIRED');if(deployment.status!=='ENABLED')throw new Error('LPFORGE_CANARY_POLICY_DISABLED');return{...deployment,rpcClass:'DEDICATED_PRIVATE',allowedActions:['OPEN','CLOSE','EMERGENCY_CLOSE']};}
export function authorizeMainnetCanary(policy:MainnetCanaryPolicy,r:MainnetCanaryReadiness,intent:MainnetCanaryIntent):ExecutionAuthority{const pool=policy.pools.find(p=>p.address===intent.poolAddress),blocks:string[]=[];if(r.globalKillSwitch)blocks.push('CANARY_GLOBAL_KILL_SWITCH');if(!r.externalReadHealthy)blocks.push('CANARY_EXTERNAL_READ_UNHEALTHY');if(!r.databaseRuntimeVerified)blocks.push('CANARY_DATABASE_NOT_VERIFIED');if(!r.phase5BoundaryPass)blocks.push('CANARY_PHASE5_BOUNDARY_NOT_VERIFIED');if(!r.recoverySuitePass)blocks.push('CANARY_RECOVERY_NOT_VERIFIED');if(!r.emergencyStopTested)blocks.push('CANARY_EMERGENCY_STOP_NOT_TESTED');if(r.devnetConfirmedRuns<policy.minDevnetConfirmedRuns||r.devnetReconciledRuns<policy.minDevnetConfirmedRuns)blocks.push('CANARY_DEVNET_EVIDENCE_INSUFFICIENT');if(r.unresolvedReconciliations>0)blocks.push('CANARY_RECONCILIATION_DEBT');if(r.actionsToday>=policy.maxActionsPerDay)blocks.push('CANARY_DAILY_ACTION_LIMIT');if(!pool)blocks.push('CANARY_POOL_NOT_ALLOWLISTED');if(!policy.allowedActions.includes(intent.action as 'OPEN'|'CLOSE'|'EMERGENCY_CLOSE'))blocks.push('CANARY_ACTION_NOT_ALLOWED');if(intent.action==='OPEN'){if(!pool||intent.capitalLamports<=0n||intent.capitalLamports>pool.maxCapitalLamports)blocks.push('CANARY_CAPITAL_LIMIT');if(r.openMainnetCanaryPositions>=policy.maxOpenPositions)blocks.push('CANARY_OPEN_POSITION_LIMIT');const n=Object.prototype.hasOwnProperty.call(r.openMainnetCanaryPositionsByPool,intent.poolAddress)?r.openMainnetCanaryPositionsByPool[intent.poolAddress]:undefined;if(typeof n!=='number'||!Number.isSafeInteger(n)||n<0)blocks.push('CANARY_POOL_POSITION_FACT_MISSING');else if(pool&&n>=pool.maxOpenPositions)blocks.push('CANARY_POOL_POSITION_LIMIT');}else if(intent.capitalLamports!==0n)blocks.push('CANARY_EXIT_CAPITAL_MUST_BE_ZERO');if(blocks.length)throw new Error(`LPFORGE_CANARY_AUTHORITY_BLOCKED:${blocks.sort().join(',')}`);return{phase:'P5',cluster:'mainnet-beta',level:'MAINNET_CANARY',liveExecution:true,issuedAt:intent.now,expiresAt:new Date(Date.parse(intent.now)+policy.approvalTtlMs).toISOString(),reasonCodes:['MAINNET_CANARY_EXPLICIT','NO_AUTONOMOUS_SCALE','CONFIGURED_POSITION_LIMIT','PER_POOL_CAPITAL_LIMIT']};}
