// LPFORGE_PHASE5_EXECUTION_MODULE
import type { ExecutionAction, ExecutionAuthority } from '../../execution-contracts/src/index.js';
export const MAINNET_CANARY_HARD_CAP_LAMPORTS=100_000_000n;
export interface MainnetCanaryPolicy {maxLamports:bigint;allowedPools:string[];approvalTtlMs:number;minDevnetConfirmedRuns:number;maxActionsPerDay:number;rpcClass:'DEDICATED_PRIVATE';allowedActions:ReadonlyArray<'OPEN'|'CLOSE'|'EMERGENCY_CLOSE'>;}
export interface MainnetCanaryReadiness {externalReadHealthy:boolean;databaseRuntimeVerified:boolean;phase5BoundaryPass:boolean;recoverySuitePass:boolean;emergencyStopTested:boolean;devnetConfirmedRuns:number;devnetReconciledRuns:number;unresolvedReconciliations:number;openMainnetCanaryPositions:number;actionsToday:number;globalKillSwitch:boolean;}
export interface MainnetCanaryIntent {action:ExecutionAction;poolAddress:string;capitalLamports:bigint;now:string;}
function int(name:string,v:string|undefined,min:number,max:number){const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw new Error(`LPFORGE_CANARY_CONFIG:${name}`);return n;}
export function loadMainnetCanaryPolicy(env:Record<string,string|undefined>):MainnetCanaryPolicy{if(env.LPFORGE_LIVE_EXECUTION!=='true')throw new Error('LPFORGE_CANARY_LIVE_EXECUTION_NOT_ENABLED');if(env.LPFORGE_MAINNET_CANARY!=='true')throw new Error('LPFORGE_CANARY_NOT_ENABLED');if(env.LPFORGE_RPC_CLASS!=='DEDICATED_PRIVATE')throw new Error('LPFORGE_CANARY_DEDICATED_RPC_REQUIRED');const max=BigInt(env.LPFORGE_CANARY_MAX_LAMPORTS??'0');if(max<=0n||max>MAINNET_CANARY_HARD_CAP_LAMPORTS)throw new Error('LPFORGE_CANARY_CAP_INVALID');const pools=(env.LPFORGE_CANARY_ALLOWED_POOLS??'').split(',').map(x=>x.trim()).filter(Boolean);if(!pools.length)throw new Error('LPFORGE_CANARY_POOL_ALLOWLIST_REQUIRED');return{maxLamports:max,allowedPools:[...new Set(pools)],approvalTtlMs:int('APPROVAL_TTL_MS',env.LPFORGE_CANARY_APPROVAL_TTL_MS,5000,60000),minDevnetConfirmedRuns:int('MIN_DEVNET_CONFIRMED',env.LPFORGE_CANARY_MIN_DEVNET_CONFIRMED,1,1000),maxActionsPerDay:int('MAX_ACTIONS_PER_DAY',env.LPFORGE_CANARY_MAX_ACTIONS_PER_DAY,1,3),rpcClass:'DEDICATED_PRIVATE',allowedActions:['OPEN','CLOSE','EMERGENCY_CLOSE']};}
export function authorizeMainnetCanary(policy:MainnetCanaryPolicy,r:MainnetCanaryReadiness,intent:MainnetCanaryIntent):ExecutionAuthority{
  const blocks:string[]=[];if(r.globalKillSwitch)blocks.push('CANARY_GLOBAL_KILL_SWITCH');if(!r.externalReadHealthy)blocks.push('CANARY_EXTERNAL_READ_UNHEALTHY');if(!r.databaseRuntimeVerified)blocks.push('CANARY_DATABASE_NOT_VERIFIED');if(!r.phase5BoundaryPass)blocks.push('CANARY_PHASE5_BOUNDARY_NOT_VERIFIED');if(!r.recoverySuitePass)blocks.push('CANARY_RECOVERY_NOT_VERIFIED');if(!r.emergencyStopTested)blocks.push('CANARY_EMERGENCY_STOP_NOT_TESTED');if(r.devnetConfirmedRuns<policy.minDevnetConfirmedRuns||r.devnetReconciledRuns<policy.minDevnetConfirmedRuns)blocks.push('CANARY_DEVNET_EVIDENCE_INSUFFICIENT');if(r.unresolvedReconciliations>0)blocks.push('CANARY_RECONCILIATION_DEBT');if(r.actionsToday>=policy.maxActionsPerDay)blocks.push('CANARY_DAILY_ACTION_LIMIT');if(!policy.allowedPools.includes(intent.poolAddress))blocks.push('CANARY_POOL_NOT_ALLOWLISTED');if(!policy.allowedActions.includes(intent.action as 'OPEN'|'CLOSE'|'EMERGENCY_CLOSE'))blocks.push('CANARY_ACTION_NOT_ALLOWED');if(intent.action==='OPEN'){if(intent.capitalLamports<=0n||intent.capitalLamports>policy.maxLamports)blocks.push('CANARY_CAPITAL_LIMIT');if(r.openMainnetCanaryPositions>=1)blocks.push('CANARY_SINGLE_POSITION_LIMIT');}else if(intent.capitalLamports!==0n)blocks.push('CANARY_EXIT_CAPITAL_MUST_BE_ZERO');if(blocks.length)throw new Error(`LPFORGE_CANARY_AUTHORITY_BLOCKED:${blocks.sort().join(',')}`);return{phase:'P5',cluster:'mainnet-beta',level:'MAINNET_CANARY',liveExecution:true,issuedAt:intent.now,expiresAt:new Date(Date.parse(intent.now)+policy.approvalTtlMs).toISOString(),reasonCodes:['MAINNET_CANARY_EXPLICIT','NO_AUTONOMOUS_SCALE','ONE_POSITION_MAX']};}
