// LPFORGE_PHASE5_EXECUTION_MODULE
import {readFileSync} from 'node:fs';
import type { ExecutionAction, ExecutionAuthority } from '../../execution-contracts/src/index.js';
export interface MainnetCanaryPoolPolicy {address:string;maxCapitalLamports:bigint;maxOpenPositions:number;}
export interface ProductionAdmissionPolicy {enabled:boolean;eligibleTiers:ReadonlyArray<'A'|'B'|'C'>;maxCandidates:number;maxCandidateAgeMs:number;maxCapitalLamports:bigint;maxOpenPositions:number;}
export interface ProductionCapitalDeploymentPolicy {reserveLamports:bigint;maxPortfolioLamports:bigint;maxTokenLamports:bigint;targetInitialPositionLamports:bigint;maxInitialPositionLamports:bigint;minInitialPositionLamports:bigint;}
export interface MainnetCanaryDeploymentPolicy {schemaVersion:1;policyId:string;status:'DISABLED'|'ENABLED';approvalTtlMs:number;minDevnetConfirmedRuns:number;maxActionsPerDay:number;maxOpenPositions:number;pools:MainnetCanaryPoolPolicy[];productionAdmission?:ProductionAdmissionPolicy;productionCapital?:ProductionCapitalDeploymentPolicy;}
export interface MainnetCanaryPolicy extends MainnetCanaryDeploymentPolicy {rpcClass:'DEDICATED_PRIVATE';allowedActions:ReadonlyArray<'OPEN'|'CLOSE'|'EMERGENCY_CLOSE'>;}
export interface MainnetCanaryReadiness {externalReadHealthy:boolean;databaseRuntimeVerified:boolean;phase5BoundaryPass:boolean;recoverySuitePass:boolean;emergencyStopTested:boolean;devnetConfirmedRuns:number;devnetReconciledRuns:number;unresolvedReconciliations:number;openMainnetCanaryPositions:number;openMainnetCanaryPositionsByPool:Record<string,number>;actionsToday:number;globalKillSwitch:boolean;}
export interface MainnetCanaryIntent {action:ExecutionAction;poolAddress:string;capitalLamports:bigint;now:string;}
function int(name:string,v:string|undefined,min:number,max:number){const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw new Error(`LPFORGE_CANARY_CONFIG:${name}`);return n;}
function positiveSolToLamports(value:unknown){const source=typeof value==='string'?value.trim():typeof value==='number'&&Number.isFinite(value)?value.toFixed(9):'';const match=/^(0|[1-9]\d*)(?:\.(\d{1,9}))?$/.exec(source);if(!match)throw new Error('LPFORGE_CANARY_POLICY_CAPITAL_SOL');const whole=BigInt(match[1]!);const fraction=BigInt((match[2]??'').padEnd(9,'0')||'0');const lamports=whole*1_000_000_000n+fraction;if(lamports<=0n)throw new Error('LPFORGE_CANARY_POLICY_CAPITAL_SOL');return lamports;}
function nonNegativeSolToLamports(value:unknown){if(value===0||value==='0'||value==='0.0')return 0n;return positiveSolToLamports(value);}
function positiveSafeInteger(name:string,value:unknown){const n=Number(value);if(!Number.isSafeInteger(n)||n<1)throw new Error(`LPFORGE_CANARY_POLICY:${name}`);return n;}
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('LPFORGE_CANARY_POLICY_FORMAT');return value as Record<string,unknown>;}
function text(name:string,value:unknown){if(typeof value!=='string'||!value.trim())throw new Error(`LPFORGE_CANARY_POLICY:${name}`);return value.trim();}
function productionAdmission(value:unknown):ProductionAdmissionPolicy|undefined{if(value===undefined)return undefined;const v=object(value);if(typeof v.enabled!=='boolean')throw new Error('LPFORGE_CANARY_POLICY:PRODUCTION_ADMISSION_ENABLED');const tiers=Array.isArray(v.eligibleTiers)?[...new Set(v.eligibleTiers)]:[];if(!tiers.length||tiers.some(x=>x!=='A'&&x!=='B'&&x!=='C'))throw new Error('LPFORGE_CANARY_POLICY:PRODUCTION_ADMISSION_TIERS');return{enabled:v.enabled,eligibleTiers:tiers as Array<'A'|'B'|'C'>,maxCandidates:positiveSafeInteger('PRODUCTION_ADMISSION_MAX_CANDIDATES',v.maxCandidates),maxCandidateAgeMs:int('PRODUCTION_ADMISSION_MAX_CANDIDATE_AGE_MS',typeof v.maxCandidateAgeMs==='number'?String(v.maxCandidateAgeMs):undefined,60_000,86_400_000),maxCapitalLamports:positiveSolToLamports(v.maxCapitalSol),maxOpenPositions:positiveSafeInteger('PRODUCTION_ADMISSION_MAX_OPEN_POSITIONS',v.maxOpenPositions)};}
function productionCapital(value:unknown):ProductionCapitalDeploymentPolicy|undefined{if(value===undefined)return undefined;const v=object(value),reserveLamports=nonNegativeSolToLamports(v.reserveSol),maxPortfolioLamports=positiveSolToLamports(v.maxPortfolioCapitalSol),maxTokenLamports=positiveSolToLamports(v.maxTokenCapitalSol),targetInitialPositionLamports=positiveSolToLamports(v.targetInitialPositionSol),maxInitialPositionLamports=positiveSolToLamports(v.maxInitialPositionSol),minInitialPositionLamports=positiveSolToLamports(v.minInitialPositionSol);if(reserveLamports>=maxPortfolioLamports||minInitialPositionLamports>targetInitialPositionLamports||targetInitialPositionLamports>maxInitialPositionLamports||maxInitialPositionLamports>maxPortfolioLamports)throw new Error('LPFORGE_CANARY_POLICY:PRODUCTION_CAPITAL_RANGE');return{reserveLamports,maxPortfolioLamports,maxTokenLamports,targetInitialPositionLamports,maxInitialPositionLamports,minInitialPositionLamports};}
export function parseMainnetCanaryDeploymentPolicy(raw:unknown):MainnetCanaryDeploymentPolicy{const v=object(raw);if(v.schemaVersion!==1)throw new Error('LPFORGE_CANARY_POLICY_SCHEMA');const status=v.status;if(status!=='DISABLED'&&status!=='ENABLED')throw new Error('LPFORGE_CANARY_POLICY_STATUS');if(!Array.isArray(v.pools))throw new Error('LPFORGE_CANARY_POLICY:POOLS');const pools=v.pools.map((entry)=>{const p=object(entry);return{address:text('POOL_ADDRESS',p.address),maxCapitalLamports:positiveSolToLamports(p.maxCapitalSol),maxOpenPositions:positiveSafeInteger('POOL_MAX_OPEN_POSITIONS',p.maxOpenPositions)}}),admission=productionAdmission(v.productionAdmission),capital=productionCapital(v.productionCapital);if(new Set(pools.map(p=>p.address)).size!==pools.length)throw new Error('LPFORGE_CANARY_POLICY_POOL_DUPLICATE');if(status==='ENABLED'&&!pools.length&&!(admission?.enabled))throw new Error('LPFORGE_CANARY_POLICY_POOL_REQUIRED');return{schemaVersion:1,policyId:text('POLICY_ID',v.policyId),status,approvalTtlMs:int('APPROVAL_TTL_MS',typeof v.approvalTtlMs==='number'?String(v.approvalTtlMs):undefined,5000,60000),minDevnetConfirmedRuns:positiveSafeInteger('MIN_DEVNET_CONFIRMED',v.minDevnetConfirmedRuns),maxActionsPerDay:positiveSafeInteger('MAX_ACTIONS_PER_DAY',v.maxActionsPerDay),maxOpenPositions:positiveSafeInteger('MAX_OPEN_POSITIONS',v.maxOpenPositions),pools,...(admission?{productionAdmission:admission}:{}),...(capital?{productionCapital:capital}:{})};}
export function loadMainnetCanaryDeploymentPolicyFile(path:string):MainnetCanaryDeploymentPolicy{try{return parseMainnetCanaryDeploymentPolicy(JSON.parse(readFileSync(path,'utf8')));}catch(error){if(error instanceof Error&&error.message.startsWith('LPFORGE_CANARY_'))throw error;throw new Error('LPFORGE_CANARY_POLICY_FILE_INVALID');}}
export function loadMainnetCanaryPolicy(env:Record<string,string|undefined>,deployment:MainnetCanaryDeploymentPolicy):MainnetCanaryPolicy{if(env.LPFORGE_LIVE_EXECUTION!=='true')throw new Error('LPFORGE_CANARY_LIVE_EXECUTION_NOT_ENABLED');if(env.LPFORGE_MAINNET_CANARY!=='true')throw new Error('LPFORGE_CANARY_NOT_ENABLED');if(env.LPFORGE_RPC_CLASS!=='DEDICATED_PRIVATE')throw new Error('LPFORGE_CANARY_DEDICATED_RPC_REQUIRED');if(deployment.status!=='ENABLED')throw new Error('LPFORGE_CANARY_POLICY_DISABLED');return{...deployment,rpcClass:'DEDICATED_PRIVATE',allowedActions:['OPEN','CLOSE','EMERGENCY_CLOSE']};}
export function authorizeMainnetCanary(policy:MainnetCanaryPolicy,r:MainnetCanaryReadiness,intent:MainnetCanaryIntent):ExecutionAuthority{
  const pool=policy.pools.find(p=>p.address===intent.poolAddress);const blocks:string[]=[];if(r.globalKillSwitch)blocks.push('CANARY_GLOBAL_KILL_SWITCH');if(!r.externalReadHealthy)blocks.push('CANARY_EXTERNAL_READ_UNHEALTHY');if(!r.databaseRuntimeVerified)blocks.push('CANARY_DATABASE_NOT_VERIFIED');if(!r.phase5BoundaryPass)blocks.push('CANARY_PHASE5_BOUNDARY_NOT_VERIFIED');if(!r.recoverySuitePass)blocks.push('CANARY_RECOVERY_NOT_VERIFIED');if(!r.emergencyStopTested)blocks.push('CANARY_EMERGENCY_STOP_NOT_TESTED');if(r.devnetConfirmedRuns<policy.minDevnetConfirmedRuns||r.devnetReconciledRuns<policy.minDevnetConfirmedRuns)blocks.push('CANARY_DEVNET_EVIDENCE_INSUFFICIENT');if(r.unresolvedReconciliations>0)blocks.push('CANARY_RECONCILIATION_DEBT');if(r.actionsToday>=policy.maxActionsPerDay)blocks.push('CANARY_DAILY_ACTION_LIMIT');if(!pool)blocks.push('CANARY_POOL_NOT_ALLOWLISTED');if(!policy.allowedActions.includes(intent.action as 'OPEN'|'CLOSE'|'EMERGENCY_CLOSE'))blocks.push('CANARY_ACTION_NOT_ALLOWED');if(intent.action==='OPEN'){if(!pool||intent.capitalLamports<=0n||intent.capitalLamports>pool.maxCapitalLamports)blocks.push('CANARY_CAPITAL_LIMIT');if(r.openMainnetCanaryPositions>=policy.maxOpenPositions)blocks.push('CANARY_OPEN_POSITION_LIMIT');const poolPositions=Object.prototype.hasOwnProperty.call(r.openMainnetCanaryPositionsByPool,intent.poolAddress)?r.openMainnetCanaryPositionsByPool[intent.poolAddress]!:undefined;if(typeof poolPositions!=='number'||!Number.isSafeInteger(poolPositions)||poolPositions<0)blocks.push('CANARY_POOL_POSITION_FACT_MISSING');else if(pool&&poolPositions>=pool.maxOpenPositions)blocks.push('CANARY_POOL_POSITION_LIMIT');}else if(intent.capitalLamports!==0n)blocks.push('CANARY_EXIT_CAPITAL_MUST_BE_ZERO');if(blocks.length)throw new Error(`LPFORGE_CANARY_AUTHORITY_BLOCKED:${blocks.sort().join(',')}`);return{phase:'P5',cluster:'mainnet-beta',level:'MAINNET_CANARY',liveExecution:true,issuedAt:intent.now,expiresAt:new Date(Date.parse(intent.now)+policy.approvalTtlMs).toISOString(),reasonCodes:['MAINNET_CANARY_EXPLICIT','NO_AUTONOMOUS_SCALE','CONFIGURED_POSITION_LIMIT','PER_POOL_CAPITAL_LIMIT']};}
