// LPFORGE_PHASE7_RUNTIME_INTEGRATION_MODULE
import {spawn} from 'node:child_process';
import {loadMainnetCanaryDeploymentPolicyFile,type MainnetCanaryDeploymentPolicy} from '../../canary/src/index.js';
import {createMeteoraDataApi} from '../../data-api/src/index.js';
import type {Phase1Config} from '../../config/src/index.js';
import type {Phase1Store} from '../../db/src/index.js';
import {resolveLiveExecutionUniverse} from '../../live-execution-universe/src/index.js';
import {createSolanaRpcClient} from '../../meteora/src/index.js';
import {loadPhase7ControlConfig,resolvePhase7Authority} from '../../phase7-authority/src/index.js';
import type {Phase7DriftAssessment,Phase7EvaluationMetrics} from '../../phase7-drift/src/index.js';
import {assessPhase7Health,defaultPhase7HealthPolicy,type Phase7HealthAssessment} from '../../phase7-health/src/index.js';
import type {Phase7Incident} from '../../phase7-incidents/src/index.js';
import {assessPhase7LiveDrift,defaultPhase7LiveDriftPolicy} from '../../phase7-live-drift/src/index.js';
import {buildPhase7LiveControlDecision,derivePhase7AutomaticIncidents,reconcilePhase7AutomaticIncidents} from '../../phase7-live-control/src/index.js';
import {buildPhase7RuntimeEvidence} from '../../phase7-live-evidence/src/index.js';
import {collectPhase7LiveHealthObservations} from '../../phase7-live-health/src/index.js';
import {runPhase7RecoveryRuntimeTick} from '../../phase7-live-runtime/src/index.js';

export interface Phase7OperatorProbe {exitCode:number;eventDecodeWarnings:number;transactionsScanned:number;decodedSwapEvents:number;operationalCycleComplete:boolean;outputBytes:number;poolAddresses:string[];}
export interface Phase7ProductionOnceResult {runtimeId:string;instanceId:string;cycleKey:string;observedAt:string;operator?:Phase7OperatorProbe;operatorFailure?:true;health?:Phase7HealthAssessment;drift?:Phase7DriftAssessment;control?:ReturnType<typeof buildPhase7LiveControlDecision>;runtime:Awaited<ReturnType<typeof runPhase7RecoveryRuntimeTick>>;evidence?:Awaited<ReturnType<typeof buildPhase7RuntimeEvidence>>;directSigner:false;directTransactionSend:false;mainnetTransactionSent:false;}
function healthFromRow(row:Record<string,unknown>):Phase7HealthAssessment{const payload=(row.payload??{}) as Record<string,unknown>;return{status:String(row.status) as Phase7HealthAssessment['status'],observedAt:new Date(String(row.observed_at)).toISOString(),domainStatus:(row.domain_status??{}) as Phase7HealthAssessment['domainStatus'],staleDomains:(payload.staleDomains??[]) as Phase7HealthAssessment['staleDomains'],missingDomains:(payload.missingDomains??[]) as Phase7HealthAssessment['missingDomains'],reasonCodes:(row.reason_codes??[]) as string[],newEntriesAllowed:Boolean(row.new_entries_allowed),managementWritesAllowed:Boolean(row.management_writes_allowed),emergencyCloseAllowed:true};}
function driftFromRow(row:Record<string,unknown>):Phase7DriftAssessment{return{status:String(row.status) as Phase7DriftAssessment['status'],reasonCodes:(row.reason_codes??[]) as string[],observedAt:new Date(String(row.observed_at)).toISOString(),sampleCount:Number(row.sample_count),newEntriesAllowed:String(row.status)!=='BLOCK',managementAllowed:true,policyMutationAllowed:false,automaticPolicyPromotion:false,deltas:(row.deltas??{}) as Record<string,number>};}
function incidentFromRow(row:Record<string,unknown>):Phase7Incident{return{incidentId:String(row.incident_id),type:String(row.incident_type) as Phase7Incident['type'],severity:String(row.severity) as Phase7Incident['severity'],openedAt:new Date(String(row.opened_at)).toISOString(),status:String(row.status) as Phase7Incident['status'],reasonCodes:(row.reason_codes??[]) as string[],...(row.pool_address?{pool:String(row.pool_address)}:{}),...(row.token_mint?{token:String(row.token_mint)}:{}),...(row.resolved_at?{resolvedAt:new Date(String(row.resolved_at)).toISOString()}:{}),...((row.payload as Record<string,unknown>|undefined)?.acknowledgedBy?{acknowledgedBy:String((row.payload as Record<string,unknown>).acknowledgedBy)}:{})};}
export function productionPoolAddressesFromPolicy(policy:Pick<MainnetCanaryDeploymentPolicy,'pools'>){return[...new Set(policy.pools.map(pool=>pool.address))];}
/** The enabled execution policy is the sole source of the production universe. */
export function productionPoolAddresses(env:NodeJS.ProcessEnv){const path=env.LPFORGE_EXECUTION_POLICY_PATH?.trim()||'policies/live-execution-policy.json';return productionPoolAddressesFromPolicy(loadMainnetCanaryDeploymentPolicyFile(path));}
export async function productionPoolUniverse(input:{env:NodeJS.ProcessEnv;store:Pick<Phase1Store,'listDiscoveryCandidates'>;observedAt:string}){const path=input.env.LPFORGE_EXECUTION_POLICY_PATH?.trim()||'policies/live-execution-policy.json';return resolveLiveExecutionUniverse({policy:loadMainnetCanaryDeploymentPolicyFile(path),store:input.store,observedAt:input.observedAt});}
export function parsePhase7OperatorProbeOutput(combined:string,exitCode:number,poolAddress?:string):Phase7OperatorProbe{const legacyWarnings=(combined.match(/meteora_event_decode_quarantined/g)??[]).length;const machineLine=combined.split(/\r?\n/).find(line=>line.includes('\"event\":\"lpforge_operator_machine_summary\"'));const legacyLine=combined.split(/\r?\n/).find(line=>line.includes('\"event\":\"meteora_ingestion_summary\"'));let transactionsScanned=0,decodedSwapEvents=0,eventDecodeWarnings=legacyWarnings,complete=false;for(const line of [machineLine,legacyLine]){if(!line)continue;try{const x=JSON.parse(line) as Record<string,unknown>;transactionsScanned=Number(x.transactionsScanned??transactionsScanned);decodedSwapEvents=Number(x.decodedSwapEvents??decodedSwapEvents);eventDecodeWarnings=Number(x.eventDecodeWarnings??eventDecodeWarnings);if(x.event==='lpforge_operator_machine_summary')complete=true;}catch{}}if(!complete)complete=combined.includes('operational_cycle_complete');return{exitCode,eventDecodeWarnings,transactionsScanned,decodedSwapEvents,operationalCycleComplete:complete,outputBytes:combined.length,poolAddresses:poolAddress?[poolAddress]:[]};}
export async function runAutonomousDecisionProbe(input:{cwd:string;env:NodeJS.ProcessEnv;poolAddress?:string}):Promise<Phase7OperatorProbe>{
  // The operator needs only the public owner address to persist a plan.  It never
  // receives signing authority; the separately supervised execution worker is
  // the only process that loads the local signer configuration.
  const poolAddress=input.poolAddress??input.env.LPFORGE_SMOKE_POOL_ADDRESS?.trim();const childEnv:{[key:string]:string|undefined}={...input.env,LIVE_SIGNING:'false',LPFORGE_LIVE_EXECUTION:'false',LPFORGE_MAINNET_CANARY:'false',LPFORGE_DATA_MODE:'LIVE_READ_ONLY',LPFORGE_OPERATOR_MACHINE_SUMMARY:'true',...(poolAddress?{LPFORGE_SMOKE_POOL_ADDRESS:poolAddress}:{})};delete childEnv.LPFORGE_PREPARE_POSITION_ADDRESS;
  return new Promise((resolve,reject)=>{const child=spawn('node',['--enable-source-maps','.build/apps/operator/src/main.js','live-once'],{cwd:input.cwd,env:childEnv,stdio:['ignore','pipe','pipe']});let out='',err='';child.stdout?.on('data',x=>{out+=String(x);});child.stderr?.on('data',x=>{err+=String(x);});child.on('error',reject);child.on('close',code=>{const combined=out+'\n'+err;const exitCode=code??1;if(exitCode!==0)return reject(new Error(`LPFORGE_P7_OPERATOR_PROBE_FAILED:${exitCode}:${err.slice(-500)}`));resolve(parsePhase7OperatorProbeOutput(combined,exitCode,poolAddress));});});
}
export async function runPhase7ProductionOnce(input:{cfg:Phase1Config;store:Phase1Store;runtimeId:string;instanceId:string;cycleKey:string;driftBaseline:Phase7EvaluationMetrics;sourceCommit?:string;policyHash?:string;cwd:string;env:NodeJS.ProcessEnv;leaseTtlMs?:number;restarted:boolean}):Promise<Phase7ProductionOnceResult>{
  const startedAt=new Date().toISOString();if(!input.cfg.smokePoolAddress)throw new Error('LPFORGE_CONFIG_REQUIRED:LPFORGE_SMOKE_POOL_ADDRESS');const ttl=input.leaseTtlMs??60_000;const lease=await input.store.claimPhase7RuntimeLease({runtimeId:input.runtimeId,holderId:input.instanceId,now:startedAt,expiresAt:new Date(Date.parse(startedAt)+ttl).toISOString()});if(!lease){const runtime={runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,leaseAcquired:false,recoveryScanCompleted:false,recoveryFacts:{previousCompletedCycleKeys:[],completedEconomicActionKeys:[],recoveryQueueCount:0,unknownSubmissionCount:0,unresolvedReconciliationDebt:0},plan:'HOLD' as const,reasonCodes:['P7_RUNTIME_LEASE_HELD_BY_OTHER'],newEconomicActionAllowed:false,cycleInserted:false,requiresExistingExecutionWorkflow:true as const,directSigner:false as const,directTransactionSend:false as const};return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,observedAt:startedAt,runtime,directSigner:false,directTransactionSend:false,mainnetTransactionSent:false};}
  const recovery=await input.store.loadPhase7RecoveryFacts(input.runtimeId);if(recovery.recoveryQueueCount>0||recovery.unknownSubmissionCount>0||recovery.unresolvedReconciliationDebt>0){const runtime=await runPhase7RecoveryRuntimeTick({store:input.store,runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,now:new Date().toISOString(),leaseTtlMs:ttl,restarted:input.restarted,control:{authorityMode:'OBSERVE_ONLY',healthStatus:'CRITICAL',newEconomicActionAllowed:false}});return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,observedAt:new Date().toISOString(),runtime,directSigner:false,directTransactionSend:false,mainnetTransactionSent:false};}
  const rpc=createSolanaRpcClient({url:input.cfg.solanaRpcHttpUrl,timeoutMs:input.cfg.rpcTimeoutMs,minIntervalMs:input.cfg.rpcMinIntervalMs,maxRetries:input.cfg.rpcMaxRetries,retryBaseDelayMs:input.cfg.rpcRetryBaseDelayMs,retryMaxDelayMs:input.cfg.rpcRetryMaxDelayMs});const dataApi=createMeteoraDataApi({baseUrl:input.cfg.meteoraDataApiUrl,maxRps:input.cfg.dataApiMaxRps,timeoutMs:input.cfg.httpTimeoutMs});let operator:Phase7OperatorProbe;
  try{const universe=await productionPoolUniverse({env:input.env,store:input.store,observedAt:startedAt}),probes:Phase7OperatorProbe[]=[];for(const poolAddress of productionPoolAddressesFromPolicy(universe.policy))probes.push(await runAutonomousDecisionProbe({cwd:input.cwd,env:input.env,poolAddress}));if(probes.some(probe=>!probe.operationalCycleComplete))throw new Error('LPFORGE_P7_OPERATOR_CYCLE_COMPLETION_MISSING');operator={exitCode:0,eventDecodeWarnings:probes.reduce((sum,probe)=>sum+probe.eventDecodeWarnings,0),transactionsScanned:probes.reduce((sum,probe)=>sum+probe.transactionsScanned,0),decodedSwapEvents:probes.reduce((sum,probe)=>sum+probe.decodedSwapEvents,0),operationalCycleComplete:true,outputBytes:probes.reduce((sum,probe)=>sum+probe.outputBytes,0),poolAddresses:probes.flatMap(probe=>probe.poolAddresses)};}
  catch{
    const failureAt=new Date().toISOString();const observations=await collectPhase7LiveHealthObservations({assessmentAt:failureAt,poolAddress:input.cfg.smokePoolAddress,rpc,dataApi,store:input.store});observations.push({domain:'DECISION',observedAt:failureAt,status:'CRITICAL',reasonCodes:['P7_LIVE_OPERATOR_CYCLE_FAILED']});const health=assessPhase7Health(observations,defaultPhase7HealthPolicy,failureAt);await input.store.insertPhase7HealthAssessment({assessmentId:`${input.runtimeId}:${input.cycleKey}:health`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:failureAt,status:health.status,newEntriesAllowed:false,managementWritesAllowed:false,reasonCodes:health.reasonCodes,domainStatus:health.domainStatus,payload:{poolAddress:input.cfg.smokePoolAddress,observations,staleDomains:health.staleDomains,missingDomains:health.missingDomains,operatorFailure:true}});
    const drift:Phase7DriftAssessment={status:'BLOCK',reasonCodes:['P7_DRIFT_OPERATOR_CYCLE_UNAVAILABLE'],observedAt:failureAt,sampleCount:0,newEntriesAllowed:false,managementAllowed:true,policyMutationAllowed:false,automaticPolicyPromotion:false,deltas:{}};await input.store.insertPhase7DriftAssessment({assessmentId:`${input.runtimeId}:${input.cycleKey}:drift`,observedAt:failureAt,status:'BLOCK',sampleCount:0,reasonCodes:drift.reasonCodes,deltas:{},payload:{runtimeId:input.runtimeId,cycleKey:input.cycleKey,poolAddress:input.cfg.smokePoolAddress,operatorFailure:true,policyMutationAllowed:false,automaticPolicyPromotion:false}});
    const authority=resolvePhase7Authority({config:loadPhase7ControlConfig(input.env),now:failureAt});const existing=(await input.store.loadActivePhase7Incidents()).map(incidentFromRow);const current=derivePhase7AutomaticIncidents({poolAddress:input.cfg.smokePoolAddress,observedAt:failureAt,health,drift});const updates=reconcilePhase7AutomaticIncidents({existing,current,observedAt:failureAt});for(const i of updates)await input.store.upsertPhase7IncidentState({incidentId:i.incidentId,incidentType:i.type,severity:i.severity,status:i.status,openedAt:i.openedAt,observedAt:failureAt,...(i.resolvedAt?{resolvedAt:i.resolvedAt}:{}),...(i.pool?{poolAddress:i.pool}:{}),...(i.token?{tokenMint:i.token}:{}),reasonCodes:i.reasonCodes,payload:{acknowledgedBy:i.acknowledgedBy??null,automatic:i.incidentId.startsWith('auto:')}});const active=updates.filter(i=>i.status!=='RESOLVED');const control=buildPhase7LiveControlDecision({authority,health,drift,incidents:active});await input.store.insertPhase7ControlDecision({decisionId:`${input.runtimeId}:${input.cycleKey}:control`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:failureAt,authorityMode:control.authorityMode,healthStatus:control.healthStatus,driftStatus:control.driftStatus,safetyMode:control.safety.mode,daemonPlan:control.daemonPlan,newEconomicActionAllowed:false,reasonCodes:control.reasonCodes,payload:{poolAddress:input.cfg.smokePoolAddress,activeIncidentIds:active.map(i=>i.incidentId),operatorFailure:true}});
    const runtime=await runPhase7RecoveryRuntimeTick({store:input.store,runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,now:failureAt,leaseTtlMs:ttl,restarted:input.restarted,control:{authorityMode:control.authorityMode,healthStatus:'CRITICAL',newEconomicActionAllowed:false}});const evidence=await buildPhase7RuntimeEvidence({store:input.store,runtimeId:input.runtimeId,observedAt:failureAt,...(input.sourceCommit?{sourceCommit:input.sourceCommit}:{}),...(input.policyHash?{policyHash:input.policyHash}:{}),packId:`${input.runtimeId}:${input.cycleKey}:pack`});const implementationStatus=evidence.statuses.IMPLEMENTATION==='PASS'?'PASS':evidence.statuses.IMPLEMENTATION==='BLOCK'?'FAIL':'UNKNOWN';const operationalStatus=evidence.statuses.PRODUCTION==='PASS'?'PASS':evidence.statuses.PRODUCTION==='BLOCK'?'BLOCK':'HOLD';await input.store.insertPhase7EvidenceSnapshot({snapshotId:`${input.runtimeId}:${input.cycleKey}:snapshot`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:failureAt,implementationStatus,operationalStatus,payload:{statuses:evidence.statuses,facts:evidence.facts,reasonCodes:evidence.reasonCodes,operatorFailure:true}});if(evidence.pack)await input.store.insertPhase7EvidencePack({packHash:evidence.pack.packHash,packId:evidence.pack.packId,sourceCommit:evidence.pack.sourceCommit,policyHash:evidence.pack.policyHash,complete:evidence.pack.complete,operationalPass:evidence.pack.operationalPass,createdAt:evidence.pack.createdAt,payload:evidence.pack as unknown as Record<string,unknown>});return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,observedAt:failureAt,operatorFailure:true,health,drift,control,runtime,evidence,directSigner:false,directTransactionSend:false,mainnetTransactionSent:false};
  }
  const probeAt=new Date().toISOString();const observations=await collectPhase7LiveHealthObservations({assessmentAt:probeAt,poolAddress:input.cfg.smokePoolAddress,rpc,dataApi,store:input.store});const healthAt=new Date().toISOString();const health=assessPhase7Health(observations,defaultPhase7HealthPolicy,healthAt);await input.store.insertPhase7HealthAssessment({assessmentId:`${input.runtimeId}:${input.cycleKey}:health`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:healthAt,status:health.status,newEntriesAllowed:health.newEntriesAllowed,managementWritesAllowed:health.managementWritesAllowed,reasonCodes:health.reasonCodes,domainStatus:health.domainStatus,payload:{poolAddress:input.cfg.smokePoolAddress,observations,staleDomains:health.staleDomains,missingDomains:health.missingDomains}});
  const driftAt=new Date().toISOString(),since=new Date(Date.parse(driftAt)-24*3600_000).toISOString();const liveDrift=await assessPhase7LiveDrift({store:input.store,poolAddress:input.cfg.smokePoolAddress,since,observedAt:driftAt,baseline:input.driftBaseline,policy:defaultPhase7LiveDriftPolicy,decoderSkipRate:operator.eventDecodeWarnings/Math.max(1,operator.eventDecodeWarnings+operator.decodedSwapEvents)});const drift=liveDrift.assessment;await input.store.insertPhase7DriftAssessment({assessmentId:`${input.runtimeId}:${input.cycleKey}:drift`,policyHash:liveDrift.baselineHash,observedAt:driftAt,status:drift.status,sampleCount:drift.sampleCount,reasonCodes:drift.reasonCodes,deltas:drift.deltas,payload:{runtimeId:input.runtimeId,cycleKey:input.cycleKey,poolAddress:input.cfg.smokePoolAddress,current:liveDrift.current,coverage:{...liveDrift.coverage,decoderSkipTelemetry:true},operatorEventDecodeWarnings:operator.eventDecodeWarnings,operatorOutputBytes:operator.outputBytes,policyMutationAllowed:false,automaticPolicyPromotion:false}});
  const controlAt=new Date().toISOString();const authority=resolvePhase7Authority({config:loadPhase7ControlConfig(input.env),now:controlAt});const existing=(await input.store.loadActivePhase7Incidents()).map(incidentFromRow);const current=derivePhase7AutomaticIncidents({poolAddress:input.cfg.smokePoolAddress,observedAt:controlAt,health,drift});const updates=reconcilePhase7AutomaticIncidents({existing,current,observedAt:controlAt});for(const i of updates)await input.store.upsertPhase7IncidentState({incidentId:i.incidentId,incidentType:i.type,severity:i.severity,status:i.status,openedAt:i.openedAt,observedAt:controlAt,...(i.resolvedAt?{resolvedAt:i.resolvedAt}:{}),...(i.pool?{poolAddress:i.pool}:{}),...(i.token?{tokenMint:i.token}:{}),reasonCodes:i.reasonCodes,payload:{acknowledgedBy:i.acknowledgedBy??null,automatic:i.incidentId.startsWith('auto:')}});const active=updates.filter(i=>i.status!=='RESOLVED');const control=buildPhase7LiveControlDecision({authority,health,drift,incidents:active});await input.store.insertPhase7ControlDecision({decisionId:`${input.runtimeId}:${input.cycleKey}:control`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:controlAt,authorityMode:control.authorityMode,healthStatus:control.healthStatus,driftStatus:control.driftStatus,safetyMode:control.safety.mode,daemonPlan:control.daemonPlan,newEconomicActionAllowed:control.newEconomicActionAllowed,reasonCodes:control.reasonCodes,payload:{poolAddress:input.cfg.smokePoolAddress,activeIncidentIds:active.map(i=>i.incidentId),operator}});
  const runtime=await runPhase7RecoveryRuntimeTick({store:input.store,runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,now:new Date().toISOString(),leaseTtlMs:ttl,restarted:input.restarted,control:{authorityMode:control.authorityMode,healthStatus:control.healthStatus,newEconomicActionAllowed:control.newEconomicActionAllowed}});
  const evidenceAt=new Date().toISOString();const evidence=await buildPhase7RuntimeEvidence({store:input.store,runtimeId:input.runtimeId,observedAt:evidenceAt,...(input.sourceCommit?{sourceCommit:input.sourceCommit}:{}),...(input.policyHash?{policyHash:input.policyHash}:{}),packId:`${input.runtimeId}:${input.cycleKey}:pack`});const implementationStatus=evidence.statuses.IMPLEMENTATION==='PASS'?'PASS':evidence.statuses.IMPLEMENTATION==='BLOCK'?'FAIL':'UNKNOWN';const operationalStatus=evidence.statuses.PRODUCTION==='PASS'?'PASS':evidence.statuses.PRODUCTION==='BLOCK'?'BLOCK':'HOLD';await input.store.insertPhase7EvidenceSnapshot({snapshotId:`${input.runtimeId}:${input.cycleKey}:snapshot`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:evidenceAt,implementationStatus,operationalStatus,payload:{statuses:evidence.statuses,facts:evidence.facts,reasonCodes:evidence.reasonCodes,packHash:evidence.pack?.packHash??null}});if(evidence.pack)await input.store.insertPhase7EvidencePack({packHash:evidence.pack.packHash,packId:evidence.pack.packId,sourceCommit:evidence.pack.sourceCommit,policyHash:evidence.pack.policyHash,complete:evidence.pack.complete,operationalPass:evidence.pack.operationalPass,createdAt:evidence.pack.createdAt,payload:evidence.pack as unknown as Record<string,unknown>});return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,observedAt:evidenceAt,operator,health,drift,control,runtime,evidence,directSigner:false,directTransactionSend:false,mainnetTransactionSent:false};
}
export async function loadPhase7ProductionStatus(input:{store:Pick<Phase1Store,'loadLatestPhase7HealthAssessment'|'loadLatestPhase7DriftAssessment'|'loadLatestPhase7ControlDecision'|'loadRecentPhase7RuntimeCycles'|'loadLatestPhase7EvidenceSnapshot'>;runtimeId:string}){const [health,drift,control,runtime,evidence]=await Promise.all([input.store.loadLatestPhase7HealthAssessment(input.runtimeId),input.store.loadLatestPhase7DriftAssessment(),input.store.loadLatestPhase7ControlDecision(input.runtimeId),input.store.loadRecentPhase7RuntimeCycles(input.runtimeId,1),input.store.loadLatestPhase7EvidenceSnapshot(input.runtimeId)]);return{runtimeId:input.runtimeId,health,drift,control,runtime:runtime[0],evidence,directSigner:false,directTransactionSend:false};}
