// LPFORGE_PHASE7_RUNTIME_INTEGRATION_MODULE
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readFileSync,readdirSync} from 'node:fs';
import path from 'node:path';
import {Connection,PublicKey} from '@solana/web3.js';
import {loadDeploymentPolicyFile,type MainnetCanaryDeploymentPolicy} from '../../deployment-policy/src/index.js';
import {createMeteoraDataApi} from '../../data-api/src/index.js';
import type {Phase1Config} from '../../config/src/index.js';
import type {Phase1Store} from '../../db/src/index.js';
import {createMeteoraReadAdapter,createSolanaRpcClient} from '../../meteora/src/index.js';
import {derivePositionEconomics} from '../../live-exit-governor/src/index.js';
import {loadPhase7ControlConfig,loadPhase7ManualApproval,resolvePhase7Authority} from '../../phase7-authority/src/index.js';
import type {Phase7DriftAssessment,Phase7EvaluationMetrics} from '../../phase7-drift/src/index.js';
import {assessPhase7Health,defaultPhase7HealthPolicy,type Phase7HealthAssessment} from '../../phase7-health/src/index.js';
import type {Phase7Incident} from '../../phase7-incidents/src/index.js';
import {assessPhase7LiveDrift,defaultPhase7LiveDriftPolicy} from '../../phase7-live-drift/src/index.js';
import {buildPhase7LiveControlDecision,derivePhase7AutomaticIncidents,reconcilePhase7AutomaticIncidents} from '../../phase7-live-control/src/index.js';
import {buildPhase7RuntimeEvidence} from '../../phase7-live-evidence/src/index.js';
import {collectPhase7LiveHealthObservations} from '../../phase7-live-health/src/index.js';
import {runPhase7RecoveryRuntimeTick} from '../../phase7-live-runtime/src/index.js';
import {governPhase7Portfolio} from '../../phase7-portfolio-governor/src/index.js';

export interface Phase7OperatorProbe {exitCode:number;eventDecodeWarnings:number;transactionsScanned:number;decodedSwapEvents:number;operationalCycleComplete:boolean;outputBytes:number;poolAddresses:string[];}
export interface Phase7ProductionOnceResult {runtimeId:string;instanceId:string;cycleKey:string;observedAt:string;operator?:Phase7OperatorProbe;operatorFailure?:true;health?:Phase7HealthAssessment;drift?:Phase7DriftAssessment;control?:ReturnType<typeof buildPhase7LiveControlDecision>;runtime:Awaited<ReturnType<typeof runPhase7RecoveryRuntimeTick>>;evidence?:Awaited<ReturnType<typeof buildPhase7RuntimeEvidence>>;directSigner:false;directTransactionSend:false;mainnetTransactionSent:false;}
export interface ApprovedReleaseIdentity {sourceCommit:string;policyHash:string;migrationCount:number;migrationHead:string;buildIdentity:string;}
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
/** Compare the executing tree to the immutable release record. Any absence or
 * mismatch blocks only new exposure; protective paths remain available. */
export function assessPhase7ReleaseIdentity(input:{cwd:string;env:NodeJS.ProcessEnv;sourceCommit?:string;policyHash?:string}){const reasons:string[]=[];let approved:ApprovedReleaseIdentity|undefined;try{approved=JSON.parse(readFileSync(path.resolve(input.cwd,input.env.LPFORGE_APPROVED_RELEASE_IDENTITY_PATH?.trim()||'RELEASE_MANIFEST.json'),'utf8')) as ApprovedReleaseIdentity;}catch{reasons.push('P7_RELEASE_IDENTITY_MISSING');return{valid:false,reasonCodes:reasons};}const migrations=readdirSync(path.resolve(input.cwd,'packages/db/migrations')).filter(x=>/^M\d{4}_.+\.sql$/.test(x)).sort();const runtimePolicyHash=input.policyHash?.trim()||sha(readFileSync(path.resolve(input.cwd,input.env.LPFORGE_EXECUTION_POLICY_PATH?.trim()||'policies/live-execution-policy.json'),'utf8'));const runtimeBuild=input.env.LPFORGE_BUILD_ID?.trim();if(!input.sourceCommit?.trim()||approved.sourceCommit!==input.sourceCommit.trim())reasons.push('P7_RELEASE_SOURCE_MISMATCH');if(approved.policyHash!==runtimePolicyHash)reasons.push('P7_RELEASE_POLICY_MISMATCH');if(approved.migrationCount!==migrations.length||approved.migrationHead!==migrations.at(-1))reasons.push('P7_RELEASE_MIGRATION_MISMATCH');if(!runtimeBuild||approved.buildIdentity!==runtimeBuild)reasons.push('P7_RELEASE_BUILD_MISMATCH');return{valid:reasons.length===0,reasonCodes:reasons.sort(),approved,runtime:{sourceCommit:input.sourceCommit??'',policyHash:runtimePolicyHash,migrationCount:migrations.length,migrationHead:migrations.at(-1)??'',buildIdentity:runtimeBuild??''}};}
const WSOL_MINT='So11111111111111111111111111111111111111112';
const TOKEN_PROGRAM_ID='TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA';
export function positionUsdValueToSolLamports(currentEconomicValueUsd:number,solPriceUsd:number):bigint{
  if(!Number.isFinite(currentEconomicValueUsd)||currentEconomicValueUsd<0||!Number.isFinite(solPriceUsd)||solPriceUsd<=0)throw new Error('P7_PORTFOLIO_POSITION_VALUATION_UNAVAILABLE');
  return BigInt(Math.floor(currentEconomicValueUsd/solPriceUsd*1_000_000_000));
}
async function assessLivePortfolioAuthority(input:{store:Phase1Store;cfg:Phase1Config;env:NodeJS.ProcessEnv;now:string}){
  const owner=input.env.LPFORGE_OPERATOR_OWNER_ADDRESS?.trim();
  if(!owner)return{valid:false,reasonCodes:['P7_PORTFOLIO_OWNER_MISSING']};
  try{
    const policy=loadDeploymentPolicyFile(input.env.LPFORGE_EXECUTION_POLICY_PATH?.trim()||'policies/live-execution-policy.json'),capital=policy.productionCapital;
    if(!capital)return{valid:false,reasonCodes:['P7_PORTFOLIO_CAPITAL_POLICY_MISSING']};
    const connection=new Connection(input.cfg.solanaRpcHttpUrl,'confirmed');
    const [facts,prior,wallet,walletTokenAccounts,positions,ownedPoolHistory]=await Promise.all([
      input.store.loadPhase7PortfolioFacts(owner),
      input.store.loadPhase7PortfolioRiskState(owner),
      connection.getBalance(new PublicKey(owner),'confirmed'),
      connection.getParsedTokenAccountsByOwner(new PublicKey(owner),{programId:new PublicKey(TOKEN_PROGRAM_ID)},'confirmed'),
      input.store.loadOwnedPositions(owner),
      input.store.loadOwnedPoolHistory(owner),
    ]);
    const adapter=createMeteoraReadAdapter({rpcUrl:input.cfg.solanaRpcHttpUrl,cluster:input.cfg.cluster,programId:input.cfg.programId,expectedSdkVersion:input.cfg.expectedSdkVersion,rpcTimeoutMs:input.cfg.rpcTimeoutMs});
    const api=createMeteoraDataApi({baseUrl:input.cfg.meteoraDataApiUrl,maxRps:input.cfg.dataApiMaxRps,timeoutMs:input.cfg.httpTimeoutMs});
    const valuations=await Promise.all(positions.map(async row=>{
      const poolAddress=String(row.pool_address),positionAddress=String(row.position_address),initialCapitalLamports=BigInt(String(row.initial_capital_lamports));
      const [position,pool,account]=await Promise.all([adapter.getPositionV2(poolAddress,positionAddress),api.getPool(poolAddress),connection.getAccountInfo(new PublicKey(positionAddress),'confirmed')]);
      const sol=[pool.token_x,pool.token_y].find(token=>token?.address===WSOL_MINT);
      const economics=derivePositionEconomics({position,pool,initialCapitalLamports,observedAt:input.now});
      return {positionAddress,pool,lamports:positionUsdValueToSolLamports(economics.currentEconomicValueUsd??Number.NaN,sol?.price??Number.NaN),recoverableRentLamports:BigInt(account?.lamports??0)};
    }));
    if(positions.length!==facts.openPositions)throw new Error('P7_PORTFOLIO_POSITION_FACT_MISMATCH');
    const positionValueLamports=valuations.reduce((sum,value)=>sum+value.lamports,0n);
    // Wallet token balances are priced with the same pool feed that prices the
    // owned positions. Tokens unknown to the feed, and tokens without a WSOL
    // conversion price, are excluded rather than overstating NAV with guesses.
    const tokenPrices=new Map<string,number>();
    for(const value of valuations)for(const token of [value.pool.token_x,value.pool.token_y])if(token?.address&&typeof token.price==='number'&&Number.isFinite(token.price)&&token.price>0)tokenPrices.set(token.address,token.price);
    // A paired-token balance can outlive its LP account after CLOSE/CLAIM.
    // Keep every LPForge-owned pool as a price source so that residual wallet
    // inventory remains in NAV even when there are no open positions.
    for(const history of ownedPoolHistory)try{const pool=await api.getPool(history.poolAddress);for(const token of [pool.token_x,pool.token_y])if(token?.address&&typeof token.price==='number'&&Number.isFinite(token.price)&&token.price>0)tokenPrices.set(token.address,token.price);}catch{/* a missing historical price is excluded conservatively */}
    const solPriceUsd=tokenPrices.get(WSOL_MINT);
    let walletTokenValueLamports=0n;const valuedWalletTokens:{mint:string;amount:string;usdValue:number;lamports:string}[]=[];
    if(solPriceUsd)for(const account of walletTokenAccounts.value){
      const info=(account.account.data.parsed as {info?:{mint?:string;tokenAmount?:{amount?:string;decimals?:number}}}).info;
      const mint=info?.mint,amount=info?.tokenAmount?.amount,decimals=info?.tokenAmount?.decimals;
      if(!mint||!amount||typeof decimals!=='number')continue;
      const price=tokenPrices.get(mint);
      if(price===undefined)continue;
      const usd=Number(amount)/10**decimals*price;
      if(!Number.isFinite(usd)||usd<0)continue;
      const lamports=positionUsdValueToSolLamports(usd,solPriceUsd);
      walletTokenValueLamports+=lamports;
      valuedWalletTokens.push({mint,amount,usdValue:usd,lamports:lamports.toString()});
    }
    // Rent locked in open position accounts is book-value equity: it returns to
    // the operator when the position is closed.
    const rentReserveLamports=valuations.reduce((sum,value)=>sum+value.recoverableRentLamports,0n);
    const valuationMethod='POSITION_AND_WALLET_TOKENS_USD_TO_SOL_V2',priorPayload=(prior?.payload??{}) as Record<string,unknown>,dayStart=new Date(Date.UTC(new Date(input.now).getUTCFullYear(),new Date(input.now).getUTCMonth(),new Date(input.now).getUTCDate())).toISOString(),sameDay=Boolean(prior&&new Date(String(prior.day_start)).toISOString()===dayStart&&priorPayload.valuationMethod===valuationMethod),current=BigInt(wallet)+positionValueLamports+walletTokenValueLamports+rentReserveLamports,daily=sameDay?BigInt(String(prior!.daily_start_equity_lamports)):current,peak=sameDay?([BigInt(String(prior!.peak_equity_lamports)),current].reduce((a,b)=>a>b?a:b)):current;
    const decision=governPhase7Portfolio({observedAt:input.now,walletBalanceLamports:BigInt(wallet),deployedLamports:facts.deployedLamports,pendingReservedLamports:facts.pendingReservedLamports,poolExposureLamports:facts.poolExposureLamports,poolPendingLamports:facts.poolPendingLamports,tokenExposureLamports:facts.tokenExposureLamports,tokenPendingLamports:facts.tokenPendingLamports,dailyStartEquityLamports:daily,currentEquityLamports:current,peakEquityLamports:peak,openPositions:facts.openPositions,unresolvedReconciliationDebt:facts.unresolvedReconciliationDebt},{requestId:`p7-health-${input.now}`,pool:'__P7_HEALTH__',token:'__P7_HEALTH__',requestedLamports:1n,action:'OPEN',now:input.now},{minReserveLamports:capital.reserveLamports,maxDeployedBps:10000,maxPoolBps:10000,maxTokenBps:10000,maxDailyDrawdownBps:Number(input.env.LPFORGE_P7_MAX_DAILY_DRAWDOWN_BPS??600),maxRollingDrawdownBps:Number(input.env.LPFORGE_P7_MAX_ROLLING_DRAWDOWN_BPS??1000),maxOpenPositions:policy.maxOpenPositions,maxSnapshotAgeMs:60_000,permitTtlMs:60_000});
    await input.store.upsertPhase7PortfolioRiskState({ownerAddress:owner,dayStart,dailyStartEquityLamports:daily,peakEquityLamports:peak,currentEquityLamports:current,observedAt:input.now,valuationState:'RECONCILED',reasonCodes:[...(sameDay?[]:['P7_PORTFOLIO_VALUATION_BASELINE_RESET']),...decision.reasonCodes],payload:{valuationMethod,walletLamports:String(wallet),positionValueLamports:positionValueLamports.toString(),valuedPositions:valuations.map(value=>({positionAddress:value.positionAddress,lamports:value.lamports.toString(),recoverableRentLamports:value.recoverableRentLamports.toString()})),walletTokenValueLamports:walletTokenValueLamports.toString(),valuedWalletTokens,rentReserveLamports:rentReserveLamports.toString(),deployedLamports:facts.deployedLamports.toString(),pendingReservedLamports:facts.pendingReservedLamports.toString()}});
    return{valid:decision.decision==='APPROVE',reasonCodes:decision.reasonCodes,facts};
  }catch(error){
    const code=error instanceof Error?error.message:'';
    return{valid:false,reasonCodes:[code==='P7_PORTFOLIO_POSITION_VALUATION_UNAVAILABLE'?code:'P7_PORTFOLIO_FACTS_UNAVAILABLE']};
  }
}
function healthFromRow(row:Record<string,unknown>):Phase7HealthAssessment{const payload=(row.payload??{}) as Record<string,unknown>;return{status:String(row.status) as Phase7HealthAssessment['status'],observedAt:new Date(String(row.observed_at)).toISOString(),domainStatus:(row.domain_status??{}) as Phase7HealthAssessment['domainStatus'],staleDomains:(payload.staleDomains??[]) as Phase7HealthAssessment['staleDomains'],missingDomains:(payload.missingDomains??[]) as Phase7HealthAssessment['missingDomains'],reasonCodes:(row.reason_codes??[]) as string[],newEntriesAllowed:Boolean(row.new_entries_allowed),managementWritesAllowed:Boolean(row.management_writes_allowed),emergencyCloseAllowed:true};}
function driftFromRow(row:Record<string,unknown>):Phase7DriftAssessment{return{status:String(row.status) as Phase7DriftAssessment['status'],reasonCodes:(row.reason_codes??[]) as string[],observedAt:new Date(String(row.observed_at)).toISOString(),sampleCount:Number(row.sample_count),newEntriesAllowed:String(row.status)!=='BLOCK',managementAllowed:true,policyMutationAllowed:false,automaticPolicyPromotion:false,deltas:(row.deltas??{}) as Record<string,number>};}
function incidentFromRow(row:Record<string,unknown>):Phase7Incident{return{incidentId:String(row.incident_id),type:String(row.incident_type) as Phase7Incident['type'],severity:String(row.severity) as Phase7Incident['severity'],openedAt:new Date(String(row.opened_at)).toISOString(),status:String(row.status) as Phase7Incident['status'],reasonCodes:(row.reason_codes??[]) as string[],...(row.pool_address?{pool:String(row.pool_address)}:{}),...(row.token_mint?{token:String(row.token_mint)}:{}),...(row.resolved_at?{resolvedAt:new Date(String(row.resolved_at)).toISOString()}:{}),...((row.payload as Record<string,unknown>|undefined)?.acknowledgedBy?{acknowledgedBy:String((row.payload as Record<string,unknown>).acknowledgedBy)}:{})};}
export function productionPoolAddressesFromPolicy(policy:Pick<MainnetCanaryDeploymentPolicy,'pools'>){return[...new Set(policy.pools.map(pool=>pool.address))];}
/** The enabled execution policy is the sole source of the production universe. */
export function productionPoolAddresses(env:NodeJS.ProcessEnv){const path=env.LPFORGE_EXECUTION_POLICY_PATH?.trim()||'policies/live-execution-policy.json';return productionPoolAddressesFromPolicy(loadDeploymentPolicyFile(path));}
/** Discovery is advisory. Its candidates may be observed by the operator only when explicitly enabled, and never modify execution policy. */
/**
 * Static policy pools are evaluated every cycle.  Tier-A discovery candidates
 * are evaluated in a bounded round-robin so a growing candidate set cannot
 * turn the Phase-7 health probe into an RPC burst.
 */
export async function productionEvaluationPoolAddresses(store:Pick<Phase1Store,'listDiscoveryCandidates'>,env:NodeJS.ProcessEnv,rotationKey=''){const manual=productionPoolAddresses(env);if((env.LPFORGE_DISCOVERY_OPERATOR_ENABLED??'false').toLowerCase()!=='true')return manual;const discovered=await store.listDiscoveryCandidates(['A']);const max=Math.max(1,Math.min(10,Number(env.LPFORGE_PRODUCTION_OPERATOR_MAX_POOLS??10)));if(discovered.length===0)return manual;const rotation=[...rotationKey].reduce((sum,char)=>(sum*31+char.charCodeAt(0))>>>0,0)%discovered.length;const selected=Array.from({length:Math.min(max,discovered.length)},(_,index)=>discovered[(rotation+index)%discovered.length]!);return[...new Set([...manual,...selected.map(x=>x.poolAddress)])];}
export function parsePhase7OperatorProbeOutput(combined:string,exitCode:number,poolAddress?:string):Phase7OperatorProbe{const legacyWarnings=(combined.match(/meteora_event_decode_quarantined/g)??[]).length;const machineLine=combined.split(/\r?\n/).find(line=>line.includes('\"event\":\"lpforge_operator_machine_summary\"'));const legacyLine=combined.split(/\r?\n/).find(line=>line.includes('\"event\":\"meteora_ingestion_summary\"'));let transactionsScanned=0,decodedSwapEvents=0,eventDecodeWarnings=legacyWarnings,complete=false;for(const line of [machineLine,legacyLine]){if(!line)continue;try{const x=JSON.parse(line) as Record<string,unknown>;transactionsScanned=Number(x.transactionsScanned??transactionsScanned);decodedSwapEvents=Number(x.decodedSwapEvents??decodedSwapEvents);eventDecodeWarnings=Number(x.eventDecodeWarnings??eventDecodeWarnings);if(x.event==='lpforge_operator_machine_summary')complete=true;}catch{}}if(!complete)complete=combined.includes('operational_cycle_complete');return{exitCode,eventDecodeWarnings,transactionsScanned,decodedSwapEvents,operationalCycleComplete:complete,outputBytes:combined.length,poolAddresses:poolAddress?[poolAddress]:[]};}
function redactProbeFailureDetail(value:string){return value.replace(/https?:\/\/[^\s"']+/gi,'<redacted-url>').replace(/(?:api[-_]?key|token|secret|password)=[^\s&"']+/gi,'$1=<redacted>').replace(/\s+/g,' ').trim().slice(-500);}
export async function runAutonomousDecisionProbe(input:{cwd:string;env:NodeJS.ProcessEnv;poolAddress?:string}):Promise<Phase7OperatorProbe>{
  // The operator needs only the public owner address to persist a plan.  It never
  // receives signing authority; the separately supervised execution worker is
  // the only process that loads the local signer configuration.
  const poolAddress=input.poolAddress??input.env.LPFORGE_SMOKE_POOL_ADDRESS?.trim();const configuredBackfill=Number(input.env.LPFORGE_P7_OPERATOR_EVENT_BACKFILL_LIMIT??input.env.EVENT_BACKFILL_LIMIT??10),productionRpcInterval=input.env.LPFORGE_PRODUCTION_RPC_MIN_INTERVAL_MS??input.env.RPC_MIN_INTERVAL_MS;const childEnv:{[key:string]:string|undefined}={...input.env,LIVE_SIGNING:'false',LPFORGE_LIVE_EXECUTION:'false',LPFORGE_MAINNET_CANARY:'false',LPFORGE_DATA_MODE:'LIVE_READ_ONLY',LPFORGE_OPERATOR_MACHINE_SUMMARY:'true',EVENT_BACKFILL_LIMIT:String(Math.max(1,Math.min(10,configuredBackfill)),),...(productionRpcInterval?{RPC_MIN_INTERVAL_MS:productionRpcInterval}:{}),...(poolAddress?{LPFORGE_SMOKE_POOL_ADDRESS:poolAddress}:{})};delete childEnv.LPFORGE_PREPARE_POSITION_ADDRESS;
  return new Promise((resolve,reject)=>{const child=spawn('node',['--enable-source-maps','.build/apps/operator/src/main.js','live-once'],{cwd:input.cwd,env:childEnv,stdio:['ignore','pipe','pipe']});let out='',err='';child.stdout?.on('data',x=>{out+=String(x);});child.stderr?.on('data',x=>{err+=String(x);});child.on('error',reject);child.on('close',code=>{const combined=out+'\n'+err;const exitCode=code??1;if(exitCode!==0)return reject(new Error(`LPFORGE_P7_OPERATOR_PROBE_FAILED:${exitCode}:${redactProbeFailureDetail(err||out)}`));resolve(parsePhase7OperatorProbeOutput(combined,exitCode,poolAddress));});});
}
export async function runPhase7ProductionOnce(input:{cfg:Phase1Config;store:Phase1Store;runtimeId:string;instanceId:string;cycleKey:string;driftBaseline:Phase7EvaluationMetrics;sourceCommit?:string;policyHash?:string;cwd:string;env:NodeJS.ProcessEnv;leaseTtlMs?:number;restarted:boolean}):Promise<Phase7ProductionOnceResult>{
  const startedAt=new Date().toISOString();if(!input.cfg.smokePoolAddress)throw new Error('LPFORGE_CONFIG_REQUIRED:LPFORGE_SMOKE_POOL_ADDRESS');const ttl=input.leaseTtlMs??60_000;const lease=await input.store.claimPhase7RuntimeLease({runtimeId:input.runtimeId,holderId:input.instanceId,now:startedAt,expiresAt:new Date(Date.parse(startedAt)+ttl).toISOString()});if(!lease){const runtime={runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,leaseAcquired:false,recoveryScanCompleted:false,recoveryFacts:{previousCompletedCycleKeys:[],completedEconomicActionKeys:[],recoveryQueueCount:0,unknownSubmissionCount:0,unresolvedReconciliationDebt:0},plan:'HOLD' as const,reasonCodes:['P7_RUNTIME_LEASE_HELD_BY_OTHER'],newEconomicActionAllowed:false,cycleInserted:false,requiresExistingExecutionWorkflow:true as const,directSigner:false as const,directTransactionSend:false as const};return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,observedAt:startedAt,runtime,directSigner:false,directTransactionSend:false,mainnetTransactionSent:false};}
  const recovery=await input.store.loadPhase7RecoveryFacts(input.runtimeId);if(recovery.recoveryQueueCount>0||recovery.unknownSubmissionCount>0||recovery.unresolvedReconciliationDebt>0||recovery.partialEntryRecoveryCount>0){const runtime=await runPhase7RecoveryRuntimeTick({store:input.store,runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,now:new Date().toISOString(),leaseTtlMs:ttl,restarted:input.restarted,control:{authorityMode:'OBSERVE_ONLY',healthStatus:'CRITICAL',newEconomicActionAllowed:false}});return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,observedAt:new Date().toISOString(),runtime,directSigner:false,directTransactionSend:false,mainnetTransactionSent:false};}
  const productionRpcInterval=Math.max(0,Number(input.env.LPFORGE_PRODUCTION_RPC_MIN_INTERVAL_MS??input.cfg.rpcMinIntervalMs));const rpc=createSolanaRpcClient({url:input.cfg.solanaRpcHttpUrl,timeoutMs:input.cfg.rpcTimeoutMs,minIntervalMs:productionRpcInterval,maxRetries:input.cfg.rpcMaxRetries,retryBaseDelayMs:input.cfg.rpcRetryBaseDelayMs,retryMaxDelayMs:input.cfg.rpcRetryMaxDelayMs});const dataApi=createMeteoraDataApi({baseUrl:input.cfg.meteoraDataApiUrl,maxRps:input.cfg.dataApiMaxRps,timeoutMs:input.cfg.httpTimeoutMs});
  // Health, drift and the control decision persist BEFORE the operator probes
  // so the operator's own control read sees this cycle's decision — never the
  // previous cycle's. Probe outputs (decoder telemetry, probed pools) lag one
  // cycle through the stored evidence snapshot; health and drift inputs never
  // depend on the probe at all.
  const probeAt=new Date().toISOString();const observations=await collectPhase7LiveHealthObservations({assessmentAt:probeAt,poolAddress:input.cfg.smokePoolAddress,rpc,dataApi,store:input.store});const healthAt=new Date().toISOString();const health=assessPhase7Health(observations,defaultPhase7HealthPolicy,healthAt);await input.store.insertPhase7HealthAssessment({assessmentId:`${input.runtimeId}:${input.cycleKey}:health`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:healthAt,status:health.status,newEntriesAllowed:health.newEntriesAllowed,managementWritesAllowed:health.managementWritesAllowed,reasonCodes:health.reasonCodes,domainStatus:health.domainStatus,payload:{poolAddress:input.cfg.smokePoolAddress,observations,staleDomains:health.staleDomains,missingDomains:health.missingDomains}});
  const driftAt=new Date().toISOString(),since=new Date(Date.parse(driftAt)-24*3600_000).toISOString();
  const priorEvidenceRow=await input.store.loadLatestPhase7EvidenceSnapshot(input.runtimeId),priorEvidencePayload=(priorEvidenceRow?.payload??{}) as Record<string,unknown>,priorDriftRow=await input.store.loadLatestPhase7DriftAssessment(),priorDriftPayload=(priorDriftRow?.payload??{}) as Record<string,unknown>;
  const telemetryWarnings=Number(priorEvidencePayload.operatorEventDecodeWarnings??priorDriftPayload.operatorEventDecodeWarnings??NaN),telemetrySwaps=Number(priorEvidencePayload.operatorDecodedSwapEvents??priorDriftPayload.operatorDecodedSwapEvents??NaN),telemetryBytes=Number(priorEvidencePayload.operatorOutputBytes??priorDriftPayload.operatorOutputBytes??NaN);
  const decoderSkipRate=Number.isFinite(telemetryWarnings)&&Number.isFinite(telemetrySwaps)?telemetryWarnings/Math.max(1,telemetryWarnings+telemetrySwaps):undefined;
  // Drift is assessed per pool over the exact set the operator probes this
  // cycle. The smoke pool stays the full-weight RPC-liveness anchor; other
  // probed pools count at full weight only when they carry deployed capital
  // or open positions, otherwise at most WATCH — an idle candidate pool can
  // never BLOCK the system.
  const ownerAddress=input.env.LPFORGE_OPERATOR_OWNER_ADDRESS?.trim(),capitalPools=new Set<string>(),openPools=new Set<string>();
  if(ownerAddress){try{const [portfolioFacts,ownedRows]=await Promise.all([input.store.loadPhase7PortfolioFacts(ownerAddress),input.store.loadOwnedPositions(ownerAddress)]);for(const [poolAddress,lamports] of Object.entries(portfolioFacts.poolExposureLamports))if(lamports>0n)capitalPools.add(poolAddress);for(const row of ownedRows)if(String(row.lifecycle_state)!=='CLOSED'&&row.pool_address)openPools.add(String(row.pool_address));}catch{/* portfolio facts are advisory here; unreadable pools default to idle (WATCH-capped) */}}
  // Snapshot the dynamic Tier-A universe once. Discovery may mutate it while
  // this cycle runs; health, drift, persisted control and operator probes must
  // all describe the same immutable target set.
  const evaluationPoolAddresses=await productionEvaluationPoolAddresses(input.store,input.env,input.cycleKey),driftPoolAddresses=[...new Set([input.cfg.smokePoolAddress,...evaluationPoolAddresses])];
  const poolDrift:{poolAddress:string;status:Phase7DriftAssessment['status'];significant:boolean;deltas:Record<string,number>;sampleCount:number;reasonCodes:string[]}[]=[];
  let smokeLive:Awaited<ReturnType<typeof assessPhase7LiveDrift>>|undefined;
  for(const poolAddress of driftPoolAddresses){
    const liveDrift=await assessPhase7LiveDrift({store:input.store,poolAddress,since,observedAt:driftAt,baseline:input.driftBaseline,policy:defaultPhase7LiveDriftPolicy,...(decoderSkipRate!==undefined?{decoderSkipRate}:{})});
    poolDrift.push({poolAddress,status:liveDrift.assessment.status,significant:poolAddress===input.cfg.smokePoolAddress||capitalPools.has(poolAddress)||openPools.has(poolAddress),deltas:liveDrift.assessment.deltas,sampleCount:liveDrift.assessment.sampleCount,reasonCodes:liveDrift.assessment.reasonCodes});
    if(poolAddress===input.cfg.smokePoolAddress)smokeLive=liveDrift;
  }
  if(!smokeLive)throw new Error('LPFORGE_P7_DRIFT_SMOKE_POOL_MISSING');
  const rank=(status:Phase7DriftAssessment['status'])=>status==='BLOCK'?2:status==='WATCH'?1:0;
  const cappedDrift=poolDrift.map(p=>({...p,rawStatus:p.status,status:p.significant?p.status:(rank(p.status)>rank('WATCH')?'WATCH':p.status)}));
  const overallStatus=cappedDrift.reduce((worst,p)=>rank(p.status)>rank(worst)?p.status:worst,smokeLive.assessment.status);
  const drift:Phase7DriftAssessment={...smokeLive.assessment,status:overallStatus,reasonCodes:[...new Set([...smokeLive.assessment.reasonCodes,...cappedDrift.filter(p=>p.status!=='STABLE').map(p=>`P7_LIVE_DRIFT_POOL_${p.status}`)])].sort(),newEntriesAllowed:overallStatus!=='BLOCK'};
  await input.store.insertPhase7DriftAssessment({assessmentId:`${input.runtimeId}:${input.cycleKey}:drift`,policyHash:smokeLive.baselineHash,observedAt:driftAt,status:drift.status,sampleCount:drift.sampleCount,reasonCodes:drift.reasonCodes,deltas:drift.deltas,payload:{runtimeId:input.runtimeId,cycleKey:input.cycleKey,poolAddress:input.cfg.smokePoolAddress,current:smokeLive.current,coverage:{...smokeLive.coverage,decoderSkipTelemetry:decoderSkipRate!==undefined},probedPoolAddresses:driftPoolAddresses,poolDrift:cappedDrift.map(p=>({poolAddress:p.poolAddress,status:p.status,rawStatus:p.rawStatus,significant:p.significant,deltas:p.deltas,sampleCount:p.sampleCount,reasonCodes:p.reasonCodes})),operatorEventDecodeWarnings:Number.isFinite(telemetryWarnings)?telemetryWarnings:null,operatorDecodedSwapEvents:Number.isFinite(telemetrySwaps)?telemetrySwaps:null,operatorOutputBytes:Number.isFinite(telemetryBytes)?telemetryBytes:null,policyMutationAllowed:false,automaticPolicyPromotion:false}});
  const controlAt=new Date().toISOString(),approval=loadPhase7ManualApproval(input.env),authority=resolvePhase7Authority({config:loadPhase7ControlConfig(input.env),now:controlAt,...(approval?{approval}:{})}),existing=(await input.store.loadActivePhase7Incidents()).map(incidentFromRow),current=derivePhase7AutomaticIncidents({poolAddress:input.cfg.smokePoolAddress,observedAt:controlAt,health,drift}),updates=reconcilePhase7AutomaticIncidents({existing,current,observedAt:controlAt});
  for(const i of updates)await input.store.upsertPhase7IncidentState({incidentId:i.incidentId,incidentType:i.type,severity:i.severity,status:i.status,openedAt:i.openedAt,observedAt:controlAt,...(i.resolvedAt?{resolvedAt:i.resolvedAt}:{}),...(i.pool?{poolAddress:i.pool}:{}),...(i.token?{tokenMint:i.token}:{}),reasonCodes:i.reasonCodes,payload:{acknowledgedBy:i.acknowledgedBy??null,automatic:i.incidentId.startsWith('auto:')}});
  const active=updates.filter(i=>i.status!=='RESOLVED'),releaseIdentity=assessPhase7ReleaseIdentity({cwd:input.cwd,env:input.env,...(input.sourceCommit?{sourceCommit:input.sourceCommit}:{}),...(input.policyHash?{policyHash:input.policyHash}:{})}),portfolio=await assessLivePortfolioAuthority({store:input.store,cfg:input.cfg,env:input.env,now:controlAt}),control=buildPhase7LiveControlDecision({authority,health,drift,incidents:active,releaseIdentity:{valid:releaseIdentity.valid&&portfolio.valid,reasonCodes:[...releaseIdentity.reasonCodes,...portfolio.reasonCodes]}}),priorControlRow=await input.store.loadLatestPhase7ControlDecision(input.runtimeId),priorControlPayload=(priorControlRow?.payload??{}) as Record<string,unknown>;
  await input.store.insertPhase7ControlDecision({decisionId:`${input.runtimeId}:${input.cycleKey}:control`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:controlAt,authorityMode:control.authorityMode,healthStatus:control.healthStatus,driftStatus:control.driftStatus,safetyMode:control.safety.mode,daemonPlan:control.daemonPlan,newEconomicActionAllowed:control.newEconomicActionAllowed,reasonCodes:control.reasonCodes,payload:{poolAddress:input.cfg.smokePoolAddress,activeIncidentIds:active.map(i=>i.incidentId),operator:priorControlPayload.operator??null,releaseIdentity,portfolio,poolDrift:cappedDrift.map(p=>({poolAddress:p.poolAddress,status:p.status,rawStatus:p.rawStatus,significant:p.significant}))}});
  let operator:Phase7OperatorProbe;
  try{const probes:Phase7OperatorProbe[]=[];for(const poolAddress of evaluationPoolAddresses)probes.push(await runAutonomousDecisionProbe({cwd:input.cwd,env:input.env,poolAddress}));if(probes.some(probe=>!probe.operationalCycleComplete))throw new Error('LPFORGE_P7_OPERATOR_CYCLE_COMPLETION_MISSING');operator={exitCode:0,eventDecodeWarnings:probes.reduce((sum,probe)=>sum+probe.eventDecodeWarnings,0),transactionsScanned:probes.reduce((sum,probe)=>sum+probe.transactionsScanned,0),decodedSwapEvents:probes.reduce((sum,probe)=>sum+probe.decodedSwapEvents,0),operationalCycleComplete:true,outputBytes:probes.reduce((sum,probe)=>sum+probe.outputBytes,0),poolAddresses:probes.flatMap(probe=>probe.poolAddresses)};}
  catch(error){
    const operatorFailureReason=redactProbeFailureDetail(error instanceof Error?error.message:String(error));
    const failureAt=new Date().toISOString();const observations=await collectPhase7LiveHealthObservations({assessmentAt:failureAt,poolAddress:input.cfg.smokePoolAddress,rpc,dataApi,store:input.store});observations.push({domain:'DECISION',observedAt:failureAt,status:'CRITICAL',reasonCodes:['P7_LIVE_OPERATOR_CYCLE_FAILED']});const health=assessPhase7Health(observations,defaultPhase7HealthPolicy,failureAt);await input.store.insertPhase7HealthAssessment({assessmentId:`${input.runtimeId}:${input.cycleKey}:health:failure`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:failureAt,status:health.status,newEntriesAllowed:false,managementWritesAllowed:false,reasonCodes:health.reasonCodes,domainStatus:health.domainStatus,payload:{poolAddress:input.cfg.smokePoolAddress,observations,staleDomains:health.staleDomains,missingDomains:health.missingDomains,operatorFailure:true,operatorFailureReason}});
    const drift:Phase7DriftAssessment={status:'BLOCK',reasonCodes:['P7_DRIFT_OPERATOR_CYCLE_UNAVAILABLE'],observedAt:failureAt,sampleCount:0,newEntriesAllowed:false,managementAllowed:true,policyMutationAllowed:false,automaticPolicyPromotion:false,deltas:{}};await input.store.insertPhase7DriftAssessment({assessmentId:`${input.runtimeId}:${input.cycleKey}:drift:failure`,observedAt:failureAt,status:'BLOCK',sampleCount:0,reasonCodes:drift.reasonCodes,deltas:{},payload:{runtimeId:input.runtimeId,cycleKey:input.cycleKey,poolAddress:input.cfg.smokePoolAddress,operatorFailure:true,operatorFailureReason,policyMutationAllowed:false,automaticPolicyPromotion:false}});
    const approval=loadPhase7ManualApproval(input.env);const authority=resolvePhase7Authority({config:loadPhase7ControlConfig(input.env),now:failureAt,...(approval?{approval}:{})});const existing=(await input.store.loadActivePhase7Incidents()).map(incidentFromRow);const current=derivePhase7AutomaticIncidents({poolAddress:input.cfg.smokePoolAddress,observedAt:failureAt,health,drift});const updates=reconcilePhase7AutomaticIncidents({existing,current,observedAt:failureAt});for(const i of updates)await input.store.upsertPhase7IncidentState({incidentId:i.incidentId,incidentType:i.type,severity:i.severity,status:i.status,openedAt:i.openedAt,observedAt:failureAt,...(i.resolvedAt?{resolvedAt:i.resolvedAt}:{}),...(i.pool?{poolAddress:i.pool}:{}),...(i.token?{tokenMint:i.token}:{}),reasonCodes:i.reasonCodes,payload:{acknowledgedBy:i.acknowledgedBy??null,automatic:i.incidentId.startsWith('auto:')}});const active=updates.filter(i=>i.status!=='RESOLVED');const control=buildPhase7LiveControlDecision({authority,health,drift,incidents:active});await input.store.insertPhase7ControlDecision({decisionId:`${input.runtimeId}:${input.cycleKey}:control:failure`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:failureAt,authorityMode:control.authorityMode,healthStatus:control.healthStatus,driftStatus:control.driftStatus,safetyMode:control.safety.mode,daemonPlan:control.daemonPlan,newEconomicActionAllowed:false,reasonCodes:control.reasonCodes,payload:{poolAddress:input.cfg.smokePoolAddress,activeIncidentIds:active.map(i=>i.incidentId),operatorFailure:true,operatorFailureReason}});
    const runtime=await runPhase7RecoveryRuntimeTick({store:input.store,runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,now:failureAt,leaseTtlMs:ttl,restarted:input.restarted,control:{authorityMode:control.authorityMode,healthStatus:'CRITICAL',newEconomicActionAllowed:false}});const evidence=await buildPhase7RuntimeEvidence({store:input.store,runtimeId:input.runtimeId,observedAt:failureAt,...(input.sourceCommit?{sourceCommit:input.sourceCommit}:{}),...(input.policyHash?{policyHash:input.policyHash}:{}),packId:`${input.runtimeId}:${input.cycleKey}:pack`});const implementationStatus=evidence.statuses.IMPLEMENTATION==='PASS'?'PASS':evidence.statuses.IMPLEMENTATION==='BLOCK'?'FAIL':'UNKNOWN';const operationalStatus=evidence.statuses.PRODUCTION==='PASS'?'PASS':evidence.statuses.PRODUCTION==='BLOCK'?'BLOCK':'HOLD';await input.store.insertPhase7EvidenceSnapshot({snapshotId:`${input.runtimeId}:${input.cycleKey}:snapshot`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:failureAt,implementationStatus,operationalStatus,payload:{statuses:evidence.statuses,facts:evidence.facts,reasonCodes:evidence.reasonCodes,operatorFailure:true,operatorFailureReason,operatorEventDecodeWarnings:Number.isFinite(telemetryWarnings)?telemetryWarnings:null,operatorDecodedSwapEvents:Number.isFinite(telemetrySwaps)?telemetrySwaps:null,operatorOutputBytes:Number.isFinite(telemetryBytes)?telemetryBytes:null}});if(evidence.pack)await input.store.insertPhase7EvidencePack({packHash:evidence.pack.packHash,packId:evidence.pack.packId,sourceCommit:evidence.pack.sourceCommit,policyHash:evidence.pack.policyHash,complete:evidence.pack.complete,operationalPass:evidence.pack.operationalPass,createdAt:evidence.pack.createdAt,payload:evidence.pack as unknown as Record<string,unknown>});return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,observedAt:failureAt,operatorFailure:true,health,drift,control,runtime,evidence,directSigner:false,directTransactionSend:false,mainnetTransactionSent:false};
  }
  const runtime=await runPhase7RecoveryRuntimeTick({store:input.store,runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,now:new Date().toISOString(),leaseTtlMs:ttl,restarted:input.restarted,control:{authorityMode:control.authorityMode,healthStatus:control.healthStatus,newEconomicActionAllowed:control.newEconomicActionAllowed}});
  const evidenceAt=new Date().toISOString();const evidence=await buildPhase7RuntimeEvidence({store:input.store,runtimeId:input.runtimeId,observedAt:evidenceAt,...(input.sourceCommit?{sourceCommit:input.sourceCommit}:{}),...(input.policyHash?{policyHash:input.policyHash}:{}),packId:`${input.runtimeId}:${input.cycleKey}:pack`});const implementationStatus=evidence.statuses.IMPLEMENTATION==='PASS'?'PASS':evidence.statuses.IMPLEMENTATION==='BLOCK'?'FAIL':'UNKNOWN';const operationalStatus=evidence.statuses.PRODUCTION==='PASS'?'PASS':evidence.statuses.PRODUCTION==='BLOCK'?'BLOCK':'HOLD';await input.store.insertPhase7EvidenceSnapshot({snapshotId:`${input.runtimeId}:${input.cycleKey}:snapshot`,runtimeId:input.runtimeId,cycleKey:input.cycleKey,observedAt:evidenceAt,implementationStatus,operationalStatus,payload:{statuses:evidence.statuses,facts:evidence.facts,reasonCodes:evidence.reasonCodes,packHash:evidence.pack?.packHash??null,operatorEventDecodeWarnings:operator.eventDecodeWarnings,operatorDecodedSwapEvents:operator.decodedSwapEvents,operatorOutputBytes:operator.outputBytes,probedPoolAddresses:operator.poolAddresses}});if(evidence.pack)await input.store.insertPhase7EvidencePack({packHash:evidence.pack.packHash,packId:evidence.pack.packId,sourceCommit:evidence.pack.sourceCommit,policyHash:evidence.pack.policyHash,complete:evidence.pack.complete,operationalPass:evidence.pack.operationalPass,createdAt:evidence.pack.createdAt,payload:evidence.pack as unknown as Record<string,unknown>});return{runtimeId:input.runtimeId,instanceId:input.instanceId,cycleKey:input.cycleKey,observedAt:evidenceAt,operator,health,drift,control,runtime,evidence,directSigner:false,directTransactionSend:false,mainnetTransactionSent:false};
}
export async function loadPhase7ProductionStatus(input:{store:Pick<Phase1Store,'loadLatestPhase7HealthAssessment'|'loadLatestPhase7DriftAssessment'|'loadLatestPhase7ControlDecision'|'loadRecentPhase7RuntimeCycles'|'loadLatestPhase7EvidenceSnapshot'>;runtimeId:string}){const [health,drift,control,runtime,evidence]=await Promise.all([input.store.loadLatestPhase7HealthAssessment(input.runtimeId),input.store.loadLatestPhase7DriftAssessment(),input.store.loadLatestPhase7ControlDecision(input.runtimeId),input.store.loadRecentPhase7RuntimeCycles(input.runtimeId,1),input.store.loadLatestPhase7EvidenceSnapshot(input.runtimeId)]);return{runtimeId:input.runtimeId,health,drift,control,runtime:runtime[0],evidence,directSigner:false,directTransactionSend:false};}
