export type RawAmount=bigint;
export interface TokenAmount { raw:RawAmount; decimals:number; mint:string; }
export interface ReferencePrice { quote:'SOL'|'USD'; value:string; source:string; observedAt:string; }
export interface ValuedAmount { mint:string; raw:string; ui:string; quote:'SOL'|'USD'; price:string; value:string; }
export interface PositionValuation { positionAddress:string; poolAddress:string; quote:'SOL'|'USD'; tokenX:ValuedAmount; tokenY:ValuedAmount; feeX?:ValuedAmount; feeY?:ValuedAmount; grossValue:string; contributedValue?:string; absolutePnl?:string; hodlBenchmarkValue?:string; hodlRelativePnl?:string; observedAt:string; }
const SCALE=18n; const TEN18=10n**SCALE;
export function assertDecimals(d:number):void{if(!Number.isInteger(d)||d<0||d>255)throw new Error('LPFORGE_INVALID_DECIMALS');}
export function parseDecimal18(value:string):bigint { if(!/^-?\d+(\.\d+)?$/.test(value.trim()))throw new Error('LPFORGE_INVALID_DECIMAL'); const neg=value.startsWith('-'); const clean=neg?value.slice(1):value; const [whole='0',frac='']=clean.split('.'); const scaled=BigInt(whole)*TEN18+BigInt((frac+'0'.repeat(Number(SCALE))).slice(0,Number(SCALE))); return neg?-scaled:scaled; }
export function formatDecimal18(v:bigint):string { const neg=v<0n; const a=neg?-v:v; const whole=a/TEN18; const frac=(a%TEN18).toString().padStart(18,'0').replace(/0+$/,''); return`${neg?'-':''}${whole}${frac?'.'+frac:''}`; }
export function formatTokenAmount(a:TokenAmount):string { assertDecimals(a.decimals); const scale=10n**BigInt(a.decimals); const whole=a.raw/scale; const frac=(a.raw%scale).toString().padStart(a.decimals,'0').replace(/0+$/,''); return`${whole}${frac?'.'+frac:''}`; }
export function valueToken(a:TokenAmount,p:ReferencePrice):ValuedAmount { assertDecimals(a.decimals); const price=parseDecimal18(p.value); const denom=10n**BigInt(a.decimals); const valueScaled=(a.raw*price)/denom; return{mint:a.mint,raw:a.raw.toString(),ui:formatTokenAmount(a),quote:p.quote,price:p.value,value:formatDecimal18(valueScaled)}; }
export function addDecimal(...values:string[]):string{return formatDecimal18(values.reduce((s,v)=>s+parseDecimal18(v),0n));}
export function subDecimal(a:string,b:string):string{return formatDecimal18(parseDecimal18(a)-parseDecimal18(b));}
export function valuePosition(input:{positionAddress:string;poolAddress:string;tokenX:TokenAmount;tokenY:TokenAmount;priceX:ReferencePrice;priceY:ReferencePrice;feeX?:TokenAmount;feeY?:TokenAmount;contributedValue?:string;hodlBenchmarkValue?:string;observedAt?:string}):PositionValuation { if(input.priceX.quote!==input.priceY.quote)throw new Error('LPFORGE_VALUATION_QUOTE_MISMATCH'); const x=valueToken(input.tokenX,input.priceX),y=valueToken(input.tokenY,input.priceY); const fx=input.feeX?valueToken(input.feeX,input.priceX):undefined,fy=input.feeY?valueToken(input.feeY,input.priceY):undefined; const gross=addDecimal(x.value,y.value,fx?.value??'0',fy?.value??'0'); return{positionAddress:input.positionAddress,poolAddress:input.poolAddress,quote:input.priceX.quote,tokenX:x,tokenY:y,...(fx?{feeX:fx}:{}),...(fy?{feeY:fy}:{}),grossValue:gross,...(input.contributedValue?{contributedValue:input.contributedValue,absolutePnl:subDecimal(gross,input.contributedValue)}:{}),...(input.hodlBenchmarkValue?{hodlBenchmarkValue:input.hodlBenchmarkValue,hodlRelativePnl:subDecimal(gross,input.hodlBenchmarkValue)}:{}),observedAt:input.observedAt??new Date().toISOString()}; }

export const METEORA_FEE_DENOMINATOR=1_000_000_000n;
export const METEORA_MAX_FEE_RATE=100_000_000n;
export function ceilDiv(n:bigint,d:bigint):bigint{if(d<=0n)throw new Error('LPFORGE_DIVISOR');if(n<0n)throw new Error('LPFORGE_NEGATIVE_PROTOCOL_MATH');return(n+d-1n)/d;}
export function meteoraFeeFromAmountWithFee(amountWithFee:bigint,totalFeeRate:bigint):bigint{if(amountWithFee<0n||totalFeeRate<0n||totalFeeRate>METEORA_MAX_FEE_RATE)throw new Error('LPFORGE_INVALID_METEORA_FEE_INPUT');return ceilDiv(amountWithFee*totalFeeRate,METEORA_FEE_DENOMINATOR);}
export function splitMmTradingFee(tradingFeeRaw:bigint,protocolShareBps:number):{protocolFeeRaw:bigint;lpFeeRaw:bigint}{if(tradingFeeRaw<0n||!Number.isInteger(protocolShareBps)||protocolShareBps<0||protocolShareBps>2500)throw new Error('LPFORGE_INVALID_PROTOCOL_SHARE');const protocol=(tradingFeeRaw*BigInt(protocolShareBps))/10_000n;return{protocolFeeRaw:protocol,lpFeeRaw:tradingFeeRaw-protocol};}
export function liquidityShareFromDeposit(depositLiquidityRaw:bigint,existingLiquiditySupplyRaw:bigint,existingBinLiquidityRaw:bigint):bigint{if(depositLiquidityRaw<0n||existingLiquiditySupplyRaw<0n||existingBinLiquidityRaw<0n)throw new Error('LPFORGE_INVALID_LIQUIDITY_SHARE_INPUT');if(existingLiquiditySupplyRaw===0n||existingBinLiquidityRaw===0n)return depositLiquidityRaw;return(depositLiquidityRaw*existingLiquiditySupplyRaw)/existingBinLiquidityRaw;}
export function withdrawProRata(liquidityShareRemovedRaw:bigint,binAmountRaw:bigint,binLiquiditySupplyRaw:bigint):bigint{if(liquidityShareRemovedRaw<0n||binAmountRaw<0n||binLiquiditySupplyRaw<=0n)throw new Error('LPFORGE_INVALID_WITHDRAW_INPUT');return(liquidityShareRemovedRaw*binAmountRaw)/binLiquiditySupplyRaw;}
export function compositionFeeRaw(deltaAmountRaw:bigint,totalFeeRate:bigint):bigint{if(deltaAmountRaw<0n||totalFeeRate<0n||totalFeeRate>METEORA_MAX_FEE_RATE)throw new Error('LPFORGE_INVALID_COMPOSITION_FEE_INPUT');return(deltaAmountRaw*totalFeeRate*(METEORA_FEE_DENOMINATOR+totalFeeRate))/(METEORA_FEE_DENOMINATOR*METEORA_FEE_DENOMINATOR);}
