import type { Phase4RiskDecisionContract } from '../../contracts/src/index.js';
export interface RiskPolicy {id:string;maxDailyDrawdownFraction:number;maxRollingDrawdownFraction:number;maxTokenExposureFraction:number;maxPoolExposureFraction:number;maxReferenceDivergenceBps:number;maxDataAgeMs:number;liquidityCollapseFraction:number;}
export const RISK_RESEARCH_POLICY_V1:RiskPolicy={id:'risk-research-v1',maxDailyDrawdownFraction:.06,maxRollingDrawdownFraction:.10,maxTokenExposureFraction:.25,maxPoolExposureFraction:.15,maxReferenceDivergenceBps:250,maxDataAgeMs:120000,liquidityCollapseFraction:.35};
export interface RiskFacts {now:string;approvalTtlMs?:number;globalKillSwitch?:boolean;entriesPaused?:boolean;protocolCompatible:boolean;criticalDataObservedAt:string;dailyDrawdownFraction:number;rollingDrawdownFraction:number;tokenExposureFraction:number;poolExposureFraction:number;referenceDivergenceBps:number;liquidityChangeFraction:number;tokenBlacklisted?:boolean;freezeAuthorityViolation?:boolean;reconciliationRequired?:boolean;signerHealthy?:boolean;}
export interface RiskDecision extends Phase4RiskDecisionContract {policyId:string;hardBlocks:string[];emergencyReasons:string[];limits:{dailyDrawdownRemaining:number;rollingDrawdownRemaining:number;tokenExposureRemaining:number;poolExposureRemaining:number};}
/** Entry-market checks exclude portfolio, signer and reconciliation state. Those
 * facts are enforced from live authorities by P6/P7, never faked here. */
export interface MarketEntryRiskFacts {now:string;approvalTtlMs?:number;globalKillSwitch?:boolean;entriesPaused?:boolean;protocolCompatible:boolean;criticalDataObservedAt:string;tokenBlacklisted?:boolean;freezeAuthorityViolation?:boolean;liquidityChangeFraction?:number;}
export function governMarketEntryRisk(f:MarketEntryRiskFacts,policy:RiskPolicy=RISK_RESEARCH_POLICY_V1):RiskDecision{return governRisk({now:f.now,protocolCompatible:f.protocolCompatible,criticalDataObservedAt:f.criticalDataObservedAt,dailyDrawdownFraction:0,rollingDrawdownFraction:0,tokenExposureFraction:0,poolExposureFraction:0,referenceDivergenceBps:0,liquidityChangeFraction:f.liquidityChangeFraction??0,...(f.approvalTtlMs!==undefined?{approvalTtlMs:f.approvalTtlMs}:{}),...(f.globalKillSwitch!==undefined?{globalKillSwitch:f.globalKillSwitch}:{}),...(f.entriesPaused!==undefined?{entriesPaused:f.entriesPaused}:{}),...(f.tokenBlacklisted!==undefined?{tokenBlacklisted:f.tokenBlacklisted}:{}),...(f.freezeAuthorityViolation!==undefined?{freezeAuthorityViolation:f.freezeAuthorityViolation}:{})});}
export function governRisk(f:RiskFacts,policy:RiskPolicy=RISK_RESEARCH_POLICY_V1):RiskDecision{
 const block:string[]=[],emergency:string[]=[];const age=Date.parse(f.now)-Date.parse(f.criticalDataObservedAt);
 if(f.globalKillSwitch)block.push('RISK_GLOBAL_KILL_SWITCH');if(f.entriesPaused)block.push('RISK_ENTRIES_PAUSED');if(!f.protocolCompatible)block.push('RISK_PROTOCOL_COMPATIBILITY_HOLD');if(age<0||age>policy.maxDataAgeMs)block.push('RISK_CRITICAL_DATA_STALE');if(f.reconciliationRequired)block.push('RISK_RECONCILIATION_REQUIRED');
 if(f.dailyDrawdownFraction>=policy.maxDailyDrawdownFraction)block.push('RISK_DAILY_DRAWDOWN_LIMIT');if(f.rollingDrawdownFraction>=policy.maxRollingDrawdownFraction)block.push('RISK_ROLLING_DRAWDOWN_LIMIT');if(f.tokenExposureFraction>=policy.maxTokenExposureFraction)block.push('RISK_TOKEN_EXPOSURE_LIMIT');if(f.poolExposureFraction>=policy.maxPoolExposureFraction)block.push('RISK_POOL_EXPOSURE_LIMIT');if(Math.abs(f.referenceDivergenceBps)>policy.maxReferenceDivergenceBps)block.push('RISK_REFERENCE_DIVERGENCE');
 if(f.tokenBlacklisted)emergency.push('RISK_TOKEN_BLACKLISTED');if(f.freezeAuthorityViolation)emergency.push('RISK_FREEZE_AUTHORITY_VIOLATION');if(f.liquidityChangeFraction<=-policy.liquidityCollapseFraction)emergency.push('RISK_LIQUIDITY_COLLAPSE');if(f.signerHealthy===false)block.push('RISK_SIGNER_UNHEALTHY');
 const decision=emergency.length?'EMERGENCY':block.length?'BLOCK':'APPROVE';const reasonCodes=decision==='APPROVE'?['RISK_APPROVED']:[...new Set([...block,...emergency])].sort();
 return{phase:'P4',paperOnly:true,liveSigning:false,decision,scope:emergency.length?'POSITION':'ACTION',reasonCodes,expiresAt:new Date(Date.parse(f.now)+(f.approvalTtlMs??30000)).toISOString(),policyId:policy.id,hardBlocks:block,emergencyReasons:emergency,limits:{dailyDrawdownRemaining:Math.max(0,policy.maxDailyDrawdownFraction-f.dailyDrawdownFraction),rollingDrawdownRemaining:Math.max(0,policy.maxRollingDrawdownFraction-f.rollingDrawdownFraction),tokenExposureRemaining:Math.max(0,policy.maxTokenExposureFraction-f.tokenExposureFraction),poolExposureRemaining:Math.max(0,policy.maxPoolExposureFraction-f.poolExposureFraction)}};
}
